-- Marketing & Advertising AI Tools (102 tools)
-- This script adds 102 AI-powered tools for marketing and advertising
-- Covers content creation, social media, email marketing, analytics, SEO, PPC, and advertising automation
-- Uses ON CONFLICT (id, category_id) DO NOTHING to avoid duplicates within the same category

INSERT INTO tools (
  id, name, description, url, category_id, 
  pricing, tags, featured, trending, logo_url
) VALUES 
  -- AI Content Creation & Writing
  ('marketing-jasper', 'Jasper AI', 'AI-powered content creation platform that generates marketing copy, blog posts, social media content, and advertising materials at scale.', 'https://jasper.ai', 'marketing-advertising', 'Paid', ARRAY['content-creation', 'copywriting', 'marketing-copy'], false, true, 'https://jasper.ai/favicon.ico'),
  ('marketing-copy-ai', 'Copy.ai', 'AI writing assistant that creates marketing content, ad copy, product descriptions, and social media posts using advanced language models.', 'https://copy.ai', 'marketing-advertising', 'Freemium', ARRAY['ai-writing', 'ad-copy', 'content-generation'], false, true, 'https://copy.ai/favicon.ico'),
  ('marketing-writesonic', 'Writesonic', 'AI content creation tool for marketing teams that generates articles, ads, landing pages, and product descriptions with SEO optimization.', 'https://writesonic.com', 'marketing-advertising', 'Freemium', ARRAY['content-creation', 'seo-content', 'landing-pages'], false, true, 'https://writesonic.com/favicon.ico'),
  ('marketing-rytr', 'Rytr', 'AI writing assistant that creates high-quality marketing content, emails, blog posts, and social media captions in multiple languages.', 'https://rytr.me', 'marketing-advertising', 'Freemium', ARRAY['ai-writing', 'multilingual-content', 'email-marketing'], false, false, 'https://rytr.me/favicon.ico'),
  ('marketing-anyword', 'Anyword', 'AI copywriting platform that predicts content performance and generates data-driven marketing copy with performance scoring.', 'https://anyword.com', 'marketing-advertising', 'Paid', ARRAY['predictive-copywriting', 'performance-scoring', 'data-driven'], false, true, 'https://anyword.com/favicon.ico'),
  ('marketing-peppertype', 'Peppertype', 'AI content marketing platform that generates blog posts, social media content, ad copy, and email campaigns for businesses.', 'https://peppertype.ai', 'marketing-advertising', 'Freemium', ARRAY['content-marketing', 'blog-generation', 'email-campaigns'], false, false, 'https://peppertype.ai/favicon.ico'),
  ('marketing-wordtune', 'Wordtune', 'AI writing companion that helps rewrite and optimize marketing content for clarity, tone, and engagement.', 'https://wordtune.com', 'marketing-advertising', 'Freemium', ARRAY['content-optimization', 'tone-adjustment', 'clarity-improvement'], false, false, 'https://wordtune.com/favicon.ico'),
  ('marketing-shortly', 'Shortly AI', 'AI writing assistant that helps marketers create long-form content, blog posts, and marketing materials with intelligent suggestions.', 'https://shortlyai.com', 'marketing-advertising', 'Paid', ARRAY['long-form-content', 'blog-writing', 'content-assistance'], false, false, 'https://shortlyai.com/favicon.ico'),
  
  -- Social Media AI Tools
  ('marketing-hootsuite-insights', 'Hootsuite Insights', 'AI-powered social media analytics that provides sentiment analysis, trend detection, and audience insights for better engagement.', 'https://hootsuite.com', 'marketing-advertising', 'Paid', ARRAY['social-media-analytics', 'sentiment-analysis', 'audience-insights'], false, true, 'https://hootsuite.com/favicon.ico'),
  ('marketing-buffer-ai', 'Buffer AI Assistant', 'AI-enhanced social media management platform with content suggestions, optimal posting times, and engagement optimization.', 'https://buffer.com', 'marketing-advertising', 'Freemium', ARRAY['social-media-management', 'content-suggestions', 'posting-optimization'], false, false, 'https://buffer.com/favicon.ico'),
  ('marketing-sprout-social', 'Sprout Social AI', 'AI-powered social media management with automated responses, sentiment analysis, and social listening capabilities.', 'https://sproutsocial.com', 'marketing-advertising', 'Paid', ARRAY['social-listening', 'automated-responses', 'sentiment-analysis'], false, true, 'https://sproutsocial.com/favicon.ico'),
  ('marketing-socialbee', 'SocialBee AI', 'AI social media scheduler that categorizes content, suggests optimal posting times, and automates social media campaigns.', 'https://socialbee.io', 'marketing-advertising', 'Paid', ARRAY['social-scheduling', 'content-categorization', 'campaign-automation'], false, false, 'https://socialbee.io/favicon.ico'),
  ('marketing-lately', 'Lately AI', 'AI social media content generator that transforms long-form content into dozens of social media posts with brand voice consistency.', 'https://lately.ai', 'marketing-advertising', 'Paid', ARRAY['content-transformation', 'brand-voice', 'social-generation'], false, false, 'https://lately.ai/favicon.ico'),
  ('marketing-predis', 'Predis.ai', 'AI social media content creator that generates posts, captions, hashtags, and visual content for multiple platforms.', 'https://predis.ai', 'marketing-advertising', 'Freemium', ARRAY['social-content-creation', 'hashtag-generation', 'visual-content'], false, false, 'https://predis.ai/favicon.ico'),
  ('marketing-flick', 'Flick', 'AI hashtag research and social media analytics tool that optimizes hashtag strategies and tracks social performance.', 'https://flick.social', 'marketing-advertising', 'Freemium', ARRAY['hashtag-research', 'social-analytics', 'performance-tracking'], false, false, 'https://flick.social/favicon.ico'),
  ('marketing-smartwriter', 'SmartWriter', 'AI tool that creates personalized cold emails, LinkedIn messages, and social media outreach at scale.', 'https://smartwriter.ai', 'marketing-advertising', 'Paid', ARRAY['personalized-outreach', 'cold-email', 'linkedin-automation'], false, false, 'https://smartwriter.ai/favicon.ico'),
  
  -- Email Marketing AI
  ('marketing-mailchimp-ai', 'Mailchimp AI', 'AI-powered email marketing platform with predictive analytics, content optimization, and automated customer journeys.', 'https://mailchimp.com', 'marketing-advertising', 'Freemium', ARRAY['email-marketing', 'predictive-analytics', 'customer-journeys'], false, true, 'https://mailchimp.com/favicon.ico'),
  ('marketing-constant-contact-ai', 'Constant Contact AI', 'AI email marketing tool with smart content suggestions, send time optimization, and automated A/B testing.', 'https://constantcontact.com', 'marketing-advertising', 'Freemium', ARRAY['email-automation', 'ab-testing', 'send-optimization'], false, false, 'https://constantcontact.com/favicon.ico'),
  ('marketing-klaviyo', 'Klaviyo AI', 'AI-driven email and SMS marketing platform with predictive analytics, personalization, and customer lifetime value optimization.', 'https://klaviyo.com', 'marketing-advertising', 'Freemium', ARRAY['email-sms-marketing', 'personalization', 'clv-optimization'], false, true, 'https://klaviyo.com/favicon.ico'),
  ('marketing-campaign-monitor', 'Campaign Monitor AI', 'AI email marketing platform with smart segmentation, content optimization, and predictive sending.', 'https://campaignmonitor.com', 'marketing-advertising', 'Paid', ARRAY['smart-segmentation', 'content-optimization', 'predictive-sending'], false, false, 'https://campaignmonitor.com/favicon.ico'),
  ('marketing-seventh-sense', 'Seventh Sense', 'AI email delivery optimization platform that uses machine learning to determine optimal send times for each recipient.', 'https://theseventhsense.com', 'marketing-advertising', 'Paid', ARRAY['send-time-optimization', 'delivery-optimization', 'machine-learning'], false, false, 'https://theseventhsense.com/favicon.ico'),
  ('marketing-phrasee', 'Phrasee', 'AI email subject line and content optimization platform that generates and tests email copy for maximum engagement.', 'https://phrasee.co', 'marketing-advertising', 'Paid', ARRAY['subject-line-optimization', 'email-copy', 'engagement-optimization'], false, false, 'https://phrasee.co/favicon.ico'),
  ('marketing-persado', 'Persado', 'AI content generation platform that creates emotionally optimized marketing messages for email, web, and mobile campaigns.', 'https://persado.com', 'marketing-advertising', 'Paid', ARRAY['emotional-optimization', 'content-generation', 'message-optimization'], false, false, 'https://persado.com/favicon.ico'),
  ('marketing-sendinblue-ai', 'Brevo AI (SendinBlue)', 'AI-powered email marketing and automation platform with smart recommendations and predictive analytics.', 'https://brevo.com', 'marketing-advertising', 'Freemium', ARRAY['email-automation', 'smart-recommendations', 'predictive-analytics'], false, false, 'https://brevo.com/favicon.ico'),
  
  -- SEO & Content Optimization AI
  ('marketing-surfer-seo', 'Surfer SEO', 'AI-powered SEO tool that analyzes top-ranking pages and provides data-driven content optimization recommendations.', 'https://surferseo.com', 'marketing-advertising', 'Paid', ARRAY['seo-optimization', 'content-analysis', 'ranking-optimization'], false, true, 'https://surferseo.com/favicon.ico'),
  ('marketing-clearscope', 'Clearscope', 'AI content optimization platform that helps create SEO-optimized content with keyword recommendations and content grading.', 'https://clearscope.io', 'marketing-advertising', 'Paid', ARRAY['content-optimization', 'keyword-research', 'seo-grading'], false, false, 'https://clearscope.io/favicon.ico'),
  ('marketing-frase', 'Frase', 'AI content optimization tool that researches, writes, and optimizes SEO content based on search intent and competitor analysis.', 'https://frase.io', 'marketing-advertising', 'Paid', ARRAY['content-research', 'seo-writing', 'competitor-analysis'], false, true, 'https://frase.io/favicon.ico'),
  ('marketing-marketmuse', 'MarketMuse', 'AI content planning and optimization platform that identifies content gaps and provides topic modeling for SEO strategy.', 'https://marketmuse.com', 'marketing-advertising', 'Paid', ARRAY['content-planning', 'topic-modeling', 'content-gaps'], false, false, 'https://marketmuse.com/favicon.ico'),
  ('marketing-semrush-ai', 'SEMrush AI', 'AI-powered SEO and marketing toolkit with content optimization, keyword research, and competitor intelligence.', 'https://semrush.com', 'marketing-advertising', 'Paid', ARRAY['seo-toolkit', 'keyword-research', 'competitor-intelligence'], false, true, 'https://semrush.com/favicon.ico'),
  ('marketing-brightedge', 'BrightEdge', 'AI SEO platform that provides content optimization, search intent analysis, and real-time search performance insights.', 'https://brightedge.com', 'marketing-advertising', 'Paid', ARRAY['seo-platform', 'search-intent', 'performance-insights'], false, false, 'https://brightedge.com/favicon.ico'),
  ('marketing-conductor', 'Conductor', 'AI content optimization platform that helps create SEO-friendly content with search insights and content performance tracking.', 'https://conductor.com', 'marketing-advertising', 'Paid', ARRAY['content-optimization', 'search-insights', 'performance-tracking'], false, false, 'https://conductor.com/favicon.ico'),
  ('marketing-can-i-rank', 'CanIRank', 'AI SEO software that provides personalized SEO recommendations and competitive analysis using machine learning.', 'https://canirank.com', 'marketing-advertising', 'Paid', ARRAY['seo-recommendations', 'competitive-analysis', 'machine-learning'], false, false, 'https://canirank.com/favicon.ico'),
  
  -- PPC & Advertising AI
  ('marketing-google-ads-ai', 'Google Ads AI', 'AI-powered advertising platform with smart bidding, responsive ads, and automated campaign optimization.', 'https://ads.google.com', 'marketing-advertising', 'Free', ARRAY['smart-bidding', 'responsive-ads', 'campaign-optimization'], false, true, 'https://ads.google.com/favicon.ico'),
  ('marketing-facebook-ads-ai', 'Meta Ads Manager AI', 'AI advertising platform with automatic placements, lookalike audiences, and dynamic creative optimization.', 'https://business.facebook.com', 'marketing-advertising', 'Free', ARRAY['automatic-placements', 'lookalike-audiences', 'dynamic-creative'], false, true, 'https://business.facebook.com/favicon.ico'),
  ('marketing-optmyzr', 'Optmyzr', 'AI PPC management platform that automates bid management, ad testing, and campaign optimization for Google and Microsoft Ads.', 'https://optmyzr.com', 'marketing-advertising', 'Paid', ARRAY['ppc-management', 'bid-automation', 'ad-testing'], false, false, 'https://optmyzr.com/favicon.ico'),
  ('marketing-wordstream', 'WordStream AI', 'AI-powered PPC management platform with automated bidding, ad creation, and performance optimization.', 'https://wordstream.com', 'marketing-advertising', 'Paid', ARRAY['ppc-management', 'automated-bidding', 'ad-creation'], false, false, 'https://wordstream.com/favicon.ico'),
  ('marketing-acquisio', 'Acquisio', 'AI bid and budget management platform that optimizes PPC campaigns across multiple channels using machine learning.', 'https://acquisio.com', 'marketing-advertising', 'Paid', ARRAY['bid-management', 'budget-optimization', 'multi-channel'], false, false, 'https://acquisio.com/favicon.ico'),
  ('marketing-adext', 'Adext AI', 'AI audience management platform that automatically finds and targets the best audiences for digital advertising campaigns.', 'https://adext.ai', 'marketing-advertising', 'Paid', ARRAY['audience-management', 'targeting-optimization', 'campaign-automation'], false, false, 'https://adext.ai/favicon.ico'),
  ('marketing-trapica', 'Trapica', 'AI advertising platform that automates Facebook and Google ad campaigns with machine learning optimization.', 'https://trapica.com', 'marketing-advertising', 'Paid', ARRAY['ad-automation', 'facebook-ads', 'google-ads'], false, false, 'https://trapica.com/favicon.ico'),
  ('marketing-revealbot', 'Revealbot', 'AI Facebook and Instagram ads automation platform with rule-based optimization and performance monitoring.', 'https://revealbot.com', 'marketing-advertising', 'Paid', ARRAY['facebook-automation', 'instagram-ads', 'rule-based-optimization'], false, false, 'https://revealbot.com/favicon.ico'),
  
  -- Analytics & Performance AI
  ('marketing-google-analytics-ai', 'Google Analytics Intelligence', 'AI-powered web analytics with automated insights, anomaly detection, and predictive analytics for marketing performance.', 'https://analytics.google.com', 'marketing-advertising', 'Free', ARRAY['web-analytics', 'automated-insights', 'anomaly-detection'], false, true, 'https://analytics.google.com/favicon.ico'),
  ('marketing-hotjar-ai', 'Hotjar AI', 'AI website analytics platform with heatmaps, session recordings, and automated insights for user behavior analysis.', 'https://hotjar.com', 'marketing-advertising', 'Freemium', ARRAY['website-analytics', 'heatmaps', 'user-behavior'], false, false, 'https://hotjar.com/favicon.ico'),
  ('marketing-mixpanel', 'Mixpanel AI', 'AI product analytics platform that tracks user interactions and provides insights for marketing optimization and user engagement.', 'https://mixpanel.com', 'marketing-advertising', 'Freemium', ARRAY['product-analytics', 'user-tracking', 'engagement-optimization'], false, false, 'https://mixpanel.com/favicon.ico'),
  ('marketing-amplitude', 'Amplitude AI', 'AI behavioral analytics platform that helps understand user journeys and optimize marketing funnels with predictive insights.', 'https://amplitude.com', 'marketing-advertising', 'Freemium', ARRAY['behavioral-analytics', 'user-journeys', 'funnel-optimization'], false, false, 'https://amplitude.com/favicon.ico'),
  ('marketing-segment', 'Segment AI', 'AI customer data platform that unifies customer data and provides insights for personalized marketing campaigns.', 'https://segment.com', 'marketing-advertising', 'Paid', ARRAY['customer-data-platform', 'data-unification', 'personalization'], false, false, 'https://segment.com/favicon.ico'),
  ('marketing-adobe-analytics', 'Adobe Analytics AI', 'AI-powered analytics platform with predictive analytics, attribution modeling, and real-time personalization.', 'https://business.adobe.com/products/analytics/adobe-analytics.html', 'marketing-advertising', 'Paid', ARRAY['predictive-analytics', 'attribution-modeling', 'real-time-personalization'], false, false, 'https://business.adobe.com/favicon.ico'),
  ('marketing-crazy-egg', 'Crazy Egg AI', 'AI website optimization platform with heatmaps, A/B testing, and conversion optimization recommendations.', 'https://crazyegg.com', 'marketing-advertising', 'Paid', ARRAY['website-optimization', 'heatmaps', 'conversion-optimization'], false, false, 'https://crazyegg.com/favicon.ico'),
  ('marketing-kissmetrics', 'Kissmetrics AI', 'AI customer analytics platform that tracks individual customer behavior and provides insights for marketing optimization.', 'https://kissmetrics.io', 'marketing-advertising', 'Paid', ARRAY['customer-analytics', 'behavior-tracking', 'marketing-optimization'], false, false, 'https://kissmetrics.io/favicon.ico'),
  
  -- Personalization & Customer Experience AI
  ('marketing-dynamic-yield', 'Dynamic Yield', 'AI personalization platform that delivers individualized experiences across web, mobile, and email channels.', 'https://dynamicyield.com', 'marketing-advertising', 'Paid', ARRAY['personalization', 'individualized-experiences', 'omnichannel'], false, false, 'https://dynamicyield.com/favicon.ico'),
  ('marketing-optimizely', 'Optimizely AI', 'AI experimentation platform that optimizes customer experiences through A/B testing and personalization.', 'https://optimizely.com', 'marketing-advertising', 'Paid', ARRAY['experimentation', 'ab-testing', 'experience-optimization'], false, true, 'https://optimizely.com/favicon.ico'),
  ('marketing-evergage', 'Salesforce Interaction Studio', 'AI real-time personalization platform that delivers individualized experiences across all customer touchpoints.', 'https://salesforce.com/products/marketing-cloud/personalization', 'marketing-advertising', 'Paid', ARRAY['real-time-personalization', 'customer-touchpoints', 'individualized-experiences'], false, false, 'https://salesforce.com/favicon.ico'),
  ('marketing-monetate', 'Monetate', 'AI personalization platform that optimizes customer experiences through testing, targeting, and personalization.', 'https://monetate.com', 'marketing-advertising', 'Paid', ARRAY['experience-optimization', 'testing-targeting', 'personalization'], false, false, 'https://monetate.com/favicon.ico'),
  ('marketing-qubit', 'Qubit', 'AI personalization platform that uses machine learning to deliver individualized customer experiences at scale.', 'https://qubit.com', 'marketing-advertising', 'Paid', ARRAY['machine-learning', 'individualized-experiences', 'scale-personalization'], false, false, 'https://qubit.com/favicon.ico'),
  ('marketing-yotpo', 'Yotpo AI', 'AI-powered customer content marketing platform with reviews, loyalty, and SMS marketing automation.', 'https://yotpo.com', 'marketing-advertising', 'Paid', ARRAY['customer-content', 'reviews-loyalty', 'sms-marketing'], false, false, 'https://yotpo.com/favicon.ico'),
  ('marketing-bloomreach', 'Bloomreach', 'AI-powered digital experience platform that personalizes content and commerce experiences using machine learning.', 'https://bloomreach.com', 'marketing-advertising', 'Paid', ARRAY['digital-experience', 'content-personalization', 'commerce-experiences'], false, false, 'https://bloomreach.com/favicon.ico'),
  ('marketing-sailthru', 'Sailthru', 'AI customer engagement platform that personalizes email, web, and mobile experiences using predictive analytics.', 'https://sailthru.com', 'marketing-advertising', 'Paid', ARRAY['customer-engagement', 'email-personalization', 'predictive-analytics'], false, false, 'https://sailthru.com/favicon.ico'),
  
  -- Influencer Marketing AI
  ('marketing-grin', 'Grin', 'AI influencer marketing platform that helps discover, manage, and analyze influencer partnerships for brand campaigns.', 'https://grin.co', 'marketing-advertising', 'Paid', ARRAY['influencer-marketing', 'partnership-management', 'campaign-analysis'], false, false, 'https://grin.co/favicon.ico'),
  ('marketing-upfluence', 'Upfluence', 'AI influencer marketing platform with influencer discovery, campaign management, and performance analytics.', 'https://upfluence.com', 'marketing-advertising', 'Paid', ARRAY['influencer-discovery', 'campaign-management', 'performance-analytics'], false, false, 'https://upfluence.com/favicon.ico'),
  ('marketing-klear', 'Klear', 'AI influencer marketing platform that provides influencer discovery, audience analysis, and campaign measurement.', 'https://klear.com', 'marketing-advertising', 'Paid', ARRAY['influencer-discovery', 'audience-analysis', 'campaign-measurement'], false, false, 'https://klear.com/favicon.ico'),
  ('marketing-heepsy', 'Heepsy', 'AI influencer search engine that helps find and analyze influencers across social media platforms with detailed analytics.', 'https://heepsy.com', 'marketing-advertising', 'Freemium', ARRAY['influencer-search', 'social-media-analytics', 'detailed-analytics'], false, false, 'https://heepsy.com/favicon.ico'),
  ('marketing-modash', 'Modash', 'AI influencer analytics platform that provides influencer discovery, audience insights, and campaign tracking.', 'https://modash.io', 'marketing-advertising', 'Paid', ARRAY['influencer-analytics', 'audience-insights', 'campaign-tracking'], false, false, 'https://modash.io/favicon.ico'),
  ('marketing-aspire', 'AspireIQ', 'AI influencer marketing platform that connects brands with creators and manages influencer campaigns at scale.', 'https://aspireiq.com', 'marketing-advertising', 'Paid', ARRAY['creator-connections', 'campaign-management', 'scale-marketing'], false, false, 'https://aspireiq.com/favicon.ico'),
  ('marketing-creator-iq', 'CreatorIQ', 'AI influencer marketing platform with comprehensive creator discovery, relationship management, and performance measurement.', 'https://creatoriq.com', 'marketing-advertising', 'Paid', ARRAY['creator-discovery', 'relationship-management', 'performance-measurement'], false, false, 'https://creatoriq.com/favicon.ico'),
  ('marketing-ninjalitics', 'Ninjalitics', 'AI Instagram analytics tool that provides detailed influencer analysis, audience insights, and engagement metrics.', 'https://ninjalitics.com', 'marketing-advertising', 'Freemium', ARRAY['instagram-analytics', 'influencer-analysis', 'engagement-metrics'], false, false, 'https://ninjalitics.com/favicon.ico'),
  
  -- Video Marketing AI
  ('marketing-vidiq', 'VidIQ', 'AI YouTube optimization tool that provides keyword research, competitor analysis, and video performance insights.', 'https://vidiq.com', 'marketing-advertising', 'Freemium', ARRAY['youtube-optimization', 'keyword-research', 'video-analytics'], false, false, 'https://vidiq.com/favicon.ico'),
  ('marketing-tubebuddy', 'TubeBuddy', 'AI YouTube channel management tool with SEO optimization, thumbnail testing, and analytics for video marketing.', 'https://tubebuddy.com', 'marketing-advertising', 'Freemium', ARRAY['youtube-management', 'seo-optimization', 'thumbnail-testing'], false, false, 'https://tubebuddy.com/favicon.ico'),
  ('marketing-loom-ai', 'Loom AI', 'AI video messaging platform that creates personalized video content for marketing, sales, and customer communication.', 'https://loom.com', 'marketing-advertising', 'Freemium', ARRAY['video-messaging', 'personalized-video', 'customer-communication'], false, false, 'https://loom.com/favicon.ico'),
  ('marketing-synthesia', 'Synthesia', 'AI video creation platform that generates professional videos with AI avatars for marketing and training content.', 'https://synthesia.io', 'marketing-advertising', 'Paid', ARRAY['ai-video-creation', 'ai-avatars', 'professional-videos'], false, true, 'https://synthesia.io/favicon.ico'),
  ('marketing-pictory', 'Pictory', 'AI video creation platform that transforms text content into engaging videos for social media and marketing campaigns.', 'https://pictory.ai', 'marketing-advertising', 'Paid', ARRAY['text-to-video', 'social-media-videos', 'marketing-campaigns'], false, false, 'https://pictory.ai/favicon.ico'),
  ('marketing-invideo', 'InVideo AI', 'AI video creation platform with templates, automated editing, and content optimization for marketing videos.', 'https://invideo.io', 'marketing-advertising', 'Freemium', ARRAY['video-templates', 'automated-editing', 'content-optimization'], false, false, 'https://invideo.io/favicon.ico'),
  ('marketing-wave-video', 'Wave.video AI', 'AI video creation and editing platform with automated subtitles, resizing, and social media optimization.', 'https://wave.video', 'marketing-advertising', 'Freemium', ARRAY['video-editing', 'automated-subtitles', 'social-optimization'], false, false, 'https://wave.video/favicon.ico'),
  ('marketing-promo-ai', 'Promo.com', 'AI video creation platform that generates marketing videos using templates, stock footage, and automated editing.', 'https://promo.com', 'marketing-advertising', 'Freemium', ARRAY['marketing-videos', 'stock-footage', 'automated-editing'], false, false, 'https://promo.com/favicon.ico'),
  
  -- Chatbots & Conversational Marketing AI
  ('marketing-drift-bot', 'Drift', 'AI conversational marketing platform with chatbots, lead qualification, and automated customer engagement.', 'https://drift.com', 'marketing-advertising', 'Paid', ARRAY['conversational-marketing', 'lead-qualification', 'automated-engagement'], false, true, 'https://drift.com/favicon.ico'),
  ('marketing-intercom-ai', 'Intercom AI', 'AI customer messaging platform with chatbots, automated responses, and customer support automation.', 'https://intercom.com', 'marketing-advertising', 'Paid', ARRAY['customer-messaging', 'chatbots', 'support-automation'], false, false, 'https://intercom.com/favicon.ico'),
  ('marketing-zendesk-chat', 'Zendesk Chat AI', 'AI-powered live chat and chatbot platform for customer support and lead generation automation.', 'https://zendesk.com/chat', 'marketing-advertising', 'Paid', ARRAY['live-chat', 'chatbot-platform', 'lead-generation'], false, false, 'https://zendesk.com/favicon.ico'),
  ('marketing-tidio-ai', 'Tidio AI', 'AI chatbot platform that combines live chat with automated responses for customer service and marketing.', 'https://tidio.com', 'marketing-advertising', 'Freemium', ARRAY['ai-chatbot', 'live-chat', 'automated-responses'], false, false, 'https://tidio.com/favicon.ico'),
  ('marketing-manychat', 'ManyChat', 'AI chatbot platform for Facebook Messenger, Instagram, and SMS marketing automation with visual flow builder.', 'https://manychat.com', 'marketing-advertising', 'Freemium', ARRAY['messenger-marketing', 'instagram-automation', 'sms-marketing'], false, false, 'https://manychat.com/favicon.ico'),
  ('marketing-chatfuel', 'Chatfuel', 'AI chatbot platform for Facebook Messenger and Instagram with automated sequences and audience targeting.', 'https://chatfuel.com', 'marketing-advertising', 'Freemium', ARRAY['facebook-chatbots', 'instagram-chatbots', 'audience-targeting'], false, false, 'https://chatfuel.com/favicon.ico'),
  ('marketing-mobile-monkey', 'MobileMonkey', 'AI chatbot platform for Facebook Messenger, Instagram, and SMS with marketing automation and lead generation.', 'https://mobilemonkey.com', 'marketing-advertising', 'Freemium', ARRAY['multi-platform-chatbots', 'marketing-automation', 'lead-generation'], false, false, 'https://mobilemonkey.com/favicon.ico'),
  ('marketing-botsify', 'Botsify', 'AI chatbot platform that creates intelligent chatbots for websites, Facebook, and WhatsApp with natural language processing.', 'https://botsify.com', 'marketing-advertising', 'Freemium', ARRAY['intelligent-chatbots', 'natural-language-processing', 'multi-platform'], false, false, 'https://botsify.com/favicon.ico'),
  
  -- Marketing Automation AI
  ('marketing-hubspot-ai', 'HubSpot AI', 'AI-powered inbound marketing platform with content optimization, lead scoring, and automated marketing workflows.', 'https://hubspot.com', 'marketing-advertising', 'Freemium', ARRAY['inbound-marketing', 'lead-scoring', 'marketing-workflows'], false, true, 'https://hubspot.com/favicon.ico'),
  ('marketing-marketo', 'Adobe Marketo AI', 'AI marketing automation platform with predictive content, lead nurturing, and account-based marketing capabilities.', 'https://marketo.com', 'marketing-advertising', 'Paid', ARRAY['marketing-automation', 'predictive-content', 'account-based-marketing'], false, false, 'https://marketo.com/favicon.ico'),
  ('marketing-pardot', 'Salesforce Pardot AI', 'AI B2B marketing automation platform with lead scoring, email marketing, and sales alignment features.', 'https://pardot.com', 'marketing-advertising', 'Paid', ARRAY['b2b-marketing', 'lead-scoring', 'sales-alignment'], false, false, 'https://pardot.com/favicon.ico'),
  ('marketing-eloqua', 'Oracle Eloqua AI', 'AI marketing automation platform with advanced segmentation, lead nurturing, and campaign optimization.', 'https://oracle.com/cx/marketing/automation', 'marketing-advertising', 'Paid', ARRAY['advanced-segmentation', 'lead-nurturing', 'campaign-optimization'], false, false, 'https://oracle.com/favicon.ico'),
  ('marketing-activecampaign', 'ActiveCampaign AI', 'AI email marketing and automation platform with predictive sending, content recommendations, and customer experience automation.', 'https://activecampaign.com', 'marketing-advertising', 'Freemium', ARRAY['email-automation', 'predictive-sending', 'customer-experience'], false, false, 'https://activecampaign.com/favicon.ico'),
  ('marketing-getresponse', 'GetResponse AI', 'AI marketing platform with email automation, landing pages, and webinar marketing with intelligent optimization.', 'https://getresponse.com', 'marketing-advertising', 'Freemium', ARRAY['email-automation', 'landing-pages', 'webinar-marketing'], false, false, 'https://getresponse.com/favicon.ico'),
  ('marketing-drip', 'Drip AI', 'AI e-commerce marketing automation platform with personalized email campaigns and customer lifecycle automation.', 'https://drip.com', 'marketing-advertising', 'Paid', ARRAY['ecommerce-marketing', 'personalized-campaigns', 'lifecycle-automation'], false, false, 'https://drip.com/favicon.ico'),
  ('marketing-convertkit', 'ConvertKit AI', 'AI email marketing platform for creators with automated sequences, subscriber tagging, and content recommendations.', 'https://convertkit.com', 'marketing-advertising', 'Freemium', ARRAY['creator-marketing', 'automated-sequences', 'subscriber-tagging'], false, false, 'https://convertkit.com/favicon.ico'),
  
  -- Competitive Intelligence AI
  ('marketing-similarweb', 'SimilarWeb', 'AI competitive intelligence platform that analyzes website traffic, market share, and digital marketing strategies.', 'https://similarweb.com', 'marketing-advertising', 'Freemium', ARRAY['competitive-intelligence', 'website-traffic', 'market-analysis'], false, false, 'https://similarweb.com/favicon.ico'),
  ('marketing-spyfu', 'SpyFu', 'AI competitive research tool that reveals competitors\' keywords, ad copy, and PPC strategies for search marketing.', 'https://spyfu.com', 'marketing-advertising', 'Paid', ARRAY['competitive-research', 'keyword-analysis', 'ppc-intelligence'], false, false, 'https://spyfu.com/favicon.ico'),
  ('marketing-ahrefs', 'Ahrefs AI', 'AI SEO and competitive analysis platform with keyword research, backlink analysis, and content gap identification.', 'https://ahrefs.com', 'marketing-advertising', 'Paid', ARRAY['seo-analysis', 'backlink-analysis', 'content-gaps'], false, true, 'https://ahrefs.com/favicon.ico'),
  ('marketing-moz', 'Moz AI', 'AI SEO platform with keyword research, rank tracking, and competitive analysis for search marketing optimization.', 'https://moz.com', 'marketing-advertising', 'Freemium', ARRAY['seo-platform', 'rank-tracking', 'competitive-analysis'], false, false, 'https://moz.com/favicon.ico'),
  ('marketing-buzzsumo', 'BuzzSumo', 'AI content research and monitoring platform that analyzes trending content and identifies key influencers.', 'https://buzzsumo.com', 'marketing-advertising', 'Paid', ARRAY['content-research', 'trending-content', 'influencer-identification'], false, false, 'https://buzzsumo.com/favicon.ico'),
  ('marketing-brandwatch', 'Brandwatch', 'AI social listening and analytics platform that monitors brand mentions, sentiment, and competitive intelligence.', 'https://brandwatch.com', 'marketing-advertising', 'Paid', ARRAY['social-listening', 'brand-monitoring', 'sentiment-analysis'], false, false, 'https://brandwatch.com/favicon.ico'),
  ('marketing-mention', 'Mention', 'AI brand monitoring tool that tracks brand mentions across web, social media, and news with sentiment analysis.', 'https://mention.com', 'marketing-advertising', 'Freemium', ARRAY['brand-monitoring', 'mention-tracking', 'sentiment-analysis'], false, false, 'https://mention.com/favicon.ico'),
  ('marketing-socialmention', 'Social Mention', 'AI social media monitoring platform that tracks brand mentions and provides real-time sentiment analysis.', 'https://socialmention.com', 'marketing-advertising', 'Free', ARRAY['social-monitoring', 'brand-mentions', 'real-time-sentiment'], false, false, 'https://socialmention.com/favicon.ico'),
  
  -- Attribution & Analytics AI
  ('marketing-attribution', 'Attribution.com', 'AI attribution platform that tracks customer journeys across touchpoints and measures marketing effectiveness.', 'https://attribution.com', 'marketing-advertising', 'Paid', ARRAY['attribution-modeling', 'customer-journeys', 'marketing-effectiveness'], false, false, 'https://attribution.com/favicon.ico'),
  ('marketing-triple-whale', 'Triple Whale', 'AI e-commerce analytics platform that provides attribution, customer lifetime value, and marketing performance insights.', 'https://triplewhale.com', 'marketing-advertising', 'Paid', ARRAY['ecommerce-analytics', 'customer-lifetime-value', 'performance-insights'], false, false, 'https://triplewhale.com/favicon.ico'),
  ('marketing-northbeam', 'Northbeam', 'AI attribution platform that provides unified customer journey tracking and marketing mix modeling for e-commerce.', 'https://northbeam.io', 'marketing-advertising', 'Paid', ARRAY['unified-tracking', 'marketing-mix-modeling', 'ecommerce-attribution'], false, false, 'https://northbeam.io/favicon.ico'),
  ('marketing-rockerbox', 'Rockerbox', 'AI marketing attribution platform that measures cross-channel performance and optimizes media spend allocation.', 'https://rockerbox.com', 'marketing-advertising', 'Paid', ARRAY['cross-channel-attribution', 'media-optimization', 'spend-allocation'], false, false, 'https://rockerbox.com/favicon.ico'),
  ('marketing-wicked-reports', 'Wicked Reports', 'AI marketing attribution software that tracks leads and sales back to their original marketing source.', 'https://wickedreports.com', 'marketing-advertising', 'Paid', ARRAY['lead-attribution', 'sales-tracking', 'source-attribution'], false, false, 'https://wickedreports.com/favicon.ico'),
  ('marketing-hyros', 'Hyros', 'AI ad tracking and attribution platform that provides accurate ROI measurement across multiple advertising channels.', 'https://hyros.com', 'marketing-advertising', 'Paid', ARRAY['ad-tracking', 'roi-measurement', 'multi-channel-attribution'], false, false, 'https://hyros.com/favicon.ico'),
  ('marketing-ruler-analytics', 'Ruler Analytics', 'AI marketing attribution platform that connects marketing activities to revenue with full customer journey tracking.', 'https://ruleranalytics.com', 'marketing-advertising', 'Paid', ARRAY['revenue-attribution', 'customer-journey-tracking', 'marketing-revenue'], false, false, 'https://ruleranalytics.com/favicon.ico'),
  ('marketing-bizible', 'Adobe Bizible', 'AI B2B marketing attribution platform that tracks touchpoints and measures marketing impact on revenue.', 'https://bizible.com', 'marketing-advertising', 'Paid', ARRAY['b2b-attribution', 'touchpoint-tracking', 'revenue-impact'], false, false, 'https://bizible.com/favicon.ico')
ON CONFLICT (id, category_id) DO NOTHING;

-- Update the tool count for the category
UPDATE categories 
SET tool_count = (
  SELECT COUNT(*) 
  FROM tools 
  WHERE category_id = 'marketing-advertising'
) 
WHERE id = 'marketing-advertising';
