-- Video & Animation AI Tools (110 tools)
-- This script adds 110 AI-powered tools for video creation and animation
-- Covers video generation, editing, animation, motion graphics, visual effects, and post-production
-- Uses ON CONFLICT (id, category_id) DO NOTHING to avoid duplicates within the same category

INSERT INTO tools (
  id, name, description, url, category_id, 
  pricing, tags, featured, trending, logo_url
) VALUES 
  -- AI Video Generation & Creation
  ('video-runway-ml', 'Runway ML', 'AI-powered creative suite with video generation, image synthesis, and machine learning tools for content creators.', 'https://runwayml.com', 'video-animation', 'Freemium', ARRAY['video-generation', 'image-synthesis', 'machine-learning'], false, false, 'https://runwayml.com/favicon.ico'),
  ('video-synthesia', 'Synthesia', 'Leading AI video generator for studio-quality content using AI avatars. Simplifies production of training modules, presentations, internal communications, onboarding videos, customer support videos, and marketing content. Free plan allows 36 minutes of video per year, paid plans start at $29/month.', 'https://synthesia.io', 'video-animation', 'Freemium', ARRAY['ai-avatars', 'video-generation', 'multilingual', 'studio-quality', 'training-videos'], true, true, 'https://synthesia.io/favicon.ico'),
  ('video-pictory', 'Pictory', 'AI video creation platform that transforms scripts and articles into engaging videos with automatic editing.', 'https://pictory.ai', 'video-animation', 'Freemium', ARRAY['script-to-video', 'automatic-editing', 'content-creation'], false, false, 'https://pictory.ai/favicon.ico'),
  ('video-lumen5', 'Lumen5', 'AI-powered video creation platform that turns blog posts and articles into engaging social media videos.', 'https://lumen5.com', 'video-animation', 'Freemium', ARRAY['blog-to-video', 'social-media', 'content-transformation'], false, false, 'https://lumen5.com/favicon.ico'),
  ('video-invideo', 'InVideo', 'AI video creation platform with templates, automated editing, and text-to-video capabilities.', 'https://invideo.io', 'video-animation', 'Freemium', ARRAY['video-templates', 'automated-editing', 'text-to-video'], false, false, 'https://invideo.io/favicon.ico'),
  ('video-animoto', 'Animoto', 'AI-powered video maker that creates professional marketing videos with automated editing and smart suggestions.', 'https://animoto.com', 'video-animation', 'Freemium', ARRAY['marketing-videos', 'automated-editing', 'smart-suggestions'], false, false, 'https://animoto.com/favicon.ico'),
  ('video-kaiber', 'Kaiber', 'AI video generation platform that creates stunning videos from text prompts and images with artistic styles.', 'https://kaiber.ai', 'video-animation', 'Paid', ARRAY['text-to-video', 'artistic-styles', 'creative-generation'], false, false, 'https://kaiber.ai/favicon.ico'),
  ('video-stable-video', 'Stable Video Diffusion', 'AI video generation model that creates high-quality videos from text descriptions and images.', 'https://stability.ai', 'video-animation', 'Freemium', ARRAY['video-diffusion', 'text-to-video', 'high-quality'], false, false, 'https://stability.ai/favicon.ico'),
  ('video-gen2-runway', 'Gen-2 by Runway', 'Advanced AI video generation tool that creates realistic videos from text prompts and reference images.', 'https://research.runwayml.com/gen2', 'video-animation', 'Paid', ARRAY['advanced-generation', 'realistic-videos', 'text-prompts'], false, false, 'https://research.runwayml.com/favicon.ico'),
  ('video-pika-labs', 'Pika Labs', 'AI video generation platform that creates high-quality videos from text descriptions with cinematic quality.', 'https://pika.art', 'video-animation', 'Freemium', ARRAY['cinematic-quality', 'text-descriptions', 'high-quality'], false, false, 'https://pika.art/favicon.ico'),
  
  -- AI Video Editing & Enhancement
  ('video-adobe-premiere-ai', 'Adobe Premiere Pro AI', 'AI-enhanced video editing with automatic scene detection, color matching, and intelligent audio cleanup.', 'https://adobe.com/products/premiere', 'video-animation', 'Paid', ARRAY['professional-editing', 'scene-detection', 'color-matching'], false, false, 'https://adobe.com/favicon.ico'),
  ('video-davinci-resolve-ai', 'DaVinci Resolve AI', 'Professional video editing software with AI-powered color grading, face recognition, and speed optimization.', 'https://blackmagicdesign.com/products/davinciresolve', 'video-animation', 'Freemium', ARRAY['professional-editing', 'color-grading', 'face-recognition'], false, false, 'https://blackmagicdesign.com/favicon.ico'),
  ('video-magisto', 'Magisto', 'AI video editor that automatically creates professional videos from raw footage with smart editing algorithms.', 'https://magisto.com', 'video-animation', 'Freemium', ARRAY['automatic-editing', 'smart-algorithms', 'professional-videos'], false, false, 'https://magisto.com/favicon.ico'),
  ('video-clipchamp', 'Clipchamp', 'AI-powered video editor with automatic subtitle generation, smart cropping, and template suggestions.', 'https://clipchamp.com', 'video-animation', 'Freemium', ARRAY['subtitle-generation', 'smart-cropping', 'template-suggestions'], false, false, 'https://clipchamp.com/favicon.ico'),
  ('video-filmora-ai', 'Filmora AI', 'Video editing software with AI-powered motion tracking, color correction, and automatic highlight detection.', 'https://filmora.wondershare.com', 'video-animation', 'Paid', ARRAY['motion-tracking', 'color-correction', 'highlight-detection'], false, false, 'https://filmora.wondershare.com/favicon.ico'),
  ('video-topaz-video-ai', 'Topaz Video AI', 'AI-powered video enhancement tool that upscales, denoises, and stabilizes videos with machine learning.', 'https://topazlabs.com/topaz-video-ai', 'video-animation', 'Paid', ARRAY['video-upscaling', 'denoising', 'stabilization'], false, false, 'https://topazlabs.com/favicon.ico'),
  ('video-descript', 'Descript', 'AI video editor that allows text-based editing, automatic transcription, and voice cloning capabilities.', 'https://descript.com', 'video-animation', 'Freemium', ARRAY['text-based-editing', 'automatic-transcription', 'voice-cloning'], false, false, 'https://descript.com/favicon.ico'),
  ('video-wondershare-ai', 'Wondershare UniConverter AI', 'AI video converter and editor with smart compression, format optimization, and quality enhancement.', 'https://videoconverter.wondershare.com', 'video-animation', 'Paid', ARRAY['video-conversion', 'smart-compression', 'quality-enhancement'], false, false, 'https://videoconverter.wondershare.com/favicon.ico'),
  ('video-cyberlink-ai', 'CyberLink PowerDirector AI', 'Video editing software with AI-powered object removal, sky replacement, and motion graphics.', 'https://cyberlink.com/products/powerdirector', 'video-animation', 'Paid', ARRAY['object-removal', 'sky-replacement', 'motion-graphics'], false, false, 'https://cyberlink.com/favicon.ico'),
  ('video-nvidia-broadcast', 'NVIDIA Broadcast', 'AI-powered streaming and video conferencing tool with noise removal, virtual background, and eye contact.', 'https://nvidia.com/broadcast', 'video-animation', 'Free', ARRAY['streaming', 'noise-removal', 'virtual-background'], false, false, 'https://nvidia.com/favicon.ico'),
  
  -- AI Animation & Motion Graphics
  ('video-cascadeur', 'Cascadeur', 'AI-assisted 3D animation software with physics simulation and automatic key frame generation.', 'https://cascadeur.com', 'video-animation', 'Freemium', ARRAY['3d-animation', 'physics-simulation', 'keyframe-generation'], false, false, 'https://cascadeur.com/favicon.ico'),
  ('video-deepmotion', 'DeepMotion', 'AI motion capture platform that creates 3D animations from video using markerless technology.', 'https://deepmotion.com', 'video-animation', 'Freemium', ARRAY['motion-capture', '3d-animations', 'markerless-technology'], false, false, 'https://deepmotion.com/favicon.ico'),
  ('video-mixamo', 'Adobe Mixamo', 'AI-powered character animation service with automatic rigging and motion capture for 3D characters.', 'https://mixamo.com', 'video-animation', 'Free', ARRAY['character-animation', 'automatic-rigging', 'motion-capture'], false, false, 'https://mixamo.com/favicon.ico'),
  ('video-plask', 'Plask', 'AI motion capture platform that extracts 3D motion from video for character animation and game development.', 'https://plask.ai', 'video-animation', 'Freemium', ARRAY['motion-capture', 'character-animation', 'game-development'], false, false, 'https://plask.ai/favicon.ico'),
  ('video-move-ai', 'Move AI', 'Markerless motion capture technology that creates high-quality 3D animations from standard video footage.', 'https://move.ai', 'video-animation', 'Paid', ARRAY['markerless-capture', 'high-quality-animation', 'video-to-3d'], false, false, 'https://move.ai/favicon.ico'),
  ('video-vyond', 'Vyond', 'AI-enhanced animated video creation platform with character animation and storytelling tools.', 'https://vyond.com', 'video-animation', 'Paid', ARRAY['animated-videos', 'character-animation', 'storytelling'], false, false, 'https://vyond.com/favicon.ico'),
  ('video-powtoon', 'Powtoon', 'AI-powered animation platform for creating engaging presentations and explainer videos.', 'https://powtoon.com', 'video-animation', 'Freemium', ARRAY['animated-presentations', 'explainer-videos', 'engaging-content'], false, false, 'https://powtoon.com/favicon.ico'),
  ('video-renderforest', 'Renderforest', 'AI video animation platform with templates for logos, intros, and promotional videos.', 'https://renderforest.com', 'video-animation', 'Freemium', ARRAY['logo-animation', 'video-intros', 'promotional-videos'], false, false, 'https://renderforest.com/favicon.ico'),
  ('video-animaker', 'Animaker', 'AI-powered DIY animation platform for creating professional animated videos and presentations.', 'https://animaker.com', 'video-animation', 'Freemium', ARRAY['diy-animation', 'professional-videos', 'animated-presentations'], false, false, 'https://animaker.com/favicon.ico'),
  ('video-toonly', 'Toonly', 'AI animation software for creating whiteboard and doodle-style animated videos with ease.', 'https://toonly.com', 'video-animation', 'Paid', ARRAY['whiteboard-animation', 'doodle-style', 'easy-creation'], false, false, 'https://toonly.com/favicon.ico'),
  
  -- AI Character & Avatar Creation
  ('video-ready-player-me', 'Ready Player Me', 'AI-powered avatar creation platform that generates 3D characters from selfies for virtual environments.', 'https://readyplayer.me', 'video-animation', 'Free', ARRAY['avatar-creation', '3d-characters', 'virtual-environments'], false, false, 'https://readyplayer.me/favicon.ico'),
  ('video-metachat', 'MetaChat', 'AI avatar creation platform with realistic facial animations and expression mapping for video calls.', 'https://metachat.ai', 'video-animation', 'Freemium', ARRAY['realistic-avatars', 'facial-animations', 'expression-mapping'], false, false, 'https://metachat.ai/favicon.ico'),
  ('video-hour-one', 'Hour One', 'AI video creation platform with realistic human presenters and multilingual avatar capabilities.', 'https://hourone.ai', 'video-animation', 'Paid', ARRAY['human-presenters', 'multilingual-avatars', 'realistic-videos'], false, false, 'https://hourone.ai/favicon.ico'),
  ('video-d-id', 'D-ID', 'AI platform that creates talking avatars and videos from still images with natural facial movements.', 'https://d-id.com', 'video-animation', 'Freemium', ARRAY['talking-avatars', 'still-to-video', 'facial-movements'], false, false, 'https://d-id.com/favicon.ico'),
  ('video-colossyan', 'Colossyan Creator', 'AI video creation platform with AI actors, custom avatars, and automated video production.', 'https://colossyan.com', 'video-animation', 'Paid', ARRAY['ai-actors', 'custom-avatars', 'automated-production'], false, false, 'https://colossyan.com/favicon.ico'),
  ('video-elai', 'Elai.io', 'AI video generation platform with avatars, voice synthesis, and automated video creation from text.', 'https://elai.io', 'video-animation', 'Freemium', ARRAY['voice-synthesis', 'text-to-video', 'avatar-creation'], false, false, 'https://elai.io/favicon.ico'),
  ('video-movio', 'Movio', 'AI spokesperson video creator that generates professional marketing videos with virtual presenters.', 'https://movio.la', 'video-animation', 'Paid', ARRAY['spokesperson-videos', 'virtual-presenters', 'marketing-videos'], false, false, 'https://movio.la/favicon.ico'),
  ('video-vidnoz', 'Vidnoz AI', 'AI video generator with talking avatars, voice cloning, and automated video creation capabilities.', 'https://vidnoz.com', 'video-animation', 'Freemium', ARRAY['talking-avatars', 'voice-cloning', 'automated-creation'], false, false, 'https://vidnoz.com/favicon.ico'),
  ('video-rephrase-ai', 'Rephrase.ai', 'AI platform for creating personalized videos with digital avatars and natural speech synthesis.', 'https://rephrase.ai', 'video-animation', 'Paid', ARRAY['personalized-videos', 'digital-avatars', 'speech-synthesis'], false, false, 'https://rephrase.ai/favicon.ico'),
  ('video-deepbrain-ai', 'DeepBrain AI', 'AI video synthesis platform that creates realistic talking head videos from text input.', 'https://deepbrain.io', 'video-animation', 'Paid', ARRAY['video-synthesis', 'talking-heads', 'text-input'], false, false, 'https://deepbrain.io/favicon.ico'),
  
  -- AI Visual Effects & Compositing
  ('video-after-effects-ai', 'Adobe After Effects AI', 'Motion graphics and VFX software with AI-powered rotoscoping, tracking, and effect generation.', 'https://adobe.com/products/aftereffects', 'video-animation', 'Paid', ARRAY['motion-graphics', 'vfx', 'rotoscoping'], false, false, 'https://adobe.com/favicon.ico'),
  ('video-nuke-ai', 'Foundry Nuke AI', 'Professional compositing software with AI-powered paint tools and object removal capabilities.', 'https://foundry.com/products/nuke', 'video-animation', 'Paid', ARRAY['professional-compositing', 'paint-tools', 'object-removal'], false, false, 'https://foundry.com/favicon.ico'),
  ('video-mocha-pro', 'Boris FX Mocha Pro', 'Planar tracking and VFX software with AI-powered object removal and clean plate generation.', 'https://borisfx.com/products/mocha-pro', 'video-animation', 'Paid', ARRAY['planar-tracking', 'vfx', 'clean-plate-generation'], false, false, 'https://borisfx.com/favicon.ico'),
  ('video-silhouette-fx', 'SilhouetteFX', 'Advanced rotoscoping and paint software with AI-assisted masking and tracking tools.', 'https://silhouettefx.com', 'video-animation', 'Paid', ARRAY['rotoscoping', 'paint-software', 'ai-masking'], false, false, 'https://silhouettefx.com/favicon.ico'),
  ('video-remove-bg-video', 'Remove.bg Video', 'AI-powered background removal tool specifically designed for video content and green screen replacement.', 'https://remove.bg', 'video-animation', 'Freemium', ARRAY['background-removal', 'green-screen', 'video-processing'], false, false, 'https://remove.bg/favicon.ico'),
  ('video-unscreen', 'Unscreen', 'AI tool that automatically removes video backgrounds without green screen using advanced algorithms.', 'https://unscreen.com', 'video-animation', 'Freemium', ARRAY['automatic-removal', 'no-green-screen', 'advanced-algorithms'], false, false, 'https://unscreen.com/favicon.ico'),
  ('video-kapwing-bg-remover', 'Kapwing Background Remover', 'AI-powered video background removal tool with real-time processing and batch capabilities.', 'https://kapwing.com/tools/remove-background', 'video-animation', 'Freemium', ARRAY['real-time-processing', 'batch-capabilities', 'video-editing'], false, false, 'https://kapwing.com/favicon.ico'),
  ('video-pixverse', 'Pixverse', 'AI video generation platform with advanced visual effects and style transfer capabilities.', 'https://pixverse.ai', 'video-animation', 'Freemium', ARRAY['video-generation', 'visual-effects', 'style-transfer'], false, false, 'https://pixverse.ai/favicon.ico'),
  ('video-deepfacelive', 'DeepFaceLive', 'Real-time face swap technology for live streaming and video calls using deep learning.', 'https://github.com/iperov/DeepFaceLive', 'video-animation', 'Free', ARRAY['real-time-faceswap', 'live-streaming', 'deep-learning'], false, false, 'https://github.com/favicon.ico'),
  ('video-faceswapper', 'FaceSwapper', 'AI-powered face replacement tool for videos with automatic detection and seamless blending.', 'https://faceswapper.ai', 'video-animation', 'Freemium', ARRAY['face-replacement', 'automatic-detection', 'seamless-blending'], false, false, 'https://faceswapper.ai/favicon.ico'),
  
  -- AI Audio & Music for Video
  ('video-mubert', 'Mubert', 'AI music generation platform that creates royalty-free soundtracks for videos and content.', 'https://mubert.com', 'video-animation', 'Freemium', ARRAY['music-generation', 'royalty-free', 'soundtracks'], false, false, 'https://mubert.com/favicon.ico'),
  ('video-endel', 'Endel', 'AI-powered adaptive music platform that creates personalized soundscapes for focus and relaxation.', 'https://endel.io', 'video-animation', 'Freemium', ARRAY['adaptive-music', 'personalized-soundscapes', 'focus-music'], false, false, 'https://endel.io/favicon.ico'),
  ('video-aiva', 'AIVA', 'AI composer that creates original music for films, games, and video content with emotional intelligence.', 'https://aiva.ai', 'video-animation', 'Freemium', ARRAY['ai-composer', 'original-music', 'emotional-intelligence'], false, false, 'https://aiva.ai/favicon.ico'),
  ('video-boomy', 'Boomy', 'AI music creation platform that generates original songs and beats for video content creators.', 'https://boomy.com', 'video-animation', 'Freemium', ARRAY['music-creation', 'original-songs', 'content-creators'], false, false, 'https://boomy.com/favicon.ico'),
  ('video-soundraw', 'Soundraw', 'AI music generator that creates customizable royalty-free music for videos and multimedia projects.', 'https://soundraw.io', 'video-animation', 'Paid', ARRAY['music-generator', 'customizable-music', 'multimedia-projects'], false, false, 'https://soundraw.io/favicon.ico'),
  ('video-amper-music', 'Amper Music', 'AI music composition platform that creates adaptive soundtracks for video content and media.', 'https://ampermusic.com', 'video-animation', 'Paid', ARRAY['music-composition', 'adaptive-soundtracks', 'media-content'], false, false, 'https://ampermusic.com/favicon.ico'),
  ('video-eleven-labs', 'ElevenLabs', 'AI voice synthesis platform with realistic voice cloning and text-to-speech for video narration.', 'https://elevenlabs.io', 'video-animation', 'Freemium', ARRAY['voice-synthesis', 'voice-cloning', 'video-narration'], false, false, 'https://elevenlabs.io/favicon.ico'),
  ('video-murf-ai', 'Murf AI', 'AI voice generator with professional voiceovers in multiple languages for video content.', 'https://murf.ai', 'video-animation', 'Freemium', ARRAY['voice-generator', 'professional-voiceovers', 'multilingual'], false, false, 'https://murf.ai/favicon.ico'),
  ('video-resemble-ai', 'Resemble AI', 'AI voice cloning platform that creates synthetic voices for video dubbing and content creation.', 'https://resemble.ai', 'video-animation', 'Paid', ARRAY['voice-cloning', 'synthetic-voices', 'video-dubbing'], false, false, 'https://resemble.ai/favicon.ico'),
  ('video-wellsaid-labs', 'WellSaid Labs', 'AI voice platform that produces natural-sounding voiceovers for video and audio content.', 'https://wellsaidlabs.com', 'video-animation', 'Paid', ARRAY['natural-voiceovers', 'audio-content', 'voice-platform'], false, false, 'https://wellsaidlabs.com/favicon.ico'),
  
  -- AI Subtitle & Transcription
  ('video-rev-ai', 'Rev AI', 'AI-powered transcription and subtitle generation service with high accuracy and fast turnaround.', 'https://rev.ai', 'video-animation', 'Paid', ARRAY['transcription', 'subtitle-generation', 'high-accuracy'], false, false, 'https://rev.ai/favicon.ico'),
  ('video-otter-ai', 'Otter.ai', 'AI transcription service that creates real-time captions and subtitles for video content.', 'https://otter.ai', 'video-animation', 'Freemium', ARRAY['real-time-captions', 'transcription-service', 'video-content'], false, false, 'https://otter.ai/favicon.ico'),
  ('video-sonix', 'Sonix', 'AI transcription platform with automated subtitle generation and multi-language support.', 'https://sonix.ai', 'video-animation', 'Paid', ARRAY['automated-subtitles', 'multi-language', 'transcription-platform'], false, false, 'https://sonix.ai/favicon.ico'),
  ('video-happy-scribe', 'Happy Scribe', 'AI transcription and subtitle service with automatic translation and editing capabilities.', 'https://happyscribe.com', 'video-animation', 'Paid', ARRAY['automatic-translation', 'editing-capabilities', 'subtitle-service'], false, false, 'https://happyscribe.com/favicon.ico'),
  ('video-trint', 'Trint', 'AI transcription platform with collaborative editing and subtitle generation for video production.', 'https://trint.com', 'video-animation', 'Paid', ARRAY['collaborative-editing', 'video-production', 'transcription-platform'], false, false, 'https://trint.com/favicon.ico'),
  ('video-speechtext-ai', 'SpeechText.AI', 'AI transcription service with subtitle generation and speaker identification for video content.', 'https://speechtext.ai', 'video-animation', 'Freemium', ARRAY['speaker-identification', 'subtitle-generation', 'video-content'], false, false, 'https://speechtext.ai/favicon.ico'),
  ('video-subly', 'Subly', 'AI-powered subtitle generator with automatic translation and customizable styling options.', 'https://subly.app', 'video-animation', 'Freemium', ARRAY['automatic-translation', 'customizable-styling', 'subtitle-generator'], false, false, 'https://subly.app/favicon.ico'),
  ('video-zubtitle', 'Zubtitle', 'AI subtitle and caption generator specifically designed for social media video content.', 'https://zubtitle.com', 'video-animation', 'Paid', ARRAY['social-media-captions', 'caption-generator', 'video-content'], false, false, 'https://zubtitle.com/favicon.ico'),
  ('video-kapwing-subtitles', 'Kapwing Subtitles', 'AI-powered subtitle generator with automatic timing and multi-language support.', 'https://kapwing.com/subtitles', 'video-animation', 'Freemium', ARRAY['automatic-timing', 'multi-language-support', 'subtitle-generator'], false, false, 'https://kapwing.com/favicon.ico'),
  ('video-subtitle-edit', 'Subtitle Edit', 'AI-enhanced subtitle editing software with automatic synchronization and translation features.', 'https://nikse.dk/subtitleedit', 'video-animation', 'Free', ARRAY['subtitle-editing', 'automatic-sync', 'translation-features'], false, false, 'https://nikse.dk/favicon.ico'),
  
  -- AI Live Streaming & Broadcasting
  ('video-streamlabs', 'Streamlabs', 'AI-powered streaming software with automated scene switching and audience engagement tools.', 'https://streamlabs.com', 'video-animation', 'Freemium', ARRAY['streaming-software', 'scene-switching', 'audience-engagement'], false, false, 'https://streamlabs.com/favicon.ico'),
  ('video-obs-ai', 'OBS Studio AI Plugins', 'AI-enhanced broadcasting software with intelligent filters and automated production features.', 'https://obsproject.com', 'video-animation', 'Free', ARRAY['broadcasting-software', 'intelligent-filters', 'automated-production'], false, false, 'https://obsproject.com/favicon.ico'),
  ('video-restream', 'Restream', 'AI-powered multi-streaming platform with automated chat moderation and audience analytics.', 'https://restream.io', 'video-animation', 'Freemium', ARRAY['multi-streaming', 'chat-moderation', 'audience-analytics'], false, false, 'https://restream.io/favicon.ico'),
  ('video-riverside', 'Riverside', 'AI-enhanced remote recording platform with automatic transcription and progressive upload.', 'https://riverside.fm', 'video-animation', 'Paid', ARRAY['remote-recording', 'automatic-transcription', 'progressive-upload'], false, false, 'https://riverside.fm/favicon.ico'),
  ('video-mmhmm', 'mmhmm', 'AI-powered presentation software with virtual backgrounds and dynamic camera effects for streaming.', 'https://mmhmm.app', 'video-animation', 'Freemium', ARRAY['virtual-backgrounds', 'camera-effects', 'presentation-software'], false, false, 'https://mmhmm.app/favicon.ico'),
  ('video-camtasia-ai', 'Camtasia AI', 'Screen recording and video editing software with AI-powered automatic editing and enhancement.', 'https://techsmith.com/camtasia', 'video-animation', 'Paid', ARRAY['screen-recording', 'automatic-editing', 'video-enhancement'], false, false, 'https://techsmith.com/favicon.ico'),
  ('video-loom-ai', 'Loom AI', 'Screen recording platform with AI-powered video summarization and automatic transcription.', 'https://loom.com', 'video-animation', 'Freemium', ARRAY['screen-recording', 'video-summarization', 'automatic-transcription'], false, false, 'https://loom.com/favicon.ico'),
  ('video-be-live', 'BeLive', 'AI-enhanced live streaming platform with automated production and audience engagement features.', 'https://belive.tv', 'video-animation', 'Freemium', ARRAY['live-streaming', 'automated-production', 'audience-engagement'], false, false, 'https://belive.tv/favicon.ico'),
  ('video-wirecast', 'Wirecast', 'Professional live streaming software with AI-powered automation and multi-camera switching.', 'https://telestream.net/wirecast', 'video-animation', 'Paid', ARRAY['professional-streaming', 'automation', 'multi-camera'], false, false, 'https://telestream.net/favicon.ico'),
  ('video-vmix', 'vMix', 'Live production software with AI-enhanced features for automated switching and effects.', 'https://vmix.com', 'video-animation', 'Paid', ARRAY['live-production', 'automated-switching', 'ai-effects'], false, false, 'https://vmix.com/favicon.ico'),
  
  -- AI Video Analytics & Optimization
  ('video-vidiq', 'VidIQ', 'AI-powered YouTube analytics and optimization platform with keyword research and trend analysis.', 'https://vidiq.com', 'video-animation', 'Freemium', ARRAY['youtube-analytics', 'keyword-research', 'trend-analysis'], false, false, 'https://vidiq.com/favicon.ico'),
  ('video-tubebuddy', 'TubeBuddy', 'AI YouTube optimization toolkit with thumbnail testing, tag suggestions, and analytics.', 'https://tubebuddy.com', 'video-animation', 'Freemium', ARRAY['youtube-optimization', 'thumbnail-testing', 'tag-suggestions'], false, false, 'https://tubebuddy.com/favicon.ico'),
  ('video-social-blade', 'Social Blade', 'AI-powered social media analytics platform with video performance tracking and predictions.', 'https://socialblade.com', 'video-animation', 'Freemium', ARRAY['social-media-analytics', 'performance-tracking', 'predictions'], false, false, 'https://socialblade.com/favicon.ico'),
  ('video-wistia', 'Wistia', 'Video hosting platform with AI-powered analytics, viewer engagement tracking, and optimization tools.', 'https://wistia.com', 'video-animation', 'Paid', ARRAY['video-hosting', 'engagement-tracking', 'optimization-tools'], false, false, 'https://wistia.com/favicon.ico'),
  ('video-vimeo-ai', 'Vimeo AI', 'Video platform with AI-powered content analysis, automatic tagging, and performance insights.', 'https://vimeo.com', 'video-animation', 'Freemium', ARRAY['content-analysis', 'automatic-tagging', 'performance-insights'], false, false, 'https://vimeo.com/favicon.ico'),
  ('video-brightcove', 'Brightcove', 'Enterprise video platform with AI-powered content management and audience analytics.', 'https://brightcove.com', 'video-animation', 'Paid', ARRAY['enterprise-video', 'content-management', 'audience-analytics'], false, false, 'https://brightcove.com/favicon.ico'),
  ('video-jwplayer', 'JW Player', 'Video platform with AI-powered content delivery optimization and viewer analytics.', 'https://jwplayer.com', 'video-animation', 'Paid', ARRAY['content-delivery', 'optimization', 'viewer-analytics'], false, false, 'https://jwplayer.com/favicon.ico'),
  ('video-kaltura', 'Kaltura', 'Video management platform with AI-powered content analysis and automated workflows.', 'https://kaltura.com', 'video-animation', 'Paid', ARRAY['video-management', 'content-analysis', 'automated-workflows'], false, false, 'https://kaltura.com/favicon.ico'),
  ('video-panopto', 'Panopto', 'Video content management system with AI-powered search, transcription, and analytics.', 'https://panopto.com', 'video-animation', 'Paid', ARRAY['content-management', 'ai-search', 'transcription-analytics'], false, false, 'https://panopto.com/favicon.ico'),
  ('video-mediasite', 'Mediasite', 'Enterprise video platform with AI-enhanced content discovery and automated captioning.', 'https://sonicfoundry.com/mediasite', 'video-animation', 'Paid', ARRAY['enterprise-video', 'content-discovery', 'automated-captioning'], false, false, 'https://sonicfoundry.com/favicon.ico'),
  
  -- AI 3D Animation & Rendering
  ('video-blender-ai', 'Blender AI Add-ons', 'Open-source 3D software enhanced with AI plugins for automated rigging and animation.', 'https://blender.org', 'video-animation', 'Free', ARRAY['3d-software', 'ai-plugins', 'automated-rigging'], false, false, 'https://blender.org/favicon.ico'),
  ('video-maya-ai', 'Autodesk Maya AI', 'Professional 3D animation software with AI-powered character animation and motion prediction.', 'https://autodesk.com/products/maya', 'video-animation', 'Paid', ARRAY['professional-3d', 'character-animation', 'motion-prediction'], false, false, 'https://autodesk.com/favicon.ico'),
  ('video-cinema4d-ai', 'Cinema 4D AI', '3D modeling and animation software with AI-assisted workflows and automated processes.', 'https://maxon.net/cinema-4d', 'video-animation', 'Paid', ARRAY['3d-modeling', 'ai-workflows', 'automated-processes'], false, false, 'https://maxon.net/favicon.ico'),
  ('video-houdini-ai', 'SideFX Houdini AI', 'Procedural 3D animation software with AI-enhanced simulation and particle systems.', 'https://sidefx.com/products/houdini', 'video-animation', 'Paid', ARRAY['procedural-3d', 'ai-simulation', 'particle-systems'], false, false, 'https://sidefx.com/favicon.ico'),
  ('video-3ds-max-ai', '3ds Max AI', 'Professional 3D modeling software with AI-powered rendering optimization and scene analysis.', 'https://autodesk.com/products/3ds-max', 'video-animation', 'Paid', ARRAY['3d-modeling', 'rendering-optimization', 'scene-analysis'], false, false, 'https://autodesk.com/favicon.ico'),
  ('video-unity-ai', 'Unity AI', 'Game engine with AI-powered animation tools and machine learning integration for character behavior.', 'https://unity.com', 'video-animation', 'Freemium', ARRAY['game-engine', 'animation-tools', 'character-behavior'], false, false, 'https://unity.com/favicon.ico'),
  ('video-unreal-engine-ai', 'Unreal Engine AI', 'Game engine with AI-driven animation blueprints and real-time rendering capabilities.', 'https://unrealengine.com', 'video-animation', 'Free', ARRAY['game-engine', 'animation-blueprints', 'real-time-rendering'], false, false, 'https://unrealengine.com/favicon.ico'),
  ('video-octane-ai', 'Octane Render AI', 'GPU-accelerated rendering engine with AI-powered denoising and optimization features.', 'https://otoy.com/render/octane-render', 'video-animation', 'Paid', ARRAY['gpu-rendering', 'ai-denoising', 'optimization'], false, false, 'https://otoy.com/favicon.ico'),
  ('video-redshift-ai', 'Redshift AI', 'GPU-accelerated renderer with AI-enhanced noise reduction and adaptive sampling.', 'https://redshift3d.com', 'video-animation', 'Paid', ARRAY['gpu-renderer', 'noise-reduction', 'adaptive-sampling'], false, false, 'https://redshift3d.com/favicon.ico'),
  ('video-arnold-ai', 'Arnold AI', 'Monte Carlo ray tracing renderer with AI-powered adaptive sampling and denoising.', 'https://arnoldrenderer.com', 'video-animation', 'Paid', ARRAY['ray-tracing', 'adaptive-sampling', 'ai-denoising'], false, false, 'https://arnoldrenderer.com/favicon.ico'),
  
  -- AI Video Compression & Optimization
  ('video-handbrake-ai', 'HandBrake AI', 'Open-source video transcoder with AI-enhanced compression and quality optimization.', 'https://handbrake.fr', 'video-animation', 'Free', ARRAY['video-transcoder', 'compression', 'quality-optimization'], false, false, 'https://handbrake.fr/favicon.ico'),
  ('video-ffmpeg-ai', 'FFmpeg AI', 'Multimedia framework with AI-powered encoding optimization and format conversion.', 'https://ffmpeg.org', 'video-animation', 'Free', ARRAY['multimedia-framework', 'encoding-optimization', 'format-conversion'], false, false, 'https://ffmpeg.org/favicon.ico'),
  ('video-adobe-media-encoder', 'Adobe Media Encoder AI', 'Video encoding software with AI-powered compression and automated rendering workflows.', 'https://adobe.com/products/media-encoder', 'video-animation', 'Paid', ARRAY['video-encoding', 'automated-workflows', 'compression'], false, false, 'https://adobe.com/favicon.ico'),
  ('video-compressor-io', 'Compressor.io', 'AI-powered video compression tool that reduces file sizes while maintaining quality.', 'https://compressor.io', 'video-animation', 'Freemium', ARRAY['video-compression', 'file-size-reduction', 'quality-maintenance'], false, false, 'https://compressor.io/favicon.ico'),
  ('video-clideo-compressor', 'Clideo Video Compressor', 'Online AI video compressor with automatic quality adjustment and batch processing.', 'https://clideo.com/compress-video', 'video-animation', 'Freemium', ARRAY['online-compressor', 'quality-adjustment', 'batch-processing'], false, false, 'https://clideo.com/favicon.ico'),
  ('video-flexclip-compressor', 'FlexClip Compressor', 'AI video compression tool with smart quality preservation and format optimization.', 'https://flexclip.com/tools/compress-video', 'video-animation', 'Freemium', ARRAY['smart-compression', 'quality-preservation', 'format-optimization'], false, false, 'https://flexclip.com/favicon.ico'),
  ('video-wondershare-uniconverter', 'Wondershare UniConverter', 'AI video converter with intelligent compression and batch processing capabilities.', 'https://videoconverter.wondershare.com', 'video-animation', 'Paid', ARRAY['intelligent-compression', 'batch-processing', 'video-converter'], false, false, 'https://videoconverter.wondershare.com/favicon.ico'),
  ('video-movavi-converter', 'Movavi Video Converter', 'AI-enhanced video converter with automatic quality optimization and preset suggestions.', 'https://movavi.com/videoconverter', 'video-animation', 'Paid', ARRAY['automatic-optimization', 'preset-suggestions', 'video-converter'], false, false, 'https://movavi.com/favicon.ico'),
  ('video-any-video-converter', 'Any Video Converter AI', 'Video conversion software with AI-powered format detection and quality enhancement.', 'https://any-video-converter.com', 'video-animation', 'Freemium', ARRAY['format-detection', 'quality-enhancement', 'video-conversion'], false, false, 'https://any-video-converter.com/favicon.ico'),  ('video-freemake-converter', 'Freemake Video Converter', 'Free video converter with AI-assisted quality settings and format optimization.', 'https://freemake.com/free_video_converter', 'video-animation', 'Free', ARRAY['ai-quality-settings', 'format-optimization', 'free-converter'], false, false, 'https://freemake.com/favicon.ico'),
  ('video-fliki', 'Fliki', 'AI-powered platform that transforms text into engaging videos and audio content with automated voiceovers and visual creation.', 'https://fliki.ai', 'video-animation', 'Freemium', ARRAY['text-to-video', 'automated-voiceovers', 'audio-content', 'engaging-videos'], false, true, 'https://fliki.ai/favicon.ico'),
  ('video-opus-clip', 'Opus Clip', 'AI tool that efficiently creates eye-catching short clips from existing videos, ideal for social media content creation.', 'https://opus.pro', 'video-animation', 'Freemium', ARRAY['short-clips', 'social-media', 'video-editing', 'eye-catching'], false, true, 'https://opus.pro/favicon.ico'),
  ('video-heygen-podcast', 'HeyGen Podcast', 'AI tool for creating AI spokesperson videos with realistic avatars and natural speech synthesis.', 'https://heygen.com', 'video-animation', 'Freemium', ARRAY['ai-spokesperson', 'realistic-avatars', 'speech-synthesis', 'podcast-videos'], false, false, 'https://heygen.com/favicon.ico'),
  ('video-pika-2', 'Pika 2.0', 'Advanced AI tool for generating high-quality videos from images or text prompts with improved motion and realism.', 'https://pika.art', 'video-animation', 'Freemium', ARRAY['image-to-video', 'text-to-video', 'high-quality', 'motion-generation'], false, true, 'https://pika.art/favicon.ico'),
  ('video-beeble-ai', 'Beeble AI', 'AI tool that converts 2D footage into 3D for virtual lighting and effects editing in post-production workflows.', 'https://beeble.ai', 'video-animation', 'Paid', ARRAY['2d-to-3d', 'virtual-lighting', 'effects-editing', 'post-production'], false, false, 'https://beeble.ai/favicon.ico'),
  ('video-hailuo-ai', 'Hailuo AI Video', 'AI-powered video generation tool that creates videos from text descriptions or images with advanced AI models.', 'https://hailuo.ai', 'video-animation', 'Freemium', ARRAY['video-generation', 'text-to-video', 'image-to-video', 'advanced-ai'], false, false, 'https://hailuo.ai/favicon.ico'),
  ('video-infinity-ai', 'Infinity AI', 'AI tool specializing in creating character-driven videos with animated personas and storytelling capabilities.', 'https://infinity.ai', 'video-animation', 'Freemium', ARRAY['character-driven', 'animated-personas', 'storytelling', 'video-creation'], false, false, 'https://infinity.ai/favicon.ico'),
  ('video-10zebra', '10Zebra', 'AI-powered tool for creating and editing videos with storyboards, automated scene planning, and visual storytelling.', 'https://10zebra.com', 'video-animation', 'Freemium', ARRAY['storyboards', 'scene-planning', 'visual-storytelling', 'video-editing'], false, false, 'https://10zebra.com/favicon.ico'),
  ('video-aivideo-com', 'AIVideo.com', 'Comprehensive AI tool for video editing and creation with automated editing features and content optimization.', 'https://aivideo.com', 'video-animation', 'Freemium', ARRAY['video-editing', 'video-creation', 'automated-editing', 'content-optimization'], false, false, 'https://aivideo.com/favicon.ico'),
  ('video-retape-ai', 'Retape.ai', 'AI tool for creating and personalizing outreach videos for sales teams with automated customization and targeting.', 'https://retape.ai', 'video-animation', 'Paid', ARRAY['outreach-videos', 'sales-videos', 'personalization', 'automated-customization'], false, false, 'https://retape.ai/favicon.ico'),
  ('video-video-seal', 'Video Seal', 'AI tool that embeds imperceptible watermarks into videos to protect content and verify authenticity.', 'https://videoseal.com', 'video-animation', 'Paid', ARRAY['video-watermarking', 'content-protection', 'authenticity-verification', 'imperceptible-marks'], false, false, 'https://videoseal.com/favicon.ico'),
  ('video-jumper', 'Jumper', 'AI-powered video editing software for content search and workflow optimization with intelligent automation features.', 'https://jumper.ai', 'video-animation', 'Freemium', ARRAY['content-search', 'workflow-optimization', 'intelligent-automation', 'video-editing'], false, false, 'https://jumper.ai/favicon.ico')
ON CONFLICT (id, category_id) DO NOTHING;

-- Update the tool count for the category
UPDATE categories 
SET tool_count = (
  SELECT COUNT(*) 
  FROM tools 
  WHERE category_id = 'video-animation'
) 
WHERE id = 'video-animation';
