-- Interior & Architectural Design AI Tools (100 tools)
-- This script adds 100 AI-powered tools for interior and architectural design
-- Covers 3D modeling, room design, architectural visualization, space planning, and design automation
-- Uses ON CONFLICT (id, category_id) DO NOTHING to avoid duplicates within the same category

INSERT INTO tools (
  id, name, description, url, category_id, 
  pricing, tags, featured, trending, logo_url
) VALUES 
  -- AI Room & Interior Design Platforms
  ('interior-roomgpt', 'RoomGPT', 'AI-powered room redesign tool that transforms spaces using computer vision and generative AI for instant interior design suggestions.', 'https://roomgpt.io', 'interior-architectural-design', 'Free', ARRAY['room-redesign', 'computer-vision', 'generative-ai'], false, false, 'https://roomgpt.io/favicon.ico'),
  ('interior-homestyler', 'Homestyler AI', 'AI-enhanced interior design platform with 3D visualization, furniture placement, and automated room layout generation.', 'https://homestyler.com', 'interior-architectural-design', 'Freemium', ARRAY['3d-visualization', 'furniture-placement', 'room-layout'], false, false, 'https://homestyler.com/favicon.ico'),
  ('interior-planner5d-ai', 'Planner 5D AI', 'AI-powered home design software with intelligent room planning, furniture suggestions, and automated design optimization.', 'https://planner5d.com', 'interior-architectural-design', 'Freemium', ARRAY['home-design', 'room-planning', 'design-optimization'], false, false, 'https://planner5d.com/favicon.ico'),
  ('interior-roomsketcher-ai', 'RoomSketcher AI', 'AI-enhanced floor plan and interior design tool with smart furniture placement and automated space optimization.', 'https://roomsketcher.com', 'interior-architectural-design', 'Freemium', ARRAY['floor-plans', 'smart-furniture', 'space-optimization'], false, false, 'https://roomsketcher.com/favicon.ico'),
  ('interior-modsy', 'Modsy AI', 'AI-powered interior design service that creates photorealistic 3D renderings and personalized design recommendations.', 'https://modsy.com', 'interior-architectural-design', 'Paid', ARRAY['photorealistic-3d', 'personalized-design', 'design-service'], false, false, 'https://modsy.com/favicon.ico'),
  ('interior-havenly-ai', 'Havenly AI', 'AI-enhanced online interior design platform with style matching, room visualization, and automated design suggestions.', 'https://havenly.com', 'interior-architectural-design', 'Paid', ARRAY['style-matching', 'room-visualization', 'design-suggestions'], false, false, 'https://havenly.com/favicon.ico'),
  ('interior-spacely-ai', 'Spacely AI', 'AI-powered virtual reality interior design platform with immersive room visualization and intelligent design tools.', 'https://spacely.ai', 'interior-architectural-design', 'Paid', ARRAY['virtual-reality', 'immersive-visualization', 'intelligent-design'], false, false, 'https://spacely.ai/favicon.ico'),
  ('interior-decorilla-ai', 'Decorilla AI', 'AI-enhanced interior design platform connecting users with designers and providing automated design recommendations.', 'https://decorilla.com', 'interior-architectural-design', 'Paid', ARRAY['designer-matching', 'automated-recommendations', 'design-platform'], false, false, 'https://decorilla.com/favicon.ico'),
  
  -- AI Architectural Design & Modeling
  ('interior-finch3d', 'Finch 3D AI', 'AI-powered architectural design tool that generates building layouts, optimizes space usage, and automates design iterations.', 'https://finch3d.com', 'interior-architectural-design', 'Paid', ARRAY['architectural-design', 'building-layouts', 'space-optimization'], false, false, 'https://finch3d.com/favicon.ico'),
  ('interior-spacemaker', 'Spacemaker AI', 'AI-driven urban planning and architectural design platform with generative design and optimization algorithms.', 'https://spacemaker.ai', 'interior-architectural-design', 'Paid', ARRAY['urban-planning', 'generative-design', 'optimization-algorithms'], false, false, 'https://spacemaker.ai/favicon.ico'),
  ('interior-testfit', 'TestFit AI', 'AI-powered building design tool that generates optimal floor plans, maximizes unit counts, and automates design feasibility.', 'https://testfit.io', 'interior-architectural-design', 'Paid', ARRAY['building-design', 'floor-plans', 'design-feasibility'], false, false, 'https://testfit.io/favicon.ico'),
  ('interior-hypar', 'Hypar AI', 'AI-enhanced building design platform with algorithmic design generation, parametric modeling, and automated optimization.', 'https://hypar.io', 'interior-architectural-design', 'Freemium', ARRAY['algorithmic-design', 'parametric-modeling', 'automated-optimization'], false, false, 'https://hypar.io/favicon.ico'),
  ('interior-generative-design', 'Autodesk Generative Design', 'AI-powered generative design tool that explores thousands of design solutions based on constraints and goals.', 'https://autodesk.com/solutions/generative-design', 'interior-architectural-design', 'Paid', ARRAY['generative-design', 'design-exploration', 'constraint-based'], false, false, 'https://autodesk.com/favicon.ico'),
  ('interior-archicad-ai', 'Archicad AI Visualizer', 'AI-enhanced BIM software with intelligent object recognition, automated modeling, and design optimization features.', 'https://graphisoft.com/solutions/products/archicad', 'interior-architectural-design', 'Paid', ARRAY['bim-software', 'object-recognition', 'automated-modeling'], false, false, 'https://graphisoft.com/favicon.ico'),
  ('interior-revit-ai', 'Revit AI Tools', 'AI-powered extensions for Autodesk Revit with automated modeling, design optimization, and intelligent space planning.', 'https://autodesk.com/products/revit', 'interior-architectural-design', 'Paid', ARRAY['revit-extensions', 'automated-modeling', 'space-planning'], false, false, 'https://autodesk.com/favicon.ico'),
  ('interior-rhino-ai', 'Rhino Grasshopper AI', 'AI-enhanced parametric design tool with machine learning algorithms for architectural form generation and optimization.', 'https://rhino3d.com/grasshopper', 'interior-architectural-design', 'Paid', ARRAY['parametric-design', 'machine-learning', 'form-generation'], false, false, 'https://rhino3d.com/favicon.ico'),
  
  -- AI Furniture & Product Design
  ('interior-roomstyler-ai', 'Roomstyler AI', 'AI-powered furniture arrangement tool with style matching, color coordination, and automated room styling suggestions.', 'https://roomstyler.com', 'interior-architectural-design', 'Free', ARRAY['furniture-arrangement', 'style-matching', 'color-coordination'], false, false, 'https://roomstyler.com/favicon.ico'),
  ('interior-ikea-place', 'IKEA Place AI', 'AI-enhanced augmented reality app that uses machine learning for accurate furniture placement and size visualization.', 'https://ikea.com/us/en/customer-service/mobile-apps', 'interior-architectural-design', 'Free', ARRAY['augmented-reality', 'furniture-placement', 'size-visualization'], false, false, 'https://ikea.com/favicon.ico'),
  ('interior-wayfair-ai', 'Wayfair AI Visualizer', 'AI-powered furniture visualization tool with style recommendations, room matching, and automated design suggestions.', 'https://wayfair.com', 'interior-architectural-design', 'Free', ARRAY['furniture-visualization', 'style-recommendations', 'room-matching'], false, false, 'https://wayfair.com/favicon.ico'),
  ('interior-houzz-ai', 'Houzz AI Design', 'AI-enhanced home design platform with image recognition, style matching, and personalized product recommendations.', 'https://houzz.com', 'interior-architectural-design', 'Freemium', ARRAY['image-recognition', 'style-matching', 'product-recommendations'], false, false, 'https://houzz.com/favicon.ico'),
  ('interior-pottery-barn-ai', 'Pottery Barn AI Studio', 'AI-powered room design tool with furniture suggestions, style coordination, and automated layout generation.', 'https://potterybarn.com', 'interior-architectural-design', 'Free', ARRAY['room-design', 'furniture-suggestions', 'layout-generation'], false, false, 'https://potterybarn.com/favicon.ico'),
  ('interior-west-elm-ai', 'West Elm AI Designer', 'AI-enhanced interior design assistant with style analysis, furniture matching, and room optimization features.', 'https://westelm.com', 'interior-architectural-design', 'Free', ARRAY['style-analysis', 'furniture-matching', 'room-optimization'], false, false, 'https://westelm.com/favicon.ico'),
  ('interior-cb2-ai', 'CB2 AI Stylist', 'AI-powered styling tool that analyzes room photos and suggests furniture and decor combinations for modern spaces.', 'https://cb2.com', 'interior-architectural-design', 'Free', ARRAY['styling-tool', 'photo-analysis', 'modern-design'], false, false, 'https://cb2.com/favicon.ico'),
  ('interior-anthropologie-ai', 'Anthropologie AI Home', 'AI-enhanced home design assistant with bohemian style matching, pattern recognition, and curated recommendations.', 'https://anthropologie.com', 'interior-architectural-design', 'Free', ARRAY['bohemian-style', 'pattern-recognition', 'curated-recommendations'], false, false, 'https://anthropologie.com/favicon.ico'),
  
  -- AI Color & Material Selection
  ('interior-coolors-ai', 'Coolors AI Palette', 'AI-powered color palette generator for interior design with mood analysis, accessibility checking, and trend prediction.', 'https://coolors.co', 'interior-architectural-design', 'Freemium', ARRAY['color-palette', 'mood-analysis', 'trend-prediction'], false, false, 'https://coolors.co/favicon.ico'),
  ('interior-khroma-design', 'Khroma Design AI', 'AI color tool trained on design preferences that generates personalized color schemes for interior spaces.', 'https://khroma.co', 'interior-architectural-design', 'Free', ARRAY['personalized-colors', 'design-preferences', 'color-schemes'], false, false, 'https://khroma.co/favicon.ico'),
  ('interior-colormind-space', 'Colormind Space AI', 'AI-powered color scheme generator that creates harmonious palettes specifically for interior and architectural design.', 'http://colormind.io', 'interior-architectural-design', 'Free', ARRAY['color-schemes', 'harmonious-palettes', 'architectural-colors'], false, false, 'http://colormind.io/favicon.ico'),
  ('interior-sherwin-williams-ai', 'Sherwin-Williams ColorSnap AI', 'AI-enhanced color matching tool with room visualization, paint suggestions, and automated color coordination.', 'https://sherwin-williams.com/homeowners/color/color-tools/colorsnap-mobile', 'interior-architectural-design', 'Free', ARRAY['color-matching', 'room-visualization', 'paint-suggestions'], false, false, 'https://sherwin-williams.com/favicon.ico'),
  ('interior-benjamin-moore-ai', 'Benjamin Moore Personal Color Viewer', 'AI-powered paint color visualization tool with room analysis and personalized color recommendations.', 'https://benjaminmoore.com/en-us/color-overview/personal-color-viewer', 'interior-architectural-design', 'Free', ARRAY['paint-visualization', 'room-analysis', 'color-recommendations'], false, false, 'https://benjaminmoore.com/favicon.ico'),
  ('interior-behr-ai', 'Behr ColorSmart AI', 'AI-enhanced color selection tool with style matching, lighting analysis, and automated paint recommendations.', 'https://behr.com/colorsmart', 'interior-architectural-design', 'Free', ARRAY['color-selection', 'lighting-analysis', 'paint-recommendations'], false, false, 'https://behr.com/favicon.ico'),
  ('interior-dunn-edwards-ai', 'Dunn-Edwards AI Color', 'AI-powered color consultation tool with trend analysis, color psychology, and personalized palette creation.', 'https://dunnedwards.com', 'interior-architectural-design', 'Free', ARRAY['color-consultation', 'trend-analysis', 'color-psychology'], false, false, 'https://dunnedwards.com/favicon.ico'),
  ('interior-material-bank-ai', 'Material Bank AI', 'AI-enhanced material selection platform with automated matching, sustainability analysis, and design optimization.', 'https://materialbank.com', 'interior-architectural-design', 'Paid', ARRAY['material-selection', 'sustainability-analysis', 'design-optimization'], false, false, 'https://materialbank.com/favicon.ico'),
  
  -- AI Lighting Design & Analysis
  ('interior-dialux-ai', 'DIALux AI', 'AI-enhanced lighting design software with automated calculations, energy optimization, and intelligent fixture placement.', 'https://dialux.com', 'interior-architectural-design', 'Free', ARRAY['lighting-design', 'energy-optimization', 'fixture-placement'], false, false, 'https://dialux.com/favicon.ico'),
  ('interior-relux-ai', 'Relux AI Lighting', 'AI-powered lighting simulation tool with automatic optimization, daylight analysis, and energy efficiency calculations.', 'https://relux.com', 'interior-architectural-design', 'Paid', ARRAY['lighting-simulation', 'daylight-analysis', 'energy-efficiency'], false, false, 'https://relux.com/favicon.ico'),
  ('interior-lumion-ai', 'Lumion AI Lighting', 'AI-enhanced 3D rendering software with intelligent lighting simulation, atmosphere generation, and realistic visualization.', 'https://lumion.com', 'interior-architectural-design', 'Paid', ARRAY['3d-rendering', 'lighting-simulation', 'realistic-visualization'], false, false, 'https://lumion.com/favicon.ico'),
  ('interior-philips-ai', 'Philips Hue AI Designer', 'AI-powered smart lighting system with mood optimization, circadian rhythm matching, and automated scene creation.', 'https://philips-hue.com', 'interior-architectural-design', 'Paid', ARRAY['smart-lighting', 'mood-optimization', 'circadian-rhythm'], false, false, 'https://philips-hue.com/favicon.ico'),
  ('interior-lifx-ai', 'LIFX AI Themes', 'AI-enhanced smart lighting with color analysis, mood matching, and automated lighting scenes for interior spaces.', 'https://lifx.com', 'interior-architectural-design', 'Paid', ARRAY['smart-lighting', 'color-analysis', 'mood-matching'], false, false, 'https://lifx.com/favicon.ico'),
  ('interior-nanoleaf-ai', 'Nanoleaf AI Panels', 'AI-powered modular lighting system with pattern generation, music synchronization, and adaptive color schemes.', 'https://nanoleaf.me', 'interior-architectural-design', 'Paid', ARRAY['modular-lighting', 'pattern-generation', 'music-sync'], false, false, 'https://nanoleaf.me/favicon.ico'),
  ('interior-lutron-ai', 'Lutron AI Control', 'AI-enhanced lighting control system with automated scheduling, energy optimization, and personalized preferences.', 'https://lutron.com', 'interior-architectural-design', 'Paid', ARRAY['lighting-control', 'automated-scheduling', 'energy-optimization'], false, false, 'https://lutron.com/favicon.ico'),
  ('interior-ketra-ai', 'Ketra AI Lighting', 'AI-powered LED lighting system with natural light simulation, color temperature optimization, and health benefits.', 'https://ketra.com', 'interior-architectural-design', 'Paid', ARRAY['natural-light', 'color-temperature', 'health-benefits'], false, false, 'https://ketra.com/favicon.ico'),
  
  -- AI Space Planning & Layout
  ('interior-magicplan-ai', 'MagicPlan AI', 'AI-powered floor plan creation app using smartphone camera with automated measurements and space optimization.', 'https://magicplan.app', 'interior-architectural-design', 'Freemium', ARRAY['floor-plan-creation', 'automated-measurements', 'smartphone-camera'], false, false, 'https://magicplan.app/favicon.ico'),
  ('interior-floorplanner-ai', 'Floorplanner AI', 'AI-enhanced floor plan design tool with intelligent space allocation, furniture placement, and layout optimization.', 'https://floorplanner.com', 'interior-architectural-design', 'Freemium', ARRAY['floor-plan-design', 'space-allocation', 'layout-optimization'], false, false, 'https://floorplanner.com/favicon.ico'),
  ('interior-smartdraw-ai', 'SmartDraw AI Floor Plans', 'AI-powered diagramming software with automated floor plan generation, space analysis, and design suggestions.', 'https://smartdraw.com', 'interior-architectural-design', 'Paid', ARRAY['automated-floor-plans', 'space-analysis', 'design-suggestions'], false, false, 'https://smartdraw.com/favicon.ico'),
  ('interior-cedreo-ai', 'Cedreo AI Designer', 'AI-enhanced 3D home design software with automated floor plan creation and intelligent space planning.', 'https://cedreo.com', 'interior-architectural-design', 'Paid', ARRAY['3d-home-design', 'automated-floor-plans', 'space-planning'], false, false, 'https://cedreo.com/favicon.ico'),
  ('interior-punch-ai', 'Punch! Home Design AI', 'AI-powered home design software with intelligent layout suggestions, furniture placement, and design optimization.', 'https://punchsoftware.com', 'interior-architectural-design', 'Paid', ARRAY['home-design-software', 'layout-suggestions', 'furniture-placement'], false, false, 'https://punchsoftware.com/favicon.ico'),
  ('interior-chief-architect-ai', 'Chief Architect AI Tools', 'AI-enhanced architectural design software with automated framing, smart dimensions, and design optimization.', 'https://chiefarchitect.com', 'interior-architectural-design', 'Paid', ARRAY['architectural-software', 'automated-framing', 'smart-dimensions'], false, false, 'https://chiefarchitect.com/favicon.ico'),
  ('interior-sketchup-ai', 'SketchUp AI Extensions', 'AI-powered extensions for SketchUp with automated modeling, intelligent suggestions, and design optimization.', 'https://sketchup.com', 'interior-architectural-design', 'Freemium', ARRAY['sketchup-extensions', 'automated-modeling', 'intelligent-suggestions'], false, false, 'https://sketchup.com/favicon.ico'),
  ('interior-vectorworks-ai', 'Vectorworks AI Design', 'AI-enhanced CAD software with intelligent object recognition, automated drafting, and design optimization features.', 'https://vectorworks.net', 'interior-architectural-design', 'Paid', ARRAY['cad-software', 'object-recognition', 'automated-drafting'], false, false, 'https://vectorworks.net/favicon.ico'),
  
  -- AI Visualization & Rendering
  ('interior-vray-ai', 'V-Ray AI Denoiser', 'AI-powered rendering engine with intelligent noise reduction, automated lighting, and photorealistic visualization.', 'https://vray.com', 'interior-architectural-design', 'Paid', ARRAY['rendering-engine', 'noise-reduction', 'photorealistic'], false, false, 'https://vray.com/favicon.ico'),
  ('interior-corona-ai', 'Corona AI Renderer', 'AI-enhanced rendering software with automated optimization, intelligent sampling, and realistic material simulation.', 'https://corona-renderer.com', 'interior-architectural-design', 'Paid', ARRAY['rendering-software', 'automated-optimization', 'material-simulation'], false, false, 'https://corona-renderer.com/favicon.ico'),
  ('interior-octane-ai', 'Octane AI Render', 'AI-powered GPU rendering engine with machine learning acceleration, automated settings, and real-time visualization.', 'https://home.otoy.com/render/octane-render', 'interior-architectural-design', 'Paid', ARRAY['gpu-rendering', 'machine-learning', 'real-time-visualization'], false, false, 'https://home.otoy.com/favicon.ico'),
  ('interior-keyshot-ai', 'KeyShot AI', 'AI-enhanced 3D rendering software with intelligent material assignment, automated lighting, and design visualization.', 'https://keyshot.com', 'interior-architectural-design', 'Paid', ARRAY['3d-rendering', 'material-assignment', 'design-visualization'], false, false, 'https://keyshot.com/favicon.ico'),
  ('interior-enscape-ai', 'Enscape AI Rendering', 'AI-powered real-time rendering plugin with automated optimization, virtual reality support, and intelligent visualization.', 'https://enscape3d.com', 'interior-architectural-design', 'Paid', ARRAY['real-time-rendering', 'virtual-reality', 'intelligent-visualization'], false, false, 'https://enscape3d.com/favicon.ico'),
  ('interior-twinmotion-ai', 'Twinmotion AI', 'AI-enhanced real-time visualization software with automated scene generation, intelligent lighting, and immersive experiences.', 'https://twinmotion.unrealengine.com', 'interior-architectural-design', 'Free', ARRAY['real-time-visualization', 'scene-generation', 'immersive-experiences'], false, false, 'https://twinmotion.unrealengine.com/favicon.ico'),
  ('interior-blender-ai', 'Blender AI Cycles', 'AI-powered rendering engine within Blender with machine learning optimization, automated settings, and realistic rendering.', 'https://blender.org', 'interior-architectural-design', 'Free', ARRAY['blender-rendering', 'machine-learning', 'realistic-rendering'], false, false, 'https://blender.org/favicon.ico'),
  ('interior-cinema4d-ai', 'Cinema 4D AI Renderer', 'AI-enhanced 3D software with intelligent rendering, automated optimization, and design visualization capabilities.', 'https://maxon.net/cinema-4d', 'interior-architectural-design', 'Paid', ARRAY['3d-software', 'intelligent-rendering', 'design-visualization'], false, false, 'https://maxon.net/favicon.ico'),
  
  -- AI Sustainable & Green Design
  ('interior-green-building-ai', 'Green Building Studio AI', 'AI-powered energy analysis tool for sustainable design with automated optimization and environmental impact assessment.', 'https://gbs.autodesk.com', 'interior-architectural-design', 'Paid', ARRAY['energy-analysis', 'sustainable-design', 'environmental-impact'], false, false, 'https://gbs.autodesk.com/favicon.ico'),
  ('interior-equest-ai', 'eQUEST AI Energy', 'AI-enhanced building energy simulation software with automated modeling and sustainability optimization.', 'https://doe2.com/equest', 'interior-architectural-design', 'Free', ARRAY['energy-simulation', 'automated-modeling', 'sustainability'], false, false, 'https://doe2.com/favicon.ico'),
  ('interior-energyplus-ai', 'EnergyPlus AI', 'AI-powered building energy modeling with intelligent optimization, climate analysis, and performance prediction.', 'https://energyplus.net', 'interior-architectural-design', 'Free', ARRAY['energy-modeling', 'climate-analysis', 'performance-prediction'], false, false, 'https://energyplus.net/favicon.ico'),
  ('interior-iesve-ai', 'IES VE AI Analysis', 'AI-enhanced building performance analysis software with automated optimization and intelligent design recommendations.', 'https://iesve.com', 'interior-architectural-design', 'Paid', ARRAY['performance-analysis', 'automated-optimization', 'design-recommendations'], false, false, 'https://iesve.com/favicon.ico'),
  ('interior-openstudio-ai', 'OpenStudio AI', 'AI-powered energy modeling platform with automated analysis, optimization algorithms, and sustainability metrics.', 'https://openstudio.net', 'interior-architectural-design', 'Free', ARRAY['energy-modeling', 'optimization-algorithms', 'sustainability-metrics'], false, false, 'https://openstudio.net/favicon.ico'),
  ('interior-designbuilder-ai', 'DesignBuilder AI', 'AI-enhanced building simulation software with automated optimization, energy analysis, and environmental design.', 'https://designbuilder.co.uk', 'interior-architectural-design', 'Paid', ARRAY['building-simulation', 'energy-analysis', 'environmental-design'], false, false, 'https://designbuilder.co.uk/favicon.ico'),
  ('interior-honeybee-ai', 'Honeybee AI Tools', 'AI-powered environmental analysis tools for Grasshopper with automated calculations and optimization algorithms.', 'https://ladybug.tools/honeybee.html', 'interior-architectural-design', 'Free', ARRAY['environmental-analysis', 'grasshopper-tools', 'optimization-algorithms'], false, false, 'https://ladybug.tools/favicon.ico'),
  ('interior-climate-studio-ai', 'Climate Studio AI', 'AI-enhanced daylight and energy modeling software with automated analysis and intelligent design optimization.', 'https://climatestudio.com', 'interior-architectural-design', 'Paid', ARRAY['daylight-modeling', 'energy-modeling', 'design-optimization'], false, false, 'https://climatestudio.com/favicon.ico'),
  
  -- AI Virtual & Augmented Reality
  ('interior-oculus-ai', 'Oculus VR Design AI', 'AI-powered virtual reality platform for immersive interior design with intelligent object placement and spatial optimization.', 'https://oculus.com', 'interior-architectural-design', 'Paid', ARRAY['virtual-reality', 'immersive-design', 'spatial-optimization'], false, false, 'https://oculus.com/favicon.ico'),
  ('interior-htc-vive-ai', 'HTC Vive Design AI', 'AI-enhanced VR platform for architectural visualization with intelligent interaction and automated design suggestions.', 'https://vive.com', 'interior-architectural-design', 'Paid', ARRAY['vr-platform', 'architectural-visualization', 'intelligent-interaction'], false, false, 'https://vive.com/favicon.ico'),
  ('interior-hololens-ai', 'HoloLens AI Design', 'AI-powered mixed reality platform for spatial computing in interior design with intelligent object recognition.', 'https://hololens.com', 'interior-architectural-design', 'Paid', ARRAY['mixed-reality', 'spatial-computing', 'object-recognition'], false, false, 'https://hololens.com/favicon.ico'),
  ('interior-magic-leap-ai', 'Magic Leap AI Spaces', 'AI-enhanced augmented reality platform for spatial design with intelligent environment mapping and object placement.', 'https://magicleap.com', 'interior-architectural-design', 'Paid', ARRAY['augmented-reality', 'spatial-design', 'environment-mapping'], false, false, 'https://magicleap.com/favicon.ico'),
  ('interior-arkit-ai', 'ARKit AI Design', 'AI-powered augmented reality framework for iOS with intelligent plane detection and spatial understanding.', 'https://developer.apple.com/arkit', 'interior-architectural-design', 'Free', ARRAY['arkit-framework', 'plane-detection', 'spatial-understanding'], false, false, 'https://developer.apple.com/favicon.ico'),
  ('interior-arcore-ai', 'ARCore AI Tools', 'AI-enhanced augmented reality platform for Android with intelligent motion tracking and environmental understanding.', 'https://developers.google.com/ar', 'interior-architectural-design', 'Free', ARRAY['arcore-platform', 'motion-tracking', 'environmental-understanding'], false, false, 'https://developers.google.com/favicon.ico'),
  ('interior-unity-ai', 'Unity AI Visualization', 'AI-powered game engine for architectural visualization with intelligent rendering and automated scene optimization.', 'https://unity.com', 'interior-architectural-design', 'Freemium', ARRAY['game-engine', 'architectural-visualization', 'scene-optimization'], false, false, 'https://unity.com/favicon.ico'),
  ('interior-unreal-ai', 'Unreal Engine AI Arch', 'AI-enhanced game engine for architectural visualization with photorealistic rendering and intelligent optimization.', 'https://unrealengine.com', 'interior-architectural-design', 'Free', ARRAY['unreal-engine', 'photorealistic-rendering', 'intelligent-optimization'], false, false, 'https://unrealengine.com/favicon.ico'),
  
  -- AI Project Management & Collaboration
  ('interior-bim360-ai', 'BIM 360 AI', 'AI-powered construction management platform with intelligent project tracking, automated reporting, and design coordination.', 'https://autodesk.com/products/bim-360', 'interior-architectural-design', 'Paid', ARRAY['construction-management', 'project-tracking', 'design-coordination'], false, false, 'https://autodesk.com/favicon.ico'),
  ('interior-procore-ai', 'Procore AI Construction', 'AI-enhanced construction management software with intelligent scheduling, automated reporting, and project optimization.', 'https://procore.com', 'interior-architectural-design', 'Paid', ARRAY['construction-management', 'intelligent-scheduling', 'project-optimization'], false, false, 'https://procore.com/favicon.ico'),
  ('interior-buildertrend-ai', 'BuilderTrend AI', 'AI-powered construction management platform with automated workflows, intelligent tracking, and client communication.', 'https://buildertrend.com', 'interior-architectural-design', 'Paid', ARRAY['construction-platform', 'automated-workflows', 'client-communication'], false, false, 'https://buildertrend.com/favicon.ico'),
  ('interior-planswift-ai', 'PlanSwift AI Takeoff', 'AI-enhanced construction takeoff software with automated measurements, intelligent recognition, and cost estimation.', 'https://planswift.com', 'interior-architectural-design', 'Paid', ARRAY['construction-takeoff', 'automated-measurements', 'cost-estimation'], false, false, 'https://planswift.com/favicon.ico'),
  ('interior-bluebeam-ai', 'Bluebeam Revu AI', 'AI-powered PDF markup and collaboration tool for construction with intelligent document analysis and automated workflows.', 'https://bluebeam.com', 'interior-architectural-design', 'Paid', ARRAY['pdf-markup', 'document-analysis', 'automated-workflows'], false, false, 'https://bluebeam.com/favicon.ico'),
  ('interior-fieldwire-ai', 'Fieldwire AI Task', 'AI-enhanced construction task management with intelligent scheduling, automated reporting, and team coordination.', 'https://fieldwire.com', 'interior-architectural-design', 'Freemium', ARRAY['task-management', 'intelligent-scheduling', 'team-coordination'], false, false, 'https://fieldwire.com/favicon.ico'),
  ('interior-raken-ai', 'Raken AI Reports', 'AI-powered construction reporting software with automated data collection, intelligent analysis, and project insights.', 'https://rakenapp.com', 'interior-architectural-design', 'Paid', ARRAY['construction-reporting', 'data-collection', 'project-insights'], false, false, 'https://rakenapp.com/favicon.ico'),
  ('interior-smartsheet-ai', 'Smartsheet AI Construction', 'AI-enhanced project management platform with intelligent automation, resource optimization, and predictive analytics.', 'https://smartsheet.com', 'interior-architectural-design', 'Paid', ARRAY['project-management', 'resource-optimization', 'predictive-analytics'], false, false, 'https://smartsheet.com/favicon.ico'),
  
  -- AI Cost Estimation & Analysis
  ('interior-sage-ai', 'Sage Estimating AI', 'AI-powered construction estimating software with intelligent cost analysis, automated takeoffs, and predictive pricing.', 'https://sage.com/us/products/sage-estimating', 'interior-architectural-design', 'Paid', ARRAY['cost-estimation', 'automated-takeoffs', 'predictive-pricing'], false, false, 'https://sage.com/favicon.ico'),
  ('interior-buildertrend-estimating', 'BuilderTrend AI Estimating', 'AI-enhanced estimating tool with intelligent cost analysis, automated calculations, and market price predictions.', 'https://buildertrend.com/estimating', 'interior-architectural-design', 'Paid', ARRAY['cost-analysis', 'automated-calculations', 'price-predictions'], false, false, 'https://buildertrend.com/favicon.ico'),
  ('interior-coconstruct-ai', 'CoConstruct AI Estimating', 'AI-powered construction management with intelligent cost tracking, automated budgeting, and financial optimization.', 'https://coconstruct.com', 'interior-architectural-design', 'Paid', ARRAY['cost-tracking', 'automated-budgeting', 'financial-optimization'], false, false, 'https://coconstruct.com/favicon.ico'),
  ('interior-contractor-ai', 'Contractor Foreman AI', 'AI-enhanced project management software with intelligent cost estimation, automated scheduling, and resource planning.', 'https://contractorforeman.com', 'interior-architectural-design', 'Paid', ARRAY['cost-estimation', 'automated-scheduling', 'resource-planning'], false, false, 'https://contractorforeman.com/favicon.ico'),
  ('interior-jobprogress-ai', 'JobProgress AI', 'AI-powered CRM and project management for contractors with intelligent lead scoring and automated follow-ups.', 'https://jobprogress.com', 'interior-architectural-design', 'Paid', ARRAY['crm-project-management', 'lead-scoring', 'automated-follow-ups'], false, false, 'https://jobprogress.com/favicon.ico'),
  ('interior-housecall-ai', 'HouseCall Pro AI', 'AI-enhanced field service management with intelligent scheduling, automated dispatching, and customer optimization.', 'https://housecallpro.com', 'interior-architectural-design', 'Paid', ARRAY['field-service', 'intelligent-scheduling', 'customer-optimization'], false, false, 'https://housecallpro.com/favicon.ico'),
  ('interior-improveit-ai', 'ImproveIt 360 AI', 'AI-powered business management software for home improvement with intelligent lead management and sales optimization.', 'https://improveit360.com', 'interior-architectural-design', 'Paid', ARRAY['business-management', 'lead-management', 'sales-optimization'], false, false, 'https://improveit360.com/favicon.ico'),
  ('interior-acculynx-ai', 'AccuLynx AI Roofing', 'AI-enhanced roofing software with intelligent project management, automated workflows, and customer communication.', 'https://acculynx.com', 'interior-architectural-design', 'Paid', ARRAY['roofing-software', 'project-management', 'customer-communication'], false, false, 'https://acculynx.com/favicon.ico'),
  
  -- AI Material & Texture Generation
  ('interior-substance-ai', 'Substance 3D AI Materials', 'AI-powered material creation software with intelligent texture generation, automated mapping, and realistic surfaces.', 'https://substance3d.adobe.com', 'interior-architectural-design', 'Paid', ARRAY['material-creation', 'texture-generation', 'realistic-surfaces'], false, false, 'https://substance3d.adobe.com/favicon.ico'),
  ('interior-quixel-ai', 'Quixel Megascans AI', 'AI-enhanced photogrammetry library with intelligent material matching, automated optimization, and realistic textures.', 'https://quixel.com', 'interior-architectural-design', 'Freemium', ARRAY['photogrammetry', 'material-matching', 'realistic-textures'], false, false, 'https://quixel.com/favicon.ico'),
  ('interior-poliigon-ai', 'Poliigon AI Textures', 'AI-powered texture library with intelligent material suggestions, automated seamless tiling, and quality optimization.', 'https://poliigon.com', 'interior-architectural-design', 'Freemium', ARRAY['texture-library', 'seamless-tiling', 'quality-optimization'], false, false, 'https://poliigon.com/favicon.ico'),
  ('interior-arroway-ai', 'Arroway AI Textures', 'AI-enhanced material library with intelligent categorization, automated color matching, and realistic material simulation.', 'https://arroway-textures.ch', 'interior-architectural-design', 'Paid', ARRAY['material-library', 'color-matching', 'material-simulation'], false, false, 'https://arroway-textures.ch/favicon.ico'),
  ('interior-cgtrader-ai', 'CGTrader AI Materials', 'AI-powered 3D model and material marketplace with intelligent search, automated optimization, and quality assessment.', 'https://cgtrader.com', 'interior-architectural-design', 'Freemium', ARRAY['3d-marketplace', 'intelligent-search', 'quality-assessment'], false, false, 'https://cgtrader.com/favicon.ico'),
  ('interior-turbosquid-ai', 'TurboSquid AI Models', 'AI-enhanced 3D model marketplace with intelligent categorization, automated quality checks, and style matching.', 'https://turbosquid.com', 'interior-architectural-design', 'Freemium', ARRAY['3d-models', 'quality-checks', 'style-matching'], false, false, 'https://turbosquid.com/favicon.ico'),
  ('interior-design-connected-ai', 'Design Connected AI', 'AI-powered 3D model library for interior design with intelligent suggestions and automated scene integration.', 'https://designconnected.com', 'interior-architectural-design', 'Paid', ARRAY['3d-model-library', 'intelligent-suggestions', 'scene-integration'], false, false, 'https://designconnected.com/favicon.ico'),
  ('interior-polantis-ai', 'Polantis AI Models', 'AI-enhanced 3D furniture library with intelligent categorization, style matching, and automated optimization.', 'https://polantis.com', 'interior-architectural-design', 'Paid', ARRAY['furniture-library', 'style-matching', 'automated-optimization'], false, false, 'https://polantis.com/favicon.ico')
ON CONFLICT (id, category_id) DO NOTHING;

-- Update the tool count for the category
UPDATE categories 
SET tool_count = (
  SELECT COUNT(*) 
  FROM tools 
  WHERE category_id = 'interior-architectural-design'
) 
WHERE id = 'interior-architectural-design';
