-- Social Media AI Tools (105 tools)
-- This script adds 105 AI-powered tools for social media management, content creation, and analytics
-- Covers content creation, scheduling, analytics, influencer marketing, and social media optimization
-- Uses ON CONFLICT (id, category_id) DO NOTHING to avoid duplicates within the same category

INSERT INTO tools (
  id, name, description, url, category_id, 
  pricing, tags, featured, trending, logo_url
) VALUES 
  -- AI Content Creation & Writing
  ('social-jasper', 'Jasper AI', 'AI-powered content creation platform for social media posts, captions, and marketing copy with brand voice consistency.', 'https://jasper.ai', 'social-media', 'Paid', ARRAY['content-creation', 'ai-writing', 'brand-voice'], false, true, 'https://jasper.ai/favicon.ico'),
  ('social-copy-ai', 'Copy.ai', 'AI writing assistant that generates social media captions, posts, and marketing content for various platforms.', 'https://copy.ai', 'social-media', 'Freemium', ARRAY['ai-writing', 'captions', 'marketing-content'], false, true, 'https://copy.ai/favicon.ico'),
  ('social-writesonic', 'Writesonic', 'AI content generator for social media posts, ads, and marketing copy with multiple language support.', 'https://writesonic.com', 'social-media', 'Freemium', ARRAY['content-generator', 'multilingual', 'ads'], false, false, 'https://writesonic.com/favicon.ico'),
  ('social-rytr', 'Rytr', 'AI writing assistant for social media content, blog posts, and marketing copy with tone customization.', 'https://rytr.me', 'social-media', 'Freemium', ARRAY['writing-assistant', 'tone-customization', 'marketing'], false, false, 'https://rytr.me/favicon.ico'),
  ('social-simplified', 'Simplified AI Writer', 'AI-powered content creation tool for social media posts, stories, and marketing materials.', 'https://simplified.com', 'social-media', 'Freemium', ARRAY['content-creation', 'stories', 'marketing-materials'], false, false, 'https://simplified.com/favicon.ico'),
  ('social-peppertype', 'Peppertype AI', 'AI content assistant for creating engaging social media posts, captions, and marketing content.', 'https://peppertype.ai', 'social-media', 'Freemium', ARRAY['content-assistant', 'engaging-posts', 'captions'], false, false, 'https://peppertype.ai/favicon.ico'),
  ('social-shortlyai', 'ShortlyAI', 'AI writing partner for creating social media content, blog posts, and marketing copy with context understanding.', 'https://shortlyai.com', 'social-media', 'Paid', ARRAY['writing-partner', 'context-understanding', 'blog-posts'], false, false, 'https://shortlyai.com/favicon.ico'),
  ('social-contentbot', 'ContentBot AI', 'AI content automation platform for social media posts, blog content, and marketing materials.', 'https://contentbot.ai', 'social-media', 'Freemium', ARRAY['content-automation', 'blog-content', 'automation'], false, false, 'https://contentbot.ai/favicon.ico'),
  
  -- AI Visual Content Creation
  ('social-canva-ai', 'Canva AI', 'AI-powered design platform with smart templates, background removal, and automated design suggestions for social media.', 'https://canva.com', 'social-media', 'Freemium', ARRAY['design-platform', 'smart-templates', 'background-removal'], false, true, 'https://canva.com/favicon.ico'),
  ('social-crello', 'Crello AI', 'AI design tool for creating social media graphics, animations, and video content with smart suggestions.', 'https://crello.com', 'social-media', 'Freemium', ARRAY['design-tool', 'animations', 'video-content'], false, false, 'https://crello.com/favicon.ico'),
  ('social-designai', 'Designs.ai', 'AI-powered creative suite for logos, videos, and social media graphics with automated design generation.', 'https://designs.ai', 'social-media', 'Freemium', ARRAY['creative-suite', 'automated-design', 'logos'], false, false, 'https://designs.ai/favicon.ico'),
  ('social-autodraw', 'AutoDraw', 'AI drawing tool that turns sketches into professional graphics for social media and presentations.', 'https://autodraw.com', 'social-media', 'Free', ARRAY['drawing-tool', 'sketches', 'professional-graphics'], false, false, 'https://autodraw.com/favicon.ico'),
  ('social-remove-bg', 'Remove.bg', 'AI-powered background removal tool for creating clean social media images and product photos.', 'https://remove.bg', 'social-media', 'Freemium', ARRAY['background-removal', 'product-photos', 'image-editing'], false, false, 'https://remove.bg/favicon.ico'),
  ('social-artbreeder', 'Artbreeder', 'AI image generation and editing platform for creating unique social media visuals and artwork.', 'https://artbreeder.com', 'social-media', 'Freemium', ARRAY['image-generation', 'unique-visuals', 'artwork'], false, false, 'https://artbreeder.com/favicon.ico'),
  ('social-runway-ml', 'Runway ML', 'AI creative toolkit for video editing, image generation, and creative content for social media.', 'https://runwayml.com', 'social-media', 'Freemium', ARRAY['creative-toolkit', 'video-editing', 'image-generation'], false, false, 'https://runwayml.com/favicon.ico'),
  ('social-photor', 'Photor AI', 'AI photo analysis and optimization tool for selecting the best social media profile pictures and content.', 'https://photor.io', 'social-media', 'Freemium', ARRAY['photo-analysis', 'optimization', 'profile-pictures'], false, false, 'https://photor.io/favicon.ico'),
  
  -- AI Video Creation & Editing
  ('social-lumen5', 'Lumen5', 'AI video creation platform that transforms blog posts and content into engaging social media videos.', 'https://lumen5.com', 'social-media', 'Freemium', ARRAY['video-creation', 'blog-to-video', 'engaging-videos'], false, true, 'https://lumen5.com/favicon.ico'),
  ('social-pictory', 'Pictory AI', 'AI video generator that creates short social media videos from long-form content with automatic highlights.', 'https://pictory.ai', 'social-media', 'Freemium', ARRAY['video-generator', 'automatic-highlights', 'short-videos'], false, false, 'https://pictory.ai/favicon.ico'),
  ('social-synthesia', 'Synthesia', 'AI video platform for creating professional videos with AI avatars for social media and marketing.', 'https://synthesia.io', 'social-media', 'Paid', ARRAY['ai-avatars', 'professional-videos', 'marketing'], false, true, 'https://synthesia.io/favicon.ico'),
  ('social-vidiq', 'VidIQ AI', 'AI-powered YouTube optimization tool with keyword research, analytics, and content suggestions.', 'https://vidiq.com', 'social-media', 'Freemium', ARRAY['youtube-optimization', 'keyword-research', 'analytics'], false, false, 'https://vidiq.com/favicon.ico'),
  ('social-tubebuddy', 'TubeBuddy AI', 'AI YouTube channel management tool with thumbnail testing, SEO optimization, and analytics.', 'https://tubebuddy.com', 'social-media', 'Freemium', ARRAY['youtube-management', 'thumbnail-testing', 'seo-optimization'], false, false, 'https://tubebuddy.com/favicon.ico'),
  ('social-invideo', 'InVideo AI', 'AI video creation platform with smart templates, automated editing, and social media optimization.', 'https://invideo.io', 'social-media', 'Freemium', ARRAY['video-creation', 'smart-templates', 'automated-editing'], false, false, 'https://invideo.io/favicon.ico'),
  ('social-animoto', 'Animoto', 'AI video maker for creating social media videos with automated editing and music synchronization.', 'https://animoto.com', 'social-media', 'Freemium', ARRAY['video-maker', 'automated-editing', 'music-sync'], false, false, 'https://animoto.com/favicon.ico'),
  ('social-wisecut', 'Wisecut AI', 'AI video editor that automatically cuts long videos into short social media clips with smart editing.', 'https://wisecut.video', 'social-media', 'Freemium', ARRAY['video-editor', 'automatic-cutting', 'smart-editing'], false, false, 'https://wisecut.video/favicon.ico'),
  
  -- AI Social Media Scheduling & Management
  ('social-hootsuite-ai', 'Hootsuite Insights', 'AI-powered social media management with sentiment analysis, content recommendations, and automated scheduling.', 'https://hootsuite.com', 'social-media', 'Freemium', ARRAY['social-management', 'sentiment-analysis', 'automated-scheduling'], false, true, 'https://hootsuite.com/favicon.ico'),
  ('social-buffer-ai', 'Buffer AI Assistant', 'AI-enhanced social media scheduling tool with optimal posting times and content suggestions.', 'https://buffer.com', 'social-media', 'Freemium', ARRAY['scheduling-tool', 'optimal-timing', 'content-suggestions'], false, false, 'https://buffer.com/favicon.ico'),
  ('social-sprout-ai', 'Sprout Social AI', 'AI social media management platform with smart inbox, analytics, and content optimization.', 'https://sproutsocial.com', 'social-media', 'Paid', ARRAY['management-platform', 'smart-inbox', 'content-optimization'], false, false, 'https://sproutsocial.com/favicon.ico'),
  ('social-socialbee-ai', 'SocialBee AI', 'AI content categorization and scheduling tool for social media with evergreen content recycling.', 'https://socialbee.io', 'social-media', 'Freemium', ARRAY['content-categorization', 'evergreen-recycling', 'scheduling'], false, false, 'https://socialbee.io/favicon.ico'),
  ('social-later-ai', 'Later AI', 'AI visual content calendar with optimal posting suggestions and hashtag recommendations.', 'https://later.com', 'social-media', 'Freemium', ARRAY['visual-calendar', 'posting-suggestions', 'hashtag-recommendations'], false, false, 'https://later.com/favicon.ico'),
  ('social-crowdfire', 'Crowdfire AI', 'AI social media management tool with content curation, audience insights, and competitor analysis.', 'https://crowdfire.com', 'social-media', 'Freemium', ARRAY['content-curation', 'audience-insights', 'competitor-analysis'], false, false, 'https://crowdfire.com/favicon.ico'),
  ('social-agorapulse', 'Agorapulse AI', 'AI social media management platform with smart moderation, analytics, and team collaboration.', 'https://agorapulse.com', 'social-media', 'Freemium', ARRAY['smart-moderation', 'team-collaboration', 'analytics'], false, false, 'https://agorapulse.com/favicon.ico'),
  ('social-zoho-ai', 'Zoho Social AI', 'AI-powered social media management with predictive analytics and automated responses.', 'https://zoho.com/social', 'social-media', 'Freemium', ARRAY['predictive-analytics', 'automated-responses', 'management'], false, false, 'https://zoho.com/favicon.ico'),
  
  -- AI Analytics & Insights
  ('social-brandwatch', 'Brandwatch AI', 'AI social listening and analytics platform with sentiment analysis and trend detection.', 'https://brandwatch.com', 'social-media', 'Paid', ARRAY['social-listening', 'sentiment-analysis', 'trend-detection'], false, false, 'https://brandwatch.com/favicon.ico'),
  ('social-mention', 'Mention AI', 'AI-powered social media monitoring with brand mention tracking and sentiment analysis.', 'https://mention.com', 'social-media', 'Freemium', ARRAY['social-monitoring', 'brand-mentions', 'sentiment-analysis'], false, false, 'https://mention.com/favicon.ico'),
  ('social-socialmention', 'Social Mention', 'AI social media search and analysis tool with real-time monitoring and sentiment tracking.', 'https://socialmention.com', 'social-media', 'Free', ARRAY['social-search', 'real-time-monitoring', 'sentiment-tracking'], false, false, 'https://socialmention.com/favicon.ico'),
  ('social-keyhole', 'Keyhole AI', 'AI hashtag and keyword tracking tool with analytics, influencer identification, and campaign monitoring.', 'https://keyhole.co', 'social-media', 'Freemium', ARRAY['hashtag-tracking', 'influencer-identification', 'campaign-monitoring'], false, false, 'https://keyhole.co/favicon.ico'),
  ('social-talkwalker', 'Talkwalker AI', 'AI social media analytics with image recognition, crisis detection, and competitive intelligence.', 'https://talkwalker.com', 'social-media', 'Paid', ARRAY['image-recognition', 'crisis-detection', 'competitive-intelligence'], false, false, 'https://talkwalker.com/favicon.ico'),
  ('social-socialbakers', 'Socialbakers AI', 'AI social media marketing platform with audience analysis, content optimization, and influencer discovery.', 'https://socialbakers.com', 'social-media', 'Paid', ARRAY['audience-analysis', 'content-optimization', 'influencer-discovery'], false, false, 'https://socialbakers.com/favicon.ico'),
  ('social-quintly', 'Quintly AI', 'AI social media analytics tool with competitive benchmarking, custom dashboards, and automated reporting.', 'https://quintly.com', 'social-media', 'Freemium', ARRAY['competitive-benchmarking', 'custom-dashboards', 'automated-reporting'], false, false, 'https://quintly.com/favicon.ico'),
  ('social-fanpagekarma', 'Fanpage Karma', 'AI social media analytics with posting optimization, competitor analysis, and performance insights.', 'https://fanpagekarma.com', 'social-media', 'Freemium', ARRAY['posting-optimization', 'competitor-analysis', 'performance-insights'], false, false, 'https://fanpagekarma.com/favicon.ico'),
  
  -- AI Hashtag & SEO Tools
  ('social-hashtagify', 'Hashtagify AI', 'AI hashtag analytics and research tool with trending hashtags and influencer identification.', 'https://hashtagify.me', 'social-media', 'Freemium', ARRAY['hashtag-analytics', 'trending-hashtags', 'influencer-identification'], false, false, 'https://hashtagify.me/favicon.ico'),
  ('social-ritetag', 'RiteTag AI', 'AI hashtag suggestion tool with real-time hashtag scoring and engagement prediction.', 'https://ritetag.com', 'social-media', 'Freemium', ARRAY['hashtag-suggestions', 'real-time-scoring', 'engagement-prediction'], false, false, 'https://ritetag.com/favicon.ico'),
  ('social-tagboard', 'Tagboard AI', 'AI social media aggregation platform with hashtag campaigns and content curation.', 'https://tagboard.com', 'social-media', 'Freemium', ARRAY['content-aggregation', 'hashtag-campaigns', 'content-curation'], false, false, 'https://tagboard.com/favicon.ico'),
  ('social-hashtags-ai', 'Hashtags.ai', 'AI hashtag generator with platform-specific suggestions and engagement optimization.', 'https://hashtags.ai', 'social-media', 'Freemium', ARRAY['hashtag-generator', 'platform-specific', 'engagement-optimization'], false, false, 'https://hashtags.ai/favicon.ico'),
  ('social-sistrix', 'Sistrix Social', 'AI SEO and social media tool with hashtag analysis, trend tracking, and competitor monitoring.', 'https://sistrix.com', 'social-media', 'Paid', ARRAY['seo-social', 'hashtag-analysis', 'trend-tracking'], false, false, 'https://sistrix.com/favicon.ico'),
  ('social-buzzsumo', 'BuzzSumo AI', 'AI content research and social media analytics with viral content identification and influencer outreach.', 'https://buzzsumo.com', 'social-media', 'Freemium', ARRAY['content-research', 'viral-identification', 'influencer-outreach'], false, false, 'https://buzzsumo.com/favicon.ico'),
  ('social-semrush-social', 'SEMrush Social', 'AI social media toolkit with competitor analysis, hashtag research, and content planning.', 'https://semrush.com', 'social-media', 'Paid', ARRAY['competitor-analysis', 'hashtag-research', 'content-planning'], false, false, 'https://semrush.com/favicon.ico'),
  ('social-ahrefs-social', 'Ahrefs Social', 'AI social media research tool with backlink analysis, content explorer, and social signals tracking.', 'https://ahrefs.com', 'social-media', 'Paid', ARRAY['backlink-analysis', 'content-explorer', 'social-signals'], false, false, 'https://ahrefs.com/favicon.ico'),
  
  -- AI Influencer Marketing
  ('social-upfluence', 'Upfluence AI', 'AI influencer marketing platform with creator discovery, campaign management, and performance analytics.', 'https://upfluence.com', 'social-media', 'Paid', ARRAY['influencer-marketing', 'creator-discovery', 'campaign-management'], false, false, 'https://upfluence.com/favicon.ico'),
  ('social-grin', 'GRIN AI', 'AI influencer relationship management platform with creator matching and campaign optimization.', 'https://grin.co', 'social-media', 'Paid', ARRAY['relationship-management', 'creator-matching', 'campaign-optimization'], false, false, 'https://grin.co/favicon.ico'),
  ('social-klear', 'Klear AI', 'AI influencer marketing platform with audience analysis, fraud detection, and campaign tracking.', 'https://klear.com', 'social-media', 'Paid', ARRAY['audience-analysis', 'fraud-detection', 'campaign-tracking'], false, false, 'https://klear.com/favicon.ico'),
  ('social-hypeauditor', 'HypeAuditor AI', 'AI influencer analytics platform with fraud detection, audience quality analysis, and market insights.', 'https://hypeauditor.com', 'social-media', 'Freemium', ARRAY['influencer-analytics', 'fraud-detection', 'audience-quality'], false, false, 'https://hypeauditor.com/favicon.ico'),
  ('social-modash', 'Modash AI', 'AI influencer discovery and analytics platform with demographic insights and engagement analysis.', 'https://modash.io', 'social-media', 'Freemium', ARRAY['influencer-discovery', 'demographic-insights', 'engagement-analysis'], false, false, 'https://modash.io/favicon.ico'),
  ('social-aspire', 'AspireIQ', 'AI influencer marketing platform with creator relationship management and campaign automation.', 'https://aspireiq.com', 'social-media', 'Paid', ARRAY['creator-relationship', 'campaign-automation', 'influencer-marketing'], false, false, 'https://aspireiq.com/favicon.ico'),
  ('social-creator-co', 'Creator.co', 'AI influencer marketing platform with performance prediction and ROI optimization.', 'https://creator.co', 'social-media', 'Paid', ARRAY['performance-prediction', 'roi-optimization', 'influencer-platform'], false, false, 'https://creator.co/favicon.ico'),
  ('social-fourstarzz', 'Fourstarzz Media', 'AI influencer marketing agency platform with creator matching and campaign management.', 'https://fourstarzz.com', 'social-media', 'Paid', ARRAY['agency-platform', 'creator-matching', 'campaign-management'], false, false, 'https://fourstarzz.com/favicon.ico'),
  
  -- AI Chatbots & Customer Service
  ('social-chatfuel', 'Chatfuel AI', 'AI chatbot platform for Facebook Messenger and Instagram with automated customer service.', 'https://chatfuel.com', 'social-media', 'Freemium', ARRAY['chatbot-platform', 'messenger-instagram', 'customer-service'], false, false, 'https://chatfuel.com/favicon.ico'),
  ('social-manychat', 'ManyChat AI', 'AI conversation marketing platform with chatbots for Facebook, Instagram, and SMS.', 'https://manychat.com', 'social-media', 'Freemium', ARRAY['conversation-marketing', 'multi-platform-bots', 'sms-marketing'], false, false, 'https://manychat.com/favicon.ico'),
  ('social-mobilemonkey', 'MobileMonkey', 'AI chatbot builder for Facebook Messenger, Instagram, and SMS marketing automation.', 'https://mobilemonkey.com', 'social-media', 'Freemium', ARRAY['chatbot-builder', 'marketing-automation', 'multi-channel'], false, false, 'https://mobilemonkey.com/favicon.ico'),
  ('social-botsify', 'Botsify AI', 'AI chatbot platform for social media customer support with natural language processing.', 'https://botsify.com', 'social-media', 'Freemium', ARRAY['customer-support', 'natural-language', 'social-chatbots'], false, false, 'https://botsify.com/favicon.ico'),
  ('social-landbot', 'Landbot AI', 'AI conversational chatbot builder for social media lead generation and customer engagement.', 'https://landbot.io', 'social-media', 'Freemium', ARRAY['conversational-chatbot', 'lead-generation', 'customer-engagement'], false, false, 'https://landbot.io/favicon.ico'),
  ('social-botstar', 'Botstar AI', 'AI chatbot platform for Facebook Messenger with e-commerce integration and automation.', 'https://botstar.com', 'social-media', 'Freemium', ARRAY['messenger-bots', 'ecommerce-integration', 'automation'], false, false, 'https://botstar.com/favicon.ico'),
  ('social-octane-ai', 'Octane AI', 'AI quiz and chatbot platform for Shopify with social media integration and personalization.', 'https://octaneai.com', 'social-media', 'Freemium', ARRAY['quiz-platform', 'shopify-integration', 'personalization'], false, false, 'https://octaneai.com/favicon.ico'),
  ('social-gobot', 'Gobot AI', 'AI social media chatbot with lead capture, customer support, and marketing automation.', 'https://gobot.io', 'social-media', 'Freemium', ARRAY['lead-capture', 'customer-support', 'marketing-automation'], false, false, 'https://gobot.io/favicon.ico'),
  
  -- AI Community Management
  ('social-khoros', 'Khoros AI', 'AI social media management platform with community moderation and sentiment analysis.', 'https://khoros.com', 'social-media', 'Paid', ARRAY['community-moderation', 'sentiment-analysis', 'enterprise-social'], false, false, 'https://khoros.com/favicon.ico'),
  ('social-falcon-io', 'Falcon.io', 'AI social media marketing platform with content planning, publishing, and analytics.', 'https://falcon.io', 'social-media', 'Paid', ARRAY['content-planning', 'publishing', 'enterprise-analytics'], false, false, 'https://falcon.io/favicon.ico'),
  ('social-emplifi', 'Emplifi AI', 'AI social media management with automated moderation, crisis detection, and customer care.', 'https://emplifi.io', 'social-media', 'Paid', ARRAY['automated-moderation', 'crisis-detection', 'customer-care'], false, false, 'https://emplifi.io/favicon.ico'),
  ('social-oktopost', 'Oktopost AI', 'AI B2B social media management platform with lead attribution and employee advocacy.', 'https://oktopost.com', 'social-media', 'Paid', ARRAY['b2b-social', 'lead-attribution', 'employee-advocacy'], false, false, 'https://oktopost.com/favicon.ico'),
  ('social-sendible', 'Sendible AI', 'AI social media management tool with smart queues, content suggestions, and team collaboration.', 'https://sendible.com', 'social-media', 'Freemium', ARRAY['smart-queues', 'content-suggestions', 'team-collaboration'], false, false, 'https://sendible.com/favicon.ico'),
  ('social-socialpilot', 'SocialPilot AI', 'AI social media scheduling and analytics tool with team management and client reporting.', 'https://socialpilot.co', 'social-media', 'Freemium', ARRAY['team-management', 'client-reporting', 'scheduling'], false, false, 'https://socialpilot.co/favicon.ico'),
  ('social-eclincher', 'eClincher AI', 'AI social media management platform with auto-posting, inbox management, and analytics.', 'https://eclincher.com', 'social-media', 'Freemium', ARRAY['auto-posting', 'inbox-management', 'platform-analytics'], false, false, 'https://eclincher.com/favicon.ico'),
  ('social-postplanner', 'Post Planner AI', 'AI content discovery and social media scheduling tool with viral content prediction.', 'https://postplanner.com', 'social-media', 'Freemium', ARRAY['content-discovery', 'viral-prediction', 'scheduling'], false, false, 'https://postplanner.com/favicon.ico'),
  
  -- AI Personal Branding & LinkedIn
  ('social-shield-ai', 'Shield AI', 'AI LinkedIn analytics and content optimization tool for personal branding and professional networking.', 'https://shield.ai', 'social-media', 'Freemium', ARRAY['linkedin-analytics', 'personal-branding', 'professional-networking'], false, false, 'https://shield.ai/favicon.ico'),
  ('social-taplio', 'Taplio AI', 'AI LinkedIn growth tool with content inspiration, scheduling, and analytics for personal branding.', 'https://taplio.com', 'social-media', 'Freemium', ARRAY['linkedin-growth', 'content-inspiration', 'personal-branding'], false, false, 'https://taplio.com/favicon.ico'),
  ('social-linkeddatabase', 'LinkedDB AI', 'AI LinkedIn prospecting tool with lead generation, messaging automation, and CRM integration.', 'https://linkeddb.com', 'social-media', 'Paid', ARRAY['linkedin-prospecting', 'lead-generation', 'crm-integration'], false, false, 'https://linkeddb.com/favicon.ico'),
  ('social-phantombuster', 'PhantomBuster', 'AI automation tool for LinkedIn, Twitter, and other social platforms with data extraction and outreach.', 'https://phantombuster.com', 'social-media', 'Freemium', ARRAY['automation-tool', 'data-extraction', 'outreach'], false, false, 'https://phantombuster.com/favicon.ico'),
  ('social-waalaxy', 'Waalaxy AI', 'AI LinkedIn and email prospecting tool with automated sequences and lead generation.', 'https://waalaxy.com', 'social-media', 'Freemium', ARRAY['linkedin-prospecting', 'automated-sequences', 'lead-generation'], false, false, 'https://waalaxy.com/favicon.ico'),
  ('social-dripify', 'Dripify AI', 'AI LinkedIn automation tool with personalized messaging, connection requests, and analytics.', 'https://dripify.io', 'social-media', 'Paid', ARRAY['linkedin-automation', 'personalized-messaging', 'connection-automation'], false, false, 'https://dripify.io/favicon.ico'),
  ('social-expandi', 'Expandi AI', 'AI LinkedIn outreach platform with multi-channel campaigns and personalization at scale.', 'https://expandi.io', 'social-media', 'Paid', ARRAY['linkedin-outreach', 'multi-channel', 'personalization-scale'], false, false, 'https://expandi.io/favicon.ico'),
  ('social-lemlist', 'Lemlist AI', 'AI email and LinkedIn outreach tool with personalized videos, images, and automated follow-ups.', 'https://lemlist.com', 'social-media', 'Freemium', ARRAY['email-linkedin-outreach', 'personalized-videos', 'automated-followups'], false, false, 'https://lemlist.com/favicon.ico'),
  
  -- AI TikTok & Short-Form Video
  ('social-tiktok-ads-ai', 'TikTok Ads AI', 'AI advertising platform for TikTok with automated bidding, audience targeting, and creative optimization.', 'https://ads.tiktok.com', 'social-media', 'Freemium', ARRAY['tiktok-advertising', 'automated-bidding', 'creative-optimization'], false, true, 'https://ads.tiktok.com/favicon.ico'),
  ('social-pentos', 'Pentos AI', 'AI TikTok analytics and growth tool with hashtag optimization and content strategy recommendations.', 'https://pentos.ai', 'social-media', 'Freemium', ARRAY['tiktok-analytics', 'hashtag-optimization', 'content-strategy'], false, false, 'https://pentos.ai/favicon.ico'),
  ('social-creatopy', 'Creatopy AI', 'AI creative automation platform for social media ads with dynamic content and A/B testing.', 'https://creatopy.com', 'social-media', 'Freemium', ARRAY['creative-automation', 'dynamic-content', 'ab-testing'], false, false, 'https://creatopy.com/favicon.ico'),
  ('social-clipchamp', 'Clipchamp AI', 'AI video editor for social media content with automated editing and smart suggestions.', 'https://clipchamp.com', 'social-media', 'Freemium', ARRAY['video-editor', 'automated-editing', 'smart-suggestions'], false, false, 'https://clipchamp.com/favicon.ico'),
  ('social-kapwing', 'Kapwing AI', 'AI video editing platform for social media with smart cropping, subtitles, and meme generation.', 'https://kapwing.com', 'social-media', 'Freemium', ARRAY['video-editing', 'smart-cropping', 'meme-generation'], false, false, 'https://kapwing.com/favicon.ico'),
  ('social-fliki', 'Fliki AI', 'AI text-to-video platform for creating social media content with voiceovers and automated editing.', 'https://fliki.ai', 'social-media', 'Freemium', ARRAY['text-to-video', 'voiceovers', 'automated-editing'], false, false, 'https://fliki.ai/favicon.ico'),
  ('social-steve-ai', 'Steve AI', 'AI video creation platform for social media with animated characters and text-to-video conversion.', 'https://steve.ai', 'social-media', 'Freemium', ARRAY['video-creation', 'animated-characters', 'text-to-video'], false, false, 'https://steve.ai/favicon.ico'),
  ('social-rawshorts', 'RawShorts AI', 'AI animated video maker for social media marketing with drag-and-drop interface and smart templates.', 'https://rawshorts.com', 'social-media', 'Freemium', ARRAY['animated-video', 'drag-drop', 'smart-templates'], false, false, 'https://rawshorts.com/favicon.ico'),
  
  -- AI Social Commerce & Shopping
  ('social-yotpo', 'Yotpo AI', 'AI-powered social commerce platform with reviews, visual UGC, and social shopping features.', 'https://yotpo.com', 'social-media', 'Freemium', ARRAY['social-commerce', 'user-generated-content', 'social-shopping'], false, false, 'https://yotpo.com/favicon.ico'),
  ('social-bazaarvoice', 'Bazaarvoice AI', 'AI social commerce platform with review management, influencer marketing, and social selling.', 'https://bazaarvoice.com', 'social-media', 'Paid', ARRAY['review-management', 'social-selling', 'commerce-platform'], false, false, 'https://bazaarvoice.com/favicon.ico'),
  ('social-curalate', 'Curalate AI', 'AI visual commerce platform with social media integration, shoppable content, and analytics.', 'https://curalate.com', 'social-media', 'Paid', ARRAY['visual-commerce', 'shoppable-content', 'commerce-analytics'], false, false, 'https://curalate.com/favicon.ico'),
  ('social-pixlee', 'Pixlee TurnTo', 'AI visual marketing platform with user-generated content, social proof, and shoppable galleries.', 'https://pixlee.com', 'social-media', 'Paid', ARRAY['visual-marketing', 'social-proof', 'shoppable-galleries'], false, false, 'https://pixlee.com/favicon.ico'),
  ('social-olapic', 'Olapic AI', 'AI visual content platform with user-generated content curation and social commerce integration.', 'https://olapic.com', 'social-media', 'Paid', ARRAY['content-curation', 'social-commerce', 'visual-content'], false, false, 'https://olapic.com/favicon.ico'),
  ('social-taggbox', 'Taggbox AI', 'AI social media aggregation tool with user-generated content curation and social walls.', 'https://taggbox.com', 'social-media', 'Freemium', ARRAY['content-aggregation', 'social-walls', 'ugc-curation'], false, false, 'https://taggbox.com/favicon.ico'),
  ('social-flowbox', 'Flowbox AI', 'AI visual commerce platform with social media integration and user-generated content management.', 'https://flowbox.com', 'social-media', 'Paid', ARRAY['visual-commerce', 'ugc-management', 'social-integration'], false, false, 'https://flowbox.com/favicon.ico'),
  ('social-socialdatabase', 'Social Database', 'AI social media data platform with audience insights, competitor analysis, and trend tracking.', 'https://socialdatabase.com', 'social-media', 'Paid', ARRAY['social-data', 'audience-insights', 'trend-tracking'], false, false, 'https://socialdatabase.com/favicon.ico'),
  
  -- AI Social Media Compliance & Security
  ('social-proofpoint', 'Proofpoint Social', 'AI social media security platform with threat detection, compliance monitoring, and risk assessment.', 'https://proofpoint.com', 'social-media', 'Paid', ARRAY['security-platform', 'threat-detection', 'compliance-monitoring'], false, false, 'https://proofpoint.com/favicon.ico'),
  ('social-digital-shadows', 'Digital Shadows', 'AI social media monitoring for cybersecurity with brand protection and threat intelligence.', 'https://digitalshadows.com', 'social-media', 'Paid', ARRAY['cybersecurity-monitoring', 'brand-protection', 'threat-intelligence'], false, false, 'https://digitalshadows.com/favicon.ico'),
  ('social-zerofox', 'ZeroFOX AI', 'AI social media security platform with automated threat detection and incident response.', 'https://zerofox.com', 'social-media', 'Paid', ARRAY['security-platform', 'automated-threat-detection', 'incident-response'], false, false, 'https://zerofox.com/favicon.ico'),
  ('social-socialsafe', 'Social Safe AI', 'AI social media archiving and compliance platform with regulatory compliance and e-discovery.', 'https://socialsafe.net', 'social-media', 'Paid', ARRAY['social-archiving', 'regulatory-compliance', 'e-discovery'], false, false, 'https://socialsafe.net/favicon.ico'),
  ('social-crisp-thinking', 'Crisp Thinking', 'AI social media moderation platform with content filtering, sentiment analysis, and risk detection.', 'https://crispthinking.com', 'social-media', 'Paid', ARRAY['content-moderation', 'content-filtering', 'risk-detection'], false, false, 'https://crispthinking.com/favicon.ico')
ON CONFLICT (id, category_id) DO NOTHING;

-- Update the tool count for the category
UPDATE categories 
SET tool_count = (
  SELECT COUNT(*) 
  FROM tools 
  WHERE category_id = 'social-media'
) 
WHERE id = 'social-media';
