-- Music & Audio AI Tools (102 tools)
-- This script adds 102 AI-powered tools for music and audio
-- Covers music generation, audio editing, mastering, voice synthesis, and audio processing
-- Uses ON CONFLICT (id, category_id) DO NOTHING to avoid duplicates within the same category

INSERT INTO tools (
  id, name, description, url, category_id, 
  pricing, tags, featured, trending, logo_url
) VALUES 
  -- AI Music Generation & Composition (8 tools)
  ('music-suno-ai', 'Suno AI', 'AI music generator that creates original songs with vocals and instruments from text prompts and custom lyrics.', 'https://suno.ai', 'music-audio', 'Freemium', ARRAY['music-generation', 'ai-vocals', 'song-creation'], false, false, 'https://suno.ai/favicon.ico'),
  ('music-udio', 'Udio', 'AI music creation platform that generates high-quality music tracks across multiple genres from text descriptions.', 'https://udio.com', 'music-audio', 'Freemium', ARRAY['music-generation', 'multi-genre', 'text-to-music'], false, false, 'https://udio.com/favicon.ico'),
  ('music-mubert', 'Mubert', 'AI music generation platform that creates royalty-free background music for content creators and businesses.', 'https://mubert.com', 'music-audio', 'Freemium', ARRAY['background-music', 'royalty-free', 'content-creation'], false, false, 'https://mubert.com/favicon.ico'),
  ('music-aiva', 'AIVA', 'AI composer that creates original soundtracks for films, games, and commercials using deep learning algorithms.', 'https://aiva.ai', 'music-audio', 'Freemium', ARRAY['ai-composer', 'soundtracks', 'deep-learning'], false, false, 'https://aiva.ai/favicon.ico'),
  ('music-amper', 'Amper Music', 'AI music composition platform that generates custom music tracks for videos, podcasts, and other media content.', 'https://ampermusic.com', 'music-audio', 'Paid', ARRAY['custom-music', 'media-content', 'composition'], false, false, 'https://ampermusic.com/favicon.ico'),
  ('music-soundraw', 'Soundraw', 'AI music generator that creates original, royalty-free music tracks with customizable mood, genre, and length.', 'https://soundraw.io', 'music-audio', 'Freemium', ARRAY['royalty-free', 'customizable', 'mood-based'], false, false, 'https://soundraw.io/favicon.ico'),
  ('music-boomy', 'Boomy', 'AI music creation platform that allows users to generate original songs and submit them to streaming platforms.', 'https://boomy.com', 'music-audio', 'Freemium', ARRAY['song-creation', 'streaming-platform', 'original-music'], false, false, 'https://boomy.com/favicon.ico'),
  ('music-ecrett', 'Ecrett Music', 'AI music generator that creates royalty-free background music for videos, games, and podcasts.', 'https://ecrettmusic.com', 'music-audio', 'Freemium', ARRAY['background-music', 'video-games', 'podcasts'], false, false, 'https://ecrettmusic.com/favicon.ico'),
  
  -- AI Voice Synthesis & Text-to-Speech (8 tools)
  ('music-eleven-labs', 'ElevenLabs', 'AI voice synthesis platform that creates realistic human-like voices for audiobooks, podcasts, and content creation.', 'https://elevenlabs.io', 'music-audio', 'Freemium', ARRAY['voice-synthesis', 'realistic-voices', 'audiobooks'], false, false, 'https://elevenlabs.io/favicon.ico'),
  ('music-murf-ai', 'Murf AI', 'AI voice generator with 120+ realistic voices for voiceovers, presentations, and e-learning content.', 'https://murf.ai', 'music-audio', 'Freemium', ARRAY['voice-generator', 'voiceovers', 'e-learning'], false, false, 'https://murf.ai/favicon.ico'),
  ('music-speechify', 'Speechify', 'AI text-to-speech platform that converts text into natural-sounding audio with multiple voice options.', 'https://speechify.com', 'music-audio', 'Freemium', ARRAY['text-to-speech', 'natural-sounding', 'multiple-voices'], false, false, 'https://speechify.com/favicon.ico'),
  ('music-resemble-ai', 'Resemble AI', 'AI voice cloning and synthesis platform that creates custom voices for games, audiobooks, and assistants.', 'https://resemble.ai', 'music-audio', 'Paid', ARRAY['voice-cloning', 'custom-voices', 'assistants'], false, false, 'https://resemble.ai/favicon.ico'),
  ('music-replica-studios', 'Replica Studios', 'AI voice actor platform providing natural speech synthesis for games, films, and interactive media.', 'https://replicastudios.com', 'music-audio', 'Paid', ARRAY['voice-actor', 'natural-speech', 'interactive-media'], false, false, 'https://replicastudios.com/favicon.ico'),
  ('music-wellsaid-labs', 'WellSaid Labs', 'AI voice platform that creates human-like synthetic voices for corporate communications and e-learning.', 'https://wellsaidlabs.com', 'music-audio', 'Paid', ARRAY['synthetic-voices', 'corporate-communications', 'human-like'], false, false, 'https://wellsaidlabs.com/favicon.ico'),
  ('music-descript-overdub', 'Descript Overdub', 'AI voice cloning tool that creates synthetic versions of your voice for editing podcasts and videos.', 'https://descript.com', 'music-audio', 'Freemium', ARRAY['voice-cloning', 'podcast-editing', 'synthetic-voice'], false, false, 'https://descript.com/favicon.ico'),
  ('music-voicemod', 'Voicemod', 'AI voice changer and effects platform for gaming, streaming, and content creation with real-time processing.', 'https://voicemod.net', 'music-audio', 'Freemium', ARRAY['voice-changer', 'real-time', 'gaming-streaming'], false, false, 'https://voicemod.net/favicon.ico'),
  
  -- AI Audio Enhancement & Mastering (8 tools)
  ('music-landr', 'LANDR', 'AI-powered mastering service that automatically enhances and masters music tracks with professional quality.', 'https://landr.com', 'music-audio', 'Freemium', ARRAY['ai-mastering', 'professional-quality', 'automatic-enhancement'], false, false, 'https://landr.com/favicon.ico'),
  ('music-izotope-ozone', 'iZotope Ozone', 'AI-assisted mastering suite with intelligent EQ, dynamics, and stereo imaging for professional audio production.', 'https://izotope.com/ozone', 'music-audio', 'Paid', ARRAY['mastering-suite', 'intelligent-eq', 'professional-audio'], false, false, 'https://izotope.com/favicon.ico'),
  ('music-adobe-podcast', 'Adobe Podcast', 'AI-powered audio enhancement tool that removes background noise and improves speech quality automatically.', 'https://podcast.adobe.com', 'music-audio', 'Free', ARRAY['audio-enhancement', 'noise-removal', 'speech-quality'], false, false, 'https://podcast.adobe.com/favicon.ico'),
  ('music-dolby-on', 'Dolby On', 'AI audio recording and enhancement app that automatically optimizes audio quality for mobile content creation.', 'https://dolby.io/dolby-on', 'music-audio', 'Free', ARRAY['mobile-recording', 'automatic-optimization', 'content-creation'], false, false, 'https://dolby.io/favicon.ico'),
  ('music-krisp', 'Krisp', 'AI noise cancellation software that removes background noise from audio calls and recordings in real-time.', 'https://krisp.ai', 'music-audio', 'Freemium', ARRAY['noise-cancellation', 'real-time', 'audio-calls'], false, false, 'https://krisp.ai/favicon.ico'),
  ('music-audionamix', 'Audionamix', 'AI-powered audio separation technology that isolates vocals, drums, and instruments from mixed audio tracks.', 'https://audionamix.com', 'music-audio', 'Paid', ARRAY['audio-separation', 'vocal-isolation', 'instrument-extraction'], false, false, 'https://audionamix.com/favicon.ico'),
  ('music-lalal-ai', 'LALAL.AI', 'AI vocal and music separation service that extracts vocals, accompaniment, and individual instruments from audio files.', 'https://lalal.ai', 'music-audio', 'Freemium', ARRAY['vocal-separation', 'music-separation', 'instrument-isolation'], false, false, 'https://lalal.ai/favicon.ico'),
  ('music-splitter-ai', 'Splitter.ai', 'AI audio separation platform that splits songs into stems including vocals, bass, drums, and other instruments.', 'https://splitter.ai', 'music-audio', 'Freemium', ARRAY['audio-stems', 'song-splitting', 'instrument-separation'], false, false, 'https://splitter.ai/favicon.ico'),
  
  -- AI Podcast & Audio Editing (8 tools)
  ('music-descript', 'Descript', 'AI-powered audio and video editing platform with transcription, overdub, and collaborative editing features.', 'https://descript.com', 'music-audio', 'Freemium', ARRAY['audio-video-editing', 'transcription', 'collaborative'], false, false, 'https://descript.com/favicon.ico'),
  ('music-restream-studio', 'Restream Studio', 'AI-enhanced live streaming platform with audio mixing, effects, and automated production features.', 'https://restream.io/studio', 'music-audio', 'Freemium', ARRAY['live-streaming', 'audio-mixing', 'automated-production'], false, false, 'https://restream.io/favicon.ico'),
  ('music-riverside-fm', 'Riverside.fm', 'AI-powered podcast recording platform with automatic transcription, editing suggestions, and quality enhancement.', 'https://riverside.fm', 'music-audio', 'Freemium', ARRAY['podcast-recording', 'automatic-transcription', 'quality-enhancement'], false, false, 'https://riverside.fm/favicon.ico'),
  ('music-castmagic', 'Castmagic', 'AI podcast production tool that automatically generates show notes, transcripts, and social media content from audio.', 'https://castmagic.io', 'music-audio', 'Paid', ARRAY['podcast-production', 'show-notes', 'social-media-content'], false, false, 'https://castmagic.io/favicon.ico'),
  ('music-otter-ai', 'Otter.ai', 'AI transcription service that converts audio recordings to text with speaker identification and keyword search.', 'https://otter.ai', 'music-audio', 'Freemium', ARRAY['transcription', 'speaker-identification', 'keyword-search'], false, false, 'https://otter.ai/favicon.ico'),
  ('music-cleanvoice-ai', 'Cleanvoice AI', 'AI audio editing tool that automatically removes filler words, mouth sounds, and dead air from recordings.', 'https://cleanvoice.ai', 'music-audio', 'Paid', ARRAY['audio-cleaning', 'filler-removal', 'automatic-editing'], false, false, 'https://cleanvoice.ai/favicon.ico'),
  ('music-podcastle', 'Podcastle', 'AI podcast creation platform with recording, editing, transcription, and text-to-speech capabilities.', 'https://podcastle.ai', 'music-audio', 'Freemium', ARRAY['podcast-creation', 'recording-editing', 'text-to-speech'], false, false, 'https://podcastle.ai/favicon.ico'),
  ('music-squadcast', 'SquadCast', 'AI-enhanced remote podcast recording platform with automatic backup, transcription, and quality optimization.', 'https://squadcast.fm', 'music-audio', 'Paid', ARRAY['remote-recording', 'automatic-backup', 'quality-optimization'], false, false, 'https://squadcast.fm/favicon.ico'),
  
  -- AI Music Production & DAW Integration (8 tools)
  ('music-orb-producer', 'Orb Producer Suite', 'AI music production plugins that generate melodies, basslines, arpeggios, and chord progressions automatically.', 'https://orbplugins.com', 'music-audio', 'Paid', ARRAY['music-production', 'melody-generation', 'chord-progressions'], false, false, 'https://orbplugins.com/favicon.ico'),
  ('music-captain-plugins', 'Captain Plugins', 'AI music theory plugins that help producers create chord progressions, melodies, and basslines with musical intelligence.', 'https://mixedinkey.com/captain-plugins', 'music-audio', 'Paid', ARRAY['music-theory', 'chord-progressions', 'musical-intelligence'], false, false, 'https://mixedinkey.com/favicon.ico'),
  ('music-algonaut-atlas', 'Algonaut Atlas', 'AI drum machine that uses machine learning to find and organize drum samples based on sonic similarity.', 'https://algonaut.audio', 'music-audio', 'Paid', ARRAY['drum-machine', 'machine-learning', 'sample-organization'], false, false, 'https://algonaut.audio/favicon.ico'),
  ('music-output-arcade', 'Output Arcade', 'AI-powered sample player with smart recommendations and automatic loop matching for music production.', 'https://output.com/arcade', 'music-audio', 'Paid', ARRAY['sample-player', 'smart-recommendations', 'loop-matching'], false, false, 'https://output.com/favicon.ico'),
  ('music-neutone', 'Neutone', 'AI audio plugin platform that uses neural networks for creative sound design and audio processing.', 'https://neutone.space', 'music-audio', 'Freemium', ARRAY['neural-networks', 'sound-design', 'audio-processing'], false, false, 'https://neutone.space/favicon.ico'),
  ('music-baby-audio', 'Baby Audio AI', 'AI-enhanced audio plugins for mixing and mastering with intelligent processing and automatic parameter adjustment.', 'https://babyaud.io', 'music-audio', 'Paid', ARRAY['mixing-mastering', 'intelligent-processing', 'automatic-adjustment'], false, false, 'https://babyaud.io/favicon.ico'),
  ('music-plugin-alliance', 'Plugin Alliance AI', 'AI-powered mixing and mastering plugins with automatic settings and intelligent audio enhancement.', 'https://plugin-alliance.com', 'music-audio', 'Paid', ARRAY['mixing-mastering-plugins', 'automatic-settings', 'audio-enhancement'], false, false, 'https://plugin-alliance.com/favicon.ico'),
  ('music-sonible-smart', 'sonible smart:', 'AI audio plugins that automatically analyze and optimize EQ, dynamics, and reverb settings for professional mixes.', 'https://sonible.com', 'music-audio', 'Paid', ARRAY['automatic-optimization', 'eq-dynamics', 'professional-mixing'], false, false, 'https://sonible.com/favicon.ico'),
  
  -- AI Music Discovery & Recommendation (8 tools)
  ('music-spotify-ai', 'Spotify AI DJ', 'AI-powered music recommendation system that creates personalized playlists and provides DJ-style commentary.', 'https://spotify.com', 'music-audio', 'Freemium', ARRAY['music-recommendation', 'personalized-playlists', 'dj-commentary'], false, false, 'https://spotify.com/favicon.ico'),
  ('music-pandora-ai', 'Pandora AI', 'AI music discovery platform that analyzes musical DNA to recommend songs based on user preferences and listening habits.', 'https://pandora.com', 'music-audio', 'Freemium', ARRAY['music-discovery', 'musical-dna', 'listening-habits'], false, false, 'https://pandora.com/favicon.ico'),
  ('music-lastfm-ai', 'Last.fm AI', 'AI music recommendation engine that tracks listening habits and suggests new music based on user preferences.', 'https://last.fm', 'music-audio', 'Free', ARRAY['music-recommendation', 'listening-tracking', 'preference-based'], false, false, 'https://last.fm/favicon.ico'),
  ('music-endel', 'Endel', 'AI music app that generates adaptive soundscapes for focus, relaxation, and sleep based on biometric data.', 'https://endel.io', 'music-audio', 'Freemium', ARRAY['adaptive-music', 'biometric-data', 'focus-relaxation'], false, false, 'https://endel.io/favicon.ico'),
  ('music-brain-fm', 'Brain.fm', 'AI-generated music designed to enhance focus, relaxation, and sleep using neuroscience-based algorithms.', 'https://brain.fm', 'music-audio', 'Paid', ARRAY['neuroscience-based', 'focus-enhancement', 'algorithm-generated'], false, false, 'https://brain.fm/favicon.ico'),
  ('music-songfinch', 'Songfinch', 'AI-assisted custom song creation platform that connects users with musicians to create personalized songs.', 'https://songfinch.com', 'music-audio', 'Paid', ARRAY['custom-songs', 'personalized-music', 'musician-collaboration'], false, false, 'https://songfinch.com/favicon.ico'),
  ('music-jukebox-openai', 'Jukebox by OpenAI', 'AI music generation model that creates music with singing in various genres and artist styles.', 'https://openai.com/blog/jukebox', 'music-audio', 'Free', ARRAY['music-generation', 'ai-singing', 'artist-styles'], false, false, 'https://openai.com/favicon.ico'),
  ('music-moodpath', 'Moodpath Music', 'AI-powered mood-based music recommendation system that suggests songs based on emotional state and context.', 'https://moodpath.com', 'music-audio', 'Freemium', ARRAY['mood-based', 'emotional-state', 'context-aware'], false, false, 'https://moodpath.com/favicon.ico'),
  
  -- AI Audio Analysis & Recognition (8 tools)
  ('music-shazam', 'Shazam', 'AI music recognition app that identifies songs, TV shows, and ads using audio fingerprinting technology.', 'https://shazam.com', 'music-audio', 'Free', ARRAY['music-recognition', 'audio-fingerprinting', 'song-identification'], false, false, 'https://shazam.com/favicon.ico'),
  ('music-soundhound', 'SoundHound', 'AI music recognition platform that identifies songs through humming, singing, or playing, with voice search capabilities.', 'https://soundhound.com', 'music-audio', 'Free', ARRAY['music-recognition', 'humming-detection', 'voice-search'], false, false, 'https://soundhound.com/favicon.ico'),
  ('music-acrcloud', 'ACRCloud', 'AI audio recognition service that identifies music, speech, and audio content for businesses and developers.', 'https://acrcloud.com', 'music-audio', 'Freemium', ARRAY['audio-recognition', 'content-identification', 'business-solutions'], false, false, 'https://acrcloud.com/favicon.ico'),
  ('music-gracenote', 'Gracenote', 'AI music data platform that provides music recognition, metadata, and content discovery for entertainment platforms.', 'https://gracenote.com', 'music-audio', 'Paid', ARRAY['music-data', 'metadata', 'content-discovery'], false, false, 'https://gracenote.com/favicon.ico'),
  ('music-musixmatch', 'Musixmatch', 'AI-powered lyrics recognition and synchronization platform with real-time lyric display and translation.', 'https://musixmatch.com', 'music-audio', 'Freemium', ARRAY['lyrics-recognition', 'real-time-sync', 'translation'], false, false, 'https://musixmatch.com/favicon.ico'),
  ('music-chartmetric', 'Chartmetric', 'AI music analytics platform that tracks streaming data, social media metrics, and industry insights for artists.', 'https://chartmetric.com', 'music-audio', 'Paid', ARRAY['music-analytics', 'streaming-data', 'industry-insights'], false, false, 'https://chartmetric.com/favicon.ico'),
  ('music-viberate', 'Viberate', 'AI music industry analytics platform providing data insights for artists, venues, and music professionals.', 'https://viberate.com', 'music-audio', 'Freemium', ARRAY['industry-analytics', 'data-insights', 'music-professionals'], false, false, 'https://viberate.com/favicon.ico'),
  ('music-ircam-amplify', 'IRCAM Amplify', 'AI audio analysis tools for music information retrieval, audio feature extraction, and machine learning research.', 'https://ircam-amplify.com', 'music-audio', 'Paid', ARRAY['audio-analysis', 'feature-extraction', 'machine-learning'], false, false, 'https://ircam-amplify.com/favicon.ico'),
  
  -- AI Live Performance & DJing (8 tools)
  ('music-djay-pro-ai', 'djay Pro AI', 'AI-powered DJ software with neural mix technology for real-time stem separation and intelligent mixing.', 'https://djay.com', 'music-audio', 'Paid', ARRAY['dj-software', 'neural-mix', 'real-time-separation'], false, false, 'https://djay.com/favicon.ico'),
  ('music-virtual-dj-ai', 'VirtualDJ AI', 'AI-enhanced DJ software with automatic beatmatching, harmonic mixing, and intelligent song suggestions.', 'https://virtualdj.com', 'music-audio', 'Freemium', ARRAY['dj-software', 'automatic-beatmatching', 'harmonic-mixing'], false, false, 'https://virtualdj.com/favicon.ico'),
  ('music-serato-dj', 'Serato DJ', 'AI-assisted DJ software with smart cues, automatic BPM detection, and intelligent playlist creation.', 'https://serato.com', 'music-audio', 'Freemium', ARRAY['dj-software', 'smart-cues', 'automatic-bpm'], false, false, 'https://serato.com/favicon.ico'),
  ('music-pioneer-rekordbox', 'Pioneer rekordbox', 'AI-powered DJ preparation software with intelligent playlist creation, key detection, and mixing suggestions.', 'https://rekordbox.com', 'music-audio', 'Freemium', ARRAY['dj-preparation', 'key-detection', 'mixing-suggestions'], false, false, 'https://rekordbox.com/favicon.ico'),
  ('music-mixed-in-key', 'Mixed In Key', 'AI harmonic mixing software that analyzes musical keys and provides intelligent song matching for DJs.', 'https://mixedinkey.com', 'music-audio', 'Paid', ARRAY['harmonic-mixing', 'key-analysis', 'song-matching'], false, false, 'https://mixedinkey.com/favicon.ico'),
  ('music-pacemaker', 'Pacemaker', 'AI DJ app that automatically mixes music with beat matching, crossfading, and intelligent transitions.', 'https://pacemaker.net', 'music-audio', 'Freemium', ARRAY['automatic-mixing', 'beat-matching', 'intelligent-transitions'], false, false, 'https://pacemaker.net/favicon.ico'),
  ('music-cross-dj', 'Cross DJ', 'AI-enhanced mobile DJ app with automatic mixing, BPM detection, and smart playlist management.', 'https://crossdj.com', 'music-audio', 'Freemium', ARRAY['mobile-dj', 'automatic-mixing', 'smart-playlists'], false, false, 'https://crossdj.com/favicon.ico'),
  ('music-mixxx', 'Mixxx', 'AI-integrated open-source DJ software with automatic beatmatching, harmonic mixing, and effects processing.', 'https://mixxx.org', 'music-audio', 'Free', ARRAY['open-source', 'beatmatching', 'effects-processing'], false, false, 'https://mixxx.org/favicon.ico'),
  
  -- AI Sound Design & Synthesis (8 tools)
  ('music-roli-equator2', 'ROLI Equator2', 'AI-enhanced software synthesizer with MPE support and intelligent sound morphing capabilities.', 'https://roli.com/products/software/equator2', 'music-audio', 'Freemium', ARRAY['software-synthesizer', 'mpe-support', 'sound-morphing'], false, false, 'https://roli.com/favicon.ico'),
  ('music-arturia-pigments', 'Arturia Pigments', 'AI-assisted wavetable synthesizer with intelligent preset generation and morphing capabilities.', 'https://arturia.com/products/analog-classics/pigments', 'music-audio', 'Paid', ARRAY['wavetable-synthesizer', 'preset-generation', 'morphing'], false, false, 'https://arturia.com/favicon.ico'),
  ('music-native-massive-x', 'Native Instruments Massive X', 'AI-enhanced wavetable synthesizer with intelligent routing and modern sound design capabilities.', 'https://native-instruments.com/products/komplete/synths/massive-x', 'music-audio', 'Paid', ARRAY['wavetable-synth', 'intelligent-routing', 'sound-design'], false, false, 'https://native-instruments.com/favicon.ico'),
  ('music-xfer-serum', 'Xfer Serum', 'AI-integrated wavetable synthesizer with visual feedback and intelligent sound manipulation features.', 'https://xferrecords.com/products/serum', 'music-audio', 'Paid', ARRAY['wavetable-synth', 'visual-feedback', 'sound-manipulation'], false, false, 'https://xferrecords.com/favicon.ico'),
  ('music-spectrasonics-omnisphere', 'Spectrasonics Omnisphere', 'AI-powered flagship synthesizer with intelligent sample manipulation and synthesis capabilities.', 'https://spectrasonics.net/products/omnisphere', 'music-audio', 'Paid', ARRAY['flagship-synthesizer', 'sample-manipulation', 'synthesis'], false, false, 'https://spectrasonics.net/favicon.ico'),
  ('music-u-he-diva', 'u-he Diva', 'AI-enhanced virtual analog synthesizer with intelligent modeling of classic analog circuits.', 'https://u-he.com/products/diva', 'music-audio', 'Paid', ARRAY['virtual-analog', 'circuit-modeling', 'classic-synths'], false, false, 'https://u-he.com/favicon.ico'),
  ('music-kilohearts-phase-plant', 'Kilohearts Phase Plant', 'AI-assisted modular synthesizer with intelligent routing and semi-modular architecture.', 'https://kilohearts.com/products/phase_plant', 'music-audio', 'Paid', ARRAY['modular-synthesizer', 'intelligent-routing', 'semi-modular'], false, false, 'https://kilohearts.com/favicon.ico'),
  ('music-vital-synth', 'Vital Synth', 'AI-enhanced spectral warping wavetable synthesizer with visual feedback and intelligent sound design.', 'https://vital.audio', 'music-audio', 'Freemium', ARRAY['spectral-warping', 'wavetable', 'visual-feedback'], false, false, 'https://vital.audio/favicon.ico'),
  
  -- AI Music Learning & Education (8 tools)
  ('music-flowkey', 'Flowkey', 'AI-powered piano learning app that listens to acoustic piano playing and provides real-time feedback.', 'https://flowkey.com', 'music-audio', 'Freemium', ARRAY['piano-learning', 'real-time-feedback', 'acoustic-listening'], false, false, 'https://flowkey.com/favicon.ico'),
  ('music-simply-piano', 'Simply Piano', 'AI music learning app that recognizes acoustic and digital piano playing for interactive lessons.', 'https://simplypiano.com', 'music-audio', 'Freemium', ARRAY['music-learning', 'piano-recognition', 'interactive-lessons'], false, false, 'https://simplypiano.com/favicon.ico'),
  ('music-yousician', 'Yousician', 'AI-powered music education platform that teaches guitar, piano, bass, ukulele, and singing with interactive lessons.', 'https://yousician.com', 'music-audio', 'Freemium', ARRAY['music-education', 'multi-instrument', 'interactive-learning'], false, false, 'https://yousician.com/favicon.ico'),
  ('music-smartmusic', 'SmartMusic', 'AI-enhanced music education software with intelligent accompaniment and assessment for students and teachers.', 'https://smartmusic.com', 'music-audio', 'Paid', ARRAY['music-education', 'intelligent-accompaniment', 'assessment'], false, false, 'https://smartmusic.com/favicon.ico'),
  ('music-melodics', 'Melodics', 'AI-powered music learning platform for pad drumming, finger drumming, and keyboard skills with adaptive difficulty.', 'https://melodics.com', 'music-audio', 'Freemium', ARRAY['music-learning', 'drumming-keyboard', 'adaptive-difficulty'], false, false, 'https://melodics.com/favicon.ico'),
  ('music-tonegym', 'Tonegym', 'AI-assisted ear training and music theory app that adapts to user skill level and progress.', 'https://tonegym.co', 'music-audio', 'Freemium', ARRAY['ear-training', 'music-theory', 'adaptive-learning'], false, false, 'https://tonegym.co/favicon.ico'),
  ('music-perfect-ear', 'Perfect Ear', 'AI-enhanced ear training app with interval recognition, chord identification, and scale practice.', 'https://perfectear.app', 'music-audio', 'Freemium', ARRAY['ear-training', 'interval-recognition', 'chord-identification'], false, false, 'https://perfectear.app/favicon.ico'),
  ('music-functional-ear-trainer', 'Functional Ear Trainer', 'AI-powered ear training app focused on functional harmony and relative pitch development.', 'https://functionaleartrainer.com', 'music-audio', 'Free', ARRAY['functional-harmony', 'relative-pitch', 'ear-development'], false, false, 'https://functionaleartrainer.com/favicon.ico'),
  
  -- AI Music Business & Rights Management (8 tools)
  ('music-tunecore-ai', 'TuneCore AI', 'AI-powered music distribution platform with intelligent metadata optimization and royalty collection.', 'https://tunecore.com', 'music-audio', 'Paid', ARRAY['music-distribution', 'metadata-optimization', 'royalty-collection'], false, false, 'https://tunecore.com/favicon.ico'),
  ('music-distrokid', 'DistroKid', 'AI-enhanced music distribution service with automatic playlist pitching and revenue optimization.', 'https://distrokid.com', 'music-audio', 'Paid', ARRAY['music-distribution', 'playlist-pitching', 'revenue-optimization'], false, false, 'https://distrokid.com/favicon.ico'),
  ('music-cd-baby', 'CD Baby', 'AI-powered music distribution and rights management platform with intelligent promotion tools.', 'https://cdbaby.com', 'music-audio', 'Paid', ARRAY['music-distribution', 'rights-management', 'promotion-tools'], false, false, 'https://cdbaby.com/favicon.ico'),
  ('music-ascap-ace', 'ASCAP ACE', 'AI-enhanced performing rights organization system for royalty tracking and distribution management.', 'https://ascap.com', 'music-audio', 'Free', ARRAY['performing-rights', 'royalty-tracking', 'distribution-management'], false, false, 'https://ascap.com/favicon.ico'),
  ('music-bmi-repertoire', 'BMI Repertoire', 'AI-powered music rights database with intelligent search and royalty distribution capabilities.', 'https://bmi.com', 'music-audio', 'Free', ARRAY['music-rights', 'intelligent-search', 'royalty-distribution'], false, false, 'https://bmi.com/favicon.ico'),
  ('music-soundexchange', 'SoundExchange', 'AI-enhanced digital performance royalty collection service for recording artists and record labels.', 'https://soundexchange.com', 'music-audio', 'Free', ARRAY['digital-royalties', 'performance-rights', 'artist-services'], false, false, 'https://soundexchange.com/favicon.ico'),
  ('music-music-reports', 'Music Reports MRI', 'AI-powered music rights information system for licensing and royalty administration.', 'https://musicreports.com', 'music-audio', 'Paid', ARRAY['music-rights', 'licensing', 'royalty-administration'], false, false, 'https://musicreports.com/favicon.ico'),
  ('music-haawk', 'Haawk', 'AI-powered music rights management and YouTube monetization platform for content creators and rights holders.', 'https://haawk.com', 'music-audio', 'Freemium', ARRAY['rights-management', 'youtube-monetization', 'content-creators'], false, false, 'https://haawk.com/favicon.ico'),
  
  -- AI Audio Hardware Integration (6 tools)
  ('music-teenage-engineering-op-1', 'Teenage Engineering OP-1', 'AI-enhanced portable synthesizer workstation with intelligent sequencing and sound generation.', 'https://teenage.engineering/products/op-1', 'music-audio', 'Paid', ARRAY['portable-synthesizer', 'intelligent-sequencing', 'workstation'], false, false, 'https://teenage.engineering/favicon.ico'),
  ('music-elektron-digitakt', 'Elektron Digitakt', 'AI-assisted drum machine and sampler with intelligent pattern generation and sound manipulation.', 'https://elektron.se/products/digitakt', 'music-audio', 'Paid', ARRAY['drum-machine', 'pattern-generation', 'sound-manipulation'], false, false, 'https://elektron.se/favicon.ico'),
  ('music-ableton-push', 'Ableton Push', 'AI-integrated hardware controller with intelligent chord and scale suggestions for music production.', 'https://ableton.com/push', 'music-audio', 'Paid', ARRAY['hardware-controller', 'chord-suggestions', 'music-production'], false, false, 'https://ableton.com/favicon.ico'),
  ('music-native-maschine', 'Native Instruments Maschine', 'AI-powered drum machine and sampler with intelligent pattern suggestions and sound matching.', 'https://native-instruments.com/products/maschine', 'music-audio', 'Paid', ARRAY['drum-machine-sampler', 'pattern-suggestions', 'sound-matching'], false, false, 'https://native-instruments.com/favicon.ico'),
  ('music-arturia-drumbrute', 'Arturia DrumBrute', 'AI-enhanced analog drum machine with intelligent pattern generation and sound synthesis.', 'https://arturia.com/products/hardware-synths/drumbrute-impact', 'music-audio', 'Paid', ARRAY['analog-drum-machine', 'pattern-generation', 'sound-synthesis'], false, false, 'https://arturia.com/favicon.ico'),
  ('music-roland-tr-8s', 'Roland TR-8S', 'AI-assisted drum machine with intelligent pattern variations and automatic sound matching capabilities.', 'https://roland.com/products/tr-8s', 'music-audio', 'Paid', ARRAY['drum-machine', 'pattern-variations', 'automatic-matching'], false, false, 'https://roland.com/favicon.ico')
ON CONFLICT (id, category_id) DO NOTHING;

-- Update the tool count for the category
UPDATE categories 
SET tool_count = (
  SELECT COUNT(*) 
  FROM tools 
  WHERE category_id = 'music-audio'
) 
WHERE id = 'music-audio';
