-- Office & Productivity AI Tools (105 tools)
-- This script adds 105 AI-powered tools for office and productivity
-- Covers writing, project management, document processing, automation, collaboration, and productivity enhancement
-- Uses ON CONFLICT (id, category_id) DO NOTHING to avoid duplicates within the same category

INSERT INTO tools (
  id, name, description, url, category_id, 
  pricing, tags, featured, trending, logo_url
) VALUES 
  -- AI Writing & Text Generation (15 tools)
  ('office-jasper-ai', 'Jasper AI', 'AI-powered writing assistant that creates high-quality content, blog posts, marketing copy, and business documents with advanced language models.', 'https://jasper.ai', 'office-productivity', 'Paid', ARRAY['ai-writing', 'content-creation', 'marketing-copy'], false, false, 'https://jasper.ai/favicon.ico'),
  ('office-copy-ai', 'Copy.ai', 'AI copywriting tool that generates marketing content, social media posts, product descriptions, and email campaigns using advanced AI models.', 'https://copy.ai', 'office-productivity', 'Freemium', ARRAY['copywriting', 'marketing-content', 'ai-generation'], false, false, 'https://copy.ai/favicon.ico'),
  ('office-writesonic', 'Writesonic', 'AI writing platform that creates articles, ads, product descriptions, and landing page copy with SEO optimization and multiple language support.', 'https://writesonic.com', 'office-productivity', 'Freemium', ARRAY['ai-writing', 'seo-optimization', 'content-generation'], false, false, 'https://writesonic.com/favicon.ico'),
  ('office-rytr', 'Rytr', 'AI writing assistant that generates emails, blog posts, ad copy, and creative content with tone and style customization options.', 'https://rytr.me', 'office-productivity', 'Freemium', ARRAY['ai-writing', 'tone-customization', 'creative-content'], false, false, 'https://rytr.me/favicon.ico'),
  ('office-shortly-ai', 'Shortly AI', 'AI writing companion that helps overcome writers block by continuing your thoughts and expanding ideas with intelligent text generation.', 'https://shortlyai.com', 'office-productivity', 'Paid', ARRAY['writing-companion', 'writers-block', 'text-expansion'], false, false, 'https://shortlyai.com/favicon.ico'),
  ('office-peppertype', 'Peppertype', 'AI content marketing platform that generates blog posts, social media content, ad copy, and product descriptions for businesses.', 'https://peppertype.ai', 'office-productivity', 'Freemium', ARRAY['content-marketing', 'social-media', 'business-content'], false, false, 'https://peppertype.ai/favicon.ico'),
  ('office-anyword', 'Anyword', 'AI copywriting platform with predictive performance scoring that optimizes marketing content for better conversion rates.', 'https://anyword.com', 'office-productivity', 'Paid', ARRAY['predictive-scoring', 'conversion-optimization', 'marketing-ai'], false, false, 'https://anyword.com/favicon.ico'),
  ('office-closerscopy', 'ClosersCopy', 'AI copywriting tool specialized in sales copy, email sequences, and persuasive marketing content with psychology-based frameworks.', 'https://closerscopy.com', 'office-productivity', 'Paid', ARRAY['sales-copy', 'email-sequences', 'persuasive-writing'], false, false, 'https://closerscopy.com/favicon.ico'),
  ('office-wordtune', 'Wordtune', 'AI writing companion that rewrites and improves sentences, suggests better phrasing, and enhances clarity in professional writing.', 'https://wordtune.com', 'office-productivity', 'Freemium', ARRAY['sentence-rewriting', 'clarity-enhancement', 'professional-writing'], false, false, 'https://wordtune.com/favicon.ico'),
  ('office-outwrite', 'Outwrite', 'AI-powered writing assistant that checks grammar, style, and structure while providing suggestions for clearer communication.', 'https://outwrite.com', 'office-productivity', 'Freemium', ARRAY['grammar-check', 'style-improvement', 'clear-communication'], false, false, 'https://outwrite.com/favicon.ico'),
  ('office-contentbot', 'ContentBot', 'AI content creation platform that generates blog posts, social media content, and marketing copy with workflow automation.', 'https://contentbot.ai', 'office-productivity', 'Paid', ARRAY['content-creation', 'workflow-automation', 'marketing-copy'], false, false, 'https://contentbot.ai/favicon.ico'),
  ('office-article-forge', 'Article Forge', 'AI article writer that researches and creates unique, SEO-optimized articles on any topic with automatic content generation.', 'https://articleforge.com', 'office-productivity', 'Paid', ARRAY['article-generation', 'seo-optimization', 'automatic-research'], false, false, 'https://articleforge.com/favicon.ico'),
  ('office-nichesss', 'Nichesss', 'AI content generator that creates blog posts, social media content, business ideas, and marketing copy for niche markets.', 'https://nichesss.com', 'office-productivity', 'Paid', ARRAY['niche-content', 'business-ideas', 'social-media-content'], false, false, 'https://nichesss.com/favicon.ico'),
  ('office-textblaze', 'Text Blaze', 'AI-powered text expansion tool that creates smart snippets, templates, and automated responses for faster typing and communication.', 'https://blaze.today', 'office-productivity', 'Freemium', ARRAY['text-expansion', 'smart-templates', 'automated-responses'], false, false, 'https://blaze.today/favicon.ico'),
  ('office-hyperwrite', 'HyperWrite', 'AI writing assistant that helps with emails, essays, articles, and creative writing with personalized style adaptation.', 'https://hyperwriteai.com', 'office-productivity', 'Freemium', ARRAY['personalized-writing', 'style-adaptation', 'creative-writing'], false, false, 'https://hyperwriteai.com/favicon.ico'),
  
  -- Project Management & Task Automation (15 tools)
  ('office-monday-ai', 'Monday.com AI', 'AI-enhanced project management platform with intelligent task automation, predictive analytics, and smart resource allocation.', 'https://monday.com', 'office-productivity', 'Paid', ARRAY['project-management', 'task-automation', 'predictive-analytics'], false, false, 'https://monday.com/favicon.ico'),
  ('office-asana-intelligence', 'Asana Intelligence', 'AI-powered project management with smart project insights, automated task assignments, and intelligent progress tracking.', 'https://asana.com', 'office-productivity', 'Freemium', ARRAY['smart-insights', 'automated-assignments', 'progress-tracking'], false, false, 'https://asana.com/favicon.ico'),
  ('office-clickup-ai', 'ClickUp AI', 'AI project management platform with intelligent task creation, automated workflows, and smart scheduling optimization.', 'https://clickup.com', 'office-productivity', 'Freemium', ARRAY['intelligent-tasks', 'automated-workflows', 'smart-scheduling'], false, false, 'https://clickup.com/favicon.ico'),
  ('office-notion-ai', 'Notion AI', 'AI-powered workspace that combines notes, tasks, wikis, and databases with intelligent content generation and organization.', 'https://notion.so', 'office-productivity', 'Freemium', ARRAY['intelligent-workspace', 'content-generation', 'smart-organization'], false, false, 'https://notion.so/favicon.ico'),
  ('office-trello-butler', 'Trello Butler', 'AI automation tool for Trello that creates smart rules, commands, and scheduled actions to streamline project workflows.', 'https://trello.com/butler', 'office-productivity', 'Freemium', ARRAY['workflow-automation', 'smart-rules', 'scheduled-actions'], false, false, 'https://trello.com/favicon.ico'),
  ('office-smartsheet-ai', 'Smartsheet AI', 'AI-enhanced work management platform with intelligent resource planning, automated reporting, and predictive project insights.', 'https://smartsheet.com', 'office-productivity', 'Paid', ARRAY['resource-planning', 'automated-reporting', 'predictive-insights'], false, false, 'https://smartsheet.com/favicon.ico'),
  ('office-airtable-ai', 'Airtable AI', 'AI-powered database platform with intelligent data organization, automated workflows, and smart field suggestions.', 'https://airtable.com', 'office-productivity', 'Freemium', ARRAY['data-organization', 'automated-workflows', 'smart-suggestions'], false, false, 'https://airtable.com/favicon.ico'),
  ('office-wrike-ai', 'Wrike AI', 'AI project management software with intelligent workload balancing, automated status updates, and predictive project analytics.', 'https://wrike.com', 'office-productivity', 'Paid', ARRAY['workload-balancing', 'automated-updates', 'predictive-analytics'], false, false, 'https://wrike.com/favicon.ico'),
  ('office-basecamp-ai', 'Basecamp AI', 'AI-enhanced team collaboration platform with smart project organization, automated check-ins, and intelligent progress tracking.', 'https://basecamp.com', 'office-productivity', 'Paid', ARRAY['team-collaboration', 'smart-organization', 'automated-check-ins'], false, false, 'https://basecamp.com/favicon.ico'),
  ('office-teamwork-ai', 'Teamwork AI', 'AI project management tool with intelligent time tracking, automated resource allocation, and smart project predictions.', 'https://teamwork.com', 'office-productivity', 'Paid', ARRAY['intelligent-tracking', 'resource-allocation', 'project-predictions'], false, false, 'https://teamwork.com/favicon.ico'),
  ('office-height-ai', 'Height AI', 'AI-first project management platform with autonomous task creation, intelligent prioritization, and automated status updates.', 'https://height.app', 'office-productivity', 'Paid', ARRAY['autonomous-tasks', 'intelligent-prioritization', 'automated-status'], false, false, 'https://height.app/favicon.ico'),
  ('office-linear-ai', 'Linear AI', 'AI-powered issue tracking and project management with intelligent bug detection, automated workflows, and smart sprint planning.', 'https://linear.app', 'office-productivity', 'Paid', ARRAY['issue-tracking', 'bug-detection', 'smart-planning'], false, false, 'https://linear.app/favicon.ico'),
  ('office-sunsama-ai', 'Sunsama AI', 'AI daily planning tool that intelligently schedules tasks, predicts time requirements, and optimizes productivity workflows.', 'https://sunsama.com', 'office-productivity', 'Paid', ARRAY['daily-planning', 'time-prediction', 'productivity-optimization'], false, false, 'https://sunsama.com/favicon.ico'),
  ('office-motion-ai', 'Motion AI', 'AI-powered task and calendar management that automatically schedules work, manages priorities, and optimizes productivity.', 'https://usemotion.com', 'office-productivity', 'Paid', ARRAY['automated-scheduling', 'priority-management', 'productivity-optimization'], false, false, 'https://usemotion.com/favicon.ico'),
  ('office-reclaim-ai', 'Reclaim AI', 'AI calendar assistant that automatically schedules tasks, habits, and meetings while protecting focus time and work-life balance.', 'https://reclaim.ai', 'office-productivity', 'Freemium', ARRAY['calendar-ai', 'habit-scheduling', 'focus-protection'], false, false, 'https://reclaim.ai/favicon.ico'),
  
  -- Document Processing & OCR (15 tools)
  ('office-adobe-acrobat-ai', 'Adobe Acrobat AI', 'AI-powered PDF tool with intelligent document analysis, automated form recognition, and smart content extraction.', 'https://acrobat.adobe.com', 'office-productivity', 'Paid', ARRAY['pdf-ai', 'document-analysis', 'content-extraction'], false, false, 'https://acrobat.adobe.com/favicon.ico'),
  ('office-docsumo', 'Docsumo', 'AI document processing platform that extracts data from invoices, receipts, and forms with high accuracy OCR technology.', 'https://docsumo.com', 'office-productivity', 'Paid', ARRAY['document-processing', 'data-extraction', 'ocr-technology'], false, false, 'https://docsumo.com/favicon.ico'),
  ('office-rossum', 'Rossum', 'AI-powered document processing platform that automates data capture from invoices, purchase orders, and business documents.', 'https://rossum.ai', 'office-productivity', 'Paid', ARRAY['automated-capture', 'invoice-processing', 'business-documents'], false, false, 'https://rossum.ai/favicon.ico'),
  ('office-nanonets', 'Nanonets', 'AI OCR and document processing platform that extracts structured data from unstructured documents with machine learning.', 'https://nanonets.com', 'office-productivity', 'Paid', ARRAY['ocr-ai', 'structured-data', 'machine-learning'], false, false, 'https://nanonets.com/favicon.ico'),
  ('office-extractable', 'Extractable', 'AI document extraction tool that automatically captures data from PDFs, images, and scanned documents with intelligent parsing.', 'https://extractable.com', 'office-productivity', 'Paid', ARRAY['document-extraction', 'intelligent-parsing', 'scanned-documents'], false, false, 'https://extractable.com/favicon.ico'),
  ('office-mindee', 'Mindee', 'AI-powered document parsing API that extracts structured data from receipts, invoices, passports, and financial documents.', 'https://mindee.com', 'office-productivity', 'Freemium', ARRAY['document-parsing', 'financial-documents', 'api-integration'], false, false, 'https://mindee.com/favicon.ico'),
  ('office-textract', 'Amazon Textract', 'AI document analysis service that extracts text, handwriting, and data from scanned documents and forms automatically.', 'https://aws.amazon.com/textract', 'office-productivity', 'Paid', ARRAY['document-analysis', 'handwriting-recognition', 'aws-service'], false, false, 'https://aws.amazon.com/favicon.ico'),
  ('office-form-recognizer', 'Azure Form Recognizer', 'AI-powered service that extracts text, key-value pairs, and tables from documents using machine learning models.', 'https://azure.microsoft.com/services/cognitive-services/form-recognizer', 'office-productivity', 'Paid', ARRAY['form-recognition', 'key-value-extraction', 'azure-ai'], false, false, 'https://azure.microsoft.com/favicon.ico'),
  ('office-google-document-ai', 'Google Document AI', 'AI platform that processes and understands documents at scale with pre-trained and custom machine learning models.', 'https://cloud.google.com/document-ai', 'office-productivity', 'Paid', ARRAY['document-understanding', 'custom-models', 'google-cloud'], false, false, 'https://cloud.google.com/favicon.ico'),
  ('office-abbyy-vantage', 'ABBYY Vantage', 'AI-powered intelligent document processing platform that automates document-centric business processes.', 'https://abbyy.com/vantage', 'office-productivity', 'Paid', ARRAY['intelligent-processing', 'business-automation', 'document-centric'], false, false, 'https://abbyy.com/favicon.ico'),
  ('office-hypatos', 'Hypatos', 'AI document processing software that automates invoice processing, purchase order handling, and financial document workflows.', 'https://hypatos.ai', 'office-productivity', 'Paid', ARRAY['invoice-automation', 'financial-workflows', 'document-ai'], false, false, 'https://hypatos.ai/favicon.ico'),
  ('office-klippa', 'Klippa', 'AI-powered document processing platform with OCR, data extraction, and automated workflows for business documents.', 'https://klippa.com', 'office-productivity', 'Paid', ARRAY['automated-workflows', 'business-documents', 'data-extraction'], false, false, 'https://klippa.com/favicon.ico'),
  ('office-avanade', 'Avanade Document AI', 'AI document intelligence platform that transforms unstructured content into actionable business insights and data.', 'https://avanade.com', 'office-productivity', 'Paid', ARRAY['document-intelligence', 'business-insights', 'content-transformation'], false, false, 'https://avanade.com/favicon.ico'),
  ('office-infrrd', 'Infrrd', 'AI-powered intelligent document processing that extracts, validates, and processes data from complex business documents.', 'https://infrrd.ai', 'office-productivity', 'Paid', ARRAY['intelligent-processing', 'data-validation', 'complex-documents'], false, false, 'https://infrrd.ai/favicon.ico'),
  ('office-docparser', 'Docparser', 'AI document parsing tool that extracts specific data from PDFs, emails, and scanned documents with automated workflows.', 'https://docparser.com', 'office-productivity', 'Paid', ARRAY['document-parsing', 'automated-workflows', 'data-extraction'], false, false, 'https://docparser.com/favicon.ico'),
  
  -- Email & Communication AI (15 tools)
  ('office-boomerang-ai', 'Boomerang AI', 'AI email assistant with send-later scheduling, response tracking, inbox pause, and intelligent email prioritization.', 'https://boomeranggmail.com', 'office-productivity', 'Freemium', ARRAY['email-scheduling', 'response-tracking', 'inbox-management'], false, false, 'https://boomeranggmail.com/favicon.ico'),
  ('office-mixmax-ai', 'Mixmax AI', 'AI-powered email productivity suite with smart templates, send-time optimization, and engagement tracking analytics.', 'https://mixmax.com', 'office-productivity', 'Paid', ARRAY['smart-templates', 'send-optimization', 'engagement-analytics'], false, false, 'https://mixmax.com/favicon.ico'),
  ('office-superhuman-ai', 'Superhuman AI', 'AI-enhanced email client with smart shortcuts, predictive text, and intelligent email organization features.', 'https://superhuman.com', 'office-productivity', 'Paid', ARRAY['smart-shortcuts', 'predictive-text', 'email-organization'], false, false, 'https://superhuman.com/favicon.ico'),
  ('office-sanebox', 'SaneBox', 'AI email management tool that automatically sorts emails, identifies important messages, and reduces inbox clutter.', 'https://sanebox.com', 'office-productivity', 'Paid', ARRAY['email-sorting', 'important-detection', 'clutter-reduction'], false, false, 'https://sanebox.com/favicon.ico'),
  ('office-unroll-me', 'Unroll.Me', 'AI-powered email management that automatically unsubscribes from unwanted emails and organizes subscriptions.', 'https://unroll.me', 'office-productivity', 'Free', ARRAY['auto-unsubscribe', 'subscription-management', 'email-cleanup'], false, false, 'https://unroll.me/favicon.ico'),
  ('office-crystal-ai', 'Crystal AI', 'AI personality analysis tool that provides communication insights and suggestions for better email interactions.', 'https://crystalknows.com', 'office-productivity', 'Freemium', ARRAY['personality-analysis', 'communication-insights', 'email-optimization'], false, false, 'https://crystalknows.com/favicon.ico'),
  ('office-gorgias', 'Gorgias', 'AI customer service platform with intelligent email automation, smart templates, and automated response suggestions.', 'https://gorgias.com', 'office-productivity', 'Paid', ARRAY['customer-service', 'email-automation', 'response-suggestions'], false, false, 'https://gorgias.com/favicon.ico'),
  ('office-frontapp-ai', 'Front AI', 'AI-powered shared inbox that intelligently routes emails, suggests responses, and automates customer communication workflows.', 'https://front.com', 'office-productivity', 'Paid', ARRAY['shared-inbox', 'email-routing', 'automated-workflows'], false, false, 'https://front.com/favicon.ico'),
  ('office-polymail', 'Polymail', 'AI email client with smart tracking, automated follow-ups, and intelligent contact management for sales teams.', 'https://polymail.io', 'office-productivity', 'Paid', ARRAY['smart-tracking', 'automated-followups', 'contact-management'], false, false, 'https://polymail.io/favicon.ico'),
  ('office-spark-ai', 'Spark AI', 'AI email app with smart inbox organization, intelligent notifications, and automated email prioritization.', 'https://sparkmailapp.com', 'office-productivity', 'Freemium', ARRAY['inbox-organization', 'intelligent-notifications', 'email-prioritization'], false, false, 'https://sparkmailapp.com/favicon.ico'),
  ('office-lemlist-ai', 'Lemlist AI', 'AI-powered cold email platform with personalized outreach, automated sequences, and intelligent response tracking.', 'https://lemlist.com', 'office-productivity', 'Paid', ARRAY['cold-email', 'personalized-outreach', 'automated-sequences'], false, false, 'https://lemlist.com/favicon.ico'),
  ('office-reply-io', 'Reply.io', 'AI sales engagement platform with automated email sequences, intelligent follow-ups, and personalized messaging.', 'https://reply.io', 'office-productivity', 'Paid', ARRAY['sales-engagement', 'automated-sequences', 'personalized-messaging'], false, false, 'https://reply.io/favicon.ico'),
  ('office-smartwriter', 'Smartwriter', 'AI email outreach tool that creates personalized cold emails and LinkedIn messages using AI research and writing.', 'https://smartwriter.ai', 'office-productivity', 'Paid', ARRAY['email-outreach', 'personalized-emails', 'ai-research'], false, false, 'https://smartwriter.ai/favicon.ico'),
  ('office-instantly-ai', 'Instantly AI', 'AI-powered cold email platform with automated outreach, deliverability optimization, and intelligent response handling.', 'https://instantly.ai', 'office-productivity', 'Paid', ARRAY['cold-email-platform', 'deliverability-optimization', 'response-handling'], false, false, 'https://instantly.ai/favicon.ico'),
  ('office-quickmail', 'QuickMail', 'AI email automation platform with intelligent prospect research, automated follow-ups, and personalized outreach campaigns.', 'https://quickmail.io', 'office-productivity', 'Paid', ARRAY['prospect-research', 'automated-followups', 'outreach-campaigns'], false, false, 'https://quickmail.io/favicon.ico'),
  
  -- Spreadsheets & Data Analysis (15 tools)
  ('office-excel-ai', 'Microsoft Excel AI', 'AI-enhanced spreadsheet application with intelligent data analysis, automated insights, and predictive analytics features.', 'https://microsoft.com/excel', 'office-productivity', 'Paid', ARRAY['spreadsheet-ai', 'data-analysis', 'predictive-analytics'], false, false, 'https://microsoft.com/favicon.ico'),
  ('office-google-sheets-ai', 'Google Sheets AI', 'AI-powered spreadsheet with smart fill, formula suggestions, and automated data insights for collaborative work.', 'https://sheets.google.com', 'office-productivity', 'Free', ARRAY['smart-fill', 'formula-suggestions', 'collaborative-work'], false, false, 'https://sheets.google.com/favicon.ico'),
  ('office-neptyne', 'Neptyne', 'AI-powered spreadsheet platform that combines Python programming with spreadsheet functionality for advanced data analysis.', 'https://neptyne.com', 'office-productivity', 'Freemium', ARRAY['python-spreadsheet', 'advanced-analysis', 'programming-integration'], false, false, 'https://neptyne.com/favicon.ico'),
  ('office-formula-bot', 'Formula Bot', 'AI tool that converts text instructions into Excel and Google Sheets formulas, making complex calculations accessible.', 'https://formulabot.com', 'office-productivity', 'Freemium', ARRAY['formula-generation', 'text-to-formula', 'calculation-assistance'], false, false, 'https://formulabot.com/favicon.ico'),
  ('office-excelformulabot', 'Excel Formula Bot', 'AI-powered tool that generates Excel formulas, VBA code, and regex patterns from natural language descriptions.', 'https://excelformulabot.com', 'office-productivity', 'Freemium', ARRAY['excel-formulas', 'vba-generation', 'natural-language'], false, false, 'https://excelformulabot.com/favicon.ico'),
  ('office-sheetai', 'SheetAI', 'AI add-on for Google Sheets that brings GPT-3 capabilities directly into spreadsheets for content generation and analysis.', 'https://sheetai.app', 'office-productivity', 'Paid', ARRAY['gpt-integration', 'content-generation', 'spreadsheet-ai'], false, false, 'https://sheetai.app/favicon.ico'),
  ('office-numerous-ai', 'Numerous AI', 'AI tool that integrates ChatGPT and other AI models into Google Sheets and Excel for automated data processing.', 'https://numerous.ai', 'office-productivity', 'Freemium', ARRAY['chatgpt-integration', 'automated-processing', 'ai-models'], false, false, 'https://numerous.ai/favicon.ico'),
  ('office-luminal', 'Luminal', 'AI-powered data analysis platform that processes spreadsheets and provides insights through natural language queries.', 'https://luminal.ai', 'office-productivity', 'Paid', ARRAY['data-analysis', 'natural-language-queries', 'insights-generation'], false, false, 'https://luminal.ai/favicon.ico'),
  ('office-julius-ai', 'Julius AI', 'AI data analyst that analyzes spreadsheets, creates visualizations, and answers questions about your data in plain English.', 'https://julius.ai', 'office-productivity', 'Freemium', ARRAY['data-analyst', 'visualizations', 'plain-english-queries'], false, false, 'https://julius.ai/favicon.ico'),
  ('office-parseur', 'Parseur', 'AI-powered data extraction tool that automatically extracts data from emails, PDFs, and documents into spreadsheets.', 'https://parseur.com', 'office-productivity', 'Paid', ARRAY['data-extraction', 'automated-parsing', 'document-processing'], false, false, 'https://parseur.com/favicon.ico'),
  ('office-sheeter', 'Sheeter', 'AI spreadsheet tool that generates complex Excel and Google Sheets formulas from simple text descriptions.', 'https://sheeter.ai', 'office-productivity', 'Freemium', ARRAY['formula-generation', 'text-descriptions', 'complex-formulas'], false, false, 'https://sheeter.ai/favicon.ico'),
  ('office-equals-ai', 'Equals AI', 'AI-powered spreadsheet platform with SQL querying, automated data connections, and intelligent formula suggestions.', 'https://equals.app', 'office-productivity', 'Paid', ARRAY['sql-querying', 'data-connections', 'formula-suggestions'], false, false, 'https://equals.app/favicon.ico'),
  ('office-causal', 'Causal', 'AI-enhanced financial modeling and data analysis platform with intelligent forecasting and scenario planning.', 'https://causal.app', 'office-productivity', 'Paid', ARRAY['financial-modeling', 'intelligent-forecasting', 'scenario-planning'], false, false, 'https://causal.app/favicon.ico'),
  ('office-rows', 'Rows', 'AI-powered spreadsheet with built-in integrations, automated data imports, and intelligent analysis capabilities.', 'https://rows.com', 'office-productivity', 'Freemium', ARRAY['built-in-integrations', 'automated-imports', 'intelligent-analysis'], false, false, 'https://rows.com/favicon.ico'),
  ('office-quadratic', 'Quadratic', 'AI-enhanced infinite spreadsheet with Python, SQL, and JavaScript support for advanced data analysis and visualization.', 'https://quadratic.to', 'office-productivity', 'Free', ARRAY['infinite-spreadsheet', 'multi-language-support', 'data-visualization'], false, false, 'https://quadratic.to/favicon.ico'),
  
  -- Meeting & Video Conferencing AI (15 tools)
  ('office-otter-ai', 'Otter.ai', 'AI-powered meeting transcription service that provides real-time notes, speaker identification, and searchable transcripts.', 'https://otter.ai', 'office-productivity', 'Freemium', ARRAY['meeting-transcription', 'real-time-notes', 'speaker-identification'], false, false, 'https://otter.ai/favicon.ico'),
  ('office-zoom-ai', 'Zoom AI Companion', 'AI-enhanced video conferencing with intelligent meeting summaries, action item extraction, and automated follow-ups.', 'https://zoom.us', 'office-productivity', 'Freemium', ARRAY['meeting-summaries', 'action-items', 'automated-followups'], false, false, 'https://zoom.us/favicon.ico'),
  ('office-teams-ai', 'Microsoft Teams AI', 'AI-powered collaboration platform with intelligent meeting insights, automated transcription, and smart scheduling.', 'https://teams.microsoft.com', 'office-productivity', 'Freemium', ARRAY['meeting-insights', 'automated-transcription', 'smart-scheduling'], false, false, 'https://teams.microsoft.com/favicon.ico'),
  ('office-fireflies-ai', 'Fireflies.ai', 'AI meeting assistant that records, transcribes, and analyzes voice conversations with automated note-taking and insights.', 'https://fireflies.ai', 'office-productivity', 'Freemium', ARRAY['meeting-assistant', 'voice-analysis', 'automated-notes'], false, false, 'https://fireflies.ai/favicon.ico'),
  ('office-grain-ai', 'Grain', 'AI-powered meeting recorder that captures, transcribes, and creates shareable video highlights from video calls.', 'https://grain.com', 'office-productivity', 'Freemium', ARRAY['meeting-recorder', 'video-highlights', 'shareable-clips'], false, false, 'https://grain.com/favicon.ico'),
  ('office-avoma', 'Avoma', 'AI meeting assistant with conversation intelligence, automated note-taking, and CRM integration for sales teams.', 'https://avoma.com', 'office-productivity', 'Paid', ARRAY['conversation-intelligence', 'crm-integration', 'sales-meetings'], false, false, 'https://avoma.com/favicon.ico'),
  ('office-chorus-ai', 'Chorus AI', 'AI-powered conversation analytics platform that analyzes sales calls and meetings for coaching and insights.', 'https://chorus.ai', 'office-productivity', 'Paid', ARRAY['conversation-analytics', 'sales-coaching', 'meeting-insights'], false, false, 'https://chorus.ai/favicon.ico'),
  ('office-gong-ai', 'Gong AI', 'AI revenue intelligence platform that analyzes customer conversations, calls, and meetings for sales optimization.', 'https://gong.io', 'office-productivity', 'Paid', ARRAY['revenue-intelligence', 'conversation-analysis', 'sales-optimization'], false, false, 'https://gong.io/favicon.ico'),
  ('office-outreach-ai', 'Outreach AI', 'AI sales engagement platform with conversation intelligence, automated follow-ups, and meeting optimization.', 'https://outreach.io', 'office-productivity', 'Paid', ARRAY['sales-engagement', 'conversation-intelligence', 'meeting-optimization'], false, false, 'https://outreach.io/favicon.ico'),
  ('office-rev-ai', 'Rev AI', 'AI speech-to-text service that provides accurate transcription for meetings, interviews, and recorded conversations.', 'https://rev.ai', 'office-productivity', 'Paid', ARRAY['speech-to-text', 'accurate-transcription', 'conversation-recording'], false, false, 'https://rev.ai/favicon.ico'),
  ('office-sonix', 'Sonix', 'AI transcription platform that converts audio and video files into searchable text with speaker identification.', 'https://sonix.ai', 'office-productivity', 'Paid', ARRAY['audio-transcription', 'video-transcription', 'searchable-text'], false, false, 'https://sonix.ai/favicon.ico'),
  ('office-descript', 'Descript', 'AI-powered audio and video editing platform with transcription-based editing and voice cloning capabilities.', 'https://descript.com', 'office-productivity', 'Freemium', ARRAY['transcription-editing', 'voice-cloning', 'audio-video-editing'], false, false, 'https://descript.com/favicon.ico'),
  ('office-krisp', 'Krisp AI', 'AI-powered noise cancellation software that removes background noise from calls and recordings in real-time.', 'https://krisp.ai', 'office-productivity', 'Freemium', ARRAY['noise-cancellation', 'background-removal', 'call-enhancement'], false, false, 'https://krisp.ai/favicon.ico'),
  ('office-read-ai', 'Read AI', 'AI meeting analytics platform that provides insights into meeting effectiveness, participation, and conversation patterns.', 'https://read.ai', 'office-productivity', 'Freemium', ARRAY['meeting-analytics', 'participation-insights', 'conversation-patterns'], false, false, 'https://read.ai/favicon.ico'),
  ('office-Clara-labs', 'Clara Labs', 'AI scheduling assistant that coordinates meetings, manages calendars, and handles meeting logistics through email.', 'https://clara.com', 'office-productivity', 'Paid', ARRAY['scheduling-assistant', 'calendar-management', 'meeting-logistics'], false, false, 'https://clara.com/favicon.ico'),
  
  -- Time Management & Scheduling (15 tools)
  ('office-calendly-ai', 'Calendly AI', 'AI-powered scheduling platform with intelligent availability optimization, automated meeting prep, and smart routing.', 'https://calendly.com', 'office-productivity', 'Freemium', ARRAY['intelligent-scheduling', 'meeting-prep', 'smart-routing'], false, false, 'https://calendly.com/favicon.ico'),
  ('office-clockify-ai', 'Clockify AI', 'AI time tracking software with intelligent project categorization, automated time entry, and productivity insights.', 'https://clockify.me', 'office-productivity', 'Freemium', ARRAY['time-tracking', 'project-categorization', 'productivity-insights'], false, false, 'https://clockify.me/favicon.ico'),
  ('office-rescuetime', 'RescueTime', 'AI-powered time tracking and productivity analysis tool that automatically categorizes activities and provides insights.', 'https://rescuetime.com', 'office-productivity', 'Freemium', ARRAY['automatic-tracking', 'activity-categorization', 'productivity-analysis'], false, false, 'https://rescuetime.com/favicon.ico'),
  ('office-toggl-track', 'Toggl Track AI', 'AI-enhanced time tracking with intelligent project suggestions, automated time entry, and productivity optimization.', 'https://toggl.com', 'office-productivity', 'Freemium', ARRAY['intelligent-suggestions', 'automated-entry', 'optimization'], false, false, 'https://toggl.com/favicon.ico'),
  ('office-timely-ai', 'Timely AI', 'AI automatic time tracking software that monitors work activities and creates accurate timesheets without manual input.', 'https://timelyapp.com', 'office-productivity', 'Paid', ARRAY['automatic-tracking', 'activity-monitoring', 'accurate-timesheets'], false, false, 'https://timelyapp.com/favicon.ico'),
  ('office-actitime-ai', 'actiTIME AI', 'AI time tracking and project management tool with intelligent workload analysis and resource optimization.', 'https://actitime.com', 'office-productivity', 'Paid', ARRAY['workload-analysis', 'resource-optimization', 'project-management'], false, false, 'https://actitime.com/favicon.ico'),
  ('office-harvest-ai', 'Harvest AI', 'AI-powered time tracking and invoicing platform with intelligent project insights and automated billing.', 'https://getharvest.com', 'office-productivity', 'Paid', ARRAY['time-invoicing', 'project-insights', 'automated-billing'], false, false, 'https://getharvest.com/favicon.ico'),
  ('office-hubstaff-ai', 'Hubstaff AI', 'AI workforce analytics platform with intelligent time tracking, productivity monitoring, and team optimization.', 'https://hubstaff.com', 'office-productivity', 'Paid', ARRAY['workforce-analytics', 'productivity-monitoring', 'team-optimization'], false, false, 'https://hubstaff.com/favicon.ico'),
  ('office-timecamp-ai', 'TimeCamp AI', 'AI time tracking software with intelligent project categorization, automated invoicing, and productivity analysis.', 'https://timecamp.com', 'office-productivity', 'Freemium', ARRAY['project-categorization', 'automated-invoicing', 'productivity-analysis'], false, false, 'https://timecamp.com/favicon.ico'),
  ('office-desktime-ai', 'DeskTime AI', 'AI productivity tracking software with intelligent work pattern analysis and automated productivity scoring.', 'https://desktime.com', 'office-productivity', 'Freemium', ARRAY['work-pattern-analysis', 'productivity-scoring', 'automated-tracking'], false, false, 'https://desktime.com/favicon.ico'),
  ('office-plan-ai', 'Plan AI', 'AI-powered planning and scheduling tool that optimizes daily tasks, meetings, and project timelines automatically.', 'https://getplan.co', 'office-productivity', 'Paid', ARRAY['intelligent-planning', 'task-optimization', 'timeline-management'], false, false, 'https://getplan.co/favicon.ico'),
  ('office-fantastical-ai', 'Fantastical AI', 'AI calendar app with natural language event creation, intelligent scheduling suggestions, and smart notifications.', 'https://flexibits.com/fantastical', 'office-productivity', 'Paid', ARRAY['natural-language', 'scheduling-suggestions', 'smart-notifications'], false, false, 'https://flexibits.com/favicon.ico'),
  ('office-amy-ai', 'Amy by x.ai', 'AI personal assistant that schedules meetings, manages calendars, and handles appointment coordination via email.', 'https://x.ai', 'office-productivity', 'Paid', ARRAY['personal-assistant', 'meeting-scheduling', 'appointment-coordination'], false, false, 'https://x.ai/favicon.ico'),
  ('office-julie-desk', 'Julie Desk', 'AI meeting scheduling assistant that coordinates appointments and manages calendar conflicts through intelligent automation.', 'https://juliedesk.com', 'office-productivity', 'Paid', ARRAY['meeting-coordination', 'calendar-conflicts', 'intelligent-automation'], false, false, 'https://juliedesk.com/favicon.ico'),
  ('office-scheduler-ai', 'Scheduler AI', 'AI-powered scheduling optimization platform that finds optimal meeting times and manages complex scheduling constraints.', 'https://scheduler.ai', 'office-productivity', 'Paid', ARRAY['scheduling-optimization', 'optimal-timing', 'constraint-management'], false, false, 'https://scheduler.ai/favicon.ico'),
  
  -- Knowledge Management & Note-Taking (15 tools)
  ('office-obsidian-ai', 'Obsidian AI', 'AI-enhanced knowledge management tool with intelligent note linking, content suggestions, and graph-based organization.', 'https://obsidian.md', 'office-productivity', 'Freemium', ARRAY['knowledge-management', 'intelligent-linking', 'graph-organization'], false, false, 'https://obsidian.md/favicon.ico'),
  ('office-roam-research', 'Roam Research', 'AI-powered note-taking tool for networked thought with intelligent content connections and knowledge graph visualization.', 'https://roamresearch.com', 'office-productivity', 'Paid', ARRAY['networked-thought', 'content-connections', 'knowledge-graph'], false, false, 'https://roamresearch.com/favicon.ico'),
  ('office-logseq', 'Logseq', 'AI-enhanced local-first knowledge management platform with intelligent block-based editing and automated organization.', 'https://logseq.com', 'office-productivity', 'Free', ARRAY['local-first', 'block-based-editing', 'automated-organization'], false, false, 'https://logseq.com/favicon.ico'),
  ('office-dendron', 'Dendron', 'AI-powered hierarchical note-taking tool with intelligent schema management and automated knowledge organization.', 'https://dendron.so', 'office-productivity', 'Free', ARRAY['hierarchical-notes', 'schema-management', 'knowledge-organization'], false, false, 'https://dendron.so/favicon.ico'),
  ('office-craftdocs', 'Craft Docs', 'AI-enhanced structured writing and note-taking app with intelligent content organization and linking features.', 'https://craftdocs.com', 'office-productivity', 'Freemium', ARRAY['structured-writing', 'content-organization', 'intelligent-linking'], false, false, 'https://craftdocs.com/favicon.ico'),
  ('office-bear-ai', 'Bear AI', 'AI-powered markdown note-taking app with intelligent tagging, content suggestions, and automated organization.', 'https://bear.app', 'office-productivity', 'Freemium', ARRAY['markdown-notes', 'intelligent-tagging', 'automated-organization'], false, false, 'https://bear.app/favicon.ico'),
  ('office-remnote', 'RemNote', 'AI-enhanced note-taking and spaced repetition tool with intelligent knowledge graph and automated flashcard creation.', 'https://remnote.com', 'office-productivity', 'Freemium', ARRAY['spaced-repetition', 'knowledge-graph', 'automated-flashcards'], false, false, 'https://remnote.com/favicon.ico'),
  ('office-amplenote', 'Amplenote', 'AI-powered note-taking and task management app with intelligent content prioritization and automated organization.', 'https://amplenote.com', 'office-productivity', 'Freemium', ARRAY['content-prioritization', 'task-management', 'automated-organization'], false, false, 'https://amplenote.com/favicon.ico'),
  ('office-workflowy', 'WorkFlowy', 'AI-enhanced infinite outline tool with intelligent content organization and automated bullet point structuring.', 'https://workflowy.com', 'office-productivity', 'Freemium', ARRAY['infinite-outline', 'content-organization', 'bullet-structuring'], false, false, 'https://workflowy.com/favicon.ico'),
  ('office-dynalist', 'Dynalist', 'AI-powered hierarchical note-taking tool with intelligent document organization and automated content linking.', 'https://dynalist.io', 'office-productivity', 'Freemium', ARRAY['hierarchical-notes', 'document-organization', 'content-linking'], false, false, 'https://dynalist.io/favicon.ico'),
  ('office-tana', 'Tana', 'AI-enhanced structured note-taking platform with intelligent knowledge modeling and automated content relationships.', 'https://tana.inc', 'office-productivity', 'Free', ARRAY['structured-notes', 'knowledge-modeling', 'content-relationships'], false, false, 'https://tana.inc/favicon.ico'),
  ('office-mem-ai', 'Mem AI', 'AI-powered note-taking app that automatically organizes and connects notes using machine learning and natural language processing.', 'https://mem.ai', 'office-productivity', 'Paid', ARRAY['automatic-organization', 'machine-learning', 'natural-language'], false, false, 'https://mem.ai/favicon.ico'),
  ('office-reflect-ai', 'Reflect AI', 'AI-enhanced note-taking tool with intelligent content suggestions, automated backlinking, and smart organization.', 'https://reflect.app', 'office-productivity', 'Paid', ARRAY['content-suggestions', 'automated-backlinking', 'smart-organization'], false, false, 'https://reflect.app/favicon.ico'),
  ('office-athens-research', 'Athens Research', 'AI-powered open-source knowledge management platform with intelligent graph-based note organization and linking.', 'https://athensresearch.github.io', 'office-productivity', 'Free', ARRAY['open-source', 'graph-based', 'intelligent-linking'], false, false, 'https://athensresearch.github.io/favicon.ico'),
  ('office-supernotes', 'Supernotes', 'AI-enhanced card-based note-taking app with intelligent content organization and automated cross-referencing.', 'https://supernotes.app', 'office-productivity', 'Freemium', ARRAY['card-based-notes', 'content-organization', 'automated-cross-referencing'], false, false, 'https://supernotes.app/favicon.ico')
ON CONFLICT (id, category_id) DO NOTHING;

-- Update the tool count for the category
UPDATE categories 
SET tool_count = (
  SELECT COUNT(*) 
  FROM tools 
  WHERE category_id = 'office-productivity'
) 
WHERE id = 'office-productivity';
