-- Image Generation & Editing AI Tools (100 tools)
-- This script adds 100 AI-powered tools for image generation and editing
-- Covers AI art generation, photo editing, design tools, image enhancement, and creative AI platforms
-- Uses ON CONFLICT (id, category_id) DO NOTHING to avoid duplicates within the same category

INSERT INTO tools (
  id, name, description, url, category_id, 
  pricing, tags, featured, trending, logo_url
) VALUES 
  -- AI Art & Image Generation
  ('img-gen-midjourney', 'Midjourney', 'AI-powered image generation platform that creates stunning artwork and images from text prompts with artistic styles.', 'https://midjourney.com', 'image-generation-editing', 'Paid', ARRAY['ai-art', 'text-to-image', 'artistic-styles'], false, false, 'https://midjourney.com/favicon.ico'),
  ('img-gen-dall-e', 'DALL-E 3', 'OpenAI''s advanced AI image generator that creates highly detailed and creative images from natural language descriptions.', 'https://openai.com/dall-e-3', 'image-generation-editing', 'Paid', ARRAY['ai-image-generation', 'openai', 'text-to-image'], false, false, 'https://openai.com/favicon.ico'),
  ('img-gen-stable-diffusion', 'Stable Diffusion', 'Open-source AI image generation model that creates high-quality images from text prompts with customizable parameters.', 'https://stability.ai', 'image-generation-editing', 'Freemium', ARRAY['open-source', 'stable-diffusion', 'ai-art'], false, false, 'https://stability.ai/favicon.ico'),
  ('img-gen-leonardo-ai', 'Leonardo AI', 'AI-powered creative platform for generating production-quality visual assets with advanced control and customization.', 'https://leonardo.ai', 'image-generation-editing', 'Freemium', ARRAY['creative-platform', 'production-quality', 'visual-assets'], false, false, 'https://leonardo.ai/favicon.ico'),
  ('img-gen-adobe-firefly', 'Adobe Firefly', 'Adobe''s AI-powered creative suite for generating images, text effects, and creative content with commercial safety.', 'https://firefly.adobe.com', 'image-generation-editing', 'Freemium', ARRAY['adobe', 'commercial-safe', 'creative-suite'], false, false, 'https://firefly.adobe.com/favicon.ico'),
  ('img-gen-runway-ml', 'Runway ML', 'AI-powered creative toolkit for generating and editing images, videos, and multimedia content for creators.', 'https://runwayml.com', 'image-generation-editing', 'Freemium', ARRAY['creative-toolkit', 'multimedia', 'content-creators'], false, false, 'https://runwayml.com/favicon.ico'),
  ('img-gen-canva-ai', 'Canva AI', 'AI-enhanced design platform with text-to-image generation, background removal, and intelligent design suggestions.', 'https://canva.com', 'image-generation-editing', 'Freemium', ARRAY['design-platform', 'background-removal', 'design-suggestions'], false, false, 'https://canva.com/favicon.ico'),
  ('img-gen-jasper-art', 'Jasper Art', 'AI art generator that creates unique images and artwork from text descriptions for marketing and creative projects.', 'https://jasper.ai/art', 'image-generation-editing', 'Paid', ARRAY['marketing-art', 'unique-images', 'creative-projects'], false, false, 'https://jasper.ai/favicon.ico'),
  
  -- AI Photo Editing & Enhancement
  ('img-edit-photoshop-ai', 'Adobe Photoshop AI', 'AI-powered photo editing with generative fill, neural filters, and intelligent selection tools for professional editing.', 'https://adobe.com/products/photoshop', 'image-generation-editing', 'Paid', ARRAY['professional-editing', 'generative-fill', 'neural-filters'], false, false, 'https://adobe.com/favicon.ico'),
  ('img-edit-luminar-ai', 'Luminar AI', 'AI-powered photo editor with sky replacement, portrait enhancement, and automated editing features.', 'https://skylum.com/luminar-ai', 'image-generation-editing', 'Paid', ARRAY['sky-replacement', 'portrait-enhancement', 'automated-editing'], false, false, 'https://skylum.com/favicon.ico'),
  ('img-edit-topaz-ai', 'Topaz Labs AI', 'AI-enhanced photo editing suite with gigapixel upscaling, noise reduction, and image sharpening capabilities.', 'https://topazlabs.com', 'image-generation-editing', 'Paid', ARRAY['gigapixel-upscaling', 'noise-reduction', 'image-sharpening'], false, false, 'https://topazlabs.com/favicon.ico'),
  ('img-edit-remove-bg', 'Remove.bg', 'AI-powered background removal tool that automatically detects and removes backgrounds from images in seconds.', 'https://remove.bg', 'image-generation-editing', 'Freemium', ARRAY['background-removal', 'automatic-detection', 'instant-processing'], false, false, 'https://remove.bg/favicon.ico'),
  ('img-edit-upscayl', 'Upscayl', 'AI-powered image upscaling tool that enhances image resolution and quality using machine learning algorithms.', 'https://upscayl.github.io', 'image-generation-editing', 'Free', ARRAY['image-upscaling', 'resolution-enhancement', 'machine-learning'], false, false, 'https://upscayl.github.io/favicon.ico'),
  ('img-edit-waifu2x', 'Waifu2x', 'AI-based image super-resolution tool for anime-style artwork and photographs with noise reduction.', 'https://waifu2x.udp.jp', 'image-generation-editing', 'Free', ARRAY['super-resolution', 'anime-artwork', 'noise-reduction'], false, false, 'https://waifu2x.udp.jp/favicon.ico'),
  ('img-edit-real-esrgan', 'Real-ESRGAN', 'AI image restoration and enhancement tool that improves quality of low-resolution and degraded images.', 'https://github.com/xinntao/Real-ESRGAN', 'image-generation-editing', 'Free', ARRAY['image-restoration', 'quality-improvement', 'low-resolution'], false, false, 'https://github.com/favicon.ico'),
  ('img-edit-clipdrop', 'ClipDrop', 'AI-powered image editing ecosystem with object removal, background replacement, and creative editing tools.', 'https://clipdrop.co', 'image-generation-editing', 'Freemium', ARRAY['object-removal', 'background-replacement', 'creative-editing'], false, false, 'https://clipdrop.co/favicon.ico'),
  
  -- AI Face & Portrait Tools
  ('img-face-faceapp', 'FaceApp', 'AI-powered face editing app with age progression, gender swap, and facial feature modification capabilities.', 'https://faceapp.com', 'image-generation-editing', 'Freemium', ARRAY['face-editing', 'age-progression', 'facial-modification'], false, false, 'https://faceapp.com/favicon.ico'),
  ('img-face-reface', 'Reface', 'AI face swap technology that replaces faces in videos and GIFs with realistic and seamless results.', 'https://reface.ai', 'image-generation-editing', 'Freemium', ARRAY['face-swap', 'video-editing', 'seamless-results'], false, false, 'https://reface.ai/favicon.ico'),
  ('img-face-artbreeder', 'Artbreeder', 'AI-powered collaborative art platform for creating and modifying portraits, landscapes, and abstract art.', 'https://artbreeder.com', 'image-generation-editing', 'Freemium', ARRAY['collaborative-art', 'portrait-creation', 'landscape-art'], false, false, 'https://artbreeder.com/favicon.ico'),
  ('img-face-generated-photos', 'Generated Photos', 'AI-generated human faces and full-body photos with diverse demographics and customizable features.', 'https://generated.photos', 'image-generation-editing', 'Paid', ARRAY['human-faces', 'diverse-demographics', 'customizable-features'], false, false, 'https://generated.photos/favicon.ico'),
  ('img-face-thispersondoesnotexist', 'This Person Does Not Exist', 'AI-generated realistic human faces using StyleGAN technology for creative and commercial projects.', 'https://thispersondoesnotexist.com', 'image-generation-editing', 'Free', ARRAY['realistic-faces', 'stylegan', 'commercial-projects'], false, false, 'https://thispersondoesnotexist.com/favicon.ico'),
  ('img-face-deepfacelab', 'DeepFaceLab', 'Open-source deepfake software for face swapping and facial reenactment with advanced AI algorithms.', 'https://github.com/iperov/DeepFaceLab', 'image-generation-editing', 'Free', ARRAY['deepfake', 'face-swapping', 'facial-reenactment'], false, false, 'https://github.com/favicon.ico'),
  ('img-face-avatarify', 'Avatarify', 'AI-powered real-time face animation and avatar creation for video calls and content creation.', 'https://avatarify.ai', 'image-generation-editing', 'Freemium', ARRAY['face-animation', 'avatar-creation', 'real-time'], false, false, 'https://avatarify.ai/favicon.ico'),
  ('img-face-facetune', 'Facetune', 'AI-enhanced selfie editing app with portrait retouching, teeth whitening, and facial feature enhancement.', 'https://facetune.com', 'image-generation-editing', 'Freemium', ARRAY['selfie-editing', 'portrait-retouching', 'feature-enhancement'], false, false, 'https://facetune.com/favicon.ico'),
  
  -- AI Style Transfer & Artistic Tools
  ('img-style-prisma', 'Prisma', 'AI-powered photo editor that transforms images into artwork using neural networks and artistic style transfer.', 'https://prisma-ai.com', 'image-generation-editing', 'Freemium', ARRAY['artistic-style-transfer', 'neural-networks', 'photo-to-art'], false, false, 'https://prisma-ai.com/favicon.ico'),
  ('img-style-deepart', 'DeepArt.io', 'AI art generator that creates artistic renditions of photos using deep learning and famous art styles.', 'https://deepart.io', 'image-generation-editing', 'Freemium', ARRAY['artistic-renditions', 'deep-learning', 'famous-art-styles'], false, false, 'https://deepart.io/favicon.ico'),
  ('img-style-neural-love', 'Neural Love', 'AI-powered art generator with style transfer, image enhancement, and creative filters for artistic transformation.', 'https://neural.love', 'image-generation-editing', 'Freemium', ARRAY['style-transfer', 'image-enhancement', 'artistic-transformation'], false, false, 'https://neural.love/favicon.ico'),
  ('img-style-ostagram', 'Ostagram', 'AI style transfer service that combines content from one image with artistic style from another image.', 'https://ostagram.me', 'image-generation-editing', 'Freemium', ARRAY['style-transfer', 'content-combination', 'artistic-style'], false, false, 'https://ostagram.me/favicon.ico'),
  ('img-style-dreamscope', 'DreamScope', 'AI-powered image transformation platform with artistic filters and deep learning-based style effects.', 'https://dreamscopeapp.com', 'image-generation-editing', 'Freemium', ARRAY['image-transformation', 'artistic-filters', 'style-effects'], false, false, 'https://dreamscopeapp.com/favicon.ico'),
  ('img-style-deep-dream', 'Deep Dream Generator', 'AI art creation tool based on Google''s DeepDream algorithm for psychedelic and surreal image effects.', 'https://deepdreamgenerator.com', 'image-generation-editing', 'Freemium', ARRAY['deepdream', 'psychedelic-effects', 'surreal-images'], false, false, 'https://deepdreamgenerator.com/favicon.ico'),
  ('img-style-artisto', 'Artisto', 'AI video and photo editor with artistic style transfer and real-time video processing capabilities.', 'https://artisto.my.com', 'image-generation-editing', 'Free', ARRAY['video-editing', 'real-time-processing', 'style-transfer'], false, false, 'https://artisto.my.com/favicon.ico'),
  ('img-style-waterlogue', 'Waterlogue', 'AI-powered watercolor painting simulation that transforms photos into realistic watercolor artwork.', 'https://waterlogue.com', 'image-generation-editing', 'Paid', ARRAY['watercolor-painting', 'realistic-artwork', 'painting-simulation'], false, false, 'https://waterlogue.com/favicon.ico'),
  
  -- AI Design & Layout Tools
  ('img-design-figma-ai', 'Figma AI', 'AI-powered design features in Figma including auto-layout suggestions, design system recommendations, and smart components.', 'https://figma.com', 'image-generation-editing', 'Freemium', ARRAY['design-features', 'auto-layout', 'smart-components'], false, false, 'https://figma.com/favicon.ico'),
  ('img-design-sketch-ai', 'Sketch AI Assistant', 'AI-enhanced design tools for Sketch with intelligent suggestions, automated tasks, and design optimization.', 'https://sketch.com', 'image-generation-editing', 'Paid', ARRAY['design-tools', 'intelligent-suggestions', 'design-optimization'], false, false, 'https://sketch.com/favicon.ico'),
  ('img-design-brandmark', 'Brandmark', 'AI-powered logo and brand design generator that creates professional logos and brand assets automatically.', 'https://brandmark.io', 'image-generation-editing', 'Paid', ARRAY['logo-design', 'brand-assets', 'professional-logos'], false, false, 'https://brandmark.io/favicon.ico'),
  ('img-design-looka', 'Looka', 'AI logo maker and brand identity platform that generates custom logos and marketing materials.', 'https://looka.com', 'image-generation-editing', 'Paid', ARRAY['logo-maker', 'brand-identity', 'marketing-materials'], false, false, 'https://looka.com/favicon.ico'),
  ('img-design-tailor-brands', 'Tailor Brands', 'AI-powered branding platform with logo design, website creation, and brand asset generation.', 'https://tailorbrands.com', 'image-generation-editing', 'Paid', ARRAY['branding-platform', 'website-creation', 'brand-assets'], false, false, 'https://tailorbrands.com/favicon.ico'),
  ('img-design-designify', 'Designify', 'AI-powered design automation tool that creates professional designs from simple inputs and templates.', 'https://designify.com', 'image-generation-editing', 'Freemium', ARRAY['design-automation', 'professional-designs', 'templates'], false, false, 'https://designify.com/favicon.ico'),
  ('img-design-gamma', 'Gamma', 'AI-powered presentation and document design tool that creates beautiful layouts automatically.', 'https://gamma.app', 'image-generation-editing', 'Freemium', ARRAY['presentation-design', 'document-design', 'automatic-layouts'], false, false, 'https://gamma.app/favicon.ico'),
  ('img-design-beautiful-ai', 'Beautiful.ai', 'AI-enhanced presentation software with smart slide design and automatic formatting features.', 'https://beautiful.ai', 'image-generation-editing', 'Paid', ARRAY['presentation-software', 'smart-slides', 'automatic-formatting'], false, false, 'https://beautiful.ai/favicon.ico'),
  
  -- AI Image Restoration & Colorization
  ('img-restore-myheritage', 'MyHeritage In Color', 'AI-powered photo colorization and enhancement service that brings old black and white photos to life.', 'https://myheritage.com/incolor', 'image-generation-editing', 'Freemium', ARRAY['photo-colorization', 'photo-enhancement', 'historical-photos'], false, false, 'https://myheritage.com/favicon.ico'),
  ('img-restore-deepai-colorizer', 'DeepAI Colorizer', 'AI image colorization tool that automatically adds realistic colors to black and white photographs.', 'https://deepai.org/machine-learning-model/colorizer', 'image-generation-editing', 'Free', ARRAY['image-colorization', 'realistic-colors', 'automatic-processing'], false, false, 'https://deepai.org/favicon.ico'),
  ('img-restore-palette-fm', 'Palette.fm', 'AI-powered photo colorization platform with multiple colorization styles and historical accuracy options.', 'https://palette.fm', 'image-generation-editing', 'Freemium', ARRAY['photo-colorization', 'multiple-styles', 'historical-accuracy'], false, false, 'https://palette.fm/favicon.ico'),
  ('img-restore-pixelmator-ml', 'Pixelmator Pro ML', 'AI-enhanced photo editing with machine learning-powered auto-enhance and intelligent selection tools.', 'https://pixelmator.com/pro', 'image-generation-editing', 'Paid', ARRAY['photo-editing', 'auto-enhance', 'intelligent-selection'], false, false, 'https://pixelmator.com/favicon.ico'),
  ('img-restore-old-photo-restoration', 'Old Photo Restoration', 'AI-powered service for restoring damaged, faded, and torn historical photographs automatically.', 'https://oldphotorestoration.ai', 'image-generation-editing', 'Paid', ARRAY['photo-restoration', 'damaged-photos', 'historical-preservation'], false, false, 'https://oldphotorestoration.ai/favicon.ico'),
  ('img-restore-remini', 'Remini', 'AI photo enhancer that improves old, blurry, and low-quality photos with face enhancement technology.', 'https://remini.ai', 'image-generation-editing', 'Freemium', ARRAY['photo-enhancer', 'face-enhancement', 'quality-improvement'], false, false, 'https://remini.ai/favicon.ico'),
  ('img-restore-vanceai', 'VanceAI', 'AI-powered image enhancement suite with upscaling, denoising, sharpening, and background removal tools.', 'https://vanceai.com', 'image-generation-editing', 'Freemium', ARRAY['image-enhancement', 'upscaling', 'denoising'], false, false, 'https://vanceai.com/favicon.ico'),
  ('img-restore-gigapixel-ai', 'Gigapixel AI', 'AI image upscaling software that enlarges and enhances images up to 600% while preserving quality.', 'https://topazlabs.com/gigapixel-ai', 'image-generation-editing', 'Paid', ARRAY['image-upscaling', 'quality-preservation', 'enlargement'], false, false, 'https://topazlabs.com/favicon.ico'),
  
  -- AI Animation & Motion Graphics
  ('img-animate-luma-ai', 'Luma AI', 'AI-powered 3D content creation platform with photogrammetry and neural radiance fields for realistic scenes.', 'https://lumalabs.ai', 'image-generation-editing', 'Freemium', ARRAY['3d-content', 'photogrammetry', 'neural-radiance'], false, false, 'https://lumalabs.ai/favicon.ico'),
  ('img-animate-pika-labs', 'Pika Labs', 'AI video generation platform that creates animated videos from text prompts and static images.', 'https://pika.art', 'image-generation-editing', 'Freemium', ARRAY['video-generation', 'animated-videos', 'text-to-video'], false, false, 'https://pika.art/favicon.ico'),
  ('img-animate-gen2-runway', 'Gen-2 by Runway', 'AI video generation tool that creates videos from text, images, or existing video clips with style transfer.', 'https://runwayml.com/ai-magic-tools/gen-2', 'image-generation-editing', 'Paid', ARRAY['video-generation', 'style-transfer', 'ai-magic'], false, false, 'https://runwayml.com/favicon.ico'),
  ('img-animate-kaiber', 'Kaiber', 'AI video generation platform for creating music videos, animations, and artistic content from audio and prompts.', 'https://kaiber.ai', 'image-generation-editing', 'Paid', ARRAY['music-videos', 'animations', 'artistic-content'], false, false, 'https://kaiber.ai/favicon.ico'),
  ('img-animate-immersity-ai', 'Immersity AI', 'AI platform for converting 2D images into 3D and creating depth maps for immersive experiences.', 'https://immersity.ai', 'image-generation-editing', 'Freemium', ARRAY['2d-to-3d', 'depth-maps', 'immersive-experiences'], false, false, 'https://immersity.ai/favicon.ico'),
  ('img-animate-metamorphic', 'Metamorphic', 'AI-powered morphing and transformation tool for creating seamless transitions between images.', 'https://metamorphic.ai', 'image-generation-editing', 'Paid', ARRAY['morphing', 'image-transitions', 'seamless-transformation'], false, false, 'https://metamorphic.ai/favicon.ico'),
  ('img-animate-plotaverse', 'Plotaverse', 'AI-enhanced photo animation platform that adds motion and effects to static images.', 'https://plotaverse.com', 'image-generation-editing', 'Freemium', ARRAY['photo-animation', 'motion-effects', 'static-to-animated'], false, false, 'https://plotaverse.com/favicon.ico'),
  ('img-animate-immersive-limit', 'Immersive Limit', 'AI tool for creating parallax effects and depth illusions in photographs for engaging visual content.', 'https://immersivelimit.com', 'image-generation-editing', 'Paid', ARRAY['parallax-effects', 'depth-illusions', 'visual-content'], false, false, 'https://immersivelimit.com/favicon.ico'),
  
  -- AI Texture & Pattern Generation
  ('img-texture-patternify', 'Patternify', 'AI-powered pattern generator that creates seamless textures and patterns for design and web development.', 'https://patternify.com', 'image-generation-editing', 'Free', ARRAY['pattern-generator', 'seamless-textures', 'web-development'], false, false, 'https://patternify.com/favicon.ico'),
  ('img-texture-artboard-studio', 'Artboard Studio', 'AI-enhanced mockup and design tool with automatic background generation and product visualization.', 'https://artboard.studio', 'image-generation-editing', 'Freemium', ARRAY['mockup-tool', 'background-generation', 'product-visualization'], false, false, 'https://artboard.studio/favicon.ico'),
  ('img-texture-substance-ai', 'Substance 3D Sampler', 'AI-powered material creation tool that generates 3D textures and materials from photographs.', 'https://substance3d.adobe.com/products/substance-sampler', 'image-generation-editing', 'Paid', ARRAY['material-creation', '3d-textures', 'photo-to-material'], false, false, 'https://substance3d.adobe.com/favicon.ico'),
  ('img-texture-texture-ai', 'Texture.ai', 'AI texture generation platform for creating high-quality seamless textures for 3D modeling and game development.', 'https://texture.ai', 'image-generation-editing', 'Paid', ARRAY['texture-generation', '3d-modeling', 'game-development'], false, false, 'https://texture.ai/favicon.ico'),
  ('img-texture-poly-ai', 'Poly.ai', 'AI-powered 3D asset generation platform with texture creation, material design, and model optimization.', 'https://poly.ai', 'image-generation-editing', 'Freemium', ARRAY['3d-assets', 'material-design', 'model-optimization'], false, false, 'https://poly.ai/favicon.ico'),
  ('img-texture-seamless-studio', 'Seamless Studio', 'AI tool for creating seamless tileable textures and patterns with intelligent edge matching.', 'https://seamlessstudio.ai', 'image-generation-editing', 'Paid', ARRAY['seamless-textures', 'tileable-patterns', 'edge-matching'], false, false, 'https://seamlessstudio.ai/favicon.ico'),
  ('img-texture-material-maker', 'Material Maker', 'AI-enhanced procedural material creation tool with node-based workflow and texture generation.', 'https://materialmaker.org', 'image-generation-editing', 'Free', ARRAY['procedural-materials', 'node-based', 'texture-generation'], false, false, 'https://materialmaker.org/favicon.ico'),
  ('img-texture-quixel-mixer', 'Quixel Mixer', 'AI-assisted 3D material creation and texture painting tool with smart blending and material authoring.', 'https://quixel.com/mixer', 'image-generation-editing', 'Free', ARRAY['3d-materials', 'texture-painting', 'smart-blending'], false, false, 'https://quixel.com/favicon.ico'),
  
  -- AI Color & Lighting Tools
  ('img-color-coolors-ai', 'Coolors AI', 'AI-powered color palette generator with intelligent color harmony suggestions and accessibility checking.', 'https://coolors.co', 'image-generation-editing', 'Freemium', ARRAY['color-palettes', 'color-harmony', 'accessibility'], false, false, 'https://coolors.co/favicon.ico'),
  ('img-color-khroma', 'Khroma', 'AI color tool that learns your preferences and generates limitless color palettes for design projects.', 'https://khroma.co', 'image-generation-editing', 'Free', ARRAY['color-tool', 'preference-learning', 'limitless-palettes'], false, false, 'https://khroma.co/favicon.ico'),
  ('img-color-colormind', 'Colormind', 'AI color scheme generator that creates cohesive color palettes using machine learning algorithms.', 'https://colormind.io', 'image-generation-editing', 'Free', ARRAY['color-schemes', 'cohesive-palettes', 'machine-learning'], false, false, 'https://colormind.io/favicon.ico'),
  ('img-color-huemint', 'Huemint', 'AI-powered color palette generator with brand-specific color suggestions and trend analysis.', 'https://huemint.com', 'image-generation-editing', 'Free', ARRAY['brand-colors', 'trend-analysis', 'color-suggestions'], false, false, 'https://huemint.com/favicon.ico'),
  ('img-color-adobe-color', 'Adobe Color AI', 'AI-enhanced color tool with intelligent palette extraction, trend insights, and accessibility features.', 'https://color.adobe.com', 'image-generation-editing', 'Free', ARRAY['palette-extraction', 'trend-insights', 'accessibility'], false, false, 'https://color.adobe.com/favicon.ico'),
  ('img-color-paletton', 'Paletton AI', 'AI color scheme designer with advanced color theory and psychological color impact analysis.', 'https://paletton.com', 'image-generation-editing', 'Free', ARRAY['color-theory', 'psychological-impact', 'scheme-designer'], false, false, 'https://paletton.com/favicon.ico'),
  ('img-color-contrast-ai', 'Contrast.ai', 'AI-powered color contrast checker and optimizer for web accessibility and design compliance.', 'https://contrast.ai', 'image-generation-editing', 'Free', ARRAY['contrast-checker', 'accessibility', 'design-compliance'], false, false, 'https://contrast.ai/favicon.ico'),
  ('img-color-colorffy', 'Colorffy', 'AI color grading and correction tool for photos and videos with intelligent color enhancement.', 'https://colorffy.com', 'image-generation-editing', 'Paid', ARRAY['color-grading', 'color-correction', 'intelligent-enhancement'], false, false, 'https://colorffy.com/favicon.ico'),
  
  -- AI Sketch & Drawing Tools
  ('img-sketch-autodraw', 'AutoDraw', 'Google''s AI-powered drawing tool that suggests completed drawings from simple sketches using machine learning.', 'https://autodraw.com', 'image-generation-editing', 'Free', ARRAY['drawing-tool', 'sketch-completion', 'google-ai'], false, false, 'https://autodraw.com/favicon.ico'),
  ('img-sketch-quick-draw', 'Quick, Draw!', 'AI-powered drawing game that recognizes sketches and learns from user drawings to improve recognition.', 'https://quickdraw.withgoogle.com', 'image-generation-editing', 'Free', ARRAY['drawing-game', 'sketch-recognition', 'learning-ai'], false, false, 'https://quickdraw.withgoogle.com/favicon.ico'),
  ('img-sketch-scribble-diffusion', 'Scribble Diffusion', 'AI tool that turns simple sketches into detailed artwork using diffusion models and style transfer.', 'https://scribblediffusion.com', 'image-generation-editing', 'Free', ARRAY['sketch-to-art', 'diffusion-models', 'style-transfer'], false, false, 'https://scribblediffusion.com/favicon.ico'),
  ('img-sketch-sketch-metademolab', 'Sketch MetaDemoLab', 'AI sketch understanding and completion tool that interprets and enhances hand-drawn sketches.', 'https://sketch.metademolab.com', 'image-generation-editing', 'Free', ARRAY['sketch-understanding', 'sketch-completion', 'hand-drawn'], false, false, 'https://sketch.metademolab.com/favicon.ico'),
  ('img-sketch-magicsketch', 'MagicSketch', 'AI-powered sketch enhancement tool that transforms rough drawings into polished illustrations.', 'https://magicsketch.io', 'image-generation-editing', 'Freemium', ARRAY['sketch-enhancement', 'polished-illustrations', 'drawing-transformation'], false, false, 'https://magicsketch.io/favicon.ico'),
  ('img-sketch-concepts-ai', 'Concepts AI', 'AI-enhanced vector design tool with intelligent drawing assistance and precision sketching features.', 'https://concepts.app', 'image-generation-editing', 'Freemium', ARRAY['vector-design', 'drawing-assistance', 'precision-sketching'], false, false, 'https://concepts.app/favicon.ico'),
  ('img-sketch-procreate-ai', 'Procreate AI', 'AI-powered digital painting app with intelligent brush suggestions and automatic layer organization.', 'https://procreate.art', 'image-generation-editing', 'Paid', ARRAY['digital-painting', 'brush-suggestions', 'layer-organization'], false, false, 'https://procreate.art/favicon.ico'),
  ('img-sketch-adobe-fresco', 'Adobe Fresco AI', 'AI-enhanced digital painting and drawing app with live brushes and intelligent color mixing.', 'https://adobe.com/products/fresco', 'image-generation-editing', 'Freemium', ARRAY['digital-painting', 'live-brushes', 'color-mixing'], false, false, 'https://adobe.com/favicon.ico'),
  
  -- AI Video Thumbnail & Social Media Graphics
  ('img-social-thumbnail-ai', 'Thumbnail.ai', 'AI-powered YouTube thumbnail generator that creates engaging thumbnails optimized for click-through rates.', 'https://thumbnail.ai', 'image-generation-editing', 'Paid', ARRAY['youtube-thumbnails', 'click-optimization', 'engagement'], false, false, 'https://thumbnail.ai/favicon.ico'),
  ('img-social-bannerbear', 'Bannerbear', 'AI-powered auto-generation of social media graphics, video thumbnails, and marketing visuals.', 'https://bannerbear.com', 'image-generation-editing', 'Paid', ARRAY['social-media-graphics', 'auto-generation', 'marketing-visuals'], false, false, 'https://bannerbear.com/favicon.ico'),
  ('img-social-designstripe', 'DesignStripe', 'AI-enhanced social media design tool with automated post creation and brand consistency features.', 'https://designstripe.com', 'image-generation-editing', 'Freemium', ARRAY['social-media-design', 'automated-posts', 'brand-consistency'], false, false, 'https://designstripe.com/favicon.ico'),
  ('img-social-relay-that', 'Relay That', 'AI-powered social media graphics generator with smart templates and automated design suggestions.', 'https://relaythat.com', 'image-generation-editing', 'Paid', ARRAY['social-graphics', 'smart-templates', 'design-suggestions'], false, false, 'https://relaythat.com/favicon.ico'),
  ('img-social-crello-ai', 'Crello AI', 'AI-enhanced design platform for creating social media posts, stories, and marketing materials automatically.', 'https://crello.com', 'image-generation-editing', 'Freemium', ARRAY['design-platform', 'social-posts', 'marketing-materials'], false, false, 'https://crello.com/favicon.ico'),
  ('img-social-snappa', 'Snappa', 'AI-powered graphic design tool with intelligent sizing and optimization for different social media platforms.', 'https://snappa.com', 'image-generation-editing', 'Freemium', ARRAY['graphic-design', 'intelligent-sizing', 'platform-optimization'], false, false, 'https://snappa.com/favicon.ico'),
  ('img-social-easil', 'Easil', 'AI-enhanced visual content creation platform with smart brand management and automated design features.', 'https://easil.com', 'image-generation-editing', 'Freemium', ARRAY['visual-content', 'brand-management', 'automated-design'], false, false, 'https://easil.com/favicon.ico'),
  ('img-social-stencil', 'Stencil', 'AI-powered social media image creator with intelligent quote design and visual content optimization.', 'https://getstencil.com', 'image-generation-editing', 'Freemium', ARRAY['social-media-images', 'quote-design', 'content-optimization'], false, false, 'https://getstencil.com/favicon.ico'),
  
  -- AI Background & Environment Generation
  ('img-bg-photoroom', 'PhotoRoom', 'AI-powered background removal and replacement tool with professional studio backgrounds and product photography.', 'https://photoroom.com', 'image-generation-editing', 'Freemium', ARRAY['background-removal', 'studio-backgrounds', 'product-photography'], false, false, 'https://photoroom.com/favicon.ico'),
  ('img-bg-canva-bg-remover', 'Canva Background Remover', 'AI background removal tool integrated with design platform for seamless editing and replacement.', 'https://canva.com/bg-remover', 'image-generation-editing', 'Freemium', ARRAY['background-removal', 'seamless-editing', 'design-integration'], false, false, 'https://canva.com/favicon.ico'),
  ('img-bg-cutout-pro', 'Cutout.pro', 'AI-powered background removal and editing suite with batch processing and API integration capabilities.', 'https://cutout.pro', 'image-generation-editing', 'Freemium', ARRAY['background-editing', 'batch-processing', 'api-integration'], false, false, 'https://cutout.pro/favicon.ico'),
  ('img-bg-slazzer', 'Slazzer', 'AI background removal tool with high precision edge detection and instant processing for e-commerce.', 'https://slazzer.com', 'image-generation-editing', 'Freemium', ARRAY['precision-edge-detection', 'instant-processing', 'e-commerce'], false, false, 'https://slazzer.com/favicon.ico'),
  ('img-bg-erase-bg', 'Erase.bg', 'AI-powered background eraser with automatic subject detection and transparent background creation.', 'https://erase.bg', 'image-generation-editing', 'Freemium', ARRAY['background-eraser', 'subject-detection', 'transparent-backgrounds'], false, false, 'https://erase.bg/favicon.ico'),
  ('img-bg-unscreen', 'Unscreen', 'AI-powered background removal for videos and GIFs with automatic green screen effect and transparency.', 'https://unscreen.com', 'image-generation-editing', 'Freemium', ARRAY['video-background-removal', 'green-screen', 'transparency'], false, false, 'https://unscreen.com/favicon.ico'),
  ('img-bg-picmonkey', 'PicMonkey Background', 'AI background replacement and editing tool with smart selection and professional background library.', 'https://picmonkey.com', 'image-generation-editing', 'Freemium', ARRAY['background-replacement', 'smart-selection', 'background-library'], false, false, 'https://picmonkey.com/favicon.ico'),
  ('img-bg-fotor-bg', 'Fotor Background Changer', 'AI-powered background editing with automatic detection, removal, and replacement with extensive template library.', 'https://fotor.com/background-changer', 'image-generation-editing', 'Freemium', ARRAY['background-editing', 'automatic-detection', 'template-library'], false, false, 'https://fotor.com/favicon.ico'),
  
  -- AI Object Detection & Removal
  ('img-object-magiceraser', 'Magic Eraser', 'AI-powered object removal tool that intelligently fills in backgrounds after removing unwanted objects.', 'https://magiceraser.io', 'image-generation-editing', 'Free', ARRAY['object-removal', 'intelligent-fill', 'unwanted-objects'], false, false, 'https://magiceraser.io/favicon.ico'),
  ('img-object-cleanup-pictures', 'Cleanup.pictures', 'AI object removal and photo retouching tool with smart inpainting and content-aware fill.', 'https://cleanup.pictures', 'image-generation-editing', 'Freemium', ARRAY['object-removal', 'photo-retouching', 'content-aware-fill'], false, false, 'https://cleanup.pictures/favicon.ico'),
  ('img-object-inpaint-web', 'Inpaint Web', 'AI-powered photo restoration and object removal tool with intelligent reconstruction algorithms.', 'https://inpaint.theorythat.com', 'image-generation-editing', 'Free', ARRAY['photo-restoration', 'object-removal', 'reconstruction'], false, false, 'https://inpaint.theorythat.com/favicon.ico'),
  ('img-object-hama', 'Hama', 'AI eraser tool for removing objects, people, and text from photos with seamless background reconstruction.', 'https://hama.app', 'image-generation-editing', 'Free', ARRAY['eraser-tool', 'people-removal', 'seamless-reconstruction'], false, false, 'https://hama.app/favicon.ico'),
  ('img-object-touchretouch', 'TouchRetouch', 'AI-powered mobile app for removing unwanted objects and blemishes from photos with one-tap editing.', 'https://touchretouch.com', 'image-generation-editing', 'Paid', ARRAY['mobile-app', 'one-tap-editing', 'blemish-removal'], false, false, 'https://touchretouch.com/favicon.ico'),
  ('img-object-webinpaint', 'WebInpaint', 'AI photo restoration tool for removing watermarks, objects, and imperfections with smart filling.', 'https://webinpaint.com', 'image-generation-editing', 'Freemium', ARRAY['photo-restoration', 'watermark-removal', 'smart-filling'], false, false, 'https://webinpaint.com/favicon.ico'),
  ('img-object-snapseed-healing', 'Snapseed Healing', 'AI-enhanced photo editing app with intelligent healing tool for object removal and photo correction.', 'https://snapseed.online', 'image-generation-editing', 'Free', ARRAY['photo-editing-app', 'healing-tool', 'photo-correction'], false, false, 'https://snapseed.online/favicon.ico'),
  ('img-object-clipping-magic', 'Clipping Magic', 'AI-powered background removal and object isolation tool with precise edge detection and manual refinement.', 'https://clippingmagic.com', 'image-generation-editing', 'Paid', ARRAY['background-removal', 'object-isolation', 'edge-detection'], false, false, 'https://clippingmagic.com/favicon.ico')
ON CONFLICT (id, category_id) DO NOTHING;

-- Update the tool count for the category
UPDATE categories 
SET tool_count = (
  SELECT COUNT(*) 
  FROM tools 
  WHERE category_id = 'image-generation-editing'
) 
WHERE id = 'image-generation-editing';
