-- Additional Writing & Editing AI Tools (55 tools)
-- This script adds 55 more AI-powered tools for writing and editing
-- Excludes the existing 50 tools already in the category
-- Uses ON CONFLICT (id, category_id) DO NOTHING to avoid duplicates within the same category

INSERT INTO tools (
  id, name, description, url, category_id, 
  pricing, tags, featured, trending, logo_url
) VALUES 
  -- Advanced AI Writing Assistants
  ('writing-claude-3', 'Claude 3', 'Anthropic''s advanced AI assistant for complex writing, analysis, and creative tasks with superior reasoning capabilities.', 'https://claude.ai', 'writing-editing', 'Freemium', ARRAY['ai-assistant', 'advanced-writing', 'analysis'], false, true, 'https://claude.ai/favicon.ico'),
  ('writing-perplexity', 'Perplexity AI', 'AI-powered research and writing assistant that provides accurate, cited information for content creation.', 'https://perplexity.ai', 'writing-editing', 'Freemium', ARRAY['research-writing', 'citations', 'fact-checking'], false, true, 'https://perplexity.ai/favicon.ico'),
  ('writing-poe', 'Poe by Quora', 'Platform for accessing multiple AI writing models including GPT-4, Claude, and others for diverse writing needs.', 'https://poe.com', 'writing-editing', 'Freemium', ARRAY['multi-ai-platform', 'writing-models', 'diverse-tools'], false, false, 'https://poe.com/favicon.ico'),
  ('writing-chatgpt-plus', 'ChatGPT Plus', 'OpenAI''s premium AI writing assistant with GPT-4 access for advanced content creation and editing.', 'https://chat.openai.com', 'writing-editing', 'Paid', ARRAY['premium-ai', 'gpt-4', 'content-creation'], false, true, 'https://chat.openai.com/favicon.ico'),
  ('writing-notion-ai', 'Notion AI', 'Integrated AI writing assistant within Notion workspace for seamless content creation and editing.', 'https://notion.so/ai', 'writing-editing', 'Paid', ARRAY['workspace-integration', 'content-creation', 'collaborative-writing'], false, false, 'https://notion.so/favicon.ico'),
  
  -- Specialized Content Writing AI
  ('writing-articleforge', 'Article Forge', 'AI content generator that creates unique, high-quality articles on any topic using deep learning.', 'https://articleforge.com', 'writing-editing', 'Paid', ARRAY['article-generation', 'deep-learning', 'unique-content'], false, false, 'https://articleforge.com/favicon.ico'),
  ('writing-contentking', 'ContentKing', 'AI-powered content optimization platform for real-time SEO monitoring and content improvement.', 'https://contentkingapp.com', 'writing-editing', 'Paid', ARRAY['content-optimization', 'seo-monitoring', 'real-time-analysis'], false, false, 'https://contentkingapp.com/favicon.ico'),
  ('writing-writerly', 'Writerly', 'AI writing platform designed for long-form content creation with advanced editing and collaboration features.', 'https://writerly.ai', 'writing-editing', 'Freemium', ARRAY['long-form-content', 'collaboration', 'advanced-editing'], false, false, 'https://writerly.ai/favicon.ico'),
  ('writing-wordsmith', 'Wordsmith by Automated Insights', 'AI platform that transforms data into narrative content at scale for business reporting and insights.', 'https://automatedinsights.com/wordsmith', 'writing-editing', 'Paid', ARRAY['data-to-narrative', 'business-reporting', 'automated-content'], false, false, 'https://automatedinsights.com/favicon.ico'),
  ('writing-yarnit', 'Yarnit', 'AI-powered content creation platform for personalized storytelling and multimedia content generation.', 'https://yarnit.app', 'writing-editing', 'Freemium', ARRAY['storytelling', 'multimedia-content', 'personalized-creation'], false, false, 'https://yarnit.app/favicon.ico'),
  
  -- Academic & Research Writing AI
  ('writing-scholarcy', 'Scholarcy', 'AI research assistant that summarizes academic papers, extracts key insights, and generates bibliographies.', 'https://scholarcy.com', 'writing-editing', 'Freemium', ARRAY['academic-research', 'paper-summarization', 'bibliography-generation'], false, false, 'https://scholarcy.com/favicon.ico'),
  ('writing-genei', 'Genei', 'AI research tool that automatically summarizes articles, PDFs, and webpages for academic writing.', 'https://genei.io', 'writing-editing', 'Freemium', ARRAY['research-summarization', 'academic-writing', 'pdf-analysis'], false, false, 'https://genei.io/favicon.ico'),
  ('writing-elicit', 'Elicit', 'AI research assistant that helps find relevant papers, extract key claims, and synthesize findings.', 'https://elicit.org', 'writing-editing', 'Free', ARRAY['research-assistant', 'paper-analysis', 'claim-extraction'], false, false, 'https://elicit.org/favicon.ico'),
  ('writing-consensus', 'Consensus', 'AI-powered search engine for scientific research that provides evidence-based answers from peer-reviewed studies.', 'https://consensus.app', 'writing-editing', 'Freemium', ARRAY['scientific-research', 'evidence-based', 'peer-reviewed'], false, false, 'https://consensus.app/favicon.ico'),
  ('writing-scite', 'Scite', 'AI platform that analyzes citation context to help researchers evaluate and improve their academic writing.', 'https://scite.ai', 'writing-editing', 'Freemium', ARRAY['citation-analysis', 'academic-evaluation', 'research-improvement'], false, false, 'https://scite.ai/favicon.ico'),
  
  -- Creative Writing & Fiction AI
  ('writing-ai-dungeon', 'AI Dungeon', 'AI-powered text adventure game and creative writing platform for interactive storytelling.', 'https://aidungeon.io', 'writing-editing', 'Freemium', ARRAY['interactive-storytelling', 'creative-writing', 'text-adventure'], false, false, 'https://aidungeon.io/favicon.ico'),
  ('writing-story-ai', 'Story AI', 'AI creative writing assistant specialized in fiction, character development, and plot generation.', 'https://storyai.cc', 'writing-editing', 'Freemium', ARRAY['fiction-writing', 'character-development', 'plot-generation'], false, false, 'https://storyai.cc/favicon.ico'),
  ('writing-plottr', 'Plottr', 'AI-enhanced story planning and writing tool for novelists with timeline and character tracking.', 'https://plottr.com', 'writing-editing', 'Paid', ARRAY['story-planning', 'novel-writing', 'character-tracking'], false, false, 'https://plottr.com/favicon.ico'),
  ('writing-campfire', 'Campfire Write', 'AI-assisted worldbuilding and writing platform for fantasy and sci-fi authors.', 'https://campfirewrite.com', 'writing-editing', 'Paid', ARRAY['worldbuilding', 'fantasy-writing', 'sci-fi-writing'], false, false, 'https://campfirewrite.com/favicon.ico'),
  ('writing-character-ai', 'Character.AI Writing', 'AI platform for creating interactive characters and dialogue for creative writing projects.', 'https://character.ai', 'writing-editing', 'Free', ARRAY['character-creation', 'dialogue-writing', 'interactive-characters'], false, false, 'https://character.ai/favicon.ico'),
  
  -- Technical & Documentation Writing AI
  ('writing-gitbook-ai', 'GitBook AI', 'AI-powered documentation platform that helps create, organize, and maintain technical documentation.', 'https://gitbook.com', 'writing-editing', 'Freemium', ARRAY['technical-documentation', 'knowledge-management', 'team-collaboration'], false, false, 'https://gitbook.com/favicon.ico'),
  ('writing-document360', 'Document360', 'AI-enhanced knowledge base platform for creating and managing technical documentation.', 'https://document360.com', 'writing-editing', 'Paid', ARRAY['knowledge-base', 'technical-writing', 'documentation-management'], false, false, 'https://document360.com/favicon.ico'),
  ('writing-confluence-ai', 'Confluence AI', 'Atlassian''s AI-powered collaboration platform for team documentation and knowledge sharing.', 'https://atlassian.com/software/confluence', 'writing-editing', 'Paid', ARRAY['team-documentation', 'collaboration', 'knowledge-sharing'], false, false, 'https://atlassian.com/favicon.ico'),
  ('writing-helpjuice', 'Helpjuice', 'AI-powered knowledge base software for creating customer support documentation and FAQs.', 'https://helpjuice.com', 'writing-editing', 'Paid', ARRAY['customer-support', 'knowledge-base', 'faq-creation'], false, false, 'https://helpjuice.com/favicon.ico'),
  ('writing-slite', 'Slite', 'AI-enhanced team documentation tool that organizes and maintains company knowledge.', 'https://slite.com', 'writing-editing', 'Freemium', ARRAY['team-documentation', 'company-knowledge', 'organization'], false, false, 'https://slite.com/favicon.ico'),
  
  -- Translation & Localization AI
  ('writing-deepl-write', 'DeepL Write', 'AI writing assistant that improves and perfects text in multiple languages with advanced grammar checking.', 'https://deepl.com/write', 'writing-editing', 'Freemium', ARRAY['multilingual-writing', 'grammar-checking', 'text-improvement'], false, false, 'https://deepl.com/favicon.ico'),
  ('writing-linguee', 'Linguee', 'AI-powered dictionary and translation tool with context examples for better writing in foreign languages.', 'https://linguee.com', 'writing-editing', 'Free', ARRAY['translation-assistance', 'context-examples', 'multilingual-support'], false, false, 'https://linguee.com/favicon.ico'),
  ('writing-reverso-context', 'Reverso Context', 'AI translation and writing tool that provides real-world context examples for better language use.', 'https://context.reverso.net', 'writing-editing', 'Freemium', ARRAY['contextual-translation', 'language-learning', 'writing-assistance'], false, false, 'https://context.reverso.net/favicon.ico'),
  ('writing-wordreference', 'WordReference', 'AI-enhanced dictionary and translation platform for accurate multilingual writing and editing.', 'https://wordreference.com', 'writing-editing', 'Free', ARRAY['multilingual-dictionary', 'translation-accuracy', 'language-reference'], false, false, 'https://wordreference.com/favicon.ico'),
  ('writing-smartcat', 'SmartCAT', 'AI-powered translation and localization platform for collaborative multilingual content creation.', 'https://smartcat.ai', 'writing-editing', 'Freemium', ARRAY['localization', 'collaborative-translation', 'multilingual-content'], false, false, 'https://smartcat.ai/favicon.ico'),
  
  -- Email & Communication Writing AI
  ('writing-flowrite', 'Flowrite', 'AI email and message writing assistant that transforms instructions into professional communication.', 'https://flowrite.com', 'writing-editing', 'Freemium', ARRAY['email-writing', 'professional-communication', 'message-assistance'], false, false, 'https://flowrite.com/favicon.ico'),
  ('writing-ellie', 'Ellie', 'AI email assistant that learns your writing style to reply to emails in your voice.', 'https://ellieai.com', 'writing-editing', 'Freemium', ARRAY['email-assistance', 'writing-style-learning', 'personalized-replies'], false, false, 'https://ellieai.com/favicon.ico'),
  ('writing-smartwriter', 'SmartWriter', 'AI tool for creating personalized cold emails and LinkedIn messages at scale.', 'https://smartwriter.ai', 'writing-editing', 'Paid', ARRAY['cold-email-writing', 'personalization', 'outreach-automation'], false, false, 'https://smartwriter.ai/favicon.ico'),
  ('writing-lavender', 'Lavender', 'AI email coaching platform that helps improve email writing for better response rates.', 'https://lavender.ai', 'writing-editing', 'Freemium', ARRAY['email-coaching', 'response-optimization', 'communication-improvement'], false, false, 'https://lavender.ai/favicon.ico'),
  ('writing-crystal', 'Crystal', 'AI personality analysis tool that helps adapt writing style for better communication with different people.', 'https://crystalknows.com', 'writing-editing', 'Freemium', ARRAY['personality-analysis', 'communication-adaptation', 'writing-personalization'], false, false, 'https://crystalknows.com/favicon.ico'),
  
  -- Content Planning & Strategy AI
  ('writing-buzzsumo', 'BuzzSumo', 'AI content research and planning tool that identifies trending topics and influential content.', 'https://buzzsumo.com', 'writing-editing', 'Paid', ARRAY['content-research', 'trend-analysis', 'influencer-identification'], false, false, 'https://buzzsumo.com/favicon.ico'),
  ('writing-answerthepublic', 'AnswerThePublic', 'AI tool that discovers what questions people ask about topics to inform content creation.', 'https://answerthepublic.com', 'writing-editing', 'Freemium', ARRAY['question-research', 'content-ideas', 'topic-discovery'], false, false, 'https://answerthepublic.com/favicon.ico'),
  ('writing-semrush-writing', 'SEMrush Writing Assistant', 'AI writing tool that optimizes content for SEO while maintaining readability and engagement.', 'https://semrush.com/writing-assistant', 'writing-editing', 'Paid', ARRAY['seo-optimization', 'content-analysis', 'readability-improvement'], false, false, 'https://semrush.com/favicon.ico'),
  ('writing-marketmuse', 'MarketMuse', 'AI content planning and optimization platform for comprehensive content strategy.', 'https://marketmuse.com', 'writing-editing', 'Paid', ARRAY['content-strategy', 'topic-modeling', 'competitive-analysis'], false, false, 'https://marketmuse.com/favicon.ico'),
  ('writing-surfer-seo', 'Surfer SEO', 'AI content editor that provides real-time optimization suggestions for better search rankings.', 'https://surferseo.com', 'writing-editing', 'Paid', ARRAY['real-time-optimization', 'seo-analysis', 'content-scoring'], false, false, 'https://surferseo.com/favicon.ico'),
  
  -- Editing & Proofreading AI
  ('writing-languagetool', 'LanguageTool', 'AI grammar and style checker that works in 20+ languages for comprehensive editing.', 'https://languagetool.org', 'writing-editing', 'Freemium', ARRAY['multilingual-editing', 'grammar-checking', 'style-improvement'], false, false, 'https://languagetool.org/favicon.ico'),
  ('writing-readable', 'Readable', 'AI readability analyzer that helps improve text clarity and comprehension for target audiences.', 'https://readable.com', 'writing-editing', 'Paid', ARRAY['readability-analysis', 'clarity-improvement', 'audience-optimization'], false, false, 'https://readable.com/favicon.ico'),
  ('writing-editminion', 'EditMinion', 'AI editing assistant that identifies common writing errors and suggests improvements for fiction and non-fiction.', 'https://editminion.com', 'writing-editing', 'Free', ARRAY['error-detection', 'writing-improvement', 'fiction-editing'], false, false, 'https://editminion.com/favicon.ico'),
  ('writing-autocrit', 'AutoCrit', 'AI editing tool specialized for fiction writers with genre-specific analysis and improvement suggestions.', 'https://autocrit.com', 'writing-editing', 'Paid', ARRAY['fiction-editing', 'genre-analysis', 'manuscript-improvement'], false, false, 'https://autocrit.com/favicon.ico'),
  ('writing-paperrater', 'PaperRater', 'AI writing analysis tool that checks grammar, detects plagiarism, and suggests writing improvements.', 'https://paperrater.com', 'writing-editing', 'Freemium', ARRAY['writing-analysis', 'plagiarism-detection', 'improvement-suggestions'], false, false, 'https://paperrater.com/favicon.ico'),
  
  -- Voice & Dictation AI
  ('writing-otter-ai', 'Otter.ai', 'AI transcription service that converts speech to text for meetings, interviews, and voice writing.', 'https://otter.ai', 'writing-editing', 'Freemium', ARRAY['speech-to-text', 'transcription', 'voice-writing'], false, false, 'https://otter.ai/favicon.ico'),
  ('writing-rev-ai', 'Rev AI', 'AI speech-to-text API and transcription service for converting audio content into written text.', 'https://rev.ai', 'writing-editing', 'Paid', ARRAY['speech-recognition', 'audio-transcription', 'api-integration'], false, false, 'https://rev.ai/favicon.ico'),
  ('writing-dragon-speech', 'Dragon Speech Recognition', 'AI-powered speech recognition software for hands-free writing and document creation.', 'https://nuance.com/dragon', 'writing-editing', 'Paid', ARRAY['speech-recognition', 'hands-free-writing', 'document-creation'], false, false, 'https://nuance.com/favicon.ico'),
  ('writing-speechnotes', 'Speechnotes', 'AI voice typing tool that converts speech to text in real-time for efficient writing.', 'https://speechnotes.co', 'writing-editing', 'Free', ARRAY['voice-typing', 'real-time-transcription', 'efficient-writing'], false, false, 'https://speechnotes.co/favicon.ico'),
  ('writing-sonix', 'Sonix', 'AI transcription platform that automatically transcribes audio and video files into searchable text.', 'https://sonix.ai', 'writing-editing', 'Paid', ARRAY['audio-transcription', 'video-transcription', 'searchable-text'], false, false, 'https://sonix.ai/favicon.ico'),
  
  -- Collaboration & Workflow AI
  ('writing-coda-ai', 'Coda AI', 'AI-powered document platform that combines writing, data, and automation in collaborative workspaces.', 'https://coda.io', 'writing-editing', 'Freemium', ARRAY['collaborative-writing', 'document-automation', 'data-integration'], false, false, 'https://coda.io/favicon.ico'),
  ('writing-airtable-ai', 'Airtable AI', 'AI-enhanced database platform for organizing writing projects, content calendars, and editorial workflows.', 'https://airtable.com', 'writing-editing', 'Freemium', ARRAY['content-organization', 'editorial-workflow', 'project-management'], false, false, 'https://airtable.com/favicon.ico'),
  ('writing-monday-writing', 'Monday.com Writing', 'AI work management platform with writing project templates and collaborative editing features.', 'https://monday.com', 'writing-editing', 'Paid', ARRAY['work-management', 'project-collaboration', 'editorial-planning'], false, false, 'https://monday.com/favicon.ico'),
  ('writing-clickup-docs', 'ClickUp Docs', 'AI-powered document creation and collaboration platform integrated with project management.', 'https://clickup.com', 'writing-editing', 'Freemium', ARRAY['document-collaboration', 'project-integration', 'team-writing'], false, false, 'https://clickup.com/favicon.ico'),
  ('writing-craft-docs', 'Craft Docs', 'AI-enhanced note-taking and writing app with advanced linking and organization features.', 'https://craftdocs.com', 'writing-editing', 'Freemium', ARRAY['note-taking', 'document-linking', 'writing-organization'], false, false, 'https://craftdocs.com/favicon.ico'),
  
  -- Publishing & Distribution AI
  ('writing-medium-ai', 'Medium AI Assistant', 'AI writing suggestions and optimization tools built into Medium''s publishing platform.', 'https://medium.com', 'writing-editing', 'Freemium', ARRAY['publishing-platform', 'writing-optimization', 'content-distribution'], false, false, 'https://medium.com/favicon.ico'),
  ('writing-substack-ai', 'Substack AI', 'AI-powered newsletter platform with writing assistance and audience engagement tools.', 'https://substack.com', 'writing-editing', 'Freemium', ARRAY['newsletter-platform', 'audience-engagement', 'content-monetization'], false, false, 'https://substack.com/favicon.ico'),
  ('writing-ghost-ai', 'Ghost AI', 'AI-enhanced publishing platform for professional writers and content creators.', 'https://ghost.org', 'writing-editing', 'Paid', ARRAY['professional-publishing', 'content-management', 'writer-tools'], false, false, 'https://ghost.org/favicon.ico'),
  ('writing-hashnode-ai', 'Hashnode AI', 'AI writing assistant for technical blogging and developer content creation.', 'https://hashnode.com', 'writing-editing', 'Free', ARRAY['technical-blogging', 'developer-content', 'community-publishing'], false, false, 'https://hashnode.com/favicon.ico'),  ('writing-beehiiv', 'Beehiiv', 'AI-powered newsletter platform with advanced writing tools and audience analytics.', 'https://beehiiv.com', 'writing-editing', 'Freemium', ARRAY['newsletter-creation', 'audience-analytics', 'monetization-tools'], false, false, 'https://beehiiv.com/favicon.ico'),
  ('writing-rytr', 'Rytr', 'AI writing assistant ideal for short-form writing tasks like social media posts, product descriptions, and email drafts. Provides over 40 pre-designed templates and built-in plagiarism checker. Plans start at $9/month.', 'https://rytr.me', 'writing-editing', 'Freemium', ARRAY['short-form-writing', 'social-media-posts', 'product-descriptions', 'email-drafts', 'templates'], false, true, 'https://rytr.me/favicon.ico'),
  ('writing-sudowrite', 'Sudowrite', 'AI writing tool specifically designed for fiction writers. Helps overcome writer''s block, generates new ideas, and crafts vivid narratives. Not for business writing or technical content. Plans start at $19/month.', 'https://sudowrite.com', 'writing-editing', 'Paid', ARRAY['fiction-writing', 'creative-writing', 'narrative-crafting', 'writers-block', 'story-ideas'], false, true, 'https://sudowrite.com/favicon.ico'),
  ('writing-grammarly', 'Grammarly', 'AI-powered tool for grammar, spelling, and tone adjustments with integrations across various platforms. Assists with content generation and drafting emails and documents with real-time suggestions.', 'https://grammarly.com', 'writing-editing', 'Freemium', ARRAY['grammar-checking', 'spelling-correction', 'tone-adjustment', 'content-generation', 'platform-integration'], true, true, 'https://grammarly.com/favicon.ico'),
  ('writing-wordtune', 'Wordtune', 'AI tool focused on rephrasing sentences to improve clarity, tone, and style. Offers options to switch between formal and casual tones with contextual suggestions and advanced proofreading. Free version available, premium plans start at $13.99/month.', 'https://wordtune.com', 'writing-editing', 'Freemium', ARRAY['sentence-rephrasing', 'clarity-improvement', 'tone-switching', 'contextual-suggestions', 'advanced-proofreading'], false, true, 'https://wordtune.com/favicon.ico'),
  ('writing-repoprompt', 'Repoprompt', 'MacOS software for writing assistants to generate and optimize content across various formats with intelligent prompting capabilities.', 'https://repoprompt.com', 'writing-editing', 'Paid', ARRAY['macos-software', 'content-generation', 'content-optimization', 'intelligent-prompting', 'various-formats'], false, false, 'https://repoprompt.com/favicon.ico'),
  ('writing-cotypist', 'Cotypist', 'AI writing tool that suggests words and sentences to improve writing speed and efficiency with predictive text capabilities.', 'https://cotypist.com', 'writing-editing', 'Freemium', ARRAY['word-suggestions', 'sentence-suggestions', 'writing-speed', 'predictive-text', 'efficiency-improvement'], false, false, 'https://cotypist.com/favicon.ico'),
  ('writing-talktext', 'TalkText', 'AI tool designed to refine speech-to-text input and restyle written content for better clarity and presentation.', 'https://talktext.ai', 'writing-editing', 'Freemium', ARRAY['speech-to-text', 'content-refinement', 'text-restyling', 'clarity-improvement', 'presentation-enhancement'], false, false, 'https://talktext.ai/favicon.ico'),
  ('writing-pismo', 'Pismo', 'Cross-platform AI writing assistance software for Windows and Mac with comprehensive writing support and optimization features.', 'https://pismo.ai', 'writing-editing', 'Paid', ARRAY['cross-platform', 'windows-mac', 'writing-assistance', 'comprehensive-support', 'writing-optimization'], false, false, 'https://pismo.ai/favicon.ico')
ON CONFLICT (id, category_id) DO NOTHING;

-- Update the tool count for the category
UPDATE categories 
SET tool_count = (
  SELECT COUNT(*) 
  FROM tools 
  WHERE category_id = 'writing-editing'
) 
WHERE id = 'writing-editing';
