-- Education & Translation AI Tools (100 tools)
-- This script adds 100 AI-powered tools for education and translation
-- Covers language learning, educational platforms, tutoring, translation services, and academic tools
-- Uses ON CONFLICT (id, category_id) DO NOTHING to avoid duplicates within the same category

INSERT INTO tools (
  id, name, description, url, category_id, 
  pricing, tags, featured, trending, logo_url
) VALUES   -- Language Learning Platforms
  ('edu-duolingo', 'Duolingo', 'AI-powered language learning platform with personalized lessons, adaptive difficulty, and gamified learning experience for 40+ languages.', 'https://duolingo.com', 'education-translation', 'Freemium', ARRAY['language-learning', 'gamification', 'adaptive-learning'], false, false, 'https://duolingo.com/favicon.ico'),
  ('edu-babbel', 'Babbel', 'AI-enhanced language learning with conversation practice, pronunciation feedback, and real-world conversation skills for 14 languages.', 'https://babbel.com', 'education-translation', 'Paid', ARRAY['language-learning', 'conversation-practice', 'pronunciation'], false, true, 'https://babbel.com/favicon.ico'),
  ('edu-rosetta-stone', 'Rosetta Stone', 'AI-powered immersive language learning with speech recognition, pronunciation coaching, and natural language acquisition methods.', 'https://rosettastone.com', 'education-translation', 'Paid', ARRAY['immersive-learning', 'speech-recognition', 'pronunciation'], false, false, 'https://rosettastone.com/favicon.ico'),
  ('edu-busuu', 'Busuu', 'AI language learning app with personalized study plans, conversation practice with native speakers, and official certificates.', 'https://busuu.com', 'education-translation', 'Freemium', ARRAY['language-learning', 'native-speakers', 'certificates'], false, false, 'https://busuu.com/favicon.ico'),
  ('edu-mondly', 'Mondly', 'AI-powered language learning with VR/AR experiences, conversation chatbot, and speech recognition for 40+ languages.', 'https://mondly.com', 'education-translation', 'Freemium', ARRAY['vr-learning', 'chatbot', 'speech-recognition'], false, false, 'https://mondly.com/favicon.ico'),
  ('edu-memrise', 'Memrise', 'AI-enhanced language learning with spaced repetition, real-world videos, and adaptive memory techniques.', 'https://memrise.com', 'education-translation', 'Freemium', ARRAY['spaced-repetition', 'memory-techniques', 'video-learning'], false, false, 'https://memrise.com/favicon.ico'),
  ('edu-lingoda', 'Lingoda', 'AI-supported online language school with live classes, personalized curriculum, and certified teachers.', 'https://lingoda.com', 'education-translation', 'Paid', ARRAY['live-classes', 'certified-teachers', 'curriculum'], false, false, 'https://lingoda.com/favicon.ico'),
  ('edu-preply', 'Preply', 'AI-powered tutor matching platform with personalized language lessons and progress tracking.', 'https://preply.com', 'education-translation', 'Paid', ARRAY['tutor-matching', 'personalized-lessons', 'progress-tracking'], false, false, 'https://preply.com/favicon.ico'),
    -- Translation Services
  ('edu-google-translate', 'Google Translate', 'AI-powered translation service with real-time conversation translation, camera translation, and support for 130+ languages.', 'https://translate.google.com', 'education-translation', 'Free', ARRAY['real-time-translation', 'camera-translation', '130-languages'], false, false, 'https://translate.google.com/favicon.ico'),
  ('edu-deepl', 'DeepL Translator', 'AI translation service with superior accuracy for European languages, context understanding, and professional translation quality.', 'https://deepl.com', 'education-translation', 'Freemium', ARRAY['high-accuracy', 'european-languages', 'context-understanding'], false, false, 'https://deepl.com/favicon.ico'),
  ('edu-microsoft-translator', 'Microsoft Translator', 'AI translation platform with conversation mode, offline translation, and multi-device synchronization capabilities.', 'https://translator.microsoft.com', 'education-translation', 'Free', ARRAY['conversation-mode', 'offline-translation', 'multi-device'], false, false, 'https://translator.microsoft.com/favicon.ico'),
  ('edu-papago', 'Papago', 'AI translation app specialized in Asian languages with image translation, voice translation, and conversation features.', 'https://papago.naver.com', 'education-translation', 'Free', ARRAY['asian-languages', 'image-translation', 'voice-translation'], false, false, 'https://papago.naver.com/favicon.ico'),
  ('edu-reverso', 'Reverso', 'AI-powered translation and language learning with context examples, conjugation, and pronunciation assistance.', 'https://reverso.net', 'education-translation', 'Freemium', ARRAY['context-examples', 'conjugation', 'pronunciation'], false, false, 'https://reverso.net/favicon.ico'),
  ('edu-linguee', 'Linguee', 'AI-powered dictionary and translation search engine with millions of bilingual example sentences from real-world sources.', 'https://linguee.com', 'education-translation', 'Free', ARRAY['dictionary', 'bilingual-examples', 'real-world-sources'], false, false, 'https://linguee.com/favicon.ico'),
  ('edu-babylon', 'Babylon Translator', 'AI translation software with instant translation, voice recognition, and comprehensive dictionaries for multiple languages.', 'https://babylon-software.com', 'education-translation', 'Paid', ARRAY['instant-translation', 'voice-recognition', 'dictionaries'], false, false, 'https://babylon-software.com/favicon.ico'),
  ('edu-yandex-translate', 'Yandex Translate', 'AI translation service with support for 100+ languages, image translation, and offline capabilities.', 'https://translate.yandex.com', 'education-translation', 'Free', ARRAY['100-languages', 'image-translation', 'offline-capable'], false, false, 'https://translate.yandex.com/favicon.ico'),
    -- Educational Platforms
  ('edu-khan-academy', 'Khan Academy', 'AI-enhanced educational platform with personalized learning paths, mastery-based progression, and intelligent tutoring for all subjects.', 'https://khanacademy.org', 'education-translation', 'Free', ARRAY['personalized-learning', 'mastery-based', 'intelligent-tutoring'], false, false, 'https://khanacademy.org/favicon.ico'),
  ('edu-coursera', 'Coursera', 'AI-powered online learning platform with personalized course recommendations, adaptive learning paths, and university partnerships.', 'https://coursera.org', 'education-translation', 'Freemium', ARRAY['university-courses', 'adaptive-learning', 'certificates'], false, false, 'https://coursera.org/favicon.ico'),
  ('edu-udemy', 'Udemy', 'AI-enhanced online learning marketplace with personalized recommendations, skill assessments, and practical courses.', 'https://udemy.com', 'education-translation', 'Freemium', ARRAY['practical-courses', 'skill-assessments', 'marketplace'], false, false, 'https://udemy.com/favicon.ico'),
  ('edu-edx', 'edX', 'AI-powered online learning platform with university-level courses, verified certificates, and personalized learning experiences.', 'https://edx.org', 'education-translation', 'Freemium', ARRAY['university-level', 'verified-certificates', 'personalized'], false, false, 'https://edx.org/favicon.ico'),
  ('edu-brilliant', 'Brilliant', 'AI-powered interactive learning platform for math, science, and computer science with adaptive problem-solving and visual learning.', 'https://brilliant.org', 'education-translation', 'Freemium', ARRAY['interactive-learning', 'adaptive-problem-solving', 'visual-learning'], false, false, 'https://brilliant.org/favicon.ico'),
  ('edu-skillshare', 'Skillshare', 'AI-enhanced creative learning platform with personalized project recommendations and skill-building courses.', 'https://skillshare.com', 'education-translation', 'Paid', ARRAY['creative-learning', 'project-based', 'skill-building'], false, false, 'https://skillshare.com/favicon.ico'),
  ('edu-linkedin-learning', 'LinkedIn Learning', 'AI-powered professional development platform with personalized course recommendations and skill assessments.', 'https://linkedin.com/learning', 'education-translation', 'Paid', ARRAY['professional-development', 'skill-assessments', 'career-focused'], false, false, 'https://linkedin.com/favicon.ico'),
  ('edu-pluralsight', 'Pluralsight', 'AI-driven technology learning platform with skill assessments, adaptive learning paths, and hands-on labs.', 'https://pluralsight.com', 'education-translation', 'Paid', ARRAY['technology-learning', 'hands-on-labs', 'skill-paths'], false, false, 'https://pluralsight.com/favicon.ico'),
    -- AI Tutoring & Homework Help
  ('edu-socratic', 'Socratic by Google', 'AI-powered homework helper that uses image recognition and natural language processing to explain concepts across subjects.', 'https://socratic.org', 'education-translation', 'Free', ARRAY['homework-help', 'image-recognition', 'concept-explanation'], false, false, 'https://socratic.org/favicon.ico'),
  ('edu-photomath', 'PhotoMath', 'AI-powered math problem solver that solves equations by taking photos, with step-by-step explanations and learning assistance.', 'https://photomath.com', 'education-translation', 'Freemium', ARRAY['math-solver', 'photo-recognition', 'step-by-step'], false, false, 'https://photomath.com/favicon.ico'),
  ('edu-wolfram-alpha', 'Wolfram Alpha', 'AI computational knowledge engine that answers factual queries and solves complex mathematical problems with detailed solutions.', 'https://wolframalpha.com', 'education-translation', 'Freemium', ARRAY['computational-engine', 'factual-queries', 'detailed-solutions'], false, false, 'https://wolframalpha.com/favicon.ico'),
  ('edu-chegg-study', 'Chegg Study', 'AI-powered study platform with step-by-step textbook solutions, expert Q&A, and personalized study plans.', 'https://chegg.com', 'education-translation', 'Paid', ARRAY['textbook-solutions', 'expert-qa', 'study-plans'], false, false, 'https://chegg.com/favicon.ico'),
  ('edu-brainly', 'Brainly', 'AI-enhanced peer-to-peer learning platform where students help each other with homework and study questions.', 'https://brainly.com', 'education-translation', 'Freemium', ARRAY['peer-learning', 'homework-help', 'study-questions'], false, false, 'https://brainly.com/favicon.ico'),
  ('edu-quizlet', 'Quizlet', 'AI-powered study tool with flashcards, practice tests, and personalized learning modes for effective memorization.', 'https://quizlet.com', 'education-translation', 'Freemium', ARRAY['flashcards', 'practice-tests', 'memorization'], false, true, 'https://quizlet.com/favicon.ico'),
  ('edu-anki', 'Anki', 'AI-enhanced spaced repetition flashcard system with customizable decks and intelligent scheduling algorithms.', 'https://ankiweb.net', 'education-translation', 'Free', ARRAY['spaced-repetition', 'flashcards', 'scheduling-algorithms'], false, false, 'https://ankiweb.net/favicon.ico'),
  ('edu-study-buddy-ai', 'StudyBuddy AI', 'AI study companion that creates personalized study schedules, quizzes, and provides learning analytics.', 'https://studybuddyai.com', 'education-translation', 'Freemium', ARRAY['study-companion', 'personalized-schedules', 'learning-analytics'], false, false, 'https://studybuddyai.com/favicon.ico'),
  
  -- Writing & Research Tools
  ('edu-grammarly', 'Grammarly', 'AI-powered writing assistant that improves grammar, clarity, tone, and style across all digital communication platforms.', 'https://grammarly.com', 'education-translation', 'Freemium', ARRAY['writing-assistant', 'grammar-checker', 'tone-analysis'], true, true, 'https://grammarly.com/favicon.ico'),
  ('edu-turnitin', 'Turnitin', 'AI-powered plagiarism detection and feedback platform for academic integrity and writing improvement.', 'https://turnitin.com', 'education-translation', 'Paid', ARRAY['plagiarism-detection', 'academic-integrity', 'feedback'], false, false, 'https://turnitin.com/favicon.ico'),
  ('edu-hemingway-editor', 'Hemingway Editor', 'AI writing tool that analyzes text readability, suggests improvements, and highlights complex sentences for clearer writing.', 'https://hemingwayapp.com', 'education-translation', 'Freemium', ARRAY['readability-analysis', 'writing-improvement', 'clear-writing'], false, false, 'https://hemingwayapp.com/favicon.ico'),
  ('edu-mendeley', 'Mendeley', 'AI-powered reference manager and academic social network with automatic citation generation and research collaboration.', 'https://mendeley.com', 'education-translation', 'Freemium', ARRAY['reference-manager', 'citation-generation', 'research-collaboration'], false, false, 'https://mendeley.com/favicon.ico'),
  ('edu-zotero', 'Zotero', 'AI-enhanced research tool that automatically captures citation information and organizes research materials.', 'https://zotero.org', 'education-translation', 'Free', ARRAY['citation-capture', 'research-organization', 'bibliography'], false, false, 'https://zotero.org/favicon.ico'),
  ('edu-notion-ai', 'Notion AI', 'AI-powered workspace for students with intelligent note-taking, project planning, and collaborative study features.', 'https://notion.so', 'education-translation', 'Freemium', ARRAY['note-taking', 'project-planning', 'collaborative-study'], false, true, 'https://notion.so/favicon.ico'),
  ('edu-obsidian', 'Obsidian', 'AI-enhanced knowledge management tool with linked thinking, graph visualization, and smart note connections.', 'https://obsidian.md', 'education-translation', 'Freemium', ARRAY['knowledge-management', 'linked-thinking', 'graph-visualization'], false, false, 'https://obsidian.md/favicon.ico'),
  ('edu-roam-research', 'Roam Research', 'AI-powered note-taking tool for networked thought with bidirectional linking and knowledge graph visualization.', 'https://roamresearch.com', 'education-translation', 'Paid', ARRAY['networked-thought', 'bidirectional-linking', 'knowledge-graph'], false, false, 'https://roamresearch.com/favicon.ico'),
    -- Coding & Programming Education
  ('edu-codecademy', 'Codecademy', 'AI-powered interactive coding platform with personalized learning paths, hands-on projects, and skill assessments.', 'https://codecademy.com', 'education-translation', 'Freemium', ARRAY['interactive-coding', 'hands-on-projects', 'skill-assessments'], false, false, 'https://codecademy.com/favicon.ico'),
  ('edu-freecodecamp', 'freeCodeCamp', 'AI-enhanced coding bootcamp with free curriculum, hands-on projects, and certification programs.', 'https://freecodecamp.org', 'education-translation', 'Free', ARRAY['coding-bootcamp', 'certification-programs', 'hands-on-projects'], false, false, 'https://freecodecamp.org/favicon.ico'),
  ('edu-replit', 'Replit', 'AI-powered online coding environment with collaborative features, instant deployment, and educational tools.', 'https://replit.com', 'education-translation', 'Freemium', ARRAY['online-coding', 'collaborative-features', 'instant-deployment'], false, false, 'https://replit.com/favicon.ico'),
  ('edu-github-copilot', 'GitHub Copilot', 'AI-powered code completion tool that suggests entire functions and helps with programming tasks across languages.', 'https://github.com/features/copilot', 'education-translation', 'Paid', ARRAY['code-completion', 'programming-assistance', 'multiple-languages'], false, false, 'https://github.com/favicon.ico'),
  ('edu-leetcode', 'LeetCode', 'AI-enhanced coding interview platform with algorithmic problems, personalized study plans, and progress tracking.', 'https://leetcode.com', 'education-translation', 'Freemium', ARRAY['coding-interviews', 'algorithmic-problems', 'progress-tracking'], false, false, 'https://leetcode.com/favicon.ico'),
  ('edu-hackerrank', 'HackerRank', 'AI-powered coding challenge platform with skill assessments, interview preparation, and certification programs.', 'https://hackerrank.com', 'education-translation', 'Freemium', ARRAY['coding-challenges', 'interview-prep', 'certifications'], false, false, 'https://hackerrank.com/favicon.ico'),
  ('edu-codewars', 'Codewars', 'AI-enhanced coding practice platform with kata challenges, community solutions, and skill progression tracking.', 'https://codewars.com', 'education-translation', 'Free', ARRAY['coding-practice', 'kata-challenges', 'skill-progression'], false, false, 'https://codewars.com/favicon.ico'),
  ('edu-exercism', 'Exercism', 'AI-powered coding practice platform with mentor feedback, language tracks, and personalized learning paths.', 'https://exercism.org', 'education-translation', 'Free', ARRAY['mentor-feedback', 'language-tracks', 'personalized-paths'], false, false, 'https://exercism.org/favicon.ico'),
  
  -- Science & Math Education
  ('edu-wolfram-mathematica', 'Wolfram Mathematica', 'AI-powered computational platform for advanced mathematics, science, and engineering with symbolic computation.', 'https://wolfram.com/mathematica', 'education-translation', 'Paid', ARRAY['computational-platform', 'symbolic-computation', 'advanced-math'], false, false, 'https://wolfram.com/favicon.ico'),
  ('edu-desmos', 'Desmos', 'AI-enhanced graphing calculator and math visualization tool with interactive activities and classroom features.', 'https://desmos.com', 'education-translation', 'Free', ARRAY['graphing-calculator', 'math-visualization', 'interactive-activities'], false, true, 'https://desmos.com/favicon.ico'),
  ('edu-geogebra', 'GeoGebra', 'AI-powered dynamic mathematics software for geometry, algebra, and calculus with interactive visualizations.', 'https://geogebra.org', 'education-translation', 'Free', ARRAY['dynamic-mathematics', 'interactive-visualizations', 'geometry-algebra'], false, false, 'https://geogebra.org/favicon.ico'),
  ('edu-labxchange', 'LabXchange', 'AI-enhanced virtual science laboratory with simulations, experiments, and personalized learning paths.', 'https://labxchange.org', 'education-translation', 'Free', ARRAY['virtual-laboratory', 'science-simulations', 'personalized-paths'], false, false, 'https://labxchange.org/favicon.ico'),
  ('edu-phet', 'PhET Simulations', 'AI-powered interactive science and math simulations from University of Colorado Boulder.', 'https://phet.colorado.edu', 'education-translation', 'Free', ARRAY['interactive-simulations', 'science-math', 'university-developed'], false, false, 'https://phet.colorado.edu/favicon.ico'),
  ('edu-molecular-workbench', 'Molecular Workbench', 'AI-enhanced molecular dynamics simulations for chemistry and physics education.', 'https://mw.concord.org', 'education-translation', 'Free', ARRAY['molecular-dynamics', 'chemistry-physics', 'educational-simulations'], false, false, 'https://mw.concord.org/favicon.ico'),
  ('edu-chemsketch', 'ChemSketch', 'AI-powered chemical drawing and molecular modeling software for chemistry education and research.', 'https://acdlabs.com/resources/free-chemistry-software-apps/chemsketch', 'education-translation', 'Free', ARRAY['chemical-drawing', 'molecular-modeling', 'chemistry-education'], false, false, 'https://acdlabs.com/favicon.ico'),
  ('edu-stellarium', 'Stellarium', 'AI-enhanced planetarium software with realistic sky visualization and astronomical education features.', 'https://stellarium.org', 'education-translation', 'Free', ARRAY['planetarium-software', 'sky-visualization', 'astronomy-education'], false, false, 'https://stellarium.org/favicon.ico'),
  
  -- Language Exchange & Practice
  ('edu-hellotalk', 'HelloTalk', 'AI-powered language exchange app connecting learners with native speakers for conversation practice and cultural exchange.', 'https://hellotalk.com', 'education-translation', 'Freemium', ARRAY['language-exchange', 'native-speakers', 'cultural-exchange'], false, true, 'https://hellotalk.com/favicon.ico'),
  ('edu-tandem', 'Tandem', 'AI-enhanced language exchange platform with video calls, tutoring, and personalized matching for language practice.', 'https://tandem.net', 'education-translation', 'Freemium', ARRAY['language-exchange', 'video-calls', 'personalized-matching'], false, false, 'https://tandem.net/favicon.ico'),
  ('edu-speaky', 'Speaky', 'AI-powered language exchange community with text, voice, and video chat for practicing foreign languages.', 'https://speaky.com', 'education-translation', 'Free', ARRAY['language-community', 'voice-video-chat', 'foreign-languages'], false, false, 'https://speaky.com/favicon.ico'),
  ('edu-italki', 'italki', 'AI-enhanced online language learning platform with professional teachers and community tutors for personalized lessons.', 'https://italki.com', 'education-translation', 'Paid', ARRAY['professional-teachers', 'community-tutors', 'personalized-lessons'], false, true, 'https://italki.com/favicon.ico'),
  ('edu-cambly', 'Cambly', 'AI-powered English conversation practice with native speakers, instant access, and flexible scheduling.', 'https://cambly.com', 'education-translation', 'Paid', ARRAY['english-conversation', 'native-speakers', 'flexible-scheduling'], false, false, 'https://cambly.com/favicon.ico'),
  ('edu-verbling', 'Verbling', 'AI-enhanced language learning platform with live video lessons, qualified teachers, and progress tracking.', 'https://verbling.com', 'education-translation', 'Paid', ARRAY['live-video-lessons', 'qualified-teachers', 'progress-tracking'], false, false, 'https://verbling.com/favicon.ico'),
  ('edu-lingokids', 'Lingokids', 'AI-powered English learning app for children with games, songs, and interactive activities.', 'https://lingokids.com', 'education-translation', 'Freemium', ARRAY['children-learning', 'english-games', 'interactive-activities'], false, false, 'https://lingokids.com/favicon.ico'),
  ('edu-busuu-live', 'Busuu Live', 'AI-enhanced group conversation classes with native speakers and personalized feedback.', 'https://busuu.com/live', 'education-translation', 'Paid', ARRAY['group-conversations', 'native-speakers', 'personalized-feedback'], false, false, 'https://busuu.com/favicon.ico'),
  
  -- Professional Development & Certification
  ('edu-google-cloud-training', 'Google Cloud Training', 'AI-powered cloud computing education with hands-on labs, certification paths, and skill badges.', 'https://cloud.google.com/training', 'education-translation', 'Freemium', ARRAY['cloud-computing', 'hands-on-labs', 'certification-paths'], false, false, 'https://cloud.google.com/favicon.ico'),
  ('edu-aws-training', 'AWS Training', 'AI-enhanced cloud training platform with certification preparation, hands-on experience, and skill validation.', 'https://aws.amazon.com/training', 'education-translation', 'Freemium', ARRAY['aws-training', 'certification-prep', 'skill-validation'], false, false, 'https://aws.amazon.com/favicon.ico'),
  ('edu-microsoft-learn', 'Microsoft Learn', 'AI-powered learning platform for Microsoft technologies with interactive modules and certification paths.', 'https://learn.microsoft.com', 'education-translation', 'Free', ARRAY['microsoft-technologies', 'interactive-modules', 'certification-paths'], false, false, 'https://learn.microsoft.com/favicon.ico'),
  ('edu-salesforce-trailhead', 'Salesforce Trailhead', 'AI-enhanced learning platform for Salesforce skills with hands-on challenges and certification preparation.', 'https://trailhead.salesforce.com', 'education-translation', 'Free', ARRAY['salesforce-skills', 'hands-on-challenges', 'certification-prep'], false, false, 'https://trailhead.salesforce.com/favicon.ico'),
  ('edu-ibm-skillsbuild', 'IBM SkillsBuild', 'AI-powered education platform for technology and professional skills with personalized learning paths.', 'https://skillsbuild.org', 'education-translation', 'Free', ARRAY['technology-skills', 'professional-skills', 'personalized-paths'], false, false, 'https://skillsbuild.org/favicon.ico'),
  ('edu-oracle-university', 'Oracle University', 'AI-enhanced training platform for Oracle technologies with certification programs and hands-on labs.', 'https://education.oracle.com', 'education-translation', 'Paid', ARRAY['oracle-technologies', 'certification-programs', 'hands-on-labs'], false, false, 'https://education.oracle.com/favicon.ico'),
  ('edu-cisco-netacad', 'Cisco Networking Academy', 'AI-powered networking education with simulation tools, certification preparation, and career guidance.', 'https://netacad.com', 'education-translation', 'Free', ARRAY['networking-education', 'simulation-tools', 'career-guidance'], false, false, 'https://netacad.com/favicon.ico'),
  ('edu-comptia-certmaster', 'CompTIA CertMaster', 'AI-enhanced IT certification training with adaptive learning, practice exams, and performance analytics.', 'https://comptia.org/training/certmaster', 'education-translation', 'Paid', ARRAY['it-certification', 'adaptive-learning', 'performance-analytics'], false, false, 'https://comptia.org/favicon.ico'),
  
  -- Creative & Design Education
  ('edu-adobe-education', 'Adobe Education Exchange', 'AI-powered creative education platform with tutorials, projects, and professional development for educators.', 'https://edex.adobe.com', 'education-translation', 'Free', ARRAY['creative-education', 'professional-development', 'educator-resources'], false, false, 'https://edex.adobe.com/favicon.ico'),
  ('edu-skillshare-design', 'Skillshare Design', 'AI-enhanced creative learning platform with design courses, project-based learning, and community feedback.', 'https://skillshare.com/design', 'education-translation', 'Paid', ARRAY['design-courses', 'project-based', 'community-feedback'], false, false, 'https://skillshare.com/favicon.ico'),
  ('edu-domestika', 'Domestika', 'AI-powered creative education platform with courses in design, photography, and digital arts.', 'https://domestika.org', 'education-translation', 'Paid', ARRAY['creative-courses', 'design-photography', 'digital-arts'], false, false, 'https://domestika.org/favicon.ico'),
  ('edu-masterclass', 'MasterClass', 'AI-enhanced premium education platform with celebrity instructors and high-production courses.', 'https://masterclass.com', 'education-translation', 'Paid', ARRAY['celebrity-instructors', 'premium-education', 'high-production'], false, true, 'https://masterclass.com/favicon.ico'),
  ('edu-creative-live', 'CreativeLive', 'AI-powered creative education with live and recorded classes in photography, design, and business.', 'https://creativelive.com', 'education-translation', 'Freemium', ARRAY['creative-education', 'live-classes', 'photography-design'], false, false, 'https://creativelive.com/favicon.ico'),
  ('edu-udemy-design', 'Udemy Design & Arts', 'AI-enhanced design education marketplace with practical courses and hands-on projects.', 'https://udemy.com/courses/design', 'education-translation', 'Freemium', ARRAY['design-education', 'practical-courses', 'hands-on-projects'], false, false, 'https://udemy.com/favicon.ico'),
  ('edu-lynda', 'LinkedIn Learning (Lynda)', 'AI-powered professional development platform with design, technology, and business courses.', 'https://linkedin.com/learning', 'education-translation', 'Paid', ARRAY['professional-development', 'design-technology', 'business-courses'], false, false, 'https://linkedin.com/favicon.ico'),
  ('edu-pluralsight-design', 'Pluralsight Design', 'AI-enhanced design and creative technology learning with skill assessments and learning paths.', 'https://pluralsight.com/browse/creative-professional', 'education-translation', 'Paid', ARRAY['design-technology', 'skill-assessments', 'creative-professional'], false, false, 'https://pluralsight.com/favicon.ico'),
  
  -- Specialized Learning Tools
  ('edu-anki-medical', 'AnkiMed', 'AI-powered spaced repetition system specifically designed for medical education with pre-made decks.', 'https://ankiweb.net', 'education-translation', 'Free', ARRAY['medical-education', 'spaced-repetition', 'pre-made-decks'], false, false, 'https://ankiweb.net/favicon.ico'),
  ('edu-osmosis', 'Osmosis', 'AI-enhanced medical education platform with video content, practice questions, and personalized study plans.', 'https://osmosis.org', 'education-translation', 'Freemium', ARRAY['medical-education', 'video-content', 'personalized-study'], false, false, 'https://osmosis.org/favicon.ico'),
  ('edu-lecturio', 'Lecturio', 'AI-powered medical education with video lectures, practice questions, and adaptive learning for medical students.', 'https://lecturio.com', 'education-translation', 'Paid', ARRAY['medical-lectures', 'practice-questions', 'adaptive-learning'], false, false, 'https://lecturio.com/favicon.ico'),
  ('edu-amboss', 'AMBOSS', 'AI-enhanced medical knowledge platform with clinical decision support, study tools, and question banks.', 'https://amboss.com', 'education-translation', 'Paid', ARRAY['medical-knowledge', 'clinical-decision', 'question-banks'], false, false, 'https://amboss.com/favicon.ico'),
  ('edu-uworld', 'UWorld', 'AI-powered medical education with high-yield question banks, detailed explanations, and performance analytics.', 'https://uworld.com', 'education-translation', 'Paid', ARRAY['question-banks', 'detailed-explanations', 'performance-analytics'], false, false, 'https://uworld.com/favicon.ico'),
  ('edu-kaplan-medical', 'Kaplan Medical', 'AI-enhanced medical exam preparation with adaptive learning, live lectures, and diagnostic assessments.', 'https://kaplanmedical.com', 'education-translation', 'Paid', ARRAY['exam-preparation', 'adaptive-learning', 'diagnostic-assessments'], false, false, 'https://kaplanmedical.com/favicon.ico'),
  ('edu-boardvitals', 'BoardVitals', 'AI-powered medical board exam preparation with question banks, performance tracking, and personalized study plans.', 'https://boardvitals.com', 'education-translation', 'Paid', ARRAY['board-exam-prep', 'performance-tracking', 'personalized-plans'], false, false, 'https://boardvitals.com/favicon.ico'),
  ('edu-sketchy-medical', 'Sketchy Medical', 'AI-enhanced visual learning platform for medical education with memorable illustrations and spaced repetition.', 'https://sketchymedical.com', 'education-translation', 'Paid', ARRAY['visual-learning', 'medical-illustrations', 'spaced-repetition'], false, false, 'https://sketchymedical.com/favicon.ico'),
  
  -- Language Assessment & Testing
  ('edu-ielts-online', 'IELTS Online', 'AI-powered IELTS preparation with practice tests, speaking assessment, and personalized feedback.', 'https://ielts.org', 'education-translation', 'Paid', ARRAY['ielts-preparation', 'speaking-assessment', 'personalized-feedback'], false, false, 'https://ielts.org/favicon.ico'),
  ('edu-toefl-practice', 'TOEFL Practice Online', 'AI-enhanced TOEFL preparation with authentic practice tests and automated scoring.', 'https://toeflpractice.ets.org', 'education-translation', 'Paid', ARRAY['toefl-preparation', 'authentic-tests', 'automated-scoring'], false, false, 'https://toeflpractice.ets.org/favicon.ico'),
  ('edu-cambridge-english', 'Cambridge English', 'AI-powered English language assessment and learning with official practice materials.', 'https://cambridgeenglish.org', 'education-translation', 'Freemium', ARRAY['english-assessment', 'official-materials', 'language-learning'], false, false, 'https://cambridgeenglish.org/favicon.ico'),
  ('edu-pearson-pte', 'Pearson PTE', 'AI-enhanced English proficiency test with computer-based assessment and instant results.', 'https://pearsonpte.com', 'education-translation', 'Paid', ARRAY['english-proficiency', 'computer-based', 'instant-results'], false, false, 'https://pearsonpte.com/favicon.ico'),
  ('edu-linguaskill', 'Linguaskill', 'AI-powered English language assessment by Cambridge with adaptive testing and quick results.', 'https://linguaskill.com', 'education-translation', 'Paid', ARRAY['english-assessment', 'adaptive-testing', 'quick-results'], false, false, 'https://linguaskill.com/favicon.ico'),
  ('edu-versant', 'Versant by Pearson', 'AI-enhanced language proficiency testing with automated scoring and detailed analytics.', 'https://versanttest.com', 'education-translation', 'Paid', ARRAY['language-proficiency', 'automated-scoring', 'detailed-analytics'], false, false, 'https://versanttest.com/favicon.ico'),
  ('edu-oxford-placement', 'Oxford Placement Test', 'AI-powered English level assessment with adaptive questioning and detailed reports.', 'https://oxfordenglishtesting.com', 'education-translation', 'Paid', ARRAY['english-assessment', 'adaptive-questioning', 'detailed-reports'], false, false, 'https://oxfordenglishtesting.com/favicon.ico'),
  ('edu-efset', 'EF SET', 'AI-enhanced free English proficiency test with standardized scoring and certification.', 'https://efset.org', 'education-translation', 'Free', ARRAY['english-proficiency', 'standardized-scoring', 'certification'], false, false, 'https://efset.org/favicon.ico'),
  
  -- Accessibility & Special Education
  ('edu-immersive-reader', 'Microsoft Immersive Reader', 'AI-powered reading tool that improves comprehension with text-to-speech, translation, and visual supports.', 'https://education.microsoft.com/immersive-reader', 'education-translation', 'Free', ARRAY['reading-comprehension', 'text-to-speech', 'visual-supports'], false, false, 'https://education.microsoft.com/favicon.ico'),
  ('edu-speechify-education', 'Speechify Education', 'AI-powered text-to-speech platform for students with reading difficulties and learning disabilities.', 'https://speechify.com/education', 'education-translation', 'Freemium', ARRAY['text-to-speech', 'reading-difficulties', 'learning-disabilities'], false, false, 'https://speechify.com/favicon.ico'),
  ('edu-natural-reader', 'NaturalReader', 'AI-enhanced text-to-speech software with multiple voices and reading speeds for accessibility.', 'https://naturalreaders.com', 'education-translation', 'Freemium', ARRAY['text-to-speech', 'multiple-voices', 'accessibility'], false, false, 'https://naturalreaders.com/favicon.ico'),
  ('edu-read-write-gold', 'Read&Write', 'AI-powered literacy support tool with text-to-speech, word prediction, and vocabulary support.', 'https://texthelp.com/read-write', 'education-translation', 'Paid', ARRAY['literacy-support', 'word-prediction', 'vocabulary-support'], false, false, 'https://texthelp.com/favicon.ico'),
  ('edu-voice-dream', 'Voice Dream Reader', 'AI-enhanced text-to-speech app with natural voices and accessibility features for reading support.', 'https://voicedreamreader.com', 'education-translation', 'Paid', ARRAY['text-to-speech', 'natural-voices', 'reading-support'], false, false, 'https://voicedreamreader.com/favicon.ico'),
  ('edu-ginger-software', 'Ginger Software', 'AI-powered writing assistant with grammar checking, translation, and text reader for language learners.', 'https://gingersoftware.com', 'education-translation', 'Freemium', ARRAY['writing-assistant', 'grammar-checking', 'language-learners'], false, false, 'https://gingersoftware.com/favicon.ico'),
  ('edu-claroread', 'ClaroRead', 'AI-enhanced reading and writing support software with text-to-speech, screen reading, and study skills.', 'https://clarosoftware.com/claroread', 'education-translation', 'Paid', ARRAY['reading-writing-support', 'screen-reading', 'study-skills'], false, false, 'https://clarosoftware.com/favicon.ico'),
  ('edu-kurzweil-3000', 'Kurzweil 3000', 'AI-powered comprehensive reading, writing, and learning support software for students with learning differences.', 'https://kurzweiledu.com', 'education-translation', 'Paid', ARRAY['comprehensive-support', 'learning-differences', 'reading-writing'], false, false, 'https://kurzweiledu.com/favicon.ico')
ON CONFLICT (id, category_id) DO NOTHING;

-- Update the tool count for the category
UPDATE categories 
SET tool_count = (
  SELECT COUNT(*) 
  FROM tools 
  WHERE category_id = 'education-translation'
) 
WHERE id = 'education-translation';
