-- Health & Wellness AI Tools (100 tools)
-- This script adds 100 AI-powered tools for health and wellness
-- Focuses exclusively on AI-driven health technologies, medical AI, and intelligent wellness platforms
-- Uses ON CONFLICT (id, category_id) DO NOTHING to avoid duplicates within the same category

INSERT INTO tools (
  id, name, description, url, category_id, 
  pricing, tags, featured, trending, logo_url
) VALUES 
  -- AI Mental Health & Therapy
  ('health-woebot', 'Woebot', 'AI-powered mental health chatbot that provides cognitive behavioral therapy techniques and emotional support using natural language processing.', 'https://woebot.io', 'health-wellness', 'Freemium', ARRAY['ai-therapy', 'mental-health-chatbot', 'cognitive-therapy'], true, true, 'https://woebot.io/favicon.ico'),
  ('health-wysa', 'Wysa', 'AI mental health companion that uses conversational AI to provide emotional support, mood tracking, and therapeutic conversations.', 'https://wysa.io', 'health-wellness', 'Freemium', ARRAY['ai-companion', 'conversational-ai', 'mood-tracking'], true, true, 'https://wysa.io/favicon.ico'),
  ('health-youper', 'Youper', 'AI-powered emotional health assistant with mood tracking, personalized insights, and machine learning-driven mental wellness coaching.', 'https://youper.ai', 'health-wellness', 'Freemium', ARRAY['ai-emotional-health', 'machine-learning', 'wellness-coaching'], false, true, 'https://youper.ai/favicon.ico'),
  ('health-replika-therapy', 'Replika Therapy', 'AI companion specifically designed for mental health support with empathetic conversations and emotional intelligence.', 'https://replika.ai', 'health-wellness', 'Freemium', ARRAY['ai-companion', 'emotional-intelligence', 'mental-health'], false, true, 'https://replika.ai/favicon.ico'),
  ('health-tess-ai', 'Tess AI', 'AI-powered psychological AI assistant providing on-demand mental health support through conversational therapy.', 'https://tessai.com', 'health-wellness', 'Paid', ARRAY['psychological-ai', 'conversational-therapy', 'mental-health'], false, false, 'https://tessai.com/favicon.ico'),
  ('health-ellie-ai', 'Ellie AI', 'AI therapist that uses computer vision and natural language processing to detect depression and provide therapeutic interventions.', 'https://ellieai.com', 'health-wellness', 'Paid', ARRAY['ai-therapist', 'computer-vision', 'depression-detection'], false, false, 'https://ellieai.com/favicon.ico'),
  ('health-x2ai', 'X2AI', 'AI-powered mental health platform that combines chatbots with human therapists for scalable psychological care.', 'https://x2ai.com', 'health-wellness', 'Paid', ARRAY['ai-mental-health', 'chatbot-therapy', 'psychological-care'], false, false, 'https://x2ai.com/favicon.ico'),
  ('health-ginger-ai', 'Ginger AI', 'AI-driven mental health platform with predictive analytics to identify mental health risks and provide interventions.', 'https://ginger.io', 'health-wellness', 'Paid', ARRAY['predictive-analytics', 'mental-health-ai', 'risk-identification'], false, false, 'https://ginger.io/favicon.ico'),
  
  -- AI Medical Diagnosis & Symptom Analysis
  ('health-ada-health', 'Ada Health', 'AI-powered medical assessment app that uses machine learning to analyze symptoms and provide personalized health insights.', 'https://ada.com', 'health-wellness', 'Freemium', ARRAY['ai-diagnosis', 'machine-learning', 'symptom-analysis'], true, true, 'https://ada.com/favicon.ico'),
  ('health-babylon-ai', 'Babylon AI', 'AI healthcare platform with advanced symptom checker, virtual consultations, and AI-driven health monitoring.', 'https://babylonhealth.com', 'health-wellness', 'Freemium', ARRAY['ai-healthcare', 'symptom-checker', 'virtual-ai-doctor'], true, true, 'https://babylon.health/favicon.ico'),
  ('health-buoy-ai', 'Buoy AI', 'AI symptom checker that uses natural language processing to understand symptoms and provide AI-driven care recommendations.', 'https://buoyhealth.com', 'health-wellness', 'Free', ARRAY['ai-symptom-checker', 'nlp', 'care-recommendations'], true, false, 'https://buoyhealth.com/favicon.ico'),
  ('health-mediktor-ai', 'Mediktor AI', 'AI-powered medical assistant with advanced symptom assessment, triage algorithms, and pre-diagnosis capabilities.', 'https://mediktor.com', 'health-wellness', 'Freemium', ARRAY['ai-medical-assistant', 'triage-algorithms', 'pre-diagnosis'], false, false, 'https://mediktor.com/favicon.ico'),
  ('health-infermedica-ai', 'Infermedica AI', 'AI-powered symptom checker and medical interview chatbot with machine learning-driven diagnostic support.', 'https://infermedica.com', 'health-wellness', 'Freemium', ARRAY['ai-symptom-checker', 'medical-chatbot', 'diagnostic-ai'], false, false, 'https://infermedica.com/favicon.ico'),
  ('health-k-health-ai', 'K Health AI', 'AI-powered primary care app with machine learning diagnosis, symptom assessment, and AI-driven health insights.', 'https://khealth.ai', 'health-wellness', 'Freemium', ARRAY['ai-primary-care', 'machine-learning-diagnosis', 'health-ai'], false, true, 'https://khealth.ai/favicon.ico'),
  ('health-symptomate-ai', 'Symptomate AI', 'AI symptom checker with natural language processing and machine learning for accurate health assessments.', 'https://symptomate.com', 'health-wellness', 'Free', ARRAY['ai-symptom-checker', 'nlp', 'health-assessments'], false, false, 'https://symptomate.com/favicon.ico'),
  ('health-your-md-ai', 'Your.MD AI', 'AI health assistant with machine learning algorithms for symptom checking and personalized health guidance.', 'https://your.md', 'health-wellness', 'Free', ARRAY['ai-health-assistant', 'machine-learning', 'health-guidance'], false, false, 'https://your.md/favicon.ico'),
  
  -- AI-Powered Fitness & Nutrition
  ('health-freeletics-ai', 'Freeletics AI', 'AI personal trainer that creates adaptive workout plans using machine learning and exercise science algorithms.', 'https://freeletics.com', 'health-wellness', 'Freemium', ARRAY['ai-personal-trainer', 'adaptive-workouts', 'exercise-algorithms'], false, true, 'https://freeletics.com/favicon.ico'),
  ('health-fitbod-ai', 'Fitbod AI', 'AI-powered workout planner that uses machine learning to create personalized strength training programs.', 'https://fitbod.me', 'health-wellness', 'Freemium', ARRAY['ai-workout-planner', 'machine-learning', 'strength-training'], false, true, 'https://fitbod.me/favicon.ico'),
  ('health-vi-trainer', 'Vi Trainer', 'AI personal trainer with voice coaching, real-time form analysis, and adaptive workout adjustments.', 'https://vitrainer.com', 'health-wellness', 'Paid', ARRAY['ai-voice-trainer', 'form-analysis', 'adaptive-coaching'], false, false, 'https://vitrainer.com/favicon.ico'),
  ('health-noom-ai', 'Noom AI', 'AI-powered weight loss platform with behavioral psychology algorithms, personalized coaching, and predictive analytics.', 'https://noom.com', 'health-wellness', 'Paid', ARRAY['ai-weight-loss', 'behavioral-algorithms', 'predictive-analytics'], true, true, 'https://noom.com/favicon.ico'),
  ('health-myfitnesspal-ai', 'MyFitnessPal AI', 'AI-powered nutrition tracking with computer vision food recognition, macro optimization, and meal recommendations.', 'https://myfitnesspal.com', 'health-wellness', 'Freemium', ARRAY['ai-nutrition', 'computer-vision', 'food-recognition'], true, true, 'https://myfitnesspal.com/favicon.ico'),
  ('health-lose-it-ai', 'Lose It! AI', 'AI-enhanced calorie tracking with image recognition, predictive modeling, and personalized weight loss algorithms.', 'https://loseit.com', 'health-wellness', 'Freemium', ARRAY['ai-calorie-tracking', 'image-recognition', 'weight-loss-ai'], false, false, 'https://loseit.com/favicon.ico'),
  ('health-foodvisor-ai', 'Foodvisor AI', 'AI nutrition coach with computer vision food analysis, calorie estimation, and personalized dietary AI recommendations.', 'https://foodvisor.io', 'health-wellness', 'Freemium', ARRAY['ai-nutrition-coach', 'computer-vision', 'dietary-ai'], false, true, 'https://foodvisor.io/favicon.ico'),
  ('health-yazio-ai', 'YAZIO AI', 'AI-enhanced nutrition app with smart food recognition, macro tracking, and machine learning meal planning.', 'https://yazio.com', 'health-wellness', 'Freemium', ARRAY['ai-nutrition', 'smart-recognition', 'meal-planning-ai'], false, false, 'https://yazio.com/favicon.ico'),
  
  -- AI Sleep & Recovery Analysis
  ('health-sleep-ai', 'Sleep.ai', 'AI-powered sleep optimization platform with machine learning sleep stage analysis and personalized improvement recommendations.', 'https://sleep.ai', 'health-wellness', 'Freemium', ARRAY['ai-sleep-optimization', 'sleep-stage-ai', 'personalized-ai'], false, true, 'https://sleep.ai/favicon.ico'),
  ('health-oura-ai', 'Oura AI', 'AI-powered wearable ring with machine learning algorithms for sleep, recovery, and readiness optimization.', 'https://ouraring.com', 'health-wellness', 'Paid', ARRAY['ai-wearable', 'sleep-ai', 'recovery-optimization'], true, true, 'https://ouraring.com/favicon.ico'),
  ('health-whoop-ai', 'WHOOP AI', 'AI-enhanced fitness wearable with machine learning strain coaching, recovery analysis, and performance optimization.', 'https://whoop.com', 'health-wellness', 'Paid', ARRAY['ai-fitness-wearable', 'strain-coaching-ai', 'performance-ai'], false, true, 'https://whoop.com/favicon.ico'),
  ('health-sleep-cycle-ai', 'Sleep Cycle AI', 'AI sleep tracking with smart alarm algorithms, sleep pattern analysis, and AI-driven sleep improvement suggestions.', 'https://sleepcycle.com', 'health-wellness', 'Freemium', ARRAY['ai-sleep-tracking', 'smart-algorithms', 'sleep-improvement-ai'], false, true, 'https://sleepcycle.com/favicon.ico'),
  ('health-calm-ai', 'Calm AI', 'AI-powered meditation and sleep app with personalized content recommendations and stress reduction algorithms.', 'https://calm.com', 'health-wellness', 'Freemium', ARRAY['ai-meditation', 'personalized-ai', 'stress-reduction-ai'], true, true, 'https://calm.com/favicon.ico'),
  ('health-headspace-ai', 'Headspace AI', 'AI-enhanced mindfulness app with personalized meditation recommendations and mood-based content algorithms.', 'https://headspace.com', 'health-wellness', 'Freemium', ARRAY['ai-mindfulness', 'personalized-meditation', 'mood-algorithms'], true, true, 'https://headspace.com/favicon.ico'),
  ('health-pzizz-ai', 'Pzizz AI', 'AI-powered sleep and focus app with psychoacoustic algorithms and personalized audio generation.', 'https://pzizz.com', 'health-wellness', 'Freemium', ARRAY['ai-sleep-app', 'psychoacoustic-ai', 'audio-generation'], false, false, 'https://pzizz.com/favicon.ico'),
  ('health-sleepio-ai', 'Sleepio AI', 'AI-enhanced digital sleep improvement program with cognitive behavioral therapy algorithms for insomnia.', 'https://sleepio.com', 'health-wellness', 'Paid', ARRAY['ai-sleep-improvement', 'cbt-algorithms', 'insomnia-ai'], false, false, 'https://sleepio.com/favicon.ico'),
  
  -- AI Medical Imaging & Diagnostics
  ('health-skinvision-ai', 'SkinVision AI', 'AI-powered skin cancer detection using computer vision and deep learning to analyze mole photos and assess risk.', 'https://skinvision.com', 'health-wellness', 'Freemium', ARRAY['ai-skin-cancer', 'computer-vision', 'deep-learning'], true, true, 'https://skinvision.com/favicon.ico'),
  ('health-miiskin-ai', 'miiskin AI', 'AI-powered dermatology app with machine learning mole tracking and skin change detection algorithms.', 'https://miiskin.com', 'health-wellness', 'Freemium', ARRAY['ai-dermatology', 'mole-tracking-ai', 'skin-detection'], false, false, 'https://miiskin.com/favicon.ico'),
  ('health-aidoc-ai', 'Aidoc AI', 'AI-powered medical imaging platform that uses deep learning to detect abnormalities in CT scans and X-rays.', 'https://aidoc.com', 'health-wellness', 'Paid', ARRAY['ai-medical-imaging', 'deep-learning', 'abnormality-detection'], false, true, 'https://aidoc.com/favicon.ico'),
  ('health-zebra-medical', 'Zebra Medical AI', 'AI radiology platform with machine learning algorithms for automated medical image analysis and diagnosis.', 'https://zebra-med.com', 'health-wellness', 'Paid', ARRAY['ai-radiology', 'automated-analysis', 'medical-diagnosis-ai'], false, false, 'https://zebra-med.com/favicon.ico'),
  ('health-google-ai-eye', 'Google AI Eye', 'AI-powered diabetic retinopathy screening using deep learning to analyze retinal photographs.', 'https://ai.google/healthcare', 'health-wellness', 'Paid', ARRAY['ai-eye-screening', 'diabetic-retinopathy', 'deep-learning'], false, true, 'https://ai.google/favicon.ico'),
  ('health-caption-health', 'Caption Health AI', 'AI-powered ultrasound guidance system that uses machine learning to improve cardiac imaging accuracy.', 'https://captionhealth.com', 'health-wellness', 'Paid', ARRAY['ai-ultrasound', 'cardiac-imaging', 'machine-learning'], false, false, 'https://captionhealth.com/favicon.ico'),
  ('health-enlitic-ai', 'Enlitic AI', 'AI medical imaging platform with deep learning algorithms for faster and more accurate radiological diagnoses.', 'https://enlitic.com', 'health-wellness', 'Paid', ARRAY['ai-medical-imaging', 'radiological-ai', 'deep-learning'], false, false, 'https://enlitic.com/favicon.ico'),
  ('health-paige-ai', 'Paige AI', 'AI-powered pathology platform using machine learning to analyze tissue samples and detect cancer.', 'https://paige.ai', 'health-wellness', 'Paid', ARRAY['ai-pathology', 'cancer-detection', 'tissue-analysis'], false, false, 'https://paige.ai/favicon.ico'),
  
  -- AI Drug Discovery & Personalized Medicine
  ('health-atomwise-ai', 'Atomwise AI', 'AI-powered drug discovery platform using deep learning to predict molecular behavior and identify potential treatments.', 'https://atomwise.com', 'health-wellness', 'Paid', ARRAY['ai-drug-discovery', 'molecular-ai', 'deep-learning'], false, true, 'https://atomwise.com/favicon.ico'),
  ('health-benevolent-ai', 'BenevolentAI', 'AI drug discovery platform that uses machine learning to identify new therapeutic targets and drug candidates.', 'https://benevolent.ai', 'health-wellness', 'Paid', ARRAY['ai-drug-discovery', 'therapeutic-targets', 'machine-learning'], false, true, 'https://benevolent.ai/favicon.ico'),
  ('health-insilico-medicine', 'Insilico Medicine AI', 'AI-powered drug discovery and aging research platform using deep learning for pharmaceutical development.', 'https://insilico.com', 'health-wellness', 'Paid', ARRAY['ai-pharmaceutical', 'aging-research', 'deep-learning'], false, false, 'https://insilico.com/favicon.ico'),
  ('health-recursion-ai', 'Recursion AI', 'AI-powered drug discovery platform using computer vision and machine learning to analyze cellular biology.', 'https://recursion.com', 'health-wellness', 'Paid', ARRAY['ai-drug-discovery', 'computer-vision', 'cellular-biology'], false, false, 'https://recursion.com/favicon.ico'),
  ('health-tempus-ai', 'Tempus AI', 'AI-powered precision medicine platform that analyzes genomic and clinical data to personalize cancer treatment.', 'https://tempus.com', 'health-wellness', 'Paid', ARRAY['ai-precision-medicine', 'genomic-analysis', 'cancer-treatment'], false, true, 'https://tempus.com/favicon.ico'),
  ('health-flatiron-ai', 'Flatiron Health AI', 'AI-powered oncology platform that uses real-world data and machine learning to improve cancer care.', 'https://flatiron.com', 'health-wellness', 'Paid', ARRAY['ai-oncology', 'real-world-data', 'cancer-care'], false, false, 'https://flatiron.com/favicon.ico'),
  ('health-genomics-ai', 'Genomics AI', 'AI platform for genomic analysis using machine learning to identify genetic variations and disease risks.', 'https://genomicsai.com', 'health-wellness', 'Paid', ARRAY['ai-genomics', 'genetic-analysis', 'disease-risk'], false, false, 'https://genomicsai.com/favicon.ico'),
  ('health-deep-genomics', 'Deep Genomics AI', 'AI-powered platform that uses machine learning to understand how genetic mutations cause disease.', 'https://deepgenomics.com', 'health-wellness', 'Paid', ARRAY['ai-genomics', 'genetic-mutations', 'disease-understanding'], false, false, 'https://deepgenomics.com/favicon.ico'),
  
  -- AI Chronic Disease Management
  ('health-livongo-ai', 'Livongo AI', 'AI-powered diabetes management platform with predictive analytics, personalized insights, and smart device integration.', 'https://livongo.com', 'health-wellness', 'Paid', ARRAY['ai-diabetes', 'predictive-analytics', 'smart-devices'], false, true, 'https://livongo.com/favicon.ico'),
  ('health-onduo-ai', 'Onduo AI', 'AI-enhanced diabetes management with machine learning algorithms for glucose prediction and personalized recommendations.', 'https://onduo.com', 'health-wellness', 'Paid', ARRAY['ai-diabetes-management', 'glucose-prediction', 'personalized-ai'], false, false, 'https://onduo.com/favicon.ico'),
  ('health-bigfoot-ai', 'Bigfoot Biomedical AI', 'AI-powered insulin delivery system with machine learning algorithms for automated diabetes management.', 'https://bigfootbiomedical.com', 'health-wellness', 'Paid', ARRAY['ai-insulin-delivery', 'automated-diabetes', 'machine-learning'], false, false, 'https://bigfootbiomedical.com/favicon.ico'),
  ('health-propeller-ai', 'Propeller Health AI', 'AI-powered respiratory health platform with smart inhalers and predictive analytics for asthma and COPD management.', 'https://propellerhealth.com', 'health-wellness', 'Paid', ARRAY['ai-respiratory', 'smart-inhalers', 'predictive-analytics'], false, false, 'https://propellerhealth.com/favicon.ico'),
  ('health-alivecor-ai', 'AliveCor AI', 'AI-powered ECG technology with machine learning algorithms for heart rhythm analysis and atrial fibrillation detection.', 'https://alivecor.com', 'health-wellness', 'Paid', ARRAY['ai-ecg', 'heart-rhythm-ai', 'afib-detection'], false, true, 'https://alivecor.com/favicon.ico'),
  ('health-cardiologs-ai', 'Cardiologs AI', 'AI-powered ECG analysis platform using deep learning for automated cardiac rhythm interpretation.', 'https://cardiologs.com', 'health-wellness', 'Paid', ARRAY['ai-ecg-analysis', 'cardiac-rhythm', 'deep-learning'], false, false, 'https://cardiologs.com/favicon.ico'),
  ('health-eko-ai', 'Eko AI', 'AI-powered digital stethoscope with machine learning algorithms for heart and lung sound analysis.', 'https://ekohealth.com', 'health-wellness', 'Paid', ARRAY['ai-stethoscope', 'heart-sounds', 'lung-analysis'], false, false, 'https://ekohealth.com/favicon.ico'),
  ('health-veracyte-ai', 'Veracyte AI', 'AI-powered genomic diagnostics platform using machine learning for cancer detection and classification.', 'https://veracyte.com', 'health-wellness', 'Paid', ARRAY['ai-genomic-diagnostics', 'cancer-detection', 'machine-learning'], false, false, 'https://veracyte.com/favicon.ico'),
  
  -- AI Telemedicine & Virtual Care
  ('health-teladoc-ai', 'Teladoc AI', 'AI-enhanced telemedicine platform with symptom assessment algorithms and virtual health assistant capabilities.', 'https://teladoc.com', 'health-wellness', 'Paid', ARRAY['ai-telemedicine', 'symptom-assessment', 'virtual-assistant'], true, true, 'https://teladoc.com/favicon.ico'),
  ('health-amwell-ai', 'Amwell AI', 'AI-powered telehealth platform with machine learning triage and intelligent care routing algorithms.', 'https://amwell.com', 'health-wellness', 'Paid', ARRAY['ai-telehealth', 'ml-triage', 'care-routing'], false, true, 'https://amwell.com/favicon.ico'),
  ('health-98point6-ai', '98point6 AI', 'AI-powered text-based primary care with natural language processing and machine learning diagnosis assistance.', 'https://98point6.com', 'health-wellness', 'Paid', ARRAY['ai-primary-care', 'nlp', 'diagnosis-assistance'], false, false, 'https://98point6.com/favicon.ico'),
  ('health-lark-ai', 'Lark Health AI', 'AI health coach with personalized recommendations, behavioral insights, and chronic disease prevention algorithms.', 'https://lark.com', 'health-wellness', 'Freemium', ARRAY['ai-health-coach', 'behavioral-ai', 'disease-prevention'], false, false, 'https://lark.com/favicon.ico'),
  ('health-babylon-gp-ai', 'Babylon GP at Hand AI', 'AI-powered virtual GP service with machine learning symptom assessment and digital health monitoring.', 'https://gpathsnd.babylonhealth.com', 'health-wellness', 'Paid', ARRAY['ai-virtual-gp', 'symptom-assessment', 'digital-monitoring'], false, false, 'https://babylonhealth.com/favicon.ico'),
  ('health-mdlive-ai', 'MDLive AI', 'AI-enhanced virtual healthcare with intelligent scheduling, symptom pre-assessment, and care recommendation algorithms.', 'https://mdlive.com', 'health-wellness', 'Paid', ARRAY['ai-virtual-healthcare', 'intelligent-scheduling', 'care-recommendations'], false, false, 'https://mdlive.com/favicon.ico'),
  ('health-doctorondemand-ai', 'Doctor on Demand AI', 'AI-powered video healthcare platform with smart triage and personalized care pathway algorithms.', 'https://doctorondemand.com', 'health-wellness', 'Paid', ARRAY['ai-video-healthcare', 'smart-triage', 'care-pathways'], false, false, 'https://doctorondemand.com/favicon.ico'),
  ('health-healthtap-ai', 'HealthTap AI', 'AI-powered virtual care platform with Dr. A.I. symptom checker and machine learning health insights.', 'https://healthtap.com', 'health-wellness', 'Freemium', ARRAY['ai-virtual-care', 'dr-ai', 'health-insights'], false, false, 'https://healthtap.com/favicon.ico'),
  
  -- AI Women's Health
  ('health-flo-ai', 'Flo AI', 'AI-powered menstrual health app with machine learning cycle prediction, fertility insights, and symptom pattern analysis.', 'https://flo.health', 'health-wellness', 'Freemium', ARRAY['ai-menstrual-health', 'cycle-prediction', 'fertility-ai'], true, true, 'https://flo.health/favicon.ico'),
  ('health-clue-ai', 'Clue AI', 'AI-enhanced period tracking with machine learning algorithms for cycle prediction and reproductive health insights.', 'https://helloclue.com', 'health-wellness', 'Freemium', ARRAY['ai-period-tracking', 'cycle-algorithms', 'reproductive-ai'], false, true, 'https://helloclue.com/favicon.ico'),
  ('health-glow-ai', 'Glow AI', 'AI-powered fertility and pregnancy app with predictive ovulation algorithms and conception optimization.', 'https://glowing.com', 'health-wellness', 'Freemium', ARRAY['ai-fertility', 'ovulation-algorithms', 'conception-ai'], false, false, 'https://glowing.com/favicon.ico'),
  ('health-ava-ai', 'Ava AI', 'AI-powered fertility tracking bracelet with machine learning algorithms for accurate ovulation prediction.', 'https://avawomen.com', 'health-wellness', 'Paid', ARRAY['ai-fertility-tracking', 'ovulation-prediction', 'machine-learning'], false, false, 'https://avawomen.com/favicon.ico'),
  ('health-maven-ai', 'Maven AI', 'AI-enhanced women's health platform with personalized care recommendations and virtual health coaching.', 'https://maven.co', 'health-wellness', 'Paid', ARRAY['ai-womens-health', 'personalized-care', 'virtual-coaching'], false, false, 'https://maven.co/favicon.ico'),
  ('health-nurx-ai', 'Nurx AI', 'AI-powered reproductive health platform with smart contraception recommendations and health risk assessment.', 'https://nurx.com', 'health-wellness', 'Paid', ARRAY['ai-reproductive-health', 'contraception-ai', 'risk-assessment'], false, false, 'https://nurx.com/favicon.ico'),
  ('health-mindstrong-ai', 'Mindstrong AI', 'AI-powered digital phenotyping platform that analyzes smartphone interactions to assess mental health.', 'https://mindstrong.com', 'health-wellness', 'Paid', ARRAY['digital-phenotyping', 'smartphone-ai', 'mental-health-ai'], false, false, 'https://mindstrong.com/favicon.ico'),
  ('health-verily-ai', 'Verily AI', 'AI-powered health research platform using machine learning for disease detection and health monitoring.', 'https://verily.com', 'health-wellness', 'Paid', ARRAY['ai-health-research', 'disease-detection', 'health-monitoring'], false, true, 'https://verily.com/favicon.ico'),
  
  -- AI Physical Therapy & Rehabilitation
  ('health-sword-ai', 'SWORD Health AI', 'AI-powered digital physical therapy with computer vision motion tracking and personalized exercise algorithms.', 'https://swordhealth.com', 'health-wellness', 'Paid', ARRAY['ai-physical-therapy', 'computer-vision', 'motion-tracking'], false, true, 'https://swordhealth.com/favicon.ico'),
  ('health-hinge-ai', 'Hinge Health AI', 'AI-enhanced musculoskeletal care platform with sensor-guided movement analysis and personalized therapy algorithms.', 'https://hingehealth.com', 'health-wellness', 'Paid', ARRAY['ai-musculoskeletal', 'sensor-guided', 'therapy-algorithms'], false, true, 'https://hingehealth.com/favicon.ico'),
  ('health-kaia-ai', 'Kaia Health AI', 'AI-powered digital therapeutics with computer vision exercise tracking and personalized pain management algorithms.', 'https://kaiahealth.com', 'health-wellness', 'Freemium', ARRAY['ai-digital-therapeutics', 'exercise-tracking', 'pain-management'], false, false, 'https://kaiahealth.com/favicon.ico'),
  ('health-physera-ai', 'Physera AI', 'AI-enhanced physical therapy app with machine learning exercise adaptation and progress optimization algorithms.', 'https://physera.com', 'health-wellness', 'Paid', ARRAY['ai-physical-therapy', 'exercise-adaptation', 'progress-optimization'], false, false, 'https://physera.com/favicon.ico'),
  ('health-reflexion-ai', 'Reflexion Health AI', 'AI-powered virtual physical therapy with motion capture technology and adaptive exercise algorithms.', 'https://reflexionhealth.com', 'health-wellness', 'Paid', ARRAY['ai-virtual-therapy', 'motion-capture', 'adaptive-exercises'], false, false, 'https://reflexionhealth.com/favicon.ico'),
  ('health-betterpt-ai', 'BetterPT AI', 'AI-enhanced physical therapy matching platform with smart therapist recommendations and outcome prediction.', 'https://betterpt.com', 'health-wellness', 'Paid', ARRAY['ai-therapy-matching', 'smart-recommendations', 'outcome-prediction'], false, false, 'https://betterpt.com/favicon.ico'),
  ('health-mirror-ai', 'Mirror AI', 'AI-powered home fitness mirror with computer vision form correction and personalized workout adaptation.', 'https://mirror.co', 'health-wellness', 'Paid', ARRAY['ai-home-fitness', 'form-correction', 'workout-adaptation'], false, false, 'https://mirror.co/favicon.ico'),
  ('health-tone-ai', 'Tonal AI', 'AI-powered smart home gym with electromagnetic resistance and machine learning strength training optimization.', 'https://tonal.com', 'health-wellness', 'Paid', ARRAY['ai-smart-gym', 'electromagnetic-resistance', 'strength-optimization'], false, false, 'https://tonal.com/favicon.ico'),
  
  -- AI Preventive Care & Health Monitoring
  ('health-apple-ai', 'Apple Health AI', 'AI-enhanced health platform with machine learning health predictions, irregular rhythm notifications, and fall detection.', 'https://apple.com/ios/health', 'health-wellness', 'Free', ARRAY['ai-health-platform', 'health-predictions', 'rhythm-detection'], true, true, 'https://apple.com/favicon.ico'),
  ('health-fitbit-ai', 'Fitbit AI', 'AI-powered fitness tracker with machine learning health insights, stress management, and personalized recommendations.', 'https://fitbit.com', 'health-wellness', 'Freemium', ARRAY['ai-fitness-tracker', 'stress-management', 'personalized-ai'], true, true, 'https://fitbit.com/favicon.ico'),
  ('health-google-fit-ai', 'Google Fit AI', 'AI-powered fitness platform with activity recognition algorithms, goal optimization, and health trend analysis.', 'https://fit.google.com', 'health-wellness', 'Free', ARRAY['ai-fitness-platform', 'activity-recognition', 'trend-analysis'], false, true, 'https://fit.google.com/favicon.ico'),
  ('health-samsung-ai', 'Samsung Health AI', 'AI-enhanced health platform with comprehensive tracking algorithms, wellness insights, and predictive health analytics.', 'https://health.samsung.com', 'health-wellness', 'Free', ARRAY['ai-health-platform', 'wellness-insights', 'predictive-analytics'], false, true, 'https://health.samsung.com/favicon.ico'),
  ('health-garmin-ai', 'Garmin Connect AI', 'AI-powered fitness platform with advanced performance metrics, training insights, and recovery optimization algorithms.', 'https://connect.garmin.com', 'health-wellness', 'Freemium', ARRAY['ai-performance-metrics', 'training-insights', 'recovery-ai'], false, true, 'https://connect.garmin.com/favicon.ico'),
  ('health-strava-ai', 'Strava AI', 'AI-enhanced fitness platform with performance analysis algorithms, training optimization, and social fitness insights.', 'https://strava.com', 'health-wellness', 'Freemium', ARRAY['ai-performance-analysis', 'training-optimization', 'social-fitness'], false, true, 'https://strava.com/favicon.ico'),
  ('health-myzone-ai', 'MYZONE AI', 'AI-powered heart rate monitoring system with effort-based fitness tracking and personalized training algorithms.', 'https://myzone.org', 'health-wellness', 'Paid', ARRAY['ai-heart-rate', 'effort-tracking', 'training-algorithms'], false, false, 'https://myzone.org/favicon.ico'),
  ('health-polar-ai', 'Polar AI', 'AI-enhanced fitness technology with advanced heart rate algorithms, training optimization, and recovery guidance.', 'https://polar.com', 'health-wellness', 'Paid', ARRAY['ai-fitness-tech', 'heart-rate-algorithms', 'recovery-guidance'], false, false, 'https://polar.com/favicon.ico'),
  
  -- AI Health Analytics & Research
  ('health-23andme-ai', '23andMe AI', 'AI-powered genetic testing with machine learning algorithms for health predisposition analysis and trait prediction.', 'https://23andme.com', 'health-wellness', 'Paid', ARRAY['ai-genetic-testing', 'health-predisposition', 'trait-prediction'], false, true, 'https://23andme.com/favicon.ico'),
  ('health-color-ai', 'Color Health AI', 'AI-enhanced genetic testing platform with machine learning risk assessment and personalized health recommendations.', 'https://color.com', 'health-wellness', 'Paid', ARRAY['ai-genetic-testing', 'risk-assessment', 'personalized-health'], false, false, 'https://color.com/favicon.ico'),
  ('health-helix-ai', 'Helix AI', 'AI-powered genomics platform with machine learning DNA analysis and personalized health insights.', 'https://helix.com', 'health-wellness', 'Paid', ARRAY['ai-genomics', 'dna-analysis', 'health-insights'], false, false, 'https://helix.com/favicon.ico'),
  ('health-grail-ai', 'GRAIL AI', 'AI-powered multi-cancer early detection platform using machine learning to analyze circulating tumor DNA.', 'https://grail.com', 'health-wellness', 'Paid', ARRAY['ai-cancer-detection', 'circulating-dna', 'machine-learning'], false, true, 'https://grail.com/favicon.ico'),
  ('health-guardant-ai', 'Guardant Health AI', 'AI-enhanced liquid biopsy platform with machine learning algorithms for cancer detection and monitoring.', 'https://guardanthealth.com', 'health-wellness', 'Paid', ARRAY['ai-liquid-biopsy', 'cancer-monitoring', 'machine-learning'], false, false, 'https://guardanthealth.com/favicon.ico'),
  ('health-foundation-ai', 'Foundation Medicine AI', 'AI-powered genomic profiling platform with machine learning for personalized cancer treatment recommendations.', 'https://foundationmedicine.com', 'health-wellness', 'Paid', ARRAY['ai-genomic-profiling', 'cancer-treatment', 'personalized-medicine'], false, false, 'https://foundationmedicine.com/favicon.ico'),
  ('health-caris-ai', 'Caris Life Sciences AI', 'AI-enhanced molecular profiling platform with machine learning for precision oncology and treatment optimization.', 'https://carislifesciences.com', 'health-wellness', 'Paid', ARRAY['ai-molecular-profiling', 'precision-oncology', 'treatment-optimization'], false, false, 'https://carislifesciences.com/favicon.ico'),
  ('health-illumina-ai', 'Illumina AI', 'AI-powered genomic sequencing platform with machine learning algorithms for genetic variant analysis and interpretation.', 'https://illumina.com', 'health-wellness', 'Paid', ARRAY['ai-genomic-sequencing', 'variant-analysis', 'genetic-interpretation'], false, false, 'https://illumina.com/favicon.ico'),
  
  -- Medical Diagnosis & Symptom Checkers
  ('health-ada-health', 'Ada Health', 'AI-powered health assessment app that analyzes symptoms and provides personalized health insights.', 'https://ada.com', 'health-wellness', 'Freemium', ARRAY['health-assessment', 'symptom-analysis', 'health-insights'], true, true, 'https://ada.com/favicon.ico'),
  ('health-babylon-health', 'Babylon Health', 'AI-enhanced healthcare platform with symptom checker, virtual consultations, and health monitoring.', 'https://babylonhealth.com', 'health-wellness', 'Freemium', ARRAY['symptom-checker', 'virtual-consultations', 'health-monitoring'], true, false, 'https://babylonhealth.com/favicon.ico'),
  ('health-k-health', 'K Health', 'AI-powered primary care app with symptom assessment, AI-driven diagnosis, and physician consultations.', 'https://khealth.ai', 'health-wellness', 'Freemium', ARRAY['primary-care', 'ai-diagnosis', 'physician-consultations'], false, true, 'https://khealth.ai/favicon.ico'),
  ('health-buoy-health', 'Buoy Health', 'AI symptom checker that helps users understand their symptoms and find appropriate care options.', 'https://buoyhealth.com', 'health-wellness', 'Free', ARRAY['symptom-checker', 'care-options', 'health-guidance'], false, false, 'https://buoyhealth.com/favicon.ico'),
  ('health-mediktor', 'Mediktor', 'AI-powered medical assistant with symptom assessment, triage, and pre-diagnosis capabilities.', 'https://mediktor.com', 'health-wellness', 'Freemium', ARRAY['medical-assistant', 'symptom-assessment', 'pre-diagnosis'], false, false, 'https://mediktor.com/favicon.ico'),
  ('health-symptomate', 'Symptomate', 'AI symptom checker and health assistant with medical questionnaires and care recommendations.', 'https://symptomate.com', 'health-wellness', 'Free', ARRAY['symptom-checker', 'medical-questionnaires', 'care-recommendations'], false, false, 'https://symptomate.com/favicon.ico'),
  ('health-infermedica', 'Infermedica', 'AI-powered symptom checker and triage platform for healthcare providers and patients.', 'https://infermedica.com', 'health-wellness', 'Freemium', ARRAY['symptom-checker', 'triage-platform', 'healthcare-providers'], false, false, 'https://infermedica.com/favicon.ico'),
  ('health-your-md', 'Your.MD', 'AI health assistant with symptom checking, health information, and personalized health insights.', 'https://your.md', 'health-wellness', 'Free', ARRAY['health-assistant', 'symptom-checking', 'health-information'], false, false, 'https://your.md/favicon.ico'),
  
  -- Telemedicine & Virtual Care
  ('health-teladoc', 'Teladoc', 'AI-enhanced telemedicine platform with virtual consultations, health monitoring, and chronic care management.', 'https://teladoc.com', 'health-wellness', 'Paid', ARRAY['telemedicine', 'virtual-consultations', 'chronic-care'], true, true, 'https://teladoc.com/favicon.ico'),
  ('health-amwell', 'Amwell', 'AI-powered telehealth platform connecting patients with healthcare providers for virtual care and consultations.', 'https://amwell.com', 'health-wellness', 'Paid', ARRAY['telehealth', 'virtual-care', 'healthcare-providers'], false, true, 'https://amwell.com/favicon.ico'),
  ('health-mdlive', 'MDLive', 'AI-enhanced virtual healthcare platform with 24/7 access to doctors, therapy, and dermatology services.', 'https://mdlive.com', 'health-wellness', 'Paid', ARRAY['virtual-healthcare', '24-7-access', 'therapy-dermatology'], false, false, 'https://mdlive.com/favicon.ico'),
  ('health-doctor-on-demand', 'Doctor on Demand', 'AI-powered video-first healthcare platform with virtual consultations and prescription services.', 'https://doctorondemand.com', 'health-wellness', 'Paid', ARRAY['video-healthcare', 'virtual-consultations', 'prescription-services'], false, false, 'https://doctorondemand.com/favicon.ico'),
  ('health-plushcare', 'PlushCare', 'AI-enhanced virtual primary care with same-day appointments, prescription delivery, and care coordination.', 'https://plushcare.com', 'health-wellness', 'Paid', ARRAY['virtual-primary-care', 'same-day-appointments', 'prescription-delivery'], false, false, 'https://plushcare.com/favicon.ico'),
  ('health-lemonhealth', 'Lemon Health', 'AI-powered virtual healthcare platform with personalized care plans and health monitoring.', 'https://lemonhealth.com', 'health-wellness', 'Paid', ARRAY['virtual-healthcare', 'personalized-care', 'health-monitoring'], false, false, 'https://lemonhealth.com/favicon.ico'),
  ('health-circle-medical', 'Circle Medical', 'AI-enhanced primary care platform with virtual visits, in-person care, and health tracking.', 'https://circlemedical.com', 'health-wellness', 'Paid', ARRAY['primary-care', 'virtual-visits', 'health-tracking'], false, false, 'https://circlemedical.com/favicon.ico'),
  ('health-98point6', '98point6', 'AI-powered text-based primary care with virtual consultations and personalized health guidance.', 'https://98point6.com', 'health-wellness', 'Paid', ARRAY['text-based-care', 'virtual-consultations', 'health-guidance'], false, false, 'https://98point6.com/favicon.ico'),
  
  -- Women's Health
  ('health-flo', 'Flo', 'AI-powered period and ovulation tracker with fertility insights, symptom logging, and health predictions.', 'https://flo.health', 'health-wellness', 'Freemium', ARRAY['period-tracker', 'fertility-insights', 'health-predictions'], true, true, 'https://flo.health/favicon.ico'),
  ('health-clue', 'Clue', 'AI-enhanced menstrual cycle tracking with data-driven insights, symptom analysis, and reproductive health education.', 'https://helloclue.com', 'health-wellness', 'Freemium', ARRAY['menstrual-tracking', 'data-insights', 'reproductive-health'], false, true, 'https://helloclue.com/favicon.ico'),
  ('health-ovia', 'Ovia', 'AI-powered women's health platform with fertility tracking, pregnancy monitoring, and parenting guidance.', 'https://oviahealth.com', 'health-wellness', 'Free', ARRAY['fertility-tracking', 'pregnancy-monitoring', 'parenting-guidance'], false, false, 'https://oviahealth.com/favicon.ico'),
  ('health-glow', 'Glow', 'AI-enhanced fertility and pregnancy app with cycle tracking, ovulation prediction, and conception planning.', 'https://glowing.com', 'health-wellness', 'Freemium', ARRAY['fertility-app', 'ovulation-prediction', 'conception-planning'], false, false, 'https://glowing.com/favicon.ico'),
  ('health-maven', 'Maven', 'AI-powered women's and family health platform with virtual care, mental health support, and fertility services.', 'https://maven.co', 'health-wellness', 'Paid', ARRAY['womens-health', 'virtual-care', 'fertility-services'], false, false, 'https://maven.co/favicon.ico'),
  ('health-nurx', 'Nurx', 'AI-enhanced reproductive health platform with birth control delivery, STI testing, and telehealth consultations.', 'https://nurx.com', 'health-wellness', 'Paid', ARRAY['reproductive-health', 'birth-control', 'sti-testing'], false, false, 'https://nurx.com/favicon.ico'),
  ('health-planned-parenthood', 'Planned Parenthood Direct', 'AI-powered reproductive health app with birth control consultations and STI treatment.', 'https://plannedparenthood.org', 'health-wellness', 'Paid', ARRAY['reproductive-health', 'birth-control-consultations', 'sti-treatment'], false, false, 'https://plannedparenthood.org/favicon.ico'),
  ('health-kindred-bravely', 'Kindred Bravely', 'AI-enhanced maternity and nursing platform with personalized product recommendations and breastfeeding support.', 'https://kindredbravely.com', 'health-wellness', 'Freemium', ARRAY['maternity-nursing', 'product-recommendations', 'breastfeeding-support'], false, false, 'https://kindredbravely.com/favicon.ico'),
  
  -- Chronic Disease Management
  ('health-glucose-buddy', 'Glucose Buddy', 'AI-powered diabetes management app with blood sugar tracking, medication reminders, and trend analysis.', 'https://glucosebuddy.com', 'health-wellness', 'Freemium', ARRAY['diabetes-management', 'blood-sugar-tracking', 'medication-reminders'], false, false, 'https://glucosebuddy.com/favicon.ico'),
  ('health-one-drop', 'One Drop', 'AI-enhanced diabetes management platform with continuous glucose monitoring, coaching, and personalized insights.', 'https://onedrop.today', 'health-wellness', 'Freemium', ARRAY['diabetes-management', 'glucose-monitoring', 'personalized-coaching'], false, true, 'https://onedrop.today/favicon.ico'),
  ('health-carezone', 'CareZone', 'AI-powered medication management app with pill reminders, pharmacy coordination, and health tracking.', 'https://carezone.com', 'health-wellness', 'Free', ARRAY['medication-management', 'pill-reminders', 'pharmacy-coordination'], false, false, 'https://carezone.com/favicon.ico'),
  ('health-medisafe', 'Medisafe', 'AI-enhanced medication reminder and adherence app with drug interaction alerts and family coordination.', 'https://medisafe.com', 'health-wellness', 'Freemium', ARRAY['medication-reminders', 'drug-interactions', 'family-coordination'], false, false, 'https://medisafe.com/favicon.ico'),
  ('health-mymigraine', 'MyMigraine', 'AI-powered migraine tracking app with trigger identification, pattern analysis, and treatment insights.', 'https://mymigraine.com', 'health-wellness', 'Freemium', ARRAY['migraine-tracking', 'trigger-identification', 'treatment-insights'], false, false, 'https://mymigraine.com/favicon.ico'),
  ('health-arthritis-power', 'ArthritisPower', 'AI-enhanced arthritis management app with symptom tracking, medication monitoring, and research participation.', 'https://arthritispower.org', 'health-wellness', 'Free', ARRAY['arthritis-management', 'symptom-tracking', 'research-participation'], false, false, 'https://arthritispower.org/favicon.ico'),
  ('health-epocrates', 'Epocrates', 'AI-powered medical reference app with drug information, interaction checker, and clinical decision support.', 'https://epocrates.com', 'health-wellness', 'Freemium', ARRAY['medical-reference', 'drug-information', 'clinical-decision'], false, false, 'https://epocrates.com/favicon.ico'),
  ('health-symple', 'Symple Symptom Tracker', 'AI-enhanced chronic illness management with symptom tracking, medication monitoring, and trend analysis.', 'https://sympleapp.com', 'health-wellness', 'Freemium', ARRAY['chronic-illness', 'symptom-tracking', 'trend-analysis'], false, false, 'https://sympleapp.com/favicon.ico'),
  
  -- Heart & Cardiovascular Health
  ('health-cardiio', 'Cardiio', 'AI-powered heart rate monitor that uses smartphone camera to measure pulse and track cardiovascular health.', 'https://cardiio.com', 'health-wellness', 'Freemium', ARRAY['heart-rate-monitor', 'smartphone-camera', 'cardiovascular-health'], false, false, 'https://cardiio.com/favicon.ico'),
  ('health-heart-rate-plus', 'Heart Rate Plus', 'AI-enhanced heart rate monitoring app with trend analysis, health insights, and workout integration.', 'https://heartrateplus.com', 'health-wellness', 'Freemium', ARRAY['heart-rate-monitoring', 'trend-analysis', 'workout-integration'], false, false, 'https://heartrateplus.com/favicon.ico'),
  ('health-kardia', 'KardiaMobile', 'AI-powered personal EKG device with FDA-cleared heart rhythm analysis and atrial fibrillation detection.', 'https://kardia.com', 'health-wellness', 'Paid', ARRAY['personal-ekg', 'heart-rhythm-analysis', 'afib-detection'], false, true, 'https://kardia.com/favicon.ico'),
  ('health-qardio', 'QardioArm', 'AI-enhanced smart blood pressure monitor with trend tracking, medication reminders, and family sharing.', 'https://qardio.com', 'health-wellness', 'Paid', ARRAY['blood-pressure-monitor', 'trend-tracking', 'family-sharing'], false, false, 'https://qardio.com/favicon.ico'),
  ('health-withings-bpm', 'Withings BPM', 'AI-powered blood pressure monitoring with instant results, health trend analysis, and doctor sharing.', 'https://withings.com', 'health-wellness', 'Paid', ARRAY['blood-pressure-monitoring', 'health-trends', 'doctor-sharing'], false, false, 'https://withings.com/favicon.ico'),
  ('health-heart-analyzer', 'Heart Analyzer', 'AI-enhanced heart rate variability analysis with stress assessment and recovery recommendations.', 'https://heartanalyzer.com', 'health-wellness', 'Paid', ARRAY['heart-rate-variability', 'stress-assessment', 'recovery-recommendations'], false, false, 'https://heartanalyzer.com/favicon.ico'),
  ('health-instant-heart-rate', 'Instant Heart Rate', 'AI-powered heart rate measurement using smartphone camera with history tracking and health insights.', 'https://instantheartrate.com', 'health-wellness', 'Freemium', ARRAY['heart-rate-measurement', 'smartphone-camera', 'history-tracking'], false, false, 'https://instantheartrate.com/favicon.ico'),
  ('health-blood-pressure-companion', 'Blood Pressure Companion', 'AI-enhanced blood pressure tracking with medication reminders, trend analysis, and export capabilities.', 'https://bloodpressurecompanion.com', 'health-wellness', 'Paid', ARRAY['blood-pressure-tracking', 'medication-reminders', 'trend-analysis'], false, false, 'https://bloodpressurecompanion.com/favicon.ico'),
  
  -- Skin & Dermatology
  ('health-skinvision', 'SkinVision', 'AI-powered skin cancer detection app that analyzes mole photos and provides risk assessments.', 'https://skinvision.com', 'health-wellness', 'Freemium', ARRAY['skin-cancer-detection', 'mole-analysis', 'risk-assessment'], false, true, 'https://skinvision.com/favicon.ico'),
  ('health-molesafe', 'MoleSafe', 'AI-enhanced skin monitoring app with mole tracking, dermatologist consultations, and skin health education.', 'https://molesafe.com', 'health-wellness', 'Freemium', ARRAY['skin-monitoring', 'mole-tracking', 'dermatologist-consultations'], false, false, 'https://molesafe.com/favicon.ico'),
  ('health-miiskin', 'miiskin', 'AI-powered skin tracking app for monitoring moles, spots, and skin changes with photo comparison.', 'https://miiskin.com', 'health-wellness', 'Freemium', ARRAY['skin-tracking', 'mole-monitoring', 'photo-comparison'], false, false, 'https://miiskin.com/favicon.ico'),
  ('health-first-derm', 'First Derm', 'AI-enhanced dermatology platform with photo-based skin consultations and expert diagnosis.', 'https://firstderm.com', 'health-wellness', 'Paid', ARRAY['dermatology-platform', 'photo-consultations', 'expert-diagnosis'], false, false, 'https://firstderm.com/favicon.ico'),
  ('health-yuka-cosmetics', 'Yuka Cosmetics', 'AI-powered cosmetics analyzer that evaluates skincare products and provides health ratings.', 'https://yuka.io', 'health-wellness', 'Free', ARRAY['cosmetics-analyzer', 'skincare-products', 'health-ratings'], false, false, 'https://yuka.io/favicon.ico'),
  ('health-tinylogger', 'TinyLogger Skin', 'AI-enhanced skin condition tracking with photo journals, symptom logging, and progress monitoring.', 'https://tinylogger.com', 'health-wellness', 'Freemium', ARRAY['skin-condition-tracking', 'photo-journals', 'progress-monitoring'], false, false, 'https://tinylogger.com/favicon.ico'),
  ('health-eczema-tracker', 'Eczema Tracker', 'AI-powered eczema management app with flare tracking, trigger identification, and treatment monitoring.', 'https://eczematracker.com', 'health-wellness', 'Freemium', ARRAY['eczema-management', 'flare-tracking', 'trigger-identification'], false, false, 'https://eczematracker.com/favicon.ico'),
  ('health-psoriasis-advance', 'Psoriasis Advance', 'AI-enhanced psoriasis tracking with severity assessment, treatment monitoring, and lifestyle factors.', 'https://psoriasisadvance.com', 'health-wellness', 'Free', ARRAY['psoriasis-tracking', 'severity-assessment', 'treatment-monitoring'], false, false, 'https://psoriasisadvance.com/favicon.ico'),
  
  -- Eye & Vision Health
  ('health-eyeque', 'EyeQue', 'AI-powered vision testing device that measures refractive errors and tracks vision changes over time.', 'https://eyeque.com', 'health-wellness', 'Paid', ARRAY['vision-testing', 'refractive-errors', 'vision-tracking'], false, false, 'https://eyeque.com/favicon.ico'),
  ('health-eye-care-plus', 'Eye Care Plus', 'AI-enhanced eye health app with vision exercises, blue light tracking, and eye strain prevention.', 'https://eyecareplus.com', 'health-wellness', 'Freemium', ARRAY['eye-health', 'vision-exercises', 'eye-strain-prevention'], false, false, 'https://eyecareplus.com/favicon.ico'),
  ('health-glaucoma-app', 'Glaucoma App', 'AI-powered glaucoma management with pressure tracking, medication reminders, and risk assessment.', 'https://glaucomaapp.com', 'health-wellness', 'Freemium', ARRAY['glaucoma-management', 'pressure-tracking', 'risk-assessment'], false, false, 'https://glaucomaapp.com/favicon.ico'),
  ('health-myeye', 'MyEye', 'AI-enhanced vision care platform with eye exam scheduling, prescription tracking, and vision health tips.', 'https://myeye.com', 'health-wellness', 'Free', ARRAY['vision-care', 'eye-exam-scheduling', 'prescription-tracking'], false, false, 'https://myeye.com/favicon.ico'),
  ('health-warby-parker-app', 'Warby Parker App', 'AI-powered eyewear app with virtual try-on, prescription renewal, and vision health reminders.', 'https://warbyparker.com', 'health-wellness', 'Free', ARRAY['virtual-try-on', 'prescription-renewal', 'vision-health'], false, false, 'https://warbyparker.com/favicon.ico'),
  ('health-vision-therapy', 'Vision Therapy', 'AI-enhanced vision training app with eye exercises, tracking progress, and visual skill development.', 'https://visiontherapy.com', 'health-wellness', 'Paid', ARRAY['vision-training', 'eye-exercises', 'visual-skill-development'], false, false, 'https://visiontherapy.com/favicon.ico'),
  ('health-blue-light-filter', 'Blue Light Filter', 'AI-powered screen time monitoring with blue light analysis and eye protection recommendations.', 'https://bluelightfilter.com', 'health-wellness', 'Freemium', ARRAY['screen-time-monitoring', 'blue-light-analysis', 'eye-protection'], false, false, 'https://bluelightfilter.com/favicon.ico'),
  ('health-dry-eye-guru', 'Dry Eye Guru', 'AI-enhanced dry eye management with symptom tracking, environmental monitoring, and treatment guidance.', 'https://dryeyeguru.com', 'health-wellness', 'Freemium', ARRAY['dry-eye-management', 'symptom-tracking', 'environmental-monitoring'], false, false, 'https://dryeyeguru.com/favicon.ico'),
  
  -- Rehabilitation & Physical Therapy
  ('health-physera', 'Physera', 'AI-powered physical therapy app with exercise programs, progress tracking, and virtual coaching.', 'https://physera.com', 'health-wellness', 'Paid', ARRAY['physical-therapy', 'exercise-programs', 'virtual-coaching'], false, false, 'https://physera.com/favicon.ico'),
  ('health-betterpt', 'BetterPT', 'AI-enhanced physical therapy platform connecting patients with therapists for in-home and virtual care.', 'https://betterpt.com', 'health-wellness', 'Paid', ARRAY['physical-therapy-platform', 'in-home-care', 'virtual-care'], false, false, 'https://betterpt.com/favicon.ico'),
  ('health-reflexion', 'Reflexion Health', 'AI-powered virtual physical therapy with motion tracking, exercise guidance, and progress monitoring.', 'https://reflexionhealth.com', 'health-wellness', 'Paid', ARRAY['virtual-physical-therapy', 'motion-tracking', 'exercise-guidance'], false, false, 'https://reflexionhealth.com/favicon.ico'),
  ('health-sword-health', 'SWORD Health', 'AI-enhanced digital physical therapy with motion sensors, exercise programs, and therapist support.', 'https://swordhealth.com', 'health-wellness', 'Paid', ARRAY['digital-physical-therapy', 'motion-sensors', 'therapist-support'], false, true, 'https://swordhealth.com/favicon.ico'),
  ('health-hinge-health', 'Hinge Health', 'AI-powered musculoskeletal care platform with exercise therapy, education, and sensor-guided movement.', 'https://hingehealth.com', 'health-wellness', 'Paid', ARRAY['musculoskeletal-care', 'exercise-therapy', 'sensor-guided'], false, true, 'https://hingehealth.com/favicon.ico'),
  ('health-kaia-health', 'Kaia Health', 'AI-enhanced digital therapeutics for back pain, COPD, and chronic conditions with personalized programs.', 'https://kaiahealth.com', 'health-wellness', 'Freemium', ARRAY['digital-therapeutics', 'back-pain', 'chronic-conditions'], false, false, 'https://kaiahealth.com/favicon.ico'),
  ('health-recovery-guru', 'Recovery Guru', 'AI-powered injury prevention and rehabilitation app with exercise programs and movement analysis.', 'https://recoveryguru.com', 'health-wellness', 'Freemium', ARRAY['injury-prevention', 'rehabilitation', 'movement-analysis'], false, false, 'https://recoveryguru.com/favicon.ico'),
  ('health-physitrack', 'Physitrack', 'AI-enhanced home exercise prescription platform with video guidance and progress tracking for patients.', 'https://physitrack.com', 'health-wellness', 'Paid', ARRAY['home-exercise', 'video-guidance', 'progress-tracking'], false, false, 'https://physitrack.com/favicon.ico')
ON CONFLICT (id, category_id) DO NOTHING;

-- Update the tool count for the category
UPDATE categories 
SET tool_count = (
  SELECT COUNT(*) 
  FROM tools 
  WHERE category_id = 'health-wellness'
) 
WHERE id = 'health-wellness';
