-- Add 55 additional unique AI writing and editing tools to Writing & Editing category
-- Excluding the tools already provided in the list

INSERT INTO tools (id, name, description, short_description, website_url, logo_url, pricing, rating, category_id, is_featured, created_at, updated_at) VALUES
-- Advanced AI Writing & Editing Tools
(gen_random_uuid(), 'Claude', 'Advanced AI assistant for writing, editing, and research with exceptional reasoning capabilities', 'Advanced AI assistant for writing and editing', 'https://claude.ai', 'https://claude.ai/favicon.ico', 'Freemium', 4.7, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'GPT-4', 'OpenAI''s most advanced language model for creative writing, editing, and content generation', 'OpenAI''s advanced language model for writing', 'https://openai.com/gpt-4', 'https://openai.com/favicon.ico', 'Paid', 4.8, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'Notion AI', 'AI writing assistant integrated into Notion workspace for seamless content creation', 'AI writing assistant within Notion workspace', 'https://notion.so/ai', 'https://notion.so/favicon.ico', 'Freemium', 4.5, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'Perplexity AI', 'AI research and writing assistant that provides cited sources for factual content', 'AI research assistant for factual writing', 'https://perplexity.ai', 'https://perplexity.ai/favicon.ico', 'Freemium', 4.4, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'ChatGPT Plus', 'Enhanced version of ChatGPT with advanced writing and editing capabilities', 'Enhanced ChatGPT for writing and editing', 'https://chat.openai.com', 'https://chat.openai.com/favicon.ico', 'Paid', 4.6, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),

-- Academic & Technical Writing
(gen_random_uuid(), 'Scholarcy', 'AI tool for summarizing research papers and academic content', 'AI research paper summarizer', 'https://scholarcy.com', 'https://scholarcy.com/favicon.ico', 'Freemium', 4.3, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'Elicit', 'AI research assistant for finding and analyzing academic papers', 'AI research assistant for academic writing', 'https://elicit.org', 'https://elicit.org/favicon.ico', 'Freemium', 4.4, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'Writefull', 'AI writing assistant specifically designed for academic and research writing', 'AI assistant for academic writing', 'https://writefull.com', 'https://writefull.com/favicon.ico', 'Freemium', 4.2, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'Researcher', 'AI-powered research and writing platform for academic content', 'AI research and writing platform', 'https://researcher.life', 'https://researcher.life/favicon.ico', 'Paid', 4.1, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'PaperPal', 'AI writing assistant for academic papers and research documents', 'AI assistant for academic papers', 'https://paperpal.com', 'https://paperpal.com/favicon.ico', 'Freemium', 4.0, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),

-- Creative Writing & Storytelling
(gen_random_uuid(), 'Jenni AI', 'AI writing assistant for academic and creative content with research capabilities', 'AI writing assistant with research', 'https://jenni.ai', 'https://jenni.ai/favicon.ico', 'Freemium', 4.3, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'Moonbeam', 'AI writing assistant for long-form content and creative writing', 'AI assistant for long-form content', 'https://moonbeam.ai', 'https://moonbeam.ai/favicon.ico', 'Freemium', 4.2, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'Character.AI', 'AI platform for creative writing with character-based conversations', 'AI platform for character-based writing', 'https://character.ai', 'https://character.ai/favicon.ico', 'Freemium', 4.1, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'Plot Factory', 'AI-powered story planning and creative writing platform', 'AI story planning and writing platform', 'https://plotfactory.com', 'https://plotfactory.com/favicon.ico', 'Freemium', 4.0, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'Squibler', 'AI writing assistant for novels, screenplays, and creative content', 'AI assistant for novels and screenplays', 'https://squibler.io', 'https://squibler.io/favicon.ico', 'Freemium', 3.9, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),

-- Grammar & Style Enhancement
(gen_random_uuid(), 'LanguageTool', 'AI-powered grammar and style checker supporting multiple languages', 'Multilingual AI grammar checker', 'https://languagetool.org', 'https://languagetool.org/favicon.ico', 'Freemium', 4.3, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'WhiteSmoke', 'AI writing assistant with grammar, style, and translation features', 'AI writing assistant with translation', 'https://whitesmoke.com', 'https://whitesmoke.com/favicon.ico', 'Paid', 4.1, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'PaperRater', 'AI writing analysis and proofreading tool for students and professionals', 'AI writing analysis and proofreading', 'https://paperrater.com', 'https://paperrater.com/favicon.ico', 'Freemium', 3.9, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'Slick Write', 'AI-powered writing assistant for grammar, style, and flow improvement', 'AI assistant for grammar and style', 'https://slickwrite.com', 'https://slickwrite.com/favicon.ico', 'Free', 3.8, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'After the Deadline', 'AI proofreading and style checking tool for content creators', 'AI proofreading and style checker', 'https://afterthedeadline.com', 'https://afterthedeadline.com/favicon.ico', 'Free', 3.7, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),

-- Content Optimization & SEO
(gen_random_uuid(), 'MarketMuse', 'AI content strategy and optimization platform for SEO-focused writing', 'AI content strategy for SEO writing', 'https://marketmuse.com', 'https://marketmuse.com/favicon.ico', 'Paid', 4.2, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'Surfer SEO', 'AI content optimization tool for search engine ranking improvement', 'AI content optimization for SEO', 'https://surferseo.com', 'https://surferseo.com/favicon.ico', 'Paid', 4.3, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'ContentKing', 'AI-powered content optimization and SEO writing assistant', 'AI content optimization assistant', 'https://contentkingapp.com', 'https://contentkingapp.com/favicon.ico', 'Paid', 4.0, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'Page Optimizer Pro', 'AI content optimization tool for better search rankings', 'AI tool for content optimization', 'https://pageoptimizer.pro', 'https://pageoptimizer.pro/favicon.ico', 'Paid', 3.9, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'ContentGap', 'AI content analysis and optimization for competitive advantage', 'AI content analysis for optimization', 'https://contentgap.com', 'https://contentgap.com/favicon.ico', 'Paid', 3.8, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),

-- AI Editors & Proofreaders
(gen_random_uuid(), 'Editor.com', 'AI-powered editing and proofreading service for professional content', 'AI editing and proofreading service', 'https://editor.com', 'https://editor.com/favicon.ico', 'Paid', 4.1, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'Reedsy Editor', 'AI-enhanced writing and editing platform for authors and publishers', 'AI writing platform for authors', 'https://reedsy.com/editor', 'https://reedsy.com/favicon.ico', 'Freemium', 4.0, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'EditPad', 'AI text editor with smart writing assistance and collaboration features', 'AI text editor with writing assistance', 'https://editpad.org', 'https://editpad.org/favicon.ico', 'Free', 3.8, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'ProWritingAid Desktop', 'Desktop version of AI writing mentor with advanced editing features', 'Desktop AI writing mentor', 'https://prowritingaid.com/desktop', 'https://prowritingaid.com/favicon.ico', 'Paid', 4.2, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'SmartEdit', 'AI editing software for fiction and non-fiction writers', 'AI editing software for writers', 'https://smartedit.com', 'https://smartedit.com/favicon.ico', 'Paid', 3.9, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),

-- Email & Communication Writing
(gen_random_uuid(), 'Boomerang Respondable', 'AI email writing assistant for better response rates', 'AI email writing for better responses', 'https://boomerangapp.com/respondable', 'https://boomerangapp.com/favicon.ico', 'Freemium', 4.0, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'Crystal', 'AI personality insights for personalized communication writing', 'AI for personalized communication', 'https://crystalknows.com', 'https://crystalknows.com/favicon.ico', 'Freemium', 3.9, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'EmailTree', 'AI email composer and management tool for businesses', 'AI email composer for businesses', 'https://emailtree.ai', 'https://emailtree.ai/favicon.ico', 'Paid', 3.8, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'Mixmax', 'AI email enhancement and writing assistance platform', 'AI email enhancement platform', 'https://mixmax.com', 'https://mixmax.com/favicon.ico', 'Freemium', 4.1, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'Seventh Sense', 'AI email optimization for timing and content effectiveness', 'AI email optimization tool', 'https://seventhsense.ai', 'https://seventhsense.ai/favicon.ico', 'Paid', 3.7, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),

-- Specialized Writing Tools
(gen_random_uuid(), 'Accessible Writer', 'AI writing assistant focused on accessibility and inclusive content', 'AI assistant for accessible writing', 'https://accessiblewriter.com', 'https://accessiblewriter.com/favicon.ico', 'Freemium', 4.0, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'Textio', 'AI writing platform for inclusive and effective job postings and communications', 'AI platform for inclusive writing', 'https://textio.com', 'https://textio.com/favicon.ico', 'Paid', 4.1, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'Verb', 'AI writing assistant for technical documentation and user guides', 'AI assistant for technical documentation', 'https://verb.ai', 'https://verb.ai/favicon.ico', 'Paid', 3.9, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'Scapple', 'AI-enhanced mind mapping tool for writing and content planning', 'AI mind mapping for writing planning', 'https://literatureandlatte.com/scapple', 'https://literatureandlatte.com/favicon.ico', 'Paid', 3.8, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'Ulysses', 'AI-powered writing app for authors and content creators', 'AI writing app for authors', 'https://ulysses.app', 'https://ulysses.app/favicon.ico', 'Paid', 4.2, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),

-- Translation & Multilingual Writing
(gen_random_uuid(), 'DeepL Write', 'AI writing assistant with translation and multilingual support', 'AI writing with translation support', 'https://deepl.com/write', 'https://deepl.com/favicon.ico', 'Freemium', 4.4, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'Reverso', 'AI translation and writing assistance for multilingual content', 'AI translation and writing assistance', 'https://reverso.net', 'https://reverso.net/favicon.ico', 'Freemium', 4.0, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'Lingoda', 'AI language learning with writing practice and correction', 'AI language learning with writing', 'https://lingoda.com', 'https://lingoda.com/favicon.ico', 'Paid', 3.9, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'Phrase', 'AI translation management for content localization and writing', 'AI translation management platform', 'https://phrase.com', 'https://phrase.com/favicon.ico', 'Paid', 3.8, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'Smartling', 'AI translation and content management for global writing projects', 'AI translation for global content', 'https://smartling.com', 'https://smartling.com/favicon.ico', 'Paid', 3.7, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),

-- Productivity & Workflow
(gen_random_uuid(), 'Scrivener', 'AI-enhanced writing software for long-form content and research', 'AI writing software for long-form content', 'https://literatureandlatte.com/scrivener', 'https://literatureandlatte.com/favicon.ico', 'Paid', 4.3, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'Obsidian', 'AI-powered knowledge management and writing platform', 'AI knowledge management for writing', 'https://obsidian.md', 'https://obsidian.md/favicon.ico', 'Freemium', 4.2, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'RemNote', 'AI note-taking and writing platform with spaced repetition', 'AI note-taking and writing platform', 'https://remnote.com', 'https://remnote.com/favicon.ico', 'Freemium', 4.0, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'Roam Research', 'AI knowledge graph for connected writing and research', 'AI knowledge graph for writing', 'https://roamresearch.com', 'https://roamresearch.com/favicon.ico', 'Paid', 3.9, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'Logseq', 'AI-powered local-first writing and knowledge management tool', 'AI writing and knowledge management', 'https://logseq.com', 'https://logseq.com/favicon.ico', 'Free', 3.8, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),

-- Voice-to-Text & Dictation
(gen_random_uuid(), 'Otter.ai', 'AI transcription and note-taking for voice-to-text writing', 'AI transcription for voice writing', 'https://otter.ai', 'https://otter.ai/favicon.ico', 'Freemium', 4.3, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'Dragon NaturallySpeaking', 'AI speech recognition software for dictation and writing', 'AI speech recognition for writing', 'https://nuance.com/dragon', 'https://nuance.com/favicon.ico', 'Paid', 4.1, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'Speeko', 'AI speech coach and transcription for presentation writing', 'AI speech coach for presentation writing', 'https://speeko.co', 'https://speeko.co/favicon.ico', 'Freemium', 3.9, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'Trint', 'AI transcription platform for converting audio to written content', 'AI transcription for audio content', 'https://trint.com', 'https://trint.com/favicon.ico', 'Paid', 4.0, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW()),
(gen_random_uuid(), 'Rev', 'AI transcription and captioning service for content creation', 'AI transcription and captioning service', 'https://rev.com', 'https://rev.com/favicon.ico', 'Paid', 3.8, (SELECT id FROM categories WHERE slug = 'writing-editing'), false, NOW(), NOW())

ON CONFLICT (id) DO NOTHING;
