-- Legal & Finance AI Tools (101 tools)
-- This script adds 101 AI-powered tools for legal and financial services
-- Covers legal research, document automation, financial analysis, compliance, and fintech solutions
-- Uses ON CONFLICT (id, category_id) DO NOTHING to avoid duplicates within the same category

INSERT INTO tools (
  id, name, description, url, category_id, 
  pricing, tags, featured, trending, logo_url
) VALUES 
  -- Legal AI Platforms & Research
  ('legal-westlaw-edge', 'Westlaw Edge', 'AI-powered legal research platform with natural language processing, case analysis, and predictive analytics for legal professionals.', 'https://legal.thomsonreuters.com/westlaw', 'legal-finance', 'Paid', ARRAY['legal-research', 'case-analysis', 'predictive-analytics'], false, true, 'https://legal.thomsonreuters.com/favicon.ico'),
  ('legal-lexis-plus', 'Lexis+', 'AI-enhanced legal research tool with intelligent search, case summaries, and legal analytics for comprehensive legal research.', 'https://lexis.com', 'legal-finance', 'Paid', ARRAY['legal-research', 'intelligent-search', 'legal-analytics'], false, true, 'https://lexis.com/favicon.ico'),
  ('legal-case-text', 'CaseText', 'AI-powered legal research platform with CARA AI technology for brief analysis and legal document review.', 'https://casetext.com', 'legal-finance', 'Paid', ARRAY['legal-research', 'brief-analysis', 'document-review'], false, true, 'https://casetext.com/favicon.ico'),
  ('legal-ross-intelligence', 'ROSS Intelligence', 'AI legal researcher that provides natural language legal research and case law analysis using machine learning.', 'https://rossintelligence.com', 'legal-finance', 'Paid', ARRAY['ai-legal-researcher', 'natural-language', 'case-law-analysis'], false, false, 'https://rossintelligence.com/favicon.ico'),
  ('legal-lex-machina', 'Lex Machina', 'AI-powered legal analytics platform that provides litigation insights, judge analytics, and case outcome predictions.', 'https://lexmachina.com', 'legal-finance', 'Paid', ARRAY['legal-analytics', 'litigation-insights', 'outcome-predictions'], false, false, 'https://lexmachina.com/favicon.ico'),
  ('legal-ravel-law', 'Ravel Law', 'AI-enhanced legal research with data visualization, case analytics, and judicial insights for strategic legal decisions.', 'https://ravellaw.com', 'legal-finance', 'Paid', ARRAY['legal-research', 'data-visualization', 'judicial-insights'], false, false, 'https://ravellaw.com/favicon.ico'),
  ('legal-fastcase', 'Fastcase', 'AI-powered legal research platform with predictive search, case analysis, and legal AI tools for attorneys.', 'https://fastcase.com', 'legal-finance', 'Paid', ARRAY['legal-research', 'predictive-search', 'case-analysis'], false, false, 'https://fastcase.com/favicon.ico'),
  ('legal-justia', 'Justia AI', 'AI-enhanced legal research platform with free case law search, legal analytics, and document automation tools.', 'https://justia.com', 'legal-finance', 'Freemium', ARRAY['legal-research', 'case-law-search', 'document-automation'], false, false, 'https://justia.com/favicon.ico'),
  
  -- Contract Analysis & Review
  ('legal-kira-systems', 'Kira Systems', 'AI-powered contract analysis platform that extracts and analyzes provisions from legal documents with machine learning.', 'https://kirasystems.com', 'legal-finance', 'Paid', ARRAY['contract-analysis', 'document-extraction', 'machine-learning'], false, true, 'https://kirasystems.com/favicon.ico'),
  ('legal-ebrevia', 'Ebrevia', 'AI contract analytics platform that reviews and extracts key terms from legal documents for due diligence and compliance.', 'https://ebrevia.com', 'legal-finance', 'Paid', ARRAY['contract-analytics', 'due-diligence', 'compliance'], false, false, 'https://ebrevia.com/favicon.ico'),
  ('legal-luminance', 'Luminance', 'AI-powered legal technology platform for contract review, due diligence, and regulatory compliance using machine learning.', 'https://luminance.com', 'legal-finance', 'Paid', ARRAY['contract-review', 'due-diligence', 'regulatory-compliance'], false, true, 'https://luminance.com/favicon.ico'),
  ('legal-lawgeex', 'LawGeex', 'AI contract review platform that automatically reviews and approves contracts using artificial intelligence and legal expertise.', 'https://lawgeex.com', 'legal-finance', 'Paid', ARRAY['contract-review', 'automatic-approval', 'legal-ai'], false, false, 'https://lawgeex.com/favicon.ico'),
  ('legal-seal-software', 'Seal Software', 'AI-powered contract analytics platform that discovers, extracts, and analyzes contract data for enterprise legal teams.', 'https://seal-software.com', 'legal-finance', 'Paid', ARRAY['contract-analytics', 'data-extraction', 'enterprise-legal'], false, false, 'https://seal-software.com/favicon.ico'),
  ('legal-contract-ai', 'Contract AI', 'AI-driven contract analysis tool that identifies risks, extracts key terms, and provides contract intelligence insights.', 'https://contractai.com', 'legal-finance', 'Paid', ARRAY['contract-analysis', 'risk-identification', 'contract-intelligence'], false, false, 'https://contractai.com/favicon.ico'),
  ('legal-beagle', 'Beagle', 'AI contract analysis platform that reviews legal documents, identifies risks, and extracts important clauses automatically.', 'https://beagle.ai', 'legal-finance', 'Paid', ARRAY['contract-analysis', 'risk-identification', 'clause-extraction'], false, false, 'https://beagle.ai/favicon.ico'),
  ('legal-icertis', 'Icertis Contract Intelligence', 'AI-powered contract lifecycle management platform with intelligent contract analytics and risk assessment.', 'https://icertis.com', 'legal-finance', 'Paid', ARRAY['contract-lifecycle', 'contract-analytics', 'risk-assessment'], false, false, 'https://icertis.com/favicon.ico'),
  
  -- Document Automation & Generation
  ('legal-hotdocs', 'HotDocs', 'AI-enhanced document automation platform that generates legal documents using templates and intelligent questionnaires.', 'https://hotdocs.com', 'legal-finance', 'Paid', ARRAY['document-automation', 'legal-documents', 'intelligent-questionnaires'], false, false, 'https://hotdocs.com/favicon.ico'),
  ('legal-contract-express', 'Contract Express', 'AI-powered document automation software for creating complex legal documents with intelligent template systems.', 'https://contractexpress.com', 'legal-finance', 'Paid', ARRAY['document-automation', 'template-systems', 'complex-documents'], false, false, 'https://contractexpress.com/favicon.ico'),
  ('legal-documate', 'Documate', 'AI document automation platform that transforms static legal forms into intelligent, interactive experiences.', 'https://documate.org', 'legal-finance', 'Paid', ARRAY['document-automation', 'interactive-forms', 'legal-forms'], false, false, 'https://documate.org/favicon.ico'),
  ('legal-clause-match', 'ClauseMatch', 'AI-powered regulatory compliance platform with intelligent document automation and policy management.', 'https://clausematch.com', 'legal-finance', 'Paid', ARRAY['regulatory-compliance', 'document-automation', 'policy-management'], false, false, 'https://clausematch.com/favicon.ico'),
  ('legal-nivaura', 'Nivaura', 'AI-powered financial document automation platform for capital markets with intelligent contract generation.', 'https://nivaura.com', 'legal-finance', 'Paid', ARRAY['financial-documents', 'capital-markets', 'contract-generation'], false, false, 'https://nivaura.com/favicon.ico'),
  ('legal-legion', 'Legion', 'AI document assembly platform that automates legal document creation with intelligent templates and workflows.', 'https://legion.ai', 'legal-finance', 'Paid', ARRAY['document-assembly', 'legal-documents', 'intelligent-workflows'], false, false, 'https://legion.ai/favicon.ico'),
  ('legal-smokeball', 'Smokeball', 'AI-enhanced legal practice management with automated time tracking, document automation, and case analytics.', 'https://smokeball.com', 'legal-finance', 'Paid', ARRAY['practice-management', 'automated-tracking', 'case-analytics'], false, false, 'https://smokeball.com/favicon.ico'),
  ('legal-pathway', 'Pathway', 'AI-powered document automation platform that creates intelligent legal workflows and client intake systems.', 'https://pathway.legal', 'legal-finance', 'Paid', ARRAY['document-automation', 'legal-workflows', 'client-intake'], false, false, 'https://pathway.legal/favicon.ico'),
  
  -- Legal AI Assistants & Chatbots
  ('legal-donotpay', 'DoNotPay', 'AI-powered legal assistant that helps users fight bureaucracy, cancel subscriptions, and handle legal issues automatically.', 'https://donotpay.com', 'legal-finance', 'Freemium', ARRAY['legal-assistant', 'bureaucracy-fighting', 'automatic-legal-help'], false, true, 'https://donotpay.com/favicon.ico'),
  ('legal-ada', 'Ada for Legal', 'AI chatbot platform specialized for legal services with intelligent client intake and legal question answering.', 'https://ada.support', 'legal-finance', 'Paid', ARRAY['legal-chatbot', 'client-intake', 'question-answering'], false, false, 'https://ada.support/favicon.ico'),
  ('legal-lawyaw', 'Lawyaw', 'AI-enhanced legal document automation with intelligent forms, e-signatures, and client collaboration tools.', 'https://lawyaw.com', 'legal-finance', 'Paid', ARRAY['document-automation', 'e-signatures', 'client-collaboration'], false, false, 'https://lawyaw.com/favicon.ico'),
  ('legal-lexicata', 'Lexicata', 'AI-powered client intake and CRM platform for law firms with intelligent lead qualification and automation.', 'https://lexicata.com', 'legal-finance', 'Paid', ARRAY['client-intake', 'crm-platform', 'lead-qualification'], false, false, 'https://lexicata.com/favicon.ico'),
  ('legal-legalmation', 'Legalmation', 'AI litigation support platform that automates discovery responses and legal document drafting.', 'https://legalmation.com', 'legal-finance', 'Paid', ARRAY['litigation-support', 'discovery-responses', 'document-drafting'], false, false, 'https://legalmation.com/favicon.ico'),
  ('legal-judicata', 'Judicata', 'AI-powered legal research platform with patent-pending legal data analysis and case outcome prediction.', 'https://judicata.com', 'legal-finance', 'Paid', ARRAY['legal-research', 'data-analysis', 'outcome-prediction'], false, false, 'https://judicata.com/favicon.ico'),
  ('legal-everlaw', 'Everlaw', 'AI-enhanced ediscovery platform with predictive coding, document review, and litigation analytics.', 'https://everlaw.com', 'legal-finance', 'Paid', ARRAY['ediscovery', 'predictive-coding', 'litigation-analytics'], false, false, 'https://everlaw.com/favicon.ico'),
  ('legal-eigen', 'Eigen Technologies', 'AI document intelligence platform that extracts insights from unstructured legal and financial documents.', 'https://eigentech.com', 'legal-finance', 'Paid', ARRAY['document-intelligence', 'unstructured-data', 'insight-extraction'], false, false, 'https://eigentech.com/favicon.ico'),
  
  -- Financial AI & Fintech
  ('finance-palantir', 'Palantir Foundry', 'AI-powered data analytics platform for financial institutions with fraud detection and risk management capabilities.', 'https://palantir.com', 'legal-finance', 'Paid', ARRAY['financial-analytics', 'fraud-detection', 'risk-management'], false, true, 'https://palantir.com/favicon.ico'),
  ('finance-zest-ai', 'Zest AI', 'AI-powered credit underwriting platform that improves lending decisions with machine learning and alternative data.', 'https://zest.ai', 'legal-finance', 'Paid', ARRAY['credit-underwriting', 'lending-decisions', 'alternative-data'], false, true, 'https://zest.ai/favicon.ico'),
  ('finance-upstart', 'Upstart', 'AI-driven lending platform that uses machine learning to assess creditworthiness beyond traditional credit scores.', 'https://upstart.com', 'legal-finance', 'Paid', ARRAY['ai-lending', 'creditworthiness', 'machine-learning'], false, true, 'https://upstart.com/favicon.ico'),
  ('finance-kensho', 'Kensho', 'AI analytics platform for financial markets with natural language processing and predictive analytics.', 'https://kensho.com', 'legal-finance', 'Paid', ARRAY['financial-analytics', 'natural-language', 'predictive-analytics'], false, false, 'https://kensho.com/favicon.ico'),
  ('finance-alphasense', 'AlphaSense', 'AI-powered market intelligence platform that analyzes financial documents and earnings calls for investment insights.', 'https://alpha-sense.com', 'legal-finance', 'Paid', ARRAY['market-intelligence', 'financial-documents', 'investment-insights'], false, true, 'https://alpha-sense.com/favicon.ico'),
  ('finance-yodlee', 'Yodlee', 'AI-enhanced financial data aggregation platform with intelligent account linking and transaction categorization.', 'https://yodlee.com', 'legal-finance', 'Paid', ARRAY['data-aggregation', 'account-linking', 'transaction-categorization'], false, false, 'https://yodlee.com/favicon.ico'),
  ('finance-plaid', 'Plaid', 'AI-powered financial services API that connects apps to bank accounts with intelligent data enrichment.', 'https://plaid.com', 'legal-finance', 'Paid', ARRAY['financial-api', 'bank-connections', 'data-enrichment'], false, true, 'https://plaid.com/favicon.ico'),
  ('finance-mx', 'MX', 'AI-driven financial data platform that enhances banking experiences with intelligent money management insights.', 'https://mx.com', 'legal-finance', 'Paid', ARRAY['financial-data', 'banking-experiences', 'money-management'], false, false, 'https://mx.com/favicon.ico'),
  
  -- Robo-Advisors & Investment AI
  ('finance-betterment', 'Betterment', 'AI-powered robo-advisor that provides automated investment management with goal-based financial planning.', 'https://betterment.com', 'legal-finance', 'Freemium', ARRAY['robo-advisor', 'automated-investment', 'financial-planning'], false, true, 'https://betterment.com/favicon.ico'),
  ('finance-wealthfront', 'Wealthfront', 'AI-driven investment platform with automated portfolio management, tax-loss harvesting, and financial planning.', 'https://wealthfront.com', 'legal-finance', 'Freemium', ARRAY['investment-platform', 'portfolio-management', 'tax-optimization'], false, true, 'https://wealthfront.com/favicon.ico'),
  ('finance-schwab-intelligent', 'Schwab Intelligent Portfolios', 'AI-powered robo-advisor with automated rebalancing, tax-loss harvesting, and personalized investment strategies.', 'https://schwab.com', 'legal-finance', 'Freemium', ARRAY['robo-advisor', 'automated-rebalancing', 'investment-strategies'], false, false, 'https://schwab.com/favicon.ico'),
  ('finance-vanguard-digital', 'Vanguard Digital Advisor', 'AI-enhanced investment platform with automated portfolio management and low-cost index fund investing.', 'https://vanguard.com', 'legal-finance', 'Paid', ARRAY['investment-platform', 'portfolio-management', 'index-investing'], false, false, 'https://vanguard.com/favicon.ico'),
  ('finance-acorns', 'Acorns', 'AI-powered micro-investing app that rounds up purchases and invests spare change with intelligent portfolio allocation.', 'https://acorns.com', 'legal-finance', 'Freemium', ARRAY['micro-investing', 'spare-change', 'portfolio-allocation'], false, false, 'https://acorns.com/favicon.ico'),
  ('finance-stash', 'Stash', 'AI-enhanced investment platform that provides personalized investment recommendations and financial education.', 'https://stash.com', 'legal-finance', 'Freemium', ARRAY['investment-platform', 'personalized-recommendations', 'financial-education'], false, false, 'https://stash.com/favicon.ico'),
  ('finance-robinhood', 'Robinhood', 'AI-powered commission-free trading platform with intelligent market insights and automated investing features.', 'https://robinhood.com', 'legal-finance', 'Freemium', ARRAY['commission-free-trading', 'market-insights', 'automated-investing'], false, true, 'https://robinhood.com/favicon.ico'),
  ('finance-sofi-invest', 'SoFi Invest', 'AI-driven investment platform with automated investing, stock research, and financial planning tools.', 'https://sofi.com', 'legal-finance', 'Freemium', ARRAY['investment-platform', 'stock-research', 'financial-planning'], false, false, 'https://sofi.com/favicon.ico'),
  
  -- Trading & Market Analysis AI
  ('finance-tradingview', 'TradingView', 'AI-enhanced charting platform with intelligent market analysis, trading signals, and algorithmic trading tools.', 'https://tradingview.com', 'legal-finance', 'Freemium', ARRAY['charting-platform', 'market-analysis', 'trading-signals'], false, true, 'https://tradingview.com/favicon.ico'),
  ('finance-quantconnect', 'QuantConnect', 'AI-powered algorithmic trading platform with backtesting, live trading, and machine learning capabilities.', 'https://quantconnect.com', 'legal-finance', 'Freemium', ARRAY['algorithmic-trading', 'backtesting', 'machine-learning'], false, false, 'https://quantconnect.com/favicon.ico'),
  ('finance-alpaca', 'Alpaca', 'AI-driven commission-free trading API with algorithmic trading capabilities and market data analytics.', 'https://alpaca.markets', 'legal-finance', 'Freemium', ARRAY['trading-api', 'algorithmic-trading', 'market-data'], false, false, 'https://alpaca.markets/favicon.ico'),
  ('finance-darwinex', 'Darwinex', 'AI-powered investment platform that uses machine learning to evaluate and invest in trading strategies.', 'https://darwinex.com', 'legal-finance', 'Paid', ARRAY['investment-platform', 'trading-strategies', 'machine-learning'], false, false, 'https://darwinex.com/favicon.ico'),
  ('finance-tradestation', 'TradeStation', 'AI-enhanced trading platform with automated trading strategies, market analysis, and algorithmic trading tools.', 'https://tradestation.com', 'legal-finance', 'Paid', ARRAY['trading-platform', 'automated-strategies', 'algorithmic-trading'], false, false, 'https://tradestation.com/favicon.ico'),
  ('finance-interactive-brokers', 'Interactive Brokers', 'AI-powered trading platform with intelligent order routing, portfolio analytics, and automated trading systems.', 'https://interactivebrokers.com', 'legal-finance', 'Paid', ARRAY['trading-platform', 'intelligent-routing', 'portfolio-analytics'], false, false, 'https://interactivebrokers.com/favicon.ico'),
  ('finance-thinkorswim', 'thinkorswim', 'AI-enhanced trading platform with advanced charting, options analysis, and intelligent trading tools.', 'https://tdameritrade.com', 'legal-finance', 'Free', ARRAY['trading-platform', 'advanced-charting', 'options-analysis'], false, false, 'https://tdameritrade.com/favicon.ico'),
  ('finance-etoro', 'eToro', 'AI-powered social trading platform with copy trading, sentiment analysis, and intelligent portfolio management.', 'https://etoro.com', 'legal-finance', 'Freemium', ARRAY['social-trading', 'copy-trading', 'sentiment-analysis'], false, false, 'https://etoro.com/favicon.ico'),
  
  -- Personal Finance AI
  ('finance-mint', 'Mint', 'AI-powered personal finance app with automatic categorization, budget tracking, and spending insights.', 'https://mint.com', 'legal-finance', 'Free', ARRAY['personal-finance', 'budget-tracking', 'spending-insights'], false, true, 'https://mint.com/favicon.ico'),
  ('finance-ynab', 'YNAB (You Need A Budget)', 'AI-enhanced budgeting software with intelligent spending predictions and personalized financial recommendations.', 'https://youneedabudget.com', 'legal-finance', 'Paid', ARRAY['budgeting-software', 'spending-predictions', 'financial-recommendations'], false, false, 'https://youneedabudget.com/favicon.ico'),
  ('finance-personal-capital', 'Personal Capital', 'AI-driven wealth management platform with investment tracking, retirement planning, and fee analysis.', 'https://personalcapital.com', 'legal-finance', 'Freemium', ARRAY['wealth-management', 'investment-tracking', 'retirement-planning'], false, false, 'https://personalcapital.com/favicon.ico'),
  ('finance-tiller', 'Tiller', 'AI-powered spreadsheet-based financial tracking with automated data feeds and intelligent categorization.', 'https://tillerhq.com', 'legal-finance', 'Paid', ARRAY['financial-tracking', 'automated-data', 'intelligent-categorization'], false, false, 'https://tillerhq.com/favicon.ico'),
  ('finance-pocketguard', 'PocketGuard', 'AI-enhanced budgeting app with spending limits, bill tracking, and personalized saving recommendations.', 'https://pocketguard.com', 'legal-finance', 'Freemium', ARRAY['budgeting-app', 'spending-limits', 'saving-recommendations'], false, false, 'https://pocketguard.com/favicon.ico'),
  ('finance-goodbudget', 'Goodbudget', 'AI-powered envelope budgeting app with intelligent spending tracking and financial goal management.', 'https://goodbudget.com', 'legal-finance', 'Freemium', ARRAY['envelope-budgeting', 'spending-tracking', 'goal-management'], false, false, 'https://goodbudget.com/favicon.ico'),
  ('finance-spendee', 'Spendee', 'AI-enhanced expense tracking app with automatic categorization, budget insights, and financial analytics.', 'https://spendee.com', 'legal-finance', 'Freemium', ARRAY['expense-tracking', 'budget-insights', 'financial-analytics'], false, false, 'https://spendee.com/favicon.ico'),
  ('finance-clarity-money', 'Clarity Money', 'AI-powered financial wellness app with spending analysis, subscription tracking, and saving optimization.', 'https://claritymoney.com', 'legal-finance', 'Free', ARRAY['financial-wellness', 'spending-analysis', 'subscription-tracking'], false, false, 'https://claritymoney.com/favicon.ico'),
  
  -- Insurance AI & Insurtech
  ('finance-lemonade', 'Lemonade', 'AI-powered insurance company with instant claims processing, personalized policies, and behavioral economics.', 'https://lemonade.com', 'legal-finance', 'Paid', ARRAY['ai-insurance', 'instant-claims', 'personalized-policies'], false, true, 'https://lemonade.com/favicon.ico'),
  ('finance-root-insurance', 'Root Insurance', 'AI-driven auto insurance that uses telematics and machine learning to price policies based on driving behavior.', 'https://rootinsurance.com', 'legal-finance', 'Paid', ARRAY['auto-insurance', 'telematics', 'driving-behavior'], false, false, 'https://rootinsurance.com/favicon.ico'),
  ('finance-metromile', 'Metromile', 'AI-powered pay-per-mile auto insurance with intelligent mileage tracking and personalized pricing.', 'https://metromile.com', 'legal-finance', 'Paid', ARRAY['pay-per-mile', 'mileage-tracking', 'personalized-pricing'], false, false, 'https://metromile.com/favicon.ico'),
  ('finance-next-insurance', 'Next Insurance', 'AI-enhanced small business insurance with instant quotes, personalized coverage, and automated underwriting.', 'https://nextinsurance.com', 'legal-finance', 'Paid', ARRAY['business-insurance', 'instant-quotes', 'automated-underwriting'], false, false, 'https://nextinsurance.com/favicon.ico'),
  ('finance-tractable', 'Tractable', 'AI-powered damage assessment platform for insurance claims using computer vision and machine learning.', 'https://tractable.ai', 'legal-finance', 'Paid', ARRAY['damage-assessment', 'insurance-claims', 'computer-vision'], false, false, 'https://tractable.ai/favicon.ico'),
  ('finance-cape-analytics', 'Cape Analytics', 'AI property intelligence platform that uses aerial imagery and machine learning for insurance underwriting.', 'https://capeanalytics.com', 'legal-finance', 'Paid', ARRAY['property-intelligence', 'aerial-imagery', 'insurance-underwriting'], false, false, 'https://capeanalytics.com/favicon.ico'),
  ('finance-shift-technology', 'Shift Technology', 'AI-powered fraud detection and claims automation platform for insurance companies.', 'https://shift-technology.com', 'legal-finance', 'Paid', ARRAY['fraud-detection', 'claims-automation', 'insurance-ai'], false, false, 'https://shift-technology.com/favicon.ico'),
  ('finance-hippo-insurance', 'Hippo Insurance', 'AI-enhanced home insurance with proactive protection, smart home integration, and personalized coverage.', 'https://hippo.com', 'legal-finance', 'Paid', ARRAY['home-insurance', 'proactive-protection', 'smart-home'], false, false, 'https://hippo.com/favicon.ico'),
  
  -- Compliance & RegTech
  ('legal-chainalysis', 'Chainalysis', 'AI-powered blockchain analytics platform for cryptocurrency compliance, investigation, and risk management.', 'https://chainalysis.com', 'legal-finance', 'Paid', ARRAY['blockchain-analytics', 'crypto-compliance', 'risk-management'], false, true, 'https://chainalysis.com/favicon.ico'),
  ('legal-elliptic', 'Elliptic', 'AI-driven cryptocurrency compliance platform with transaction monitoring and blockchain analytics.', 'https://elliptic.co', 'legal-finance', 'Paid', ARRAY['crypto-compliance', 'transaction-monitoring', 'blockchain-analytics'], false, false, 'https://elliptic.co/favicon.ico'),
  ('legal-trulioo', 'Trulioo', 'AI-powered identity verification platform for global KYC/AML compliance with document verification.', 'https://trulioo.com', 'legal-finance', 'Paid', ARRAY['identity-verification', 'kyc-aml', 'document-verification'], false, false, 'https://trulioo.com/favicon.ico'),
  ('legal-jumio', 'Jumio', 'AI-enhanced identity verification and eKYC platform with biometric authentication and fraud prevention.', 'https://jumio.com', 'legal-finance', 'Paid', ARRAY['identity-verification', 'biometric-auth', 'fraud-prevention'], false, false, 'https://jumio.com/favicon.ico'),
  ('legal-onfido', 'Onfido', 'AI-powered identity verification platform with document verification, biometric matching, and fraud detection.', 'https://onfido.com', 'legal-finance', 'Paid', ARRAY['identity-verification', 'biometric-matching', 'fraud-detection'], false, false, 'https://onfido.com/favicon.ico'),
  ('legal-persona', 'Persona', 'AI-driven identity verification infrastructure with customizable workflows and fraud prevention capabilities.', 'https://withpersona.com', 'legal-finance', 'Paid', ARRAY['identity-verification', 'customizable-workflows', 'fraud-prevention'], false, false, 'https://withpersona.com/favicon.ico'),
  ('legal-socure', 'Socure', 'AI-powered identity verification and fraud prevention platform with predictive analytics and machine learning.', 'https://socure.com', 'legal-finance', 'Paid', ARRAY['identity-verification', 'fraud-prevention', 'predictive-analytics'], false, false, 'https://socure.com/favicon.ico'),
  ('legal-alloy', 'Alloy', 'AI-enhanced identity decisioning platform for financial services with fraud detection and compliance automation.', 'https://alloy.com', 'legal-finance', 'Paid', ARRAY['identity-decisioning', 'fraud-detection', 'compliance-automation'], false, false, 'https://alloy.com/favicon.ico'),
  
  -- Fraud Detection & Security
  ('finance-feedzai', 'Feedzai', 'AI-powered fraud prevention platform with real-time risk scoring and machine learning-based detection.', 'https://feedzai.com', 'legal-finance', 'Paid', ARRAY['fraud-prevention', 'real-time-scoring', 'machine-learning'], false, true, 'https://feedzai.com/favicon.ico'),
  ('finance-sift', 'Sift', 'AI-driven fraud prevention platform that protects against payment fraud, account takeover, and content abuse.', 'https://sift.com', 'legal-finance', 'Paid', ARRAY['fraud-prevention', 'payment-fraud', 'account-protection'], false, false, 'https://sift.com/favicon.ico'),
  ('finance-kount', 'Kount', 'AI-powered fraud prevention and digital identity platform with real-time decision making and risk assessment.', 'https://kount.com', 'legal-finance', 'Paid', ARRAY['fraud-prevention', 'digital-identity', 'risk-assessment'], false, false, 'https://kount.com/favicon.ico'),
  ('finance-riskified', 'Riskified', 'AI-enhanced ecommerce fraud prevention platform with chargeback guarantee and revenue protection.', 'https://riskified.com', 'legal-finance', 'Paid', ARRAY['ecommerce-fraud', 'chargeback-protection', 'revenue-protection'], false, false, 'https://riskified.com/favicon.ico'),
  ('finance-signifyd', 'Signifyd', 'AI-powered commerce protection platform with fraud prevention, chargeback protection, and revenue optimization.', 'https://signifyd.com', 'legal-finance', 'Paid', ARRAY['commerce-protection', 'fraud-prevention', 'revenue-optimization'], false, false, 'https://signifyd.com/favicon.ico'),
  ('finance-forter', 'Forter', 'AI-driven fraud prevention platform for ecommerce with real-time decisions and abuse prevention.', 'https://forter.com', 'legal-finance', 'Paid', ARRAY['fraud-prevention', 'real-time-decisions', 'abuse-prevention'], false, false, 'https://forter.com/favicon.ico'),
  ('finance-cybersource', 'CyberSource', 'AI-enhanced payment security platform with fraud management, tokenization, and risk assessment.', 'https://cybersource.com', 'legal-finance', 'Paid', ARRAY['payment-security', 'fraud-management', 'tokenization'], false, false, 'https://cybersource.com/favicon.ico'),
  ('finance-emailage', 'Emailage', 'AI-powered email intelligence platform for fraud prevention with risk scoring and identity verification.', 'https://emailage.com', 'legal-finance', 'Paid', ARRAY['email-intelligence', 'fraud-prevention', 'identity-verification'], false, false, 'https://emailage.com/favicon.ico'),
  
  -- Credit Scoring & Alternative Data
  ('finance-fico', 'FICO', 'AI-powered credit scoring and decision management platform with predictive analytics and machine learning.', 'https://fico.com', 'legal-finance', 'Paid', ARRAY['credit-scoring', 'decision-management', 'predictive-analytics'], false, false, 'https://fico.com/favicon.ico'),
  ('finance-experian', 'Experian AI', 'AI-enhanced credit services with alternative data analytics, identity verification, and fraud prevention.', 'https://experian.com', 'legal-finance', 'Paid', ARRAY['credit-services', 'alternative-data', 'identity-verification'], false, false, 'https://experian.com/favicon.ico'),
  ('finance-equifax', 'Equifax AI', 'AI-powered credit information services with machine learning-based risk assessment and identity solutions.', 'https://equifax.com', 'legal-finance', 'Paid', ARRAY['credit-information', 'risk-assessment', 'identity-solutions'], false, false, 'https://equifax.com/favicon.ico'),
  ('finance-transunion', 'TransUnion AI', 'AI-enhanced credit reporting and identity management platform with fraud detection and risk analytics.', 'https://transunion.com', 'legal-finance', 'Paid', ARRAY['credit-reporting', 'identity-management', 'fraud-detection'], false, false, 'https://transunion.com/favicon.ico'),
  ('finance-nova-credit', 'Nova Credit', 'AI-powered credit infrastructure platform that translates international credit history for cross-border lending.', 'https://novacredit.com', 'legal-finance', 'Paid', ARRAY['credit-infrastructure', 'international-credit', 'cross-border-lending'], false, false, 'https://novacredit.com/favicon.ico'),
  ('finance-petal', 'Petal', 'AI-driven credit card platform that uses alternative data and machine learning for credit assessment.', 'https://petalcard.com', 'legal-finance', 'Freemium', ARRAY['credit-card', 'alternative-data', 'credit-assessment'], false, false, 'https://petalcard.com/favicon.ico'),
  ('finance-tala', 'Tala', 'AI-powered mobile lending platform that uses smartphone data and machine learning for credit scoring.', 'https://tala.co', 'legal-finance', 'Freemium', ARRAY['mobile-lending', 'smartphone-data', 'credit-scoring'], false, false, 'https://tala.co/favicon.ico'),
  ('finance-branch', 'Branch', 'AI-enhanced mobile banking and lending platform with alternative credit scoring and financial services.', 'https://branch.co', 'legal-finance', 'Freemium', ARRAY['mobile-banking', 'alternative-credit', 'financial-services'], false, false, 'https://branch.co/favicon.ico'),
  
  -- Accounting & Tax AI
  ('finance-quickbooks-ai', 'QuickBooks AI', 'AI-powered accounting software with automated bookkeeping, expense categorization, and financial insights.', 'https://quickbooks.intuit.com', 'legal-finance', 'Paid', ARRAY['accounting-software', 'automated-bookkeeping', 'financial-insights'], false, true, 'https://quickbooks.intuit.com/favicon.ico'),
  ('finance-xero-ai', 'Xero AI', 'AI-enhanced cloud accounting platform with bank reconciliation, invoice processing, and financial reporting.', 'https://xero.com', 'legal-finance', 'Paid', ARRAY['cloud-accounting', 'bank-reconciliation', 'financial-reporting'], false, false, 'https://xero.com/favicon.ico'),
  ('finance-freshbooks-ai', 'FreshBooks AI', 'AI-powered accounting software for small businesses with time tracking, invoicing, and expense management.', 'https://freshbooks.com', 'legal-finance', 'Paid', ARRAY['small-business-accounting', 'time-tracking', 'expense-management'], false, false, 'https://freshbooks.com/favicon.ico'),
  ('finance-turbotax-ai', 'TurboTax AI', 'AI-enhanced tax preparation software with intelligent deduction finding and automated tax filing.', 'https://turbotax.intuit.com', 'legal-finance', 'Paid', ARRAY['tax-preparation', 'deduction-finding', 'automated-filing'], false, true, 'https://turbotax.intuit.com/favicon.ico'),
  ('finance-taxact-ai', 'TaxAct AI', 'AI-powered tax software with automated data import, deduction maximization, and error checking.', 'https://taxact.com', 'legal-finance', 'Paid', ARRAY['tax-software', 'automated-import', 'error-checking'], false, false, 'https://taxact.com/favicon.ico'),
  ('finance-hrblock-ai', 'H&R Block AI', 'AI-enhanced tax preparation platform with virtual tax assistance and intelligent refund optimization.', 'https://hrblock.com', 'legal-finance', 'Paid', ARRAY['tax-preparation', 'virtual-assistance', 'refund-optimization'], false, false, 'https://hrblock.com/favicon.ico'),
  ('finance-freetaxusa-ai', 'FreeTaxUSA AI', 'AI-powered free tax filing platform with intelligent form completion and deduction suggestions.', 'https://freetaxusa.com', 'legal-finance', 'Freemium', ARRAY['free-tax-filing', 'form-completion', 'deduction-suggestions'], false, false, 'https://freetaxusa.com/favicon.ico'),
  ('finance-sage-ai', 'Sage AI', 'AI-enhanced business accounting software with intelligent cash flow forecasting and financial analytics.', 'https://sage.com', 'legal-finance', 'Paid', ARRAY['business-accounting', 'cash-flow-forecasting', 'financial-analytics'], false, false, 'https://sage.com/favicon.ico'),
  
  -- Cryptocurrency & Blockchain AI
  ('finance-coinbase-ai', 'Coinbase AI', 'AI-powered cryptocurrency exchange with intelligent trading features and portfolio analytics.', 'https://coinbase.com', 'legal-finance', 'Freemium', ARRAY['cryptocurrency-exchange', 'intelligent-trading', 'portfolio-analytics'], false, true, 'https://coinbase.com/favicon.ico'),
  ('finance-binance-ai', 'Binance AI', 'AI-enhanced cryptocurrency trading platform with algorithmic trading and market analysis tools.', 'https://binance.com', 'legal-finance', 'Freemium', ARRAY['crypto-trading', 'algorithmic-trading', 'market-analysis'], false, false, 'https://binance.com/favicon.ico'),
  ('finance-kraken-ai', 'Kraken AI', 'AI-powered cryptocurrency exchange with advanced trading features and security intelligence.', 'https://kraken.com', 'legal-finance', 'Freemium', ARRAY['crypto-exchange', 'advanced-trading', 'security-intelligence'], false, false, 'https://kraken.com/favicon.ico'),
  ('finance-bitfinex-ai', 'Bitfinex AI', 'AI-enhanced cryptocurrency trading platform with margin trading and algorithmic order types.', 'https://bitfinex.com', 'legal-finance', 'Freemium', ARRAY['crypto-trading', 'margin-trading', 'algorithmic-orders'], false, false, 'https://bitfinex.com/favicon.ico'),
  ('finance-messari', 'Messari', 'AI-powered cryptocurrency research and analytics platform with market intelligence and data analysis.', 'https://messari.io', 'legal-finance', 'Freemium', ARRAY['crypto-research', 'market-intelligence', 'data-analysis'], false, false, 'https://messari.io/favicon.ico'),
  ('finance-glassnode', 'Glassnode', 'AI-enhanced blockchain analytics platform with on-chain data analysis and market insights.', 'https://glassnode.com', 'legal-finance', 'Freemium', ARRAY['blockchain-analytics', 'on-chain-data', 'market-insights'], false, false, 'https://glassnode.com/favicon.ico'),
  ('finance-dune-analytics', 'Dune Analytics', 'AI-powered blockchain data analytics platform with customizable dashboards and query tools.', 'https://dune.com', 'legal-finance', 'Freemium', ARRAY['blockchain-data', 'customizable-dashboards', 'query-tools'], false, false, 'https://dune.com/favicon.ico'),
  ('finance-nansen', 'Nansen', 'AI-driven blockchain analytics platform with wallet profiling and DeFi protocol analysis.', 'https://nansen.ai', 'legal-finance', 'Paid', ARRAY['blockchain-analytics', 'wallet-profiling', 'defi-analysis'], false, false, 'https://nansen.ai/favicon.ico')
ON CONFLICT (id, category_id) DO NOTHING;

-- Update the tool count for the category
UPDATE categories 
SET tool_count = (
  SELECT COUNT(*) 
  FROM tools 
  WHERE category_id = 'legal-finance'
) 
WHERE id = 'legal-finance';
