-- Add 50 AI Tools to Social Media Category
-- Excluding existing tools already mentioned

-- Get the social media category ID
DO $$
DECLARE
    social_media_category_id VARCHAR(50);
BEGIN
    -- Get the social media category ID
    SELECT id INTO social_media_category_id FROM categories WHERE id = 'social-media';
    
    -- If category doesn't exist, create it
    IF social_media_category_id IS NULL THEN
        INSERT INTO categories (id, name, description, icon, color, created_at, updated_at)
        VALUES ('social-media', 'Social Media', 'AI tools for social media management, content creation, and analytics', '📱', 'from-blue-500 to-indigo-500', NOW(), NOW());
        social_media_category_id := 'social-media';
    END IF;    -- Insert 50 new social media AI tools
    INSERT INTO tools (id, name, description, url, logo_url, category_id, pricing, featured, trending, created_at, updated_at) VALUES
    ('social-predis-ai', 'Predis AI', 'AI-powered social media content creation and scheduling platform with automated post generation', 'https://predis.ai', 'https://images.unsplash.com/photo-1611605698335-8b1569810432?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Freemium', false, false, NOW(), NOW()),
    ('social-flick-social', 'Flick Social', 'Instagram-focused AI tool for hashtag research, content planning, and analytics', 'https://flick.social', 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Paid', false, false, NOW(), NOW()),
    ('social-ocoya-ai', 'Ocoya AI', 'All-in-one AI social media management platform with content creation and scheduling', 'https://ocoya.com', 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Freemium', false, false, NOW(), NOW()),
    ('social-publer-ai', 'Publer AI', 'AI-enhanced social media scheduler with smart content suggestions and analytics', 'https://publer.io', 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Freemium', false, false, NOW(), NOW()),
    ('social-contentstudio-ai', 'ContentStudio AI', 'Comprehensive social media management with AI content discovery and automation', 'https://contentstudio.io', 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Paid', false, false, NOW(), NOW()),
    ('social-postwise-ai', 'Postwise AI', 'AI ghostwriter for Twitter and LinkedIn with viral content generation', 'https://postwise.ai', 'https://images.unsplash.com/photo-1579952363873-27d3bfad9c0d?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Paid', false, false, NOW(), NOW()),
    ('social-hypefury-ai', 'Hypefury AI', 'Twitter growth tool with AI-powered content scheduling and engagement automation', 'https://hypefury.com', 'https://images.unsplash.com/photo-1611605698323-b1e99cfd37ea?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Paid', false, false, NOW(), NOW()),
    ('social-tweet-hunter', 'Tweet Hunter', 'AI-powered Twitter growth platform with content inspiration and scheduling', 'https://tweethunter.io', 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Paid', false, false, NOW(), NOW()),
    ('social-typefully-ai', 'Typefully AI', 'AI-assisted Twitter thread writer and scheduler with analytics', 'https://typefully.com', 'https://images.unsplash.com/photo-1558655146-d09347e92766?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Freemium', false, false, NOW(), NOW()),
    ('social-postify-ai', 'Postify AI', 'AI social media content generator with multi-platform publishing', 'https://postify.ai', 'https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Paid', false, false, NOW(), NOW()),
    ('social-socialbu-ai', 'SocialBu AI', 'AI-powered social media management with automated posting and engagement', 'https://socialbu.com', 'https://images.unsplash.com/photo-1611605698319-b1e99cfd37ea?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Freemium', false, false, NOW(), NOW()),
    ('social-circleboom-ai', 'Circleboom AI', 'Twitter management tool with AI content curation and follower analytics', 'https://circleboom.com', 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Freemium', false, false, NOW(), NOW()),
    ('social-feedhive-ai', 'FeedHive AI', 'AI social media scheduler with performance prediction and content optimization', 'https://feedhive.com', 'https://images.unsplash.com/photo-1535738606787-0da9bb2d6f7b?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Freemium', false, false, NOW(), NOW()),
    ('social-pallyy-ai', 'Pallyy AI', 'AI-enhanced social media scheduler with content suggestions and team collaboration', 'https://pallyy.com', 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Freemium', false, false, NOW(), NOW()),
    ('social-recurpost-ai', 'RecurPost AI', 'AI-powered social media recycling tool with automated content resharing', 'https://recurpost.com', 'https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Paid', false, false, NOW(), NOW()),
    ('social-socialoomph-ai', 'SocialOomph AI', 'AI-driven social media productivity tool with smart scheduling and automation', 'https://socialoomph.com', 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Paid', false, false, NOW(), NOW()),
    ('social-friendsme-ai', 'Friends+Me AI', 'AI social media management for Google+ and multi-platform publishing', 'https://friendsplus.me', 'https://images.unsplash.com/photo-1535738606787-0da9bb2d6f7b?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Freemium', false, false, NOW(), NOW()),
    ('social-sked-social-ai', 'Sked Social AI', 'Instagram-first AI scheduler with visual content planning and analytics', 'https://skedsocial.com', 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Paid', false, false, NOW(), NOW()),
    ('social-planable-ai', 'Planable AI', 'AI-powered social media collaboration platform with content approval workflows', 'https://planable.io', 'https://images.unsplash.com/photo-1579952363873-27d3bfad9c0d?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Paid', false, false, NOW(), NOW()),
    ('social-meetedgar-ai', 'MeetEdgar AI', 'AI social media automation with content recycling and category-based scheduling', 'https://meetedgar.com', 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Paid', false, false, NOW(), NOW()),
    ('social-loomly-ai', 'Loomly AI', 'AI brand success platform with content suggestions and social media calendar', 'https://loomly.com', 'https://images.unsplash.com/photo-1611605698335-8b1569810432?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Paid', false, false, NOW(), NOW()),
    ('social-coschedule-ai', 'CoSchedule AI', 'AI marketing calendar with social media scheduling and content optimization', 'https://coschedule.com', 'https://images.unsplash.com/photo-1558655146-d09347e92766?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Paid', false, false, NOW(), NOW()),
    ('social-viralpost-ai', 'ViralPost AI', 'AI content generator specifically designed for viral social media posts', 'https://viralpost.ai', 'https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Paid', false, false, NOW(), NOW()),
    ('social-socialchamp-ai', 'SocialChamp AI', 'AI social media management with bulk uploading and advanced scheduling', 'https://socialchamp.io', 'https://images.unsplash.com/photo-1611605698323-b1e99cfd37ea?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Freemium', false, false, NOW(), NOW()),
    ('social-promorepublic-ai', 'PromoRepublic AI', 'AI-powered content creation platform with 100,000+ social media templates', 'https://promorepublic.com', 'https://images.unsplash.com/photo-1535738606787-0da9bb2d6f7b?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Paid', false, false, NOW(), NOW()),
    ('social-tailwind-ai', 'Tailwind AI', 'AI-powered Pinterest and Instagram scheduler with SmartSchedule and hashtag finder', 'https://tailwindapp.com', 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Freemium', false, false, NOW(), NOW()),
    ('social-later-influence-ai', 'Later Influence AI', 'AI influencer marketing platform with creator discovery and campaign management', 'https://later.com', 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Paid', false, false, NOW(), NOW()),
    ('social-creatorkit-ai', 'CreatorKit AI', 'AI video and image creation tool for social media content', 'https://creatorkit.com', 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Freemium', false, false, NOW(), NOW()),
    ('social-smartly-ai', 'Smartly AI', 'AI-powered social media advertising automation for Facebook, Instagram, and Snapchat', 'https://smartly.io', 'https://images.unsplash.com/photo-1579952363873-27d3bfad9c0d?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Paid', false, false, NOW(), NOW()),
    ('social-revealbot-ai', 'Revealbot AI', 'AI Facebook and Instagram ads automation with smart bidding and optimization', 'https://revealbot.com', 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Paid', false, false, NOW(), NOW()),
    ('social-madgicx-ai', 'Madgicx AI', 'AI-powered Facebook ads optimization with creative intelligence and audience targeting', 'https://madgicx.com', 'https://images.unsplash.com/photo-1611605698335-8b1569810432?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Paid', false, false, NOW(), NOW()),
    ('social-adespresso-ai', 'AdEspresso AI', 'AI Facebook and Instagram ads creation and optimization platform', 'https://adespresso.com', 'https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Paid', false, false, NOW(), NOW()),
    ('social-socialdraft-ai', 'Socialdraft AI', 'AI copywriting tool specialized for social media posts and campaigns', 'https://socialdraft.com', 'https://images.unsplash.com/photo-1558655146-d09347e92766?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Paid', false, false, NOW(), NOW()),
    ('social-lately-ai', 'Lately AI', 'AI content repurposing tool that transforms long-form content into social media posts', 'https://lately.ai', 'https://images.unsplash.com/photo-1535738606787-0da9bb2d6f7b?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Paid', false, false, NOW(), NOW()),
    ('social-creatosaurus-ai', 'Creatosaurus AI', 'AI-powered creative workspace for social media content creation and storytelling', 'https://creatosaurus.io', 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Freemium', false, false, NOW(), NOW()),
    ('social-socialpika-ai', 'SocialPika AI', 'AI social media post generator with customizable templates and brand consistency', 'https://socialpika.com', 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Freemium', false, false, NOW(), NOW()),
    ('social-contentcal-ai', 'ContentCal AI', 'AI social media content planner with team collaboration and approval workflows', 'https://contentcal.io', 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Paid', false, false, NOW(), NOW()),
    ('social-zoho-social-ai', 'Zoho Social AI Assistant', 'AI-powered social media management integrated with Zoho CRM and marketing suite', 'https://zoho.com/social', 'https://images.unsplash.com/photo-1579952363873-27d3bfad9c0d?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Paid', false, false, NOW(), NOW()),
    ('social-tweet-assist-ai', 'Tweet Assist AI', 'AI Twitter assistant for generating engaging tweets and thread ideas', 'https://tweetassist.ai', 'https://images.unsplash.com/photo-1611605698323-b1e99cfd37ea?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Freemium', false, false, NOW(), NOW()),
    ('social-instatext-ai', 'InstaText AI', 'AI writing assistant for Instagram captions and social media content', 'https://instatext.io', 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Freemium', false, false, NOW(), NOW()),
    ('social-postly-ai', 'Postly AI', 'AI social media scheduler with smart content suggestions and performance analytics', 'https://postly.ai', 'https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Paid', false, false, NOW(), NOW()),
    ('social-vista-social-ai', 'Vista Social AI', 'AI-enhanced social media management with content curation and publishing automation', 'https://vistasocial.com', 'https://images.unsplash.com/photo-1535738606787-0da9bb2d6f7b?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Freemium', false, false, NOW(), NOW()),
    ('social-statusbrew-ai', 'Statusbrew AI', 'AI social media management platform with unified inbox and engagement automation', 'https://statusbrew.com', 'https://images.unsplash.com/photo-1558655146-d09347e92766?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Paid', false, false, NOW(), NOW()),
    ('social-napoleoncat-ai', 'NapoleonCat AI', 'AI social media management with automated moderation and customer service', 'https://napoleoncat.com', 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Paid', false, false, NOW(), NOW()),
    ('social-eclincher-ai-pro', 'eClincher AI Pro', 'Advanced AI social media management with predictive analytics and content optimization', 'https://eclincher.com', 'https://images.unsplash.com/photo-1611605698335-8b1569810432?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Paid', false, false, NOW(), NOW()),
    ('social-socialflow-ai', 'SocialFlow AI', 'AI-powered social media optimization with real-time audience engagement prediction', 'https://socialflow.com', 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Paid', false, false, NOW(), NOW()),
    ('social-spredfast-ai', 'Spredfast AI', 'Enterprise AI social media management with advanced analytics and workflow automation', 'https://spredfast.com', 'https://images.unsplash.com/photo-1579952363873-27d3bfad9c0d?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Paid', false, false, NOW(), NOW()),
    ('social-socialbakers-ai-suite', 'Socialbakers AI Suite', 'Comprehensive AI social media analytics with content performance prediction', 'https://socialbakers.com', 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Paid', false, false, NOW(), NOW()),
    ('social-brand24-ai', 'Brand24 AI', 'AI social media monitoring with sentiment analysis and influencer identification', 'https://brand24.com', 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Paid', false, false, NOW(), NOW()),
    ('social-awario-ai', 'Awario AI', 'AI-powered social media and web monitoring with brand mention tracking', 'https://awario.com', 'https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?w=64&h=64&fit=crop&crop=center', social_media_category_id, 'Paid', false, false, NOW(), NOW());

    RAISE NOTICE 'Successfully added 50 new AI tools to the Social Media category (ID: %)', social_media_category_id;
END $$;
