-- Voice Generation & Conversion AI Tools (110 tools)
-- This script adds 110 AI-powered tools for voice generation and conversion
-- Covers text-to-speech, voice cloning, voice conversion, speech synthesis, and audio AI
-- Uses ON CONFLICT (id, category_id) DO NOTHING to avoid duplicates within the same category

INSERT INTO tools (
  id, name, description, url, category_id, 
  pricing, tags, featured, trending, logo_url
) VALUES 
  -- Text-to-Speech AI Platforms
  ('voice-elevenlabs', 'ElevenLabs', 'AI voice generation platform with realistic speech synthesis, voice cloning, and multilingual support for content creators.', 'https://elevenlabs.io', 'voice-generation-conversion', 'Freemium', ARRAY['text-to-speech', 'voice-cloning', 'speech-synthesis'], false, false, 'https://elevenlabs.io/favicon.ico'),
  ('voice-murf-ai', 'Murf AI', 'AI-powered text-to-speech platform with 120+ voices in 20+ languages for voiceovers, podcasts, and presentations.', 'https://murf.ai', 'voice-generation-conversion', 'Freemium', ARRAY['text-to-speech', 'voiceovers', 'multilingual'], false, false, 'https://murf.ai/favicon.ico'),
  ('voice-speechify', 'Speechify', 'AI text-to-speech app that reads any text aloud with natural voices and speed control for accessibility and productivity.', 'https://speechify.com', 'voice-generation-conversion', 'Freemium', ARRAY['text-to-speech', 'natural-voices', 'accessibility'], false, false, 'https://speechify.com/favicon.ico'),
  ('voice-naturalreader', 'NaturalReader', 'AI-enhanced text-to-speech software with multiple voices, reading speeds, and document support for personal and commercial use.', 'https://naturalreaders.com', 'voice-generation-conversion', 'Freemium', ARRAY['text-to-speech', 'multiple-voices', 'document-support'], false, false, 'https://naturalreaders.com/favicon.ico'),
  ('voice-amazon-polly', 'Amazon Polly', 'AI speech service that turns text into lifelike speech with deep learning technologies and neural text-to-speech capabilities.', 'https://aws.amazon.com/polly', 'voice-generation-conversion', 'Paid', ARRAY['speech-service', 'deep-learning', 'neural-tts'], false, false, 'https://aws.amazon.com/favicon.ico'),
  ('voice-google-cloud-tts', 'Google Cloud Text-to-Speech', 'AI-powered text-to-speech service with WaveNet voices, custom voice models, and SSML support for developers.', 'https://cloud.google.com/text-to-speech', 'voice-generation-conversion', 'Paid', ARRAY['wavenet-voices', 'custom-models', 'ssml-support'], false, false, 'https://cloud.google.com/favicon.ico'),
  ('voice-microsoft-speech', 'Microsoft Speech Services', 'AI speech platform with neural text-to-speech, custom neural voice, and real-time speech synthesis capabilities.', 'https://azure.microsoft.com/services/cognitive-services/speech-services', 'voice-generation-conversion', 'Paid', ARRAY['neural-tts', 'custom-voice', 'real-time-synthesis'], false, false, 'https://azure.microsoft.com/favicon.ico'),
  ('voice-ibm-watson-tts', 'IBM Watson Text to Speech', 'AI speech synthesis service with expressive neural voices, customization options, and enterprise-grade security.', 'https://ibm.com/cloud/watson-text-to-speech', 'voice-generation-conversion', 'Paid', ARRAY['neural-voices', 'customization', 'enterprise-security'], false, false, 'https://ibm.com/favicon.ico'),
  ('voice-resemble-ai', 'Resemble AI', 'AI voice cloning and generation platform with real-time voice synthesis, emotional control, and voice conversion capabilities.', 'https://resemble.ai', 'voice-generation-conversion', 'Paid', ARRAY['voice-cloning', 'real-time-synthesis', 'emotional-control'], false, false, 'https://resemble.ai/favicon.ico'),
  ('voice-wellsaid-labs', 'WellSaid Labs', 'AI voice generation platform with studio-quality voices for enterprise content creation and brand voice consistency.', 'https://wellsaidlabs.com', 'voice-generation-conversion', 'Paid', ARRAY['studio-quality', 'enterprise-content', 'brand-voice'], false, false, 'https://wellsaidlabs.com/favicon.ico'),
  
  -- Voice Cloning & Synthesis
  ('voice-descript-overdub', 'Descript Overdub', 'AI voice cloning tool that creates a synthetic version of your voice for seamless audio editing and content creation.', 'https://descript.com/overdub', 'voice-generation-conversion', 'Paid', ARRAY['voice-cloning', 'synthetic-voice', 'audio-editing'], false, false, 'https://descript.com/favicon.ico'),
  ('voice-replica-studios', 'Replica Studios', 'AI voice acting platform with a library of synthetic voices for games, films, and immersive media production.', 'https://replicastudios.com', 'voice-generation-conversion', 'Freemium', ARRAY['voice-acting', 'synthetic-voices', 'immersive-media'], false, false, 'https://replicastudios.com/favicon.ico'),
  ('voice-mycroft-mimic', 'Mycroft Mimic', 'Open-source AI text-to-speech engine with neural voice synthesis and customizable voice models for developers.', 'https://mycroft.ai/mimic-3', 'voice-generation-conversion', 'Free', ARRAY['open-source', 'neural-synthesis', 'customizable-models'], false, false, 'https://mycroft.ai/favicon.ico'),
  ('voice-coqui-tts', 'Coqui TTS', 'Open-source AI text-to-speech toolkit with voice cloning, multilingual support, and real-time speech synthesis.', 'https://coqui.ai', 'voice-generation-conversion', 'Free', ARRAY['open-source', 'voice-cloning', 'multilingual'], false, false, 'https://coqui.ai/favicon.ico'),
  ('voice-vall-e', 'VALL-E by Microsoft', 'AI voice synthesis model that can replicate any voice from just a 3-second audio sample with high fidelity.', 'https://valle-demo.github.io', 'voice-generation-conversion', 'Free', ARRAY['voice-synthesis', '3-second-sample', 'high-fidelity'], false, false, 'https://microsoft.com/favicon.ico'),
  ('voice-tortoise-tts', 'Tortoise TTS', 'AI text-to-speech system with voice cloning capabilities and high-quality speech synthesis for creative projects.', 'https://github.com/neonbjb/tortoise-tts', 'voice-generation-conversion', 'Free', ARRAY['voice-cloning', 'high-quality', 'creative-projects'], false, false, 'https://github.com/favicon.ico'),
  ('voice-bark-ai', 'Bark AI', 'Open-source AI audio generation model that can create speech, music, and sound effects with text prompts.', 'https://github.com/suno-ai/bark', 'voice-generation-conversion', 'Free', ARRAY['audio-generation', 'speech-music', 'sound-effects'], false, false, 'https://github.com/favicon.ico'),
  ('voice-real-time-voice-cloning', 'Real-Time Voice Cloning', 'AI voice cloning toolkit that can clone voices in real-time with minimal training data and high accuracy.', 'https://github.com/CorentinJ/Real-Time-Voice-Cloning', 'voice-generation-conversion', 'Free', ARRAY['real-time-cloning', 'minimal-data', 'high-accuracy'], false, false, 'https://github.com/favicon.ico'),
  ('voice-so-vits-svc', 'SoftVC VITS Singing Voice Conversion', 'AI singing voice conversion model that can transform any voice into a singing voice with pitch and tone control.', 'https://github.com/svc-develop-team/so-vits-svc', 'voice-generation-conversion', 'Free', ARRAY['singing-voice', 'voice-conversion', 'pitch-control'], false, false, 'https://github.com/favicon.ico'),
  ('voice-voicefixer', 'VoiceFixer', 'AI audio restoration tool that enhances speech quality, removes noise, and improves voice clarity automatically.', 'https://github.com/haoheliu/voicefixer', 'voice-generation-conversion', 'Free', ARRAY['audio-restoration', 'speech-enhancement', 'noise-removal'], false, false, 'https://github.com/favicon.ico'),
  
  -- Real-Time Voice Conversion
  ('voice-voice-ai', 'Voice.ai', 'Real-time AI voice changer with voice cloning, soundboard features, and custom voice creation for gaming and streaming.', 'https://voice.ai', 'voice-generation-conversion', 'Freemium', ARRAY['real-time-changer', 'voice-cloning', 'gaming-streaming'], false, false, 'https://voice.ai/favicon.ico'),
  ('voice-voicemod', 'Voicemod', 'Real-time AI voice changer and soundboard with voice effects, custom voices, and integration with popular apps.', 'https://voicemod.net', 'voice-generation-conversion', 'Freemium', ARRAY['real-time-changer', 'voice-effects', 'app-integration'], false, false, 'https://voicemod.net/favicon.ico'),
  ('voice-clownfish', 'Clownfish Voice Changer', 'Real-time AI voice changing application with various voice effects and integration with VoIP applications.', 'https://clownfish-translator.com/voicechanger', 'voice-generation-conversion', 'Free', ARRAY['real-time-changer', 'voice-effects', 'voip-integration'], false, false, 'https://clownfish-translator.com/favicon.ico'),
  ('voice-morphvox', 'MorphVOX', 'AI-powered voice changing software with high-quality voice algorithms and background noise cancellation.', 'https://screamingbee.com/morphvox', 'voice-generation-conversion', 'Paid', ARRAY['voice-changing', 'high-quality', 'noise-cancellation'], false, false, 'https://screamingbee.com/favicon.ico'),
  ('voice-voxal', 'Voxal Voice Changer', 'Real-time AI voice modification software with voice effects, recording capabilities, and audio enhancement.', 'https://nchsoftware.com/voicechanger', 'voice-generation-conversion', 'Freemium', ARRAY['voice-modification', 'recording', 'audio-enhancement'], false, false, 'https://nchsoftware.com/favicon.ico'),
  ('voice-av-voice-changer', 'AV Voice Changer Software', 'Advanced AI voice changing and audio editing suite with real-time processing and voice morphing.', 'https://audio4fun.com', 'voice-generation-conversion', 'Paid', ARRAY['voice-changing', 'audio-editing', 'voice-morphing'], false, false, 'https://audio4fun.com/favicon.ico'),
  ('voice-real-time-voice-swap', 'Real-Time Voice Swap', 'AI voice conversion technology that swaps voices in real-time during live conversations and calls.', 'https://github.com/AI-VoiceSwap/Real-Time-Voice-Swap', 'voice-generation-conversion', 'Free', ARRAY['voice-swap', 'real-time', 'live-conversations'], false, false, 'https://github.com/favicon.ico'),
  ('voice-nvidia-maxine', 'NVIDIA Maxine', 'AI platform for real-time voice and video processing with noise removal, voice effects, and enhancement.', 'https://developer.nvidia.com/maxine', 'voice-generation-conversion', 'Free', ARRAY['nvidia-ai', 'real-time-processing', 'voice-effects'], false, false, 'https://developer.nvidia.com/favicon.ico'),
  ('voice-krisp', 'Krisp', 'AI-powered noise cancellation and voice enhancement tool for clear communication in calls and recordings.', 'https://krisp.ai', 'voice-generation-conversion', 'Freemium', ARRAY['noise-cancellation', 'voice-enhancement', 'clear-communication'], false, false, 'https://krisp.ai/favicon.ico'),
  ('voice-rtx-voice', 'NVIDIA RTX Voice', 'AI noise suppression plugin that removes background noise from voice recordings and live calls.', 'https://nvidia.com/broadcast', 'voice-generation-conversion', 'Free', ARRAY['noise-suppression', 'background-removal', 'live-calls'], false, false, 'https://nvidia.com/favicon.ico'),
  
  -- Speech-to-Speech Translation
  ('voice-google-translate-voice', 'Google Translate Voice', 'AI-powered voice translation with real-time speech-to-speech conversion in 100+ languages.', 'https://translate.google.com', 'voice-generation-conversion', 'Free', ARRAY['voice-translation', 'speech-to-speech', '100-languages'], false, false, 'https://translate.google.com/favicon.ico'),
  ('voice-microsoft-translator-speech', 'Microsoft Translator Speech', 'AI speech translation service with real-time conversation translation and voice preservation.', 'https://translator.microsoft.com', 'voice-generation-conversion', 'Free', ARRAY['speech-translation', 'conversation-translation', 'voice-preservation'], false, false, 'https://translator.microsoft.com/favicon.ico'),
  ('voice-deepl-voice', 'DeepL Voice', 'AI-powered voice translation with high-accuracy speech-to-speech conversion and natural voice output.', 'https://deepl.com', 'voice-generation-conversion', 'Freemium', ARRAY['voice-translation', 'high-accuracy', 'natural-output'], false, false, 'https://deepl.com/favicon.ico'),
  ('voice-papago-voice', 'Papago Voice Translation', 'AI voice translation service specialized in Asian languages with real-time speech conversion.', 'https://papago.naver.com', 'voice-generation-conversion', 'Free', ARRAY['asian-languages', 'voice-translation', 'speech-conversion'], false, false, 'https://papago.naver.com/favicon.ico'),
  ('voice-bing-translator-speech', 'Bing Translator Speech', 'AI-powered speech translation with voice input and output in multiple languages for conversations.', 'https://bing.com/translator', 'voice-generation-conversion', 'Free', ARRAY['speech-translation', 'voice-input-output', 'conversations'], false, false, 'https://bing.com/favicon.ico'),
  ('voice-iTranslate-voice', 'iTranslate Voice', 'AI voice translation app with speech-to-speech conversion and offline translation capabilities.', 'https://itranslate.com', 'voice-generation-conversion', 'Freemium', ARRAY['voice-translation', 'speech-to-speech', 'offline-translation'], false, false, 'https://itranslate.com/favicon.ico'),
  ('voice-sayhi-translate', 'SayHi Translate', 'AI voice translator with real-time speech translation and natural voice output for conversations.', 'https://sayhi.com', 'voice-generation-conversion', 'Freemium', ARRAY['voice-translator', 'real-time', 'natural-voice'], false, false, 'https://sayhi.com/favicon.ico'),
  ('voice-vocre', 'Vocre', 'AI voice translation app with speech-to-speech conversion, offline mode, and conversation translation.', 'https://vocre.com', 'voice-generation-conversion', 'Freemium', ARRAY['voice-translation', 'offline-mode', 'conversation-translation'], false, false, 'https://vocre.com/favicon.ico'),
  ('voice-babel-fish', 'Babel Fish Voice', 'AI-powered universal voice translator with real-time speech conversion and accent preservation.', 'https://babelfish.com', 'voice-generation-conversion', 'Paid', ARRAY['universal-translator', 'speech-conversion', 'accent-preservation'], false, false, 'https://babelfish.com/favicon.ico'),
  ('voice-timekettle', 'Timekettle Translator', 'AI voice translation earbuds with real-time speech translation and noise cancellation technology.', 'https://timekettle.co', 'voice-generation-conversion', 'Paid', ARRAY['translation-earbuds', 'real-time-translation', 'noise-cancellation'], false, false, 'https://timekettle.co/favicon.ico'),
  
  -- Voice Acting & Character Voices
  ('voice-fakeyou', 'FakeYou', 'AI voice generation platform with celebrity voices, character voices, and text-to-speech for entertainment.', 'https://fakeyou.com', 'voice-generation-conversion', 'Freemium', ARRAY['celebrity-voices', 'character-voices', 'entertainment'], false, false, 'https://fakeyou.com/favicon.ico'),
  ('voice-uberduck', 'Uberduck', 'AI voice synthesis platform with celebrity voices, custom voice cloning, and API access for developers.', 'https://uberduck.ai', 'voice-generation-conversion', 'Freemium', ARRAY['voice-synthesis', 'celebrity-voices', 'api-access'], false, false, 'https://uberduck.ai/favicon.ico'),
  ('voice-15-ai', '15.ai', 'AI voice synthesis platform specializing in character voices from popular media and entertainment.', 'https://15.ai', 'voice-generation-conversion', 'Free', ARRAY['character-voices', 'media-voices', 'entertainment'], false, false, 'https://15.ai/favicon.ico'),
  ('voice-voiceful', 'Voiceful', 'AI voice acting platform with professional voice talent and synthetic voice generation for media production.', 'https://voiceful.io', 'voice-generation-conversion', 'Paid', ARRAY['voice-acting', 'professional-talent', 'media-production'], false, false, 'https://voiceful.io/favicon.ico'),
  ('voice-respeecher', 'Respeecher', 'AI voice cloning and synthesis platform for film, TV, and gaming with celebrity and character voices.', 'https://respeecher.com', 'voice-generation-conversion', 'Paid', ARRAY['voice-cloning', 'film-tv-gaming', 'celebrity-voices'], false, false, 'https://respeecher.com/favicon.ico'),
  ('voice-modulate', 'Modulate', 'AI voice conversion technology for real-time voice transformation in gaming and virtual environments.', 'https://modulate.ai', 'voice-generation-conversion', 'Paid', ARRAY['voice-conversion', 'real-time-transformation', 'gaming-virtual'], false, false, 'https://modulate.ai/favicon.ico'),
  ('voice-lyrebird', 'Lyrebird', 'AI voice cloning platform that creates synthetic voices from short audio samples for personalization.', 'https://lyrebird.ai', 'voice-generation-conversion', 'Paid', ARRAY['voice-cloning', 'synthetic-voices', 'personalization'], false, false, 'https://lyrebird.ai/favicon.ico'),
  ('voice-voicery', 'Voicery', 'AI text-to-speech platform with expressive voices and emotional control for storytelling and media.', 'https://voicery.com', 'voice-generation-conversion', 'Paid', ARRAY['expressive-voices', 'emotional-control', 'storytelling'], false, false, 'https://voicery.com/favicon.ico'),
  ('voice-cereproc', 'CereProc', 'AI speech synthesis with character voices, emotional expression, and custom voice development services.', 'https://cereproc.com', 'voice-generation-conversion', 'Paid', ARRAY['character-voices', 'emotional-expression', 'custom-development'], false, false, 'https://cereproc.com/favicon.ico'),
  ('voice-speechelo', 'Speechelo', 'AI text-to-speech software with human-like voices, breathing sounds, and pause control for video creation.', 'https://speechelo.com', 'voice-generation-conversion', 'Paid', ARRAY['human-like-voices', 'breathing-sounds', 'video-creation'], false, false, 'https://speechelo.com/favicon.ico'),
  
  -- Audiobook & Podcast AI
  ('voice-listening-audiobooks', 'Listening.com Audiobooks', 'AI-powered audiobook platform with voice synthesis and personalized reading experiences.', 'https://listening.com', 'voice-generation-conversion', 'Freemium', ARRAY['audiobook-platform', 'voice-synthesis', 'personalized-reading'], false, false, 'https://listening.com/favicon.ico'),
  ('voice-murf-audiobooks', 'Murf Audiobooks', 'AI audiobook creation platform with professional voices for self-publishing authors and content creators.', 'https://murf.ai/audiobooks', 'voice-generation-conversion', 'Paid', ARRAY['audiobook-creation', 'professional-voices', 'self-publishing'], false, false, 'https://murf.ai/favicon.ico'),
  ('voice-spotify-ai-dj', 'Spotify AI DJ', 'AI-powered DJ that creates personalized playlists with voice commentary and music recommendations.', 'https://spotify.com', 'voice-generation-conversion', 'Freemium', ARRAY['ai-dj', 'personalized-playlists', 'voice-commentary'], false, false, 'https://spotify.com/favicon.ico'),
  ('voice-podcast-ai', 'Podcast.ai', 'AI podcast generation platform that creates synthetic podcast episodes with realistic conversations.', 'https://podcast.ai', 'voice-generation-conversion', 'Freemium', ARRAY['podcast-generation', 'synthetic-episodes', 'realistic-conversations'], false, false, 'https://podcast.ai/favicon.ico'),
  ('voice-wondercraft', 'Wondercraft', 'AI podcast creation platform with voice cloning, script generation, and audio production tools.', 'https://wondercraft.ai', 'voice-generation-conversion', 'Freemium', ARRAY['podcast-creation', 'voice-cloning', 'script-generation'], false, false, 'https://wondercraft.ai/favicon.ico'),
  ('voice-castmagic', 'Castmagic', 'AI podcast post-production platform with voice enhancement, transcription, and content extraction.', 'https://castmagic.io', 'voice-generation-conversion', 'Paid', ARRAY['podcast-production', 'voice-enhancement', 'content-extraction'], false, false, 'https://castmagic.io/favicon.ico'),
  ('voice-podcastle', 'Podcastle', 'AI podcast creation studio with voice synthesis, noise removal, and collaborative editing features.', 'https://podcastle.ai', 'voice-generation-conversion', 'Freemium', ARRAY['podcast-studio', 'voice-synthesis', 'collaborative-editing'], false, false, 'https://podcastle.ai/favicon.ico'),
  ('voice-anchor-ai', 'Anchor AI', 'AI podcast hosting platform with voice enhancement, auto-transcription, and distribution tools.', 'https://anchor.fm', 'voice-generation-conversion', 'Free', ARRAY['podcast-hosting', 'voice-enhancement', 'auto-transcription'], false, false, 'https://anchor.fm/favicon.ico'),
  ('voice-riverside-ai', 'Riverside.fm AI', 'AI-powered podcast and video recording platform with voice enhancement and automatic editing.', 'https://riverside.fm', 'voice-generation-conversion', 'Paid', ARRAY['podcast-recording', 'voice-enhancement', 'automatic-editing'], false, false, 'https://riverside.fm/favicon.ico'),
  ('voice-descript-podcast', 'Descript Podcast', 'AI podcast editing platform with voice cloning, transcription, and collaborative editing features.', 'https://descript.com', 'voice-generation-conversion', 'Paid', ARRAY['podcast-editing', 'voice-cloning', 'collaborative-editing'], false, false, 'https://descript.com/favicon.ico'),
  
  -- Voice Assistants & AI Companions
  ('voice-custom-assistant', 'Custom Voice Assistant', 'AI platform for creating custom voice assistants with personalized voices and conversation capabilities.', 'https://customvoiceassistant.ai', 'voice-generation-conversion', 'Paid', ARRAY['custom-assistant', 'personalized-voices', 'conversation-ai'], false, false, 'https://customvoiceassistant.ai/favicon.ico'),
  ('voice-mycroft-ai', 'Mycroft AI', 'Open-source AI voice assistant with customizable voices, privacy protection, and smart home integration.', 'https://mycroft.ai', 'voice-generation-conversion', 'Free', ARRAY['open-source', 'voice-assistant', 'smart-home'], false, false, 'https://mycroft.ai/favicon.ico'),
  ('voice-jarvis-ai', 'Jarvis AI Voice', 'AI voice assistant with natural language processing, voice commands, and personalized responses.', 'https://jarvis.ai', 'voice-generation-conversion', 'Freemium', ARRAY['voice-assistant', 'natural-language', 'voice-commands'], false, false, 'https://jarvis.ai/favicon.ico'),
  ('voice-braina', 'Braina AI Assistant', 'AI voice assistant with speech recognition, voice commands, and natural language interaction.', 'https://brainasoft.com', 'voice-generation-conversion', 'Freemium', ARRAY['voice-assistant', 'speech-recognition', 'natural-language'], false, false, 'https://brainasoft.com/favicon.ico'),
  ('voice-alan-ai', 'Alan AI', 'AI voice assistant platform for adding voice interfaces to applications with natural conversation.', 'https://alan.app', 'voice-generation-conversion', 'Freemium', ARRAY['voice-interface', 'natural-conversation', 'app-integration'], false, false, 'https://alan.app/favicon.ico'),
  ('voice-voiceflow', 'Voiceflow', 'AI conversation design platform for creating voice assistants and chatbots with voice capabilities.', 'https://voiceflow.com', 'voice-generation-conversion', 'Freemium', ARRAY['conversation-design', 'voice-assistants', 'chatbots'], false, false, 'https://voiceflow.com/favicon.ico'),
  ('voice-botframework-speech', 'Bot Framework Speech', 'Microsoft AI platform for building voice-enabled bots with speech recognition and synthesis.', 'https://dev.botframework.com', 'voice-generation-conversion', 'Freemium', ARRAY['voice-bots', 'speech-recognition', 'microsoft-ai'], false, false, 'https://dev.botframework.com/favicon.ico'),
  ('voice-dialogflow-speech', 'Dialogflow Speech', 'Google AI platform for building conversational interfaces with voice input and output capabilities.', 'https://dialogflow.cloud.google.com', 'voice-generation-conversion', 'Freemium', ARRAY['conversational-ai', 'voice-input-output', 'google-ai'], false, false, 'https://dialogflow.cloud.google.com/favicon.ico'),
  ('voice-lex-speech', 'Amazon Lex Speech', 'AWS AI service for building conversational interfaces with voice and text input/output.', 'https://aws.amazon.com/lex', 'voice-generation-conversion', 'Paid', ARRAY['conversational-interfaces', 'voice-text', 'aws-ai'], false, false, 'https://aws.amazon.com/favicon.ico'),
  ('voice-rasa-voice', 'Rasa Voice', 'Open-source AI framework for building voice assistants with natural language understanding and generation.', 'https://rasa.com', 'voice-generation-conversion', 'Free', ARRAY['open-source', 'voice-assistants', 'natural-language'], false, false, 'https://rasa.com/favicon.ico'),
  
  -- Music & Singing Voice AI
  ('voice-suno-ai', 'Suno AI', 'AI music and singing voice generation platform that creates original songs with AI-generated vocals.', 'https://suno.ai', 'voice-generation-conversion', 'Freemium', ARRAY['music-generation', 'singing-voice', 'original-songs'], false, false, 'https://suno.ai/favicon.ico'),
  ('voice-lalal-ai', 'LALAL.AI', 'AI vocal and instrumental track separation with voice isolation and music source separation.', 'https://lalal.ai', 'voice-generation-conversion', 'Freemium', ARRAY['vocal-separation', 'voice-isolation', 'music-separation'], false, false, 'https://lalal.ai/favicon.ico'),
  ('voice-synthesizer-v', 'Synthesizer V', 'AI singing voice synthesis software with realistic vocal generation and multilingual support.', 'https://dreamtonics.com/synthesizerv', 'voice-generation-conversion', 'Paid', ARRAY['singing-synthesis', 'realistic-vocals', 'multilingual'], false, false, 'https://dreamtonics.com/favicon.ico'),
  ('voice-vocaloid', 'VOCALOID', 'AI singing voice synthesis technology with virtual singers and vocal generation capabilities.', 'https://vocaloid.com', 'voice-generation-conversion', 'Paid', ARRAY['singing-synthesis', 'virtual-singers', 'vocal-generation'], false, false, 'https://vocaloid.com/favicon.ico'),
  ('voice-ace-studio', 'ACE Studio', 'AI singing voice synthesis platform with natural vocal generation and music production tools.', 'https://acestudio.ai', 'voice-generation-conversion', 'Freemium', ARRAY['singing-synthesis', 'natural-vocals', 'music-production'], false, false, 'https://acestudio.ai/favicon.ico'),
  ('voice-diffsinger', 'DiffSinger', 'AI singing voice synthesis model with high-quality vocal generation and pitch control.', 'https://github.com/MoonInTheRiver/DiffSinger', 'voice-generation-conversion', 'Free', ARRAY['singing-synthesis', 'high-quality', 'pitch-control'], false, false, 'https://github.com/favicon.ico'),
  ('voice-openutau', 'OpenUTAU', 'Open-source AI singing voice synthesis software with custom voice banks and vocal editing.', 'https://openutau.com', 'voice-generation-conversion', 'Free', ARRAY['open-source', 'singing-synthesis', 'vocal-editing'], false, false, 'https://openutau.com/favicon.ico'),
  ('voice-cevio', 'CeVIO', 'AI speech and singing synthesis software with character voices and emotional expression.', 'https://cevio.jp', 'voice-generation-conversion', 'Paid', ARRAY['speech-singing', 'character-voices', 'emotional-expression'], false, false, 'https://cevio.jp/favicon.ico'),
  ('voice-voiceroid', 'VOICEROID', 'AI text-to-speech software with character voices and natural speech synthesis for Japanese content.', 'https://voiceroid.com', 'voice-generation-conversion', 'Paid', ARRAY['character-voices', 'natural-speech', 'japanese-content'], false, false, 'https://voiceroid.com/favicon.ico'),
  ('voice-neutrino', 'NEUTRINO', 'AI singing voice synthesis system with neural network-based vocal generation and music production.', 'https://n3utrino.work', 'voice-generation-conversion', 'Free', ARRAY['neural-network', 'vocal-generation', 'music-production'], false, false, 'https://n3utrino.work/favicon.ico'),
  
  -- Voice Analytics & Processing
  ('voice-speechmatics', 'Speechmatics', 'AI speech recognition and voice analytics platform with real-time transcription and language detection.', 'https://speechmatics.com', 'voice-generation-conversion', 'Paid', ARRAY['speech-recognition', 'voice-analytics', 'language-detection'], false, false, 'https://speechmatics.com/favicon.ico'),
  ('voice-rev-ai', 'Rev.ai', 'AI speech-to-text API with voice recognition, speaker identification, and audio intelligence features.', 'https://rev.ai', 'voice-generation-conversion', 'Paid', ARRAY['speech-to-text', 'speaker-identification', 'audio-intelligence'], false, false, 'https://rev.ai/favicon.ico'),
  ('voice-deepgram', 'Deepgram', 'AI speech recognition platform with real-time transcription, voice analytics, and natural language processing.', 'https://deepgram.com', 'voice-generation-conversion', 'Paid', ARRAY['speech-recognition', 'real-time-transcription', 'voice-analytics'], false, false, 'https://deepgram.com/favicon.ico'),
  ('voice-assemblyai', 'AssemblyAI', 'AI speech recognition and audio intelligence platform with transcription, sentiment analysis, and topic detection.', 'https://assemblyai.com', 'voice-generation-conversion', 'Paid', ARRAY['speech-recognition', 'sentiment-analysis', 'topic-detection'], false, false, 'https://assemblyai.com/favicon.ico'),
  ('voice-otter-ai', 'Otter.ai', 'AI transcription service with real-time voice recognition, speaker identification, and meeting notes.', 'https://otter.ai', 'voice-generation-conversion', 'Freemium', ARRAY['transcription-service', 'speaker-identification', 'meeting-notes'], false, false, 'https://otter.ai/favicon.ico'),
  ('voice-verbit', 'Verbit', 'AI transcription platform with voice recognition, live captioning, and accessibility solutions.', 'https://verbit.ai', 'voice-generation-conversion', 'Paid', ARRAY['transcription-platform', 'live-captioning', 'accessibility'], false, false, 'https://verbit.ai/favicon.ico'),
  ('voice-sonix', 'Sonix', 'AI transcription service with voice recognition, automated subtitles, and translation capabilities.', 'https://sonix.ai', 'voice-generation-conversion', 'Paid', ARRAY['transcription-service', 'automated-subtitles', 'translation'], false, false, 'https://sonix.ai/favicon.ico'),
  ('voice-trint', 'Trint', 'AI transcription platform with voice recognition, collaborative editing, and content search features.', 'https://trint.com', 'voice-generation-conversion', 'Paid', ARRAY['transcription-platform', 'collaborative-editing', 'content-search'], false, false, 'https://trint.com/favicon.ico'),
  ('voice-descript-transcription', 'Descript Transcription', 'AI transcription service with voice recognition, automatic punctuation, and speaker identification.', 'https://descript.com', 'voice-generation-conversion', 'Freemium', ARRAY['transcription-service', 'automatic-punctuation', 'speaker-identification'], false, false, 'https://descript.com/favicon.ico'),
  ('voice-happy-scribe', 'Happy Scribe', 'AI transcription and subtitle service with voice recognition, translation, and editing tools.', 'https://happyscribe.com', 'voice-generation-conversion', 'Paid', ARRAY['transcription-subtitles', 'voice-recognition', 'editing-tools'], false, false, 'https://happyscribe.com/favicon.ico'),
  
  -- Voice Training & Education
  ('voice-orai', 'Orai', 'AI speech coach that analyzes voice patterns, provides feedback, and helps improve public speaking skills.', 'https://orai.com', 'voice-generation-conversion', 'Freemium', ARRAY['speech-coach', 'voice-analysis', 'public-speaking'], false, false, 'https://orai.com/favicon.ico'),
  ('voice-speeko', 'Speeko', 'AI public speaking coach with voice analysis, presentation feedback, and communication training.', 'https://speeko.co', 'voice-generation-conversion', 'Freemium', ARRAY['speaking-coach', 'voice-analysis', 'communication-training'], false, false, 'https://speeko.co/favicon.ico'),
  ('voice-yoodli', 'Yoodli', 'AI speech coach for improving communication skills with real-time feedback and voice analysis.', 'https://yoodli.ai', 'voice-generation-conversion', 'Freemium', ARRAY['speech-coach', 'real-time-feedback', 'communication-skills'], false, false, 'https://yoodli.ai/favicon.ico'),
  ('voice-ummo', 'Ummo Speech Coach', 'AI speech training app with voice analysis, pace tracking, and presentation improvement tools.', 'https://ummo.com', 'voice-generation-conversion', 'Freemium', ARRAY['speech-training', 'pace-tracking', 'presentation-improvement'], false, false, 'https://ummo.com/favicon.ico'),
  ('voice-voice-analyst', 'Voice Analyst', 'AI voice analysis platform for speech therapy, accent reduction, and pronunciation improvement.', 'https://voiceanalyst.co', 'voice-generation-conversion', 'Paid', ARRAY['voice-analysis', 'speech-therapy', 'accent-reduction'], false, false, 'https://voiceanalyst.co/favicon.ico'),
  ('voice-pronunciation-coach', 'Pronunciation Coach AI', 'AI pronunciation training platform with voice recognition and accent improvement features.', 'https://pronunciationcoach.ai', 'voice-generation-conversion', 'Freemium', ARRAY['pronunciation-training', 'accent-improvement', 'voice-recognition'], false, false, 'https://pronunciationcoach.ai/favicon.ico'),
  ('voice-elsa-speak', 'ELSA Speak', 'AI English pronunciation coach with voice recognition and personalized accent training.', 'https://elsaspeak.com', 'voice-generation-conversion', 'Freemium', ARRAY['pronunciation-coach', 'accent-training', 'english-learning'], false, false, 'https://elsaspeak.com/favicon.ico'),
  ('voice-speechling', 'Speechling', 'AI language learning platform with pronunciation feedback and voice analysis for multiple languages.', 'https://speechling.com', 'voice-generation-conversion', 'Freemium', ARRAY['language-learning', 'pronunciation-feedback', 'voice-analysis'], false, false, 'https://speechling.com/favicon.ico'),
  ('voice-sounds-pronunciation', 'Sounds Pronunciation', 'AI pronunciation app with voice recognition, phonetic training, and accent improvement for English.', 'https://soundspronunciation.com', 'voice-generation-conversion', 'Paid', ARRAY['pronunciation-app', 'phonetic-training', 'accent-improvement'], false, false, 'https://soundspronunciation.com/favicon.ico'),
  ('voice-cambly-ai', 'Cambly AI Voice', 'AI conversation practice platform with voice analysis and pronunciation feedback for language learners.', 'https://cambly.com', 'voice-generation-conversion', 'Paid', ARRAY['conversation-practice', 'pronunciation-feedback', 'language-learning'], false, false, 'https://cambly.com/favicon.ico')
ON CONFLICT (id, category_id) DO NOTHING;

-- Update the tool count for the category
UPDATE categories 
SET tool_count = (
  SELECT COUNT(*) 
  FROM tools 
  WHERE category_id = 'voice-generation-conversion'
) 
WHERE id = 'voice-generation-conversion';
