-- Add Automations category and tools
-- This script adds a new category for automation tools and populates it with automation platforms

-- Add the category
INSERT INTO categories (
  id, name, description, icon, color, tool_count
) VALUES (
  'automations', 
  'Automations', 
  'AI tools for workflow automation and task optimization', 
  '🤖', 
  'from-purple-500 to-pink-500', 
  0
)
ON CONFLICT (id) DO NOTHING;

-- Add automation tools
INSERT INTO tools (
  id, name, description, url, category_id, 
  pricing, tags, featured, trending, logo_url
) VALUES 
  ('automation-n8n', 'n8n', 'Automate tasks across different services and applications using a visual workflow builder and custom code integration.', 'https://n8n.io', 'automations', 'Freemium', ARRAY['workflow-automation', 'visual-builder', 'custom-code'], false, true, 'https://n8n.io/favicon.ico'),
  ('automation-make', 'Make.com', 'Create complex automated workflows with conditional logic and custom HTTP requests across various services and applications.', 'https://make.com', 'automations', 'Freemium', ARRAY['workflow-automation', 'conditional-logic', 'http-requests'], false, true, 'https://make.com/favicon.ico'),
  ('automation-pabbly', 'Pabbly Connect', 'Automation tool for connecting apps and automating workflows with multi-step integrations and data synchronization.', 'https://pabbly.com/connect', 'automations', 'Freemium', ARRAY['app-integration', 'workflow-automation', 'data-sync'], false, false, 'https://pabbly.com/favicon.ico'),
  ('automation-ifttt', 'IFTTT', 'Automate tasks across various web services and devices using simple conditional statements and trigger-action workflows.', 'https://ifttt.com', 'automations', 'Freemium', ARRAY['conditional-automation', 'web-services', 'iot-devices'], false, true, 'https://ifttt.com/favicon.ico'),
  ('automation-zapier', 'Zapier', 'Integrate various business tools and automate repetitive tasks across different apps and services with no-code workflows.', 'https://zapier.com', 'automations', 'Freemium', ARRAY['business-integration', 'no-code', 'app-automation'], true, true, 'https://zapier.com/favicon.ico'),
  ('automation-huginn', 'Huginn', 'Create automated agents to perform tasks based on events and filters across different online services and data sources.', 'https://github.com/huginn/huginn', 'automations', 'Free', ARRAY['automated-agents', 'event-based', 'open-source'], false, false, 'https://github.com/favicon.ico'),
  ('automation-ui-vision', 'UI Vision RPA', 'Automate web and desktop applications using a visual interface for creating robotic process automation workflows.', 'https://ui.vision', 'automations', 'Freemium', ARRAY['rpa', 'desktop-automation', 'visual-interface'], false, false, 'https://ui.vision/favicon.ico'),
  ('automation-node-red', 'Node-RED', 'Create automated workflows for IoT applications using a visual interface to connect hardware devices, APIs, and online services.', 'https://nodered.org', 'automations', 'Free', ARRAY['iot-automation', 'visual-workflows', 'hardware-integration'], false, false, 'https://nodered.org/favicon.ico'),
  ('automation-airflow', 'Apache Airflow', 'Manage and automate complex data engineering pipelines and workflows across various systems and applications.', 'https://airflow.apache.org', 'automations', 'Free', ARRAY['data-pipelines', 'workflow-management', 'data-engineering'], false, true, 'https://airflow.apache.org/favicon.ico'),
  ('automation-workato', 'Workato', 'Automate business processes and workflows using a drag-and-drop interface and AI-powered bots across different applications and services.', 'https://workato.com', 'automations', 'Paid', ARRAY['business-automation', 'ai-powered', 'drag-and-drop'], false, true, 'https://workato.com/favicon.ico'),
  ('automation-tray', 'Tray.io', 'Automate business processes using a visual workflow builder, data mapping, and workflow triggers with enterprise-level security and compliance.', 'https://tray.io', 'automations', 'Paid', ARRAY['enterprise-automation', 'data-mapping', 'compliance'], false, false, 'https://tray.io/favicon.ico'),  ('automation-power-automate', 'Microsoft Power Automate', 'Automate workflows between apps and services, integrating seamlessly with Office 365 tools to streamline business processes.', 'https://powerautomate.microsoft.com', 'automations', 'Freemium', ARRAY['microsoft-integration', 'office-365', 'business-workflows'], true, true, 'https://powerautomate.microsoft.com/favicon.ico'),
  ('automation-botpress', 'Botpress', 'Build and deploy AI-powered chatbots with automated conversation flows and natural language processing capabilities.', 'https://botpress.com', 'automations', 'Freemium', ARRAY['chatbot-automation', 'nlp', 'conversation-flows'], false, true, 'https://botpress.com/favicon.ico'),
  ('automation-activepieces', 'Activepieces', 'Create automated workflows with AI-powered integrations and custom logic for business process optimization.', 'https://activepieces.com', 'automations', 'Freemium', ARRAY['ai-workflows', 'business-process', 'custom-logic'], false, false, 'https://activepieces.com/favicon.ico'),
  ('automation-typeform', 'Typeform Connect', 'Automate form responses and data collection with AI-powered analysis and workflow triggers.', 'https://typeform.com', 'automations', 'Freemium', ARRAY['form-automation', 'data-collection', 'response-analysis'], false, false, 'https://typeform.com/favicon.ico'),
  ('automation-calendly', 'Calendly Automation', 'Automate scheduling workflows with AI-powered meeting optimization and follow-up sequences.', 'https://calendly.com', 'automations', 'Freemium', ARRAY['scheduling-automation', 'meeting-optimization', 'follow-up'], false, true, 'https://calendly.com/favicon.ico'),
  ('automation-hubspot', 'HubSpot Workflows', 'Automate marketing, sales, and customer service processes with AI-driven lead scoring and nurturing.', 'https://hubspot.com', 'automations', 'Freemium', ARRAY['marketing-automation', 'lead-scoring', 'crm-automation'], false, true, 'https://hubspot.com/favicon.ico'),
  ('automation-mailchimp', 'Mailchimp Automation', 'Create automated email marketing campaigns with AI-powered content optimization and audience segmentation.', 'https://mailchimp.com', 'automations', 'Freemium', ARRAY['email-automation', 'content-optimization', 'audience-segmentation'], false, true, 'https://mailchimp.com/favicon.ico'),
  ('automation-buffer', 'Buffer Automation', 'Automate social media posting and engagement with AI-powered content scheduling and performance analysis.', 'https://buffer.com', 'automations', 'Freemium', ARRAY['social-media-automation', 'content-scheduling', 'performance-analysis'], false, false, 'https://buffer.com/favicon.ico'),
  ('automation-hootsuite', 'Hootsuite Automation', 'Streamline social media management with automated posting, monitoring, and AI-driven content suggestions.', 'https://hootsuite.com', 'automations', 'Freemium', ARRAY['social-media-management', 'automated-posting', 'content-suggestions'], false, true, 'https://hootsuite.com/favicon.ico'),
  ('automation-later', 'Later Automation', 'Automate Instagram, Facebook, and Pinterest posting with AI-powered optimal timing and hashtag suggestions.', 'https://later.com', 'automations', 'Freemium', ARRAY['instagram-automation', 'posting-optimization', 'hashtag-suggestions'], false, false, 'https://later.com/favicon.ico'),
  ('automation-sprout-social', 'Sprout Social', 'Automate social media workflows with AI-powered analytics, scheduling, and customer engagement tools.', 'https://sproutsocial.com', 'automations', 'Paid', ARRAY['social-analytics', 'engagement-automation', 'customer-service'], false, false, 'https://sproutsocial.com/favicon.ico'),
  ('automation-phantom-buster', 'PhantomBuster', 'Automate lead generation and data extraction from social media platforms using AI-powered web scraping.', 'https://phantombuster.com', 'automations', 'Freemium', ARRAY['lead-generation', 'data-extraction', 'web-scraping'], false, true, 'https://phantombuster.com/favicon.ico'),
  ('automation-lemlist', 'Lemlist', 'Automate personalized cold email outreach campaigns with AI-powered message customization and follow-up sequences.', 'https://lemlist.com', 'automations', 'Paid', ARRAY['email-outreach', 'personalization', 'cold-email'], false, true, 'https://lemlist.com/favicon.ico'),
  ('automation-outreach', 'Outreach.io', 'Automate sales engagement processes with AI-driven prospect scoring and personalized communication sequences.', 'https://outreach.io', 'automations', 'Paid', ARRAY['sales-automation', 'prospect-scoring', 'engagement-sequences'], false, false, 'https://outreach.io/favicon.ico'),
  ('automation-salesloft', 'SalesLoft', 'Streamline sales workflows with automated cadences, AI-powered conversation intelligence, and pipeline management.', 'https://salesloft.com', 'automations', 'Paid', ARRAY['sales-cadences', 'conversation-intelligence', 'pipeline-automation'], false, false, 'https://salesloft.com/favicon.ico'),
  ('automation-pipedrive', 'Pipedrive Automation', 'Automate CRM workflows with AI-powered deal insights, activity reminders, and sales process optimization.', 'https://pipedrive.com', 'automations', 'Freemium', ARRAY['crm-automation', 'deal-insights', 'sales-optimization'], false, true, 'https://pipedrive.com/favicon.ico'),
  ('automation-intercom', 'Intercom Automation', 'Automate customer support and engagement with AI-powered chatbots and workflow triggers.', 'https://intercom.com', 'automations', 'Freemium', ARRAY['customer-support', 'chatbot-flows', 'engagement-automation'], false, true, 'https://intercom.com/favicon.ico'),
  ('automation-zendesk', 'Zendesk Automation', 'Streamline customer service workflows with automated ticket routing, AI-powered responses, and escalation rules.', 'https://zendesk.com', 'automations', 'Freemium', ARRAY['ticket-automation', 'ai-responses', 'escalation-rules'], false, false, 'https://zendesk.com/favicon.ico'),
  ('automation-freshworks', 'Freshworks Automation', 'Automate customer lifecycle management with AI-driven lead scoring, nurturing campaigns, and support workflows.', 'https://freshworks.com', 'automations', 'Freemium', ARRAY['lifecycle-management', 'lead-nurturing', 'support-automation'], false, false, 'https://freshworks.com/favicon.ico'),
  ('automation-monday', 'Monday.com Automation', 'Create automated project workflows with AI-powered task assignment, progress tracking, and team collaboration.', 'https://monday.com', 'automations', 'Freemium', ARRAY['project-automation', 'task-assignment', 'team-collaboration'], false, true, 'https://monday.com/favicon.ico'),
  ('automation-asana', 'Asana Automation', 'Streamline project management with automated task dependencies, progress updates, and team notifications.', 'https://asana.com', 'automations', 'Freemium', ARRAY['project-management', 'task-dependencies', 'progress-automation'], false, true, 'https://asana.com/favicon.ico'),
  ('automation-trello', 'Trello Automation', 'Automate Kanban workflows with Butler automation rules, card movements, and deadline notifications.', 'https://trello.com', 'automations', 'Freemium', ARRAY['kanban-automation', 'card-workflows', 'deadline-tracking'], false, false, 'https://trello.com/favicon.ico'),
  ('automation-notion', 'Notion Automation', 'Create automated databases and workflows with AI-powered content generation and task management.', 'https://notion.so', 'automations', 'Freemium', ARRAY['database-automation', 'content-generation', 'workspace-automation'], false, true, 'https://notion.so/favicon.ico'),
  ('automation-airtable', 'Airtable Automation', 'Automate database workflows with trigger-based actions, AI-powered data analysis, and integration capabilities.', 'https://airtable.com', 'automations', 'Freemium', ARRAY['database-workflows', 'trigger-actions', 'data-analysis'], false, true, 'https://airtable.com/favicon.ico'),
  ('automation-smartsheet', 'Smartsheet Automation', 'Streamline project workflows with automated approvals, notifications, and AI-driven insights.', 'https://smartsheet.com', 'automations', 'Paid', ARRAY['approval-workflows', 'automated-notifications', 'project-insights'], false, false, 'https://smartsheet.com/favicon.ico'),
  ('automation-clickup', 'ClickUp Automation', 'Automate task management and project workflows with AI-powered time tracking and productivity optimization.', 'https://clickup.com', 'automations', 'Freemium', ARRAY['task-automation', 'time-tracking', 'productivity-optimization'], false, true, 'https://clickup.com/favicon.ico'),
  ('automation-slack', 'Slack Workflow Builder', 'Create automated team communication workflows with AI-powered message routing and response triggers.', 'https://slack.com', 'automations', 'Freemium', ARRAY['team-communication', 'message-routing', 'workflow-builder'], false, true, 'https://slack.com/favicon.ico'),
  ('automation-microsoft-teams', 'Microsoft Teams Automation', 'Automate team collaboration with AI-powered meeting summaries, task assignments, and workflow integration.', 'https://teams.microsoft.com', 'automations', 'Freemium', ARRAY['team-collaboration', 'meeting-automation', 'task-integration'], false, false, 'https://teams.microsoft.com/favicon.ico'),
  ('automation-discord', 'Discord Bots', 'Create automated Discord server management with AI-powered moderation, welcome messages, and community engagement.', 'https://discord.com', 'automations', 'Free', ARRAY['server-automation', 'moderation-bots', 'community-management'], false, false, 'https://discord.com/favicon.ico'),
  ('automation-telegram', 'Telegram Bot API', 'Build automated Telegram bots with AI-powered conversation flows, command processing, and notification systems.', 'https://telegram.org', 'automations', 'Free', ARRAY['telegram-bots', 'conversation-automation', 'notification-systems'], false, false, 'https://telegram.org/favicon.ico'),
  ('automation-whatsapp-business', 'WhatsApp Business API', 'Automate customer communication with AI-powered chatbots, message templates, and business workflow integration.', 'https://business.whatsapp.com', 'automations', 'Freemium', ARRAY['whatsapp-automation', 'customer-communication', 'business-integration'], false, true, 'https://business.whatsapp.com/favicon.ico'),
  ('automation-twilio', 'Twilio Automation', 'Automate SMS, voice, and communication workflows with AI-powered message routing and customer engagement.', 'https://twilio.com', 'automations', 'Paid', ARRAY['sms-automation', 'voice-workflows', 'communication-apis'], false, false, 'https://twilio.com/favicon.ico'),
  ('automation-sendgrid', 'SendGrid Automation', 'Automate email delivery and marketing campaigns with AI-powered deliverability optimization and analytics.', 'https://sendgrid.com', 'automations', 'Freemium', ARRAY['email-delivery', 'deliverability-optimization', 'email-analytics'], false, false, 'https://sendgrid.com/favicon.ico'),
  ('automation-mailgun', 'Mailgun Automation', 'Streamline transactional email workflows with automated delivery, tracking, and AI-powered spam detection.', 'https://mailgun.com', 'automations', 'Paid', ARRAY['transactional-email', 'delivery-automation', 'spam-detection'], false, false, 'https://mailgun.com/favicon.ico'),
  ('automation-convertkit', 'ConvertKit Automation', 'Automate email marketing sequences with AI-powered subscriber segmentation and content personalization.', 'https://convertkit.com', 'automations', 'Freemium', ARRAY['email-sequences', 'subscriber-segmentation', 'content-personalization'], false, false, 'https://convertkit.com/favicon.ico'),
  ('automation-activecampaign', 'ActiveCampaign', 'Create automated marketing workflows with AI-powered customer journey mapping and behavioral triggers.', 'https://activecampaign.com', 'automations', 'Freemium', ARRAY['marketing-workflows', 'journey-mapping', 'behavioral-triggers'], false, true, 'https://activecampaign.com/favicon.ico'),
  ('automation-drip', 'Drip Automation', 'Automate e-commerce email marketing with AI-powered product recommendations and customer lifecycle campaigns.', 'https://drip.com', 'automations', 'Freemium', ARRAY['ecommerce-automation', 'product-recommendations', 'lifecycle-campaigns'], false, false, 'https://drip.com/favicon.ico'),
  ('automation-klaviyo', 'Klaviyo', 'Streamline e-commerce marketing automation with AI-driven customer segmentation and predictive analytics.', 'https://klaviyo.com', 'automations', 'Freemium', ARRAY['ecommerce-marketing', 'customer-segmentation', 'predictive-analytics'], false, true, 'https://klaviyo.com/favicon.ico'),
  ('automation-omnisend', 'Omnisend', 'Automate omnichannel marketing campaigns with AI-powered cross-platform messaging and customer insights.', 'https://omnisend.com', 'automations', 'Freemium', ARRAY['omnichannel-marketing', 'cross-platform-messaging', 'customer-insights'], false, false, 'https://omnisend.com/favicon.ico'),
  ('automation-sendinblue', 'Brevo (Sendinblue)', 'Create automated marketing workflows with AI-powered email optimization, SMS campaigns, and CRM integration.', 'https://brevo.com', 'automations', 'Freemium', ARRAY['marketing-optimization', 'sms-campaigns', 'crm-integration'], false, false, 'https://brevo.com/favicon.ico'),
  ('automation-getresponse', 'GetResponse', 'Automate email marketing and webinar workflows with AI-powered content suggestions and audience targeting.', 'https://getresponse.com', 'automations', 'Freemium', ARRAY['email-marketing', 'webinar-automation', 'audience-targeting'], false, false, 'https://getresponse.com/favicon.ico'),
  ('automation-aweber', 'AWeber', 'Streamline email automation with AI-powered subject line optimization and subscriber engagement tracking.', 'https://aweber.com', 'automations', 'Freemium', ARRAY['email-automation', 'subject-optimization', 'engagement-tracking'], false, false, 'https://aweber.com/favicon.ico'),
  ('automation-constant-contact', 'Constant Contact', 'Automate small business marketing with AI-powered email campaigns, social media posting, and event management.', 'https://constantcontact.com', 'automations', 'Freemium', ARRAY['small-business-marketing', 'social-posting', 'event-automation'], false, false, 'https://constantcontact.com/favicon.ico'),
  ('automation-campaign-monitor', 'Campaign Monitor', 'Create automated email marketing campaigns with AI-driven personalization and performance optimization.', 'https://campaignmonitor.com', 'automations', 'Freemium', ARRAY['email-campaigns', 'personalization', 'performance-optimization'], false, false, 'https://campaignmonitor.com/favicon.ico'),
  ('automation-emma', 'Emma Email Marketing', 'Automate email workflows with AI-powered content curation, A/B testing, and subscriber journey optimization.', 'https://myemma.com', 'automations', 'Paid', ARRAY['content-curation', 'ab-testing', 'journey-optimization'], false, false, 'https://myemma.com/favicon.ico'),
  ('automation-pardot', 'Salesforce Pardot', 'Streamline B2B marketing automation with AI-powered lead scoring, nurturing campaigns, and sales alignment.', 'https://pardot.com', 'automations', 'Paid', ARRAY['b2b-marketing', 'lead-scoring', 'sales-alignment'], false, false, 'https://pardot.com/favicon.ico'),
  ('automation-marketo', 'Adobe Marketo Engage', 'Automate enterprise marketing workflows with AI-driven customer engagement and revenue attribution.', 'https://marketo.com', 'automations', 'Paid', ARRAY['enterprise-marketing', 'customer-engagement', 'revenue-attribution'], false, false, 'https://marketo.com/favicon.ico'),
  ('automation-eloqua', 'Oracle Eloqua', 'Create sophisticated marketing automation campaigns with AI-powered lead management and cross-channel orchestration.', 'https://eloqua.com', 'automations', 'Paid', ARRAY['lead-management', 'cross-channel-orchestration', 'enterprise-automation'], false, false, 'https://eloqua.com/favicon.ico'),
  ('automation-act-on', 'Act-On', 'Automate marketing processes with AI-powered behavioral tracking, lead nurturing, and campaign optimization.', 'https://act-on.com', 'automations', 'Paid', ARRAY['behavioral-tracking', 'lead-nurturing', 'campaign-optimization'], false, false, 'https://act-on.com/favicon.ico'),
  ('automation-sharpspring', 'SharpSpring', 'Streamline marketing and sales automation with AI-driven lead tracking, email workflows, and CRM integration.', 'https://sharpspring.com', 'automations', 'Paid', ARRAY['lead-tracking', 'email-workflows', 'marketing-sales-alignment'], false, false, 'https://sharpspring.com/favicon.ico'),
  ('automation-ontraport', 'Ontraport', 'Automate business processes with AI-powered CRM, email marketing, and e-commerce workflow integration.', 'https://ontraport.com', 'automations', 'Paid', ARRAY['business-automation', 'crm-workflows', 'ecommerce-integration'], false, false, 'https://ontraport.com/favicon.ico'),
  ('automation-infusionsoft', 'Keap (Infusionsoft)', 'Create automated small business workflows with AI-powered contact management, sales pipelines, and marketing campaigns.', 'https://keap.com', 'automations', 'Paid', ARRAY['small-business-workflows', 'contact-management', 'sales-pipelines'], false, false, 'https://keap.com/favicon.ico'),
  ('automation-autopilot', 'Ortto (Autopilot)', 'Automate customer journey workflows with AI-powered multi-channel messaging and behavioral analytics.', 'https://ortto.com', 'automations', 'Freemium', ARRAY['customer-journey', 'multi-channel-messaging', 'behavioral-analytics'], false, false, 'https://ortto.com/favicon.ico'),
  ('automation-customer-io', 'Customer.io', 'Streamline automated messaging workflows with AI-powered customer segmentation and event-triggered campaigns.', 'https://customer.io', 'automations', 'Freemium', ARRAY['automated-messaging', 'customer-segmentation', 'event-triggered'], false, true, 'https://customer.io/favicon.ico'),
  ('automation-mixpanel', 'Mixpanel Automation', 'Automate product analytics workflows with AI-powered user behavior tracking and engagement optimization.', 'https://mixpanel.com', 'automations', 'Freemium', ARRAY['product-analytics', 'behavior-tracking', 'engagement-optimization'], false, false, 'https://mixpanel.com/favicon.ico'),
  ('automation-amplitude', 'Amplitude Automation', 'Create automated product insights workflows with AI-driven user journey analysis and retention optimization.', 'https://amplitude.com', 'automations', 'Freemium', ARRAY['product-insights', 'user-journey-analysis', 'retention-optimization'], false, false, 'https://amplitude.com/favicon.ico'),
  ('automation-segment', 'Twilio Segment', 'Automate customer data workflows with AI-powered data collection, transformation, and activation across platforms.', 'https://segment.com', 'automations', 'Freemium', ARRAY['customer-data', 'data-transformation', 'cross-platform-activation'], false, false, 'https://segment.com/favicon.ico'),
  ('automation-rudderstack', 'RudderStack', 'Streamline customer data automation with AI-powered event streaming, data transformation, and privacy compliance.', 'https://rudderstack.com', 'automations', 'Freemium', ARRAY['event-streaming', 'data-transformation', 'privacy-compliance'], false, false, 'https://rudderstack.com/favicon.ico'),
  ('automation-snowplow', 'Snowplow Analytics', 'Automate behavioral data collection with AI-powered event tracking, data modeling, and real-time processing.', 'https://snowplow.io', 'automations', 'Freemium', ARRAY['behavioral-data', 'event-tracking', 'real-time-processing'], false, false, 'https://snowplow.io/favicon.ico'),
  ('automation-google-analytics', 'Google Analytics Intelligence', 'Automate web analytics insights with AI-powered anomaly detection, automated reporting, and predictive metrics.', 'https://analytics.google.com', 'automations', 'Freemium', ARRAY['web-analytics', 'anomaly-detection', 'predictive-metrics'], false, true, 'https://analytics.google.com/favicon.ico'),
  ('automation-hotjar', 'Hotjar Automation', 'Streamline user experience analysis with automated heatmap generation, session recordings, and feedback collection.', 'https://hotjar.com', 'automations', 'Freemium', ARRAY['ux-analysis', 'heatmap-automation', 'feedback-collection'], false, false, 'https://hotjar.com/favicon.ico'),
  ('automation-fullstory', 'FullStory', 'Automate digital experience analytics with AI-powered session capture, user journey mapping, and conversion optimization.', 'https://fullstory.com', 'automations', 'Paid', ARRAY['digital-experience', 'session-capture', 'conversion-optimization'], false, false, 'https://fullstory.com/favicon.ico'),
  ('automation-logrocket', 'LogRocket', 'Create automated frontend monitoring workflows with AI-powered error detection, performance analysis, and user session replay.', 'https://logrocket.com', 'automations', 'Freemium', ARRAY['frontend-monitoring', 'error-detection', 'session-replay'], false, false, 'https://logrocket.com/favicon.ico'),
  ('automation-sentry', 'Sentry Automation', 'Automate application monitoring and error tracking with AI-powered issue detection, alerting, and resolution workflows.', 'https://sentry.io', 'automations', 'Freemium', ARRAY['application-monitoring', 'error-tracking', 'issue-resolution'], false, true, 'https://sentry.io/favicon.ico')
ON CONFLICT (id, category_id) DO NOTHING;

-- Update the tool count for the category
UPDATE categories 
SET tool_count = (
  SELECT COUNT(*) 
  FROM tools 
  WHERE category_id = 'automations'
) 
WHERE id = 'automations';
