-- Daily Life AI Tools (100 tools)
-- This script adds 100 AI-powered tools for daily life activities
-- Covers productivity, health, finance, entertainment, and daily tasks
-- Uses ON CONFLICT (id, category_id) DO NOTHING to avoid duplicates within the same category

INSERT INTO tools (
  id, name, description, url, category_id, 
  pricing, tags, featured, trending
) VALUES
-- Personal Productivity & Organization
('daily-life-notion-ai', 'Notion AI', 'AI-powered workspace that helps you write, plan, organize, and think better with intelligent assistance built into your notes and documents.', 'https://notion.so', 'daily-life', 'Freemium', ARRAY['productivity', 'note-taking', 'workspace'], false, false),
('daily-life-todoist', 'Todoist', 'Smart task management with natural language processing, intelligent scheduling, and AI-powered project templates for better productivity.', 'https://todoist.com', 'daily-life', 'Freemium', ARRAY['task-management', 'productivity', 'scheduling'], false, false),
('daily-life-any-do', 'Any.do', 'AI-powered to-do list app that learns your habits and suggests optimal times for tasks, with smart reminders and calendar integration.', 'https://any.do', 'daily-life', 'Freemium', ARRAY['todo-list', 'habit-tracking', 'reminders'], false, false),
('daily-life-clickup-ai', 'ClickUp AI', 'Comprehensive productivity platform with AI writing assistant, smart scheduling, and automated project management features.', 'https://clickup.com', 'daily-life', 'Freemium', ARRAY['project-management', 'productivity', 'ai-writing'], false, false),
('daily-life-reclaim-ai', 'Reclaim.ai', 'AI calendar assistant that automatically schedules your tasks, habits, and meetings for optimal productivity and work-life balance.', 'https://reclaim.ai', 'daily-life', 'Freemium', ARRAY['calendar-ai', 'time-blocking', 'work-life-balance'], false, false),

-- Smart Home & IoT
('daily-life-alexa', 'Amazon Alexa', 'Voice-controlled AI assistant for smart home automation, music, shopping, information, and controlling connected devices.', 'https://alexa.amazon.com', 'daily-life', 'Free', ARRAY['voice-assistant', 'smart-home', 'automation'], false, false),
('daily-life-google-assistant', 'Google Assistant', 'AI-powered virtual assistant for voice commands, smart home control, scheduling, and personalized recommendations.', 'https://assistant.google.com', 'daily-life', 'Free', ARRAY['voice-assistant', 'smart-home', 'google'], false, false),
('daily-life-siri', 'Apple Siri', 'Intelligent personal assistant that uses voice recognition and AI to perform tasks, answer questions, and control devices.', 'https://apple.com/siri', 'daily-life', 'Free', ARRAY['voice-assistant', 'apple', 'personal-assistant'], false, false),
('daily-life-samsung-bixby', 'Samsung Bixby', 'AI assistant designed for Samsung devices with contextual awareness and smart home integration capabilities.', 'https://bixby.samsung.com', 'daily-life', 'Free', ARRAY['voice-assistant', 'samsung', 'device-control'], false, false),
('daily-life-philips-hue', 'Philips Hue with AI', 'Smart lighting system with AI-powered automation, circadian rhythm matching, and adaptive lighting schedules.', 'https://philips-hue.com', 'daily-life', 'Paid', ARRAY['smart-lighting', 'automation', 'circadian'], false, false),

-- Health & Fitness
('daily-life-myfitnesspal', 'MyFitnessPal AI', 'AI-powered nutrition tracking with food recognition, meal planning, and personalized health recommendations.', 'https://myfitnesspal.com', 'daily-life', 'Freemium', ARRAY['nutrition-tracking', 'meal-planning', 'health'], false, false),
('daily-life-fitbit-sense', 'Fitbit Sense AI', 'Advanced fitness tracker with AI-powered health insights, stress management, and personalized workout recommendations.', 'https://fitbit.com', 'daily-life', 'Paid', ARRAY['fitness-tracking', 'health-insights', 'stress-management'], false, false),
('daily-life-calm-ai', 'Calm AI', 'Meditation and mindfulness app with AI-powered personalized sessions, sleep stories, and mental health tracking.', 'https://calm.com', 'daily-life', 'Freemium', ARRAY['meditation', 'mindfulness', 'sleep'], false, false),
('daily-life-headspace', 'Headspace AI', 'AI-enhanced meditation app with personalized mindfulness exercises, sleep assistance, and mood tracking.', 'https://headspace.com', 'daily-life', 'Freemium', ARRAY['meditation', 'mindfulness', 'mood-tracking'], false, false),
('daily-life-noom', 'Noom AI', 'AI-powered weight loss and wellness app with personalized coaching, habit tracking, and behavioral psychology insights.', 'https://noom.com', 'daily-life', 'Paid', ARRAY['weight-loss', 'wellness', 'coaching'], false, false),

-- Personal Finance
('daily-life-mint-ai', 'Mint AI', 'AI-powered personal finance management with automatic categorization, spending insights, and budget optimization.', 'https://mint.com', 'daily-life', 'Free', ARRAY['personal-finance', 'budgeting', 'expense-tracking'], false, false),
('daily-life-ynab', 'YNAB AI', 'Intelligent budgeting software with AI-powered spending predictions and personalized financial recommendations.', 'https://youneedabudget.com', 'daily-life', 'Paid', ARRAY['budgeting', 'financial-planning', 'spending-prediction'], false, false),
('daily-life-personal-capital', 'Personal Capital AI', 'AI-driven wealth management with investment tracking, retirement planning, and personalized financial advice.', 'https://personalcapital.com', 'daily-life', 'Freemium', ARRAY['wealth-management', 'investment-tracking', 'retirement-planning'], false, false),
('daily-life-cleo-ai', 'Cleo AI', 'AI financial assistant that analyzes spending patterns, provides budgeting advice, and offers personalized money management tips.', 'https://meetcleo.com', 'daily-life', 'Freemium', ARRAY['financial-assistant', 'spending-analysis', 'money-management'], false, false),
('daily-life-truebill', 'Truebill AI', 'AI-powered subscription management and expense tracking with automatic bill negotiation and savings optimization.', 'https://truebill.com', 'daily-life', 'Freemium', ARRAY['subscription-management', 'bill-negotiation', 'savings'], false, false),

-- Transportation & Navigation
('daily-life-google-maps-ai', 'Google Maps AI', 'AI-enhanced navigation with real-time traffic prediction, optimal route planning, and location recommendations.', 'https://maps.google.com', 'daily-life', 'Free', ARRAY['navigation', 'traffic-prediction', 'route-optimization'], false, false),
('daily-life-waze-ai', 'Waze AI', 'Community-driven navigation app with AI-powered traffic predictions, hazard detection, and optimal route suggestions.', 'https://waze.com', 'daily-life', 'Free', ARRAY['navigation', 'traffic-prediction', 'community-driven'], false, false),
('daily-life-uber-ai', 'Uber AI', 'AI-powered ride-sharing with predictive pickup times, surge pricing optimization, and personalized ride preferences.', 'https://uber.com', 'daily-life', 'Free', ARRAY['ride-sharing', 'transportation', 'predictive-ai'], false, false),
('daily-life-lyft-ai', 'Lyft AI', 'Smart ride-sharing platform with AI-driven route optimization, driver matching, and predictive arrival times.', 'https://lyft.com', 'daily-life', 'Free', ARRAY['ride-sharing', 'route-optimization', 'driver-matching'], false, false),
('daily-life-citymapper', 'Citymapper AI', 'AI-powered urban transportation app with real-time transit updates, route optimization, and multimodal journey planning.', 'https://citymapper.com', 'daily-life', 'Freemium', ARRAY['urban-transport', 'transit-updates', 'multimodal'], false, false),

-- Food & Cooking
('daily-life-yuka-ai', 'Yuka AI', 'AI-powered food scanner that analyzes ingredients, nutritional value, and health impact of products with personalized recommendations.', 'https://yuka.io', 'daily-life', 'Freemium', ARRAY['food-scanner', 'nutrition', 'health-analysis'], false, false),
('daily-life-plantjammer', 'PlantJammer AI', 'AI recipe generator that creates personalized plant-based recipes based on available ingredients and dietary preferences.', 'https://plantjammer.com', 'daily-life', 'Freemium', ARRAY['recipe-generator', 'plant-based', 'dietary-preferences'], false, false),
('daily-life-whisk-ai', 'Whisk AI', 'AI-powered meal planning and recipe organization with smart grocery lists and dietary accommodation features.', 'https://whisk.com', 'daily-life', 'Freemium', ARRAY['meal-planning', 'recipe-organization', 'grocery-lists'], false, false),
('daily-life-foodvisor', 'Foodvisor AI', 'AI nutrition coach that analyzes food photos, tracks calories, and provides personalized dietary recommendations.', 'https://foodvisor.io', 'daily-life', 'Freemium', ARRAY['nutrition-tracking', 'calorie-tracking', 'food-analysis'], false, false),
('daily-life-epicurious', 'Epicurious AI', 'AI-enhanced recipe platform with personalized recommendations, cooking technique guidance, and meal planning assistance.', 'https://epicurious.com', 'daily-life', 'Freemium', ARRAY['recipe-platform', 'cooking-guidance', 'meal-planning'], false, false),

-- Shopping & E-commerce
('daily-life-honey-ai', 'Honey AI', 'AI-powered shopping assistant that automatically finds and applies coupon codes, tracks prices, and suggests better deals.', 'https://joinhoney.com', 'daily-life', 'Free', ARRAY['shopping-assistant', 'coupon-finder', 'price-tracking'], false, false),
('daily-life-rakuten-ai', 'Rakuten AI', 'AI-driven cashback and rewards platform with personalized shopping recommendations and deal discovery.', 'https://rakuten.com', 'daily-life', 'Free', ARRAY['cashback', 'rewards', 'deal-discovery'], false, false),
('daily-life-amazon-ai', 'Amazon AI Recommendations', 'AI-powered product recommendations, predictive shopping, and personalized deal suggestions on Amazon platform.', 'https://amazon.com', 'daily-life', 'Free', ARRAY['product-recommendations', 'predictive-shopping', 'personalized-deals'], false, false),
('daily-life-instacart-ai', 'Instacart AI', 'AI-powered grocery delivery with smart product suggestions, dietary filtering, and optimal shopping route planning.', 'https://instacart.com', 'daily-life', 'Free', ARRAY['grocery-delivery', 'product-suggestions', 'dietary-filtering'], false, false),
('daily-life-shipt-ai', 'Shipt AI', 'AI-enhanced grocery delivery service with personalized shopping preferences and smart substitution recommendations.', 'https://shipt.com', 'daily-life', 'Free', ARRAY['grocery-delivery', 'personalized-shopping', 'smart-substitution'], false, false),

-- Entertainment & Media
('daily-life-spotify-ai', 'Spotify AI', 'AI-powered music streaming with personalized playlists, mood-based recommendations, and intelligent music discovery.', 'https://spotify.com', 'daily-life', 'Freemium', ARRAY['music-streaming', 'personalized-playlists', 'music-discovery'], false, false),
('daily-life-netflix-ai', 'Netflix AI', 'AI-driven content recommendation engine that personalizes movie and TV show suggestions based on viewing habits.', 'https://netflix.com', 'daily-life', 'Paid', ARRAY['content-recommendations', 'streaming', 'personalized-content'], false, false),
('daily-life-youtube-ai', 'YouTube AI', 'AI-powered video platform with personalized recommendations, auto-generated captions, and content discovery algorithms.', 'https://youtube.com', 'daily-life', 'Free', ARRAY['video-platform', 'content-discovery', 'personalized-recommendations'], false, false),
('daily-life-pandora-ai', 'Pandora AI', 'AI music platform with genetic music analysis, personalized radio stations, and intelligent music genome recommendations.', 'https://pandora.com', 'daily-life', 'Freemium', ARRAY['music-platform', 'personalized-radio', 'music-genome'], false, false),
('daily-life-tiktok-ai', 'TikTok AI', 'AI-driven short video platform with personalized content feeds, trending topic detection, and engagement optimization.', 'https://tiktok.com', 'daily-life', 'Free', ARRAY['short-videos', 'personalized-feeds', 'trending-content'], false, false),

-- Communication & Social
('daily-life-grammarly', 'Grammarly AI', 'AI-powered writing assistant that improves grammar, clarity, tone, and style across all digital communication platforms.', 'https://grammarly.com', 'daily-life', 'Freemium', ARRAY['writing-assistant', 'grammar-checker', 'communication'], false, false),
('daily-life-boomerang-ai', 'Boomerang AI', 'AI email management with send-later scheduling, response tracking, and intelligent inbox prioritization features.', 'https://boomeranggmail.com', 'daily-life', 'Freemium', ARRAY['email-management', 'scheduling', 'inbox-prioritization'], false, false),
('daily-life-mixmax-ai', 'Mixmax AI', 'AI-powered email productivity suite with smart templates, send-time optimization, and engagement tracking.', 'https://mixmax.com', 'daily-life', 'Freemium', ARRAY['email-productivity', 'smart-templates', 'engagement-tracking'], false, false),
('daily-life-crystal-ai', 'Crystal AI', 'AI personality analysis tool that provides communication insights and suggestions for better interpersonal interactions.', 'https://crystalknows.com', 'daily-life', 'Freemium', ARRAY['personality-analysis', 'communication-insights', 'interpersonal'], false, false),
('daily-life-superhuman-ai', 'Superhuman AI', 'AI-enhanced email client with smart shortcuts, predictive text, and intelligent email organization features.', 'https://superhuman.com', 'daily-life', 'Paid', ARRAY['email-client', 'smart-shortcuts', 'predictive-text'], false, false),

-- Learning & Education
('daily-life-duolingo-ai', 'Duolingo AI', 'AI-powered language learning with personalized lessons, adaptive difficulty, and intelligent practice recommendations.', 'https://duolingo.com', 'daily-life', 'Freemium', ARRAY['language-learning', 'personalized-lessons', 'adaptive-difficulty'], false, false),
('daily-life-babbel-ai', 'Babbel AI', 'AI-enhanced language learning with conversation practice, pronunciation feedback, and personalized study plans.', 'https://babbel.com', 'daily-life', 'Paid', ARRAY['language-learning', 'conversation-practice', 'pronunciation-feedback'], false, false),
('daily-life-coursera-ai', 'Coursera AI', 'AI-powered online learning platform with personalized course recommendations and adaptive learning paths.', 'https://coursera.org', 'daily-life', 'Freemium', ARRAY['online-learning', 'course-recommendations', 'adaptive-learning'], false, false),
('daily-life-khan-academy', 'Khan Academy AI', 'AI-enhanced educational platform with personalized learning paths, mastery-based progression, and intelligent tutoring.', 'https://khanacademy.org', 'daily-life', 'Free', ARRAY['education', 'personalized-learning', 'intelligent-tutoring'], false, false),
('daily-life-brilliant-ai', 'Brilliant AI', 'AI-powered interactive learning platform for math, science, and computer science with adaptive problem-solving.', 'https://brilliant.org', 'daily-life', 'Freemium', ARRAY['interactive-learning', 'math-science', 'adaptive-problem-solving'], false, false),

-- Travel & Tourism
('daily-life-kayak-ai', 'Kayak AI', 'AI-powered travel search engine with price prediction, trip planning, and personalized travel recommendations.', 'https://kayak.com', 'daily-life', 'Free', ARRAY['travel-search', 'price-prediction', 'trip-planning'], false, false),
('daily-life-skyscanner-ai', 'Skyscanner AI', 'AI flight search platform with flexible date options, price alerts, and intelligent travel route suggestions.', 'https://skyscanner.com', 'daily-life', 'Free', ARRAY['flight-search', 'price-alerts', 'route-suggestions'], false, false),
('daily-life-airbnb-ai', 'Airbnb AI', 'AI-powered accommodation platform with personalized recommendations, smart pricing, and travel experience suggestions.', 'https://airbnb.com', 'daily-life', 'Free', ARRAY['accommodation', 'personalized-recommendations', 'travel-experiences'], false, false),
('daily-life-tripadvisor-ai', 'TripAdvisor AI', 'AI travel platform with personalized recommendations, sentiment analysis of reviews, and intelligent trip planning.', 'https://tripadvisor.com', 'daily-life', 'Free', ARRAY['travel-recommendations', 'review-analysis', 'trip-planning'], false, false),
('daily-life-hopper-ai', 'Hopper AI', 'AI-powered travel app with price prediction, booking optimization, and personalized travel deal notifications.', 'https://hopper.com', 'daily-life', 'Free', ARRAY['travel-booking', 'price-prediction', 'deal-notifications'], false, false),

-- Personal Security & Privacy
('daily-life-lastpass-ai', 'LastPass AI', 'AI-enhanced password manager with security breach monitoring, password strength analysis, and automated security alerts.', 'https://lastpass.com', 'daily-life', 'Freemium', ARRAY['password-manager', 'security-monitoring', 'breach-alerts'], false, false),
('daily-life-dashlane-ai', 'Dashlane AI', 'AI-powered password manager with dark web monitoring, identity theft protection, and security score optimization.', 'https://dashlane.com', 'daily-life', 'Freemium', ARRAY['password-manager', 'dark-web-monitoring', 'identity-protection'], false, false),
('daily-life-norton-ai', 'Norton AI', 'AI-powered cybersecurity suite with threat detection, identity monitoring, and intelligent security recommendations.', 'https://norton.com', 'daily-life', 'Paid', ARRAY['cybersecurity', 'threat-detection', 'identity-monitoring'], false, false),
('daily-life-malwarebytes-ai', 'Malwarebytes AI', 'AI-driven malware protection with behavioral analysis, real-time threat detection, and automated security responses.', 'https://malwarebytes.com', 'daily-life', 'Freemium', ARRAY['malware-protection', 'behavioral-analysis', 'threat-detection'], false, false),
('daily-life-vpn-ai', 'ExpressVPN AI', 'AI-optimized VPN service with smart server selection, connection optimization, and privacy protection automation.', 'https://expressvpn.com', 'daily-life', 'Paid', ARRAY['vpn', 'server-optimization', 'privacy-protection'], false, false),

-- Weather & Environment
('daily-life-weather-ai', 'Weather AI', 'AI-powered weather forecasting with hyperlocal predictions, severe weather alerts, and personalized weather insights.', 'https://weather.com', 'daily-life', 'Freemium', ARRAY['weather-forecasting', 'hyperlocal-predictions', 'weather-alerts'], false, false),
('daily-life-dark-sky', 'Dark Sky AI', 'AI weather app with minute-by-minute precipitation forecasts, weather pattern analysis, and location-based alerts.', 'https://darksky.net', 'daily-life', 'Paid', ARRAY['precipitation-forecasts', 'weather-patterns', 'location-alerts'], false, false),
('daily-life-weatherbug', 'WeatherBug AI', 'AI-enhanced weather tracking with real-time conditions, lightning detection, and personalized weather notifications.', 'https://weatherbug.com', 'daily-life', 'Freemium', ARRAY['weather-tracking', 'lightning-detection', 'weather-notifications'], false, false),
('daily-life-accuweather', 'AccuWeather AI', 'AI-powered weather service with long-range forecasts, weather impact analysis, and lifestyle recommendations.', 'https://accuweather.com', 'daily-life', 'Freemium', ARRAY['long-range-forecasts', 'weather-impact', 'lifestyle-recommendations'], false, false),
('daily-life-carrot-weather', 'Carrot Weather AI', 'AI weather app with personality, sarcastic commentary, and highly accurate hyperlocal weather predictions.', 'https://meetcarrot.com', 'daily-life', 'Paid', ARRAY['weather-app', 'personality', 'hyperlocal-weather'], false, false),

-- News & Information
('daily-life-flipboard-ai', 'Flipboard AI', 'AI-curated news magazine with personalized content discovery, topic clustering, and intelligent article recommendations.', 'https://flipboard.com', 'daily-life', 'Free', ARRAY['news-curation', 'content-discovery', 'article-recommendations'], false, false),
('daily-life-pocket-ai', 'Pocket AI', 'AI-powered read-later service with content recommendations, reading time estimates, and intelligent article tagging.', 'https://getpocket.com', 'daily-life', 'Freemium', ARRAY['read-later', 'content-recommendations', 'article-tagging'], false, false),
('daily-life-google-news', 'Google News AI', 'AI-powered news aggregation with personalized story selection, fact-checking, and comprehensive coverage analysis.', 'https://news.google.com', 'daily-life', 'Free', ARRAY['news-aggregation', 'personalized-news', 'fact-checking'], false, false),
('daily-life-apple-news', 'Apple News AI', 'AI-enhanced news app with personalized recommendations, topic following, and intelligent content curation.', 'https://apple.com/apple-news', 'daily-life', 'Freemium', ARRAY['news-app', 'personalized-recommendations', 'content-curation'], false, false),
('daily-life-feedly-ai', 'Feedly AI', 'AI-powered RSS reader with content filtering, trend detection, and intelligent feed organization for information professionals.', 'https://feedly.com', 'daily-life', 'Freemium', ARRAY['rss-reader', 'content-filtering', 'trend-detection'], false, false),

-- Photo & Memory Management
('daily-life-google-photos', 'Google Photos AI', 'AI-powered photo storage with automatic organization, face recognition, object detection, and intelligent search capabilities.', 'https://photos.google.com', 'daily-life', 'Freemium', ARRAY['photo-storage', 'face-recognition', 'intelligent-search'], false, false),
('daily-life-apple-photos', 'Apple Photos AI', 'AI-enhanced photo management with automatic albums, face grouping, scene detection, and memory creation.', 'https://apple.com/macos/photos', 'daily-life', 'Free', ARRAY['photo-management', 'face-grouping', 'memory-creation'], false, false),
('daily-life-amazon-photos', 'Amazon Photos AI', 'AI-powered photo storage with automatic tagging, face recognition, and intelligent photo organization features.', 'https://amazon.com/photos', 'daily-life', 'Freemium', ARRAY['photo-storage', 'automatic-tagging', 'photo-organization'], false, false),
('daily-life-prisma-ai', 'Prisma AI', 'AI-powered photo editor that transforms photos into artwork using neural networks and artistic style transfer.', 'https://prisma-ai.com', 'daily-life', 'Freemium', ARRAY['photo-editor', 'artistic-style', 'neural-networks'], false, false),
('daily-life-photomath', 'PhotoMath AI', 'AI-powered math solver that solves equations by taking photos, with step-by-step explanations and learning assistance.', 'https://photomath.net', 'daily-life', 'Freemium', ARRAY['math-solver', 'photo-recognition', 'step-by-step'], false, false),

-- Language & Translation
('daily-life-google-translate', 'Google Translate AI', 'AI-powered translation service with real-time conversation translation, camera translation, and offline capabilities.', 'https://translate.google.com', 'daily-life', 'Free', ARRAY['translation', 'real-time-translation', 'camera-translation'], false, false),
('daily-life-deepl', 'DeepL AI', 'AI translation service with superior accuracy for European languages, context understanding, and natural language output.', 'https://deepl.com', 'daily-life', 'Freemium', ARRAY['translation', 'european-languages', 'context-understanding'], false, false),
('daily-life-microsoft-translator', 'Microsoft Translator AI', 'AI translation platform with conversation mode, offline translation, and multi-device synchronization capabilities.', 'https://translator.microsoft.com', 'daily-life', 'Free', ARRAY['translation', 'conversation-mode', 'multi-device'], false, false),
('daily-life-papago', 'Papago AI', 'AI translation app specialized in Asian languages with image translation, voice translation, and conversation features.', 'https://papago.naver.com', 'daily-life', 'Free', ARRAY['translation', 'asian-languages', 'image-translation'], false, false),
('daily-life-reverso-ai', 'Reverso AI', 'AI-powered translation and language learning with context examples, conjugation, and pronunciation assistance.', 'https://reverso.net', 'daily-life', 'Freemium', ARRAY['translation', 'language-learning', 'pronunciation'], false, false),

-- Gaming & Entertainment
('daily-life-steam-ai', 'Steam AI', 'AI-powered game recommendation system that suggests games based on playing habits, preferences, and social connections.', 'https://steampowered.com', 'daily-life', 'Free', ARRAY['game-recommendations', 'gaming-platform', 'social-gaming'], false, false),
('daily-life-chess-ai', 'Chess.com AI', 'AI-powered chess platform with computer opponents, game analysis, puzzle generation, and skill improvement tracking.', 'https://chess.com', 'daily-life', 'Freemium', ARRAY['chess-platform', 'game-analysis', 'skill-tracking'], false, false),
('daily-life-lichess-ai', 'Lichess AI', 'Free AI-powered chess server with computer analysis, opening explorer, and AI opponents of varying strengths.', 'https://lichess.org', 'daily-life', 'Free', ARRAY['chess-server', 'computer-analysis', 'opening-explorer'], false, false),
('daily-life-peak-ai', 'Peak AI', 'AI-powered brain training app with personalized cognitive workouts, progress tracking, and mental performance insights.', 'https://peak.net', 'daily-life', 'Freemium', ARRAY['brain-training', 'cognitive-workouts', 'performance-tracking'], false, false),
('daily-life-elevate-ai', 'Elevate AI', 'AI-powered brain training app focused on communication and analytical skills with personalized training programs.', 'https://elevateapp.com', 'daily-life', 'Freemium', ARRAY['brain-training', 'communication-skills', 'analytical-skills'], false, false),

-- Voice & Audio
('daily-life-otter-ai', 'Otter.ai', 'AI-powered transcription service that converts speech to text in real-time with speaker identification and keyword search.', 'https://otter.ai', 'daily-life', 'Freemium', ARRAY['transcription', 'speech-to-text', 'speaker-identification'], false, false),
('daily-life-voice-recorder', 'Voice Recorder AI', 'AI-enhanced voice recording app with automatic transcription, noise reduction, and intelligent audio organization.', 'https://rev.com', 'daily-life', 'Freemium', ARRAY['voice-recording', 'transcription', 'noise-reduction'], false, false),
('daily-life-dragon-ai', 'Dragon NaturallySpeaking AI', 'Advanced AI speech recognition software for hands-free computing, dictation, and voice-controlled navigation.', 'https://nuance.com', 'daily-life', 'Paid', ARRAY['speech-recognition', 'hands-free-computing', 'dictation'], false, false),
('daily-life-whisper-ai', 'Whisper AI', 'OpenAI''s speech recognition system that transcribes and translates audio in multiple languages with high accuracy.', 'https://openai.com/research/whisper', 'daily-life', 'Free', ARRAY['speech-recognition', 'audio-translation', 'multilingual'], false, false),
('daily-life-speechify', 'Speechify AI', 'AI-powered text-to-speech app that reads any text aloud with natural voices and speed control for accessibility.', 'https://speechify.com', 'daily-life', 'Freemium', ARRAY['text-to-speech', 'natural-voices', 'accessibility'], false, false),

-- Additional Daily Life AI Tools (10 more to reach 100)
('daily-life-zoom-ai', 'Zoom AI', 'AI-enhanced video conferencing with noise cancellation, virtual backgrounds, meeting transcription, and smart scheduling.', 'https://zoom.us', 'daily-life', 'Freemium', ARRAY['video-conferencing', 'noise-cancellation', 'meeting-transcription'], false, false),
('daily-life-teams-ai', 'Microsoft Teams AI', 'AI-powered collaboration platform with intelligent meeting summaries, real-time translation, and background noise suppression.', 'https://teams.microsoft.com', 'daily-life', 'Freemium', ARRAY['collaboration', 'meeting-summaries', 'real-time-translation'], false, false),
('daily-life-slack-ai', 'Slack AI', 'AI-enhanced workplace messaging with smart notifications, message summarization, and automated workflow suggestions.', 'https://slack.com', 'daily-life', 'Freemium', ARRAY['workplace-messaging', 'smart-notifications', 'workflow-automation'], false, false),
('daily-life-discord-ai', 'Discord AI', 'AI-powered communication platform with noise suppression, voice activity detection, and automated moderation features.', 'https://discord.com', 'daily-life', 'Freemium', ARRAY['communication-platform', 'noise-suppression', 'automated-moderation'], false, false),
('daily-life-whatsapp-ai', 'WhatsApp AI', 'AI-enhanced messaging with smart reply suggestions, spam detection, business automation, and voice message transcription.', 'https://whatsapp.com', 'daily-life', 'Free', ARRAY['messaging', 'smart-replies', 'spam-detection'], false, false),
('daily-life-telegram-ai', 'Telegram AI', 'AI-powered messaging platform with intelligent bots, automated responses, and advanced spam filtering capabilities.', 'https://telegram.org', 'daily-life', 'Free', ARRAY['messaging-platform', 'intelligent-bots', 'spam-filtering'], false, false),
('daily-life-facetime-ai', 'FaceTime AI', 'AI-enhanced video calling with portrait mode, spatial audio, noise isolation, and automatic framing features.', 'https://apple.com/facetime', 'daily-life', 'Free', ARRAY['video-calling', 'portrait-mode', 'spatial-audio'], false, false),
('daily-life-skype-ai', 'Skype AI', 'AI-powered video calling with real-time translation, noise cancellation, background blur, and meeting recording.', 'https://skype.com', 'daily-life', 'Freemium', ARRAY['video-calling', 'real-time-translation', 'noise-cancellation'], false, false),
('daily-life-google-meet', 'Google Meet AI', 'AI-enhanced video conferencing with noise cancellation, live captions, automatic lighting adjustment, and smart suggestions.', 'https://meet.google.com', 'daily-life', 'Freemium', ARRAY['video-conferencing', 'live-captions', 'automatic-lighting'], false, false),
('daily-life-webex-ai', 'Webex AI', 'AI-powered meeting platform with real-time noise removal, gesture recognition, people insights, and meeting optimization.', 'https://webex.com', 'daily-life', 'Freemium', ARRAY['meeting-platform', 'gesture-recognition', 'people-insights'], false, false)

ON CONFLICT (id, category_id) DO NOTHING;
