-- Research & Data Analysis AI Tools (103 tools)
-- This script adds 103 AI-powered tools for research and data analysis
-- Covers data science, machine learning, statistical analysis, research automation, and data visualization
-- Uses ON CONFLICT (id, category_id) DO NOTHING to avoid duplicates within the same category

INSERT INTO tools (
  id, name, description, url, category_id, 
  pricing, tags, featured, trending, logo_url
) VALUES 
  -- Data Science Platforms & IDEs
  ('research-jupyter-ai', 'Jupyter AI', 'AI-powered data science notebook with intelligent code completion, automated insights, and ML model suggestions.', 'https://jupyter.org', 'research-data-analysis', 'Free', ARRAY['data-science', 'notebook', 'code-completion'], false, true, 'https://jupyter.org/favicon.ico'),
  ('research-colab-ai', 'Google Colab AI', 'AI-enhanced collaborative notebook platform with GPU access, automated data analysis, and intelligent code suggestions.', 'https://colab.research.google.com', 'research-data-analysis', 'Freemium', ARRAY['collaborative-notebook', 'gpu-access', 'code-suggestions'], false, true, 'https://colab.research.google.com/favicon.ico'),
  ('research-kaggle-ai', 'Kaggle AI', 'AI-powered data science competition platform with automated feature engineering and model optimization.', 'https://kaggle.com', 'research-data-analysis', 'Free', ARRAY['data-competitions', 'feature-engineering', 'model-optimization'], false, true, 'https://kaggle.com/favicon.ico'),
  ('research-dataiku', 'Dataiku DSS', 'AI-powered data science studio with automated machine learning, collaborative analytics, and model deployment.', 'https://dataiku.com', 'research-data-analysis', 'Paid', ARRAY['data-science-studio', 'automl', 'collaborative-analytics'], false, false, 'https://dataiku.com/favicon.ico'),
  ('research-databricks', 'Databricks AI', 'AI-enhanced unified analytics platform with automated ML, collaborative notebooks, and scalable data processing.', 'https://databricks.com', 'research-data-analysis', 'Paid', ARRAY['unified-analytics', 'automl', 'scalable-processing'], false, true, 'https://databricks.com/favicon.ico'),
  ('research-h2o-ai', 'H2O.ai', 'AI-powered machine learning platform with automated feature engineering, model interpretation, and deployment.', 'https://h2o.ai', 'research-data-analysis', 'Freemium', ARRAY['machine-learning-platform', 'automated-features', 'model-interpretation'], false, false, 'https://h2o.ai/favicon.ico'),
  ('research-rapidminer', 'RapidMiner AI', 'AI-enhanced data science platform with visual workflow design, automated analytics, and predictive modeling.', 'https://rapidminer.com', 'research-data-analysis', 'Freemium', ARRAY['visual-workflow', 'automated-analytics', 'predictive-modeling'], false, false, 'https://rapidminer.com/favicon.ico'),
  ('research-knime', 'KNIME Analytics', 'AI-powered analytics platform with visual programming, automated machine learning, and data integration.', 'https://knime.com', 'research-data-analysis', 'Free', ARRAY['visual-programming', 'data-integration', 'analytics-platform'], false, false, 'https://knime.com/favicon.ico'),
  
  -- Machine Learning & AutoML
  ('research-automl-google', 'Google AutoML', 'AI-powered automated machine learning platform with neural architecture search and model optimization.', 'https://cloud.google.com/automl', 'research-data-analysis', 'Paid', ARRAY['automl', 'neural-architecture-search', 'model-optimization'], false, true, 'https://cloud.google.com/favicon.ico'),
  ('research-azure-automl', 'Azure AutoML', 'AI-enhanced automated machine learning service with feature engineering, model selection, and hyperparameter tuning.', 'https://azure.microsoft.com/automl', 'research-data-analysis', 'Paid', ARRAY['automl', 'feature-engineering', 'hyperparameter-tuning'], false, false, 'https://azure.microsoft.com/favicon.ico'),
  ('research-aws-sagemaker', 'AWS SageMaker', 'AI-powered machine learning platform with automated model building, training, and deployment at scale.', 'https://aws.amazon.com/sagemaker', 'research-data-analysis', 'Paid', ARRAY['ml-platform', 'automated-building', 'scalable-deployment'], false, true, 'https://aws.amazon.com/favicon.ico'),
  ('research-datarobot', 'DataRobot AI', 'AI-driven automated machine learning platform with feature discovery, model interpretation, and MLOps.', 'https://datarobot.com', 'research-data-analysis', 'Paid', ARRAY['automated-ml', 'feature-discovery', 'mlops'], false, false, 'https://datarobot.com/favicon.ico'),
  ('research-pycaret', 'PyCaret', 'AI-enhanced low-code machine learning library with automated preprocessing, model comparison, and deployment.', 'https://pycaret.org', 'research-data-analysis', 'Free', ARRAY['low-code-ml', 'automated-preprocessing', 'model-comparison'], false, false, 'https://pycaret.org/favicon.ico'),
  ('research-auto-sklearn', 'Auto-sklearn', 'AI-powered automated machine learning toolkit with algorithm selection and hyperparameter optimization.', 'https://automl.github.io/auto-sklearn', 'research-data-analysis', 'Free', ARRAY['automl-toolkit', 'algorithm-selection', 'hyperparameter-optimization'], false, false, 'https://automl.github.io/favicon.ico'),
  ('research-tpot', 'TPOT AutoML', 'AI-enhanced genetic programming tool for automated machine learning pipeline optimization.', 'https://epistasislab.github.io/tpot', 'research-data-analysis', 'Free', ARRAY['genetic-programming', 'pipeline-optimization', 'automl'], false, false, 'https://epistasislab.github.io/favicon.ico'),
  ('research-autokeras', 'AutoKeras', 'AI-powered automated deep learning library with neural architecture search and hyperparameter tuning.', 'https://autokeras.com', 'research-data-analysis', 'Free', ARRAY['automated-deep-learning', 'neural-architecture-search', 'hyperparameter-tuning'], false, false, 'https://autokeras.com/favicon.ico'),
  
  -- Data Visualization & Business Intelligence
  ('research-tableau-ai', 'Tableau AI', 'AI-enhanced business intelligence platform with automated insights, natural language queries, and predictive analytics.', 'https://tableau.com', 'research-data-analysis', 'Paid', ARRAY['business-intelligence', 'automated-insights', 'natural-language-queries'], false, true, 'https://tableau.com/favicon.ico'),
  ('research-power-bi-ai', 'Power BI AI', 'AI-powered business analytics tool with automated data preparation, intelligent visualizations, and natural language Q&A.', 'https://powerbi.microsoft.com', 'research-data-analysis', 'Freemium', ARRAY['business-analytics', 'automated-preparation', 'intelligent-visualizations'], false, true, 'https://powerbi.microsoft.com/favicon.ico'),
  ('research-qlik-sense', 'Qlik Sense AI', 'AI-enhanced associative analytics platform with automated insights, conversational analytics, and augmented intelligence.', 'https://qlik.com', 'research-data-analysis', 'Paid', ARRAY['associative-analytics', 'conversational-analytics', 'augmented-intelligence'], false, false, 'https://qlik.com/favicon.ico'),
  ('research-looker', 'Looker AI', 'AI-powered business intelligence platform with automated modeling, smart recommendations, and embedded analytics.', 'https://looker.com', 'research-data-analysis', 'Paid', ARRAY['business-intelligence', 'automated-modeling', 'embedded-analytics'], false, false, 'https://looker.com/favicon.ico'),
  ('research-sisense', 'Sisense AI', 'AI-enhanced analytics platform with automated data preparation, smart visualizations, and natural language processing.', 'https://sisense.com', 'research-data-analysis', 'Paid', ARRAY['analytics-platform', 'automated-preparation', 'natural-language-processing'], false, false, 'https://sisense.com/favicon.ico'),
  ('research-plotly-dash', 'Plotly Dash AI', 'AI-powered interactive data visualization framework with automated chart recommendations and smart layouts.', 'https://plotly.com/dash', 'research-data-analysis', 'Freemium', ARRAY['data-visualization', 'automated-charts', 'interactive-framework'], false, false, 'https://plotly.com/favicon.ico'),
  ('research-observable', 'Observable AI', 'AI-enhanced collaborative data visualization platform with intelligent notebooks and automated insights.', 'https://observablehq.com', 'research-data-analysis', 'Freemium', ARRAY['collaborative-visualization', 'intelligent-notebooks', 'automated-insights'], false, false, 'https://observablehq.com/favicon.ico'),
  ('research-streamlit', 'Streamlit AI', 'AI-powered app framework for data science with automated UI generation and interactive widgets.', 'https://streamlit.io', 'research-data-analysis', 'Free', ARRAY['app-framework', 'automated-ui', 'interactive-widgets'], false, false, 'https://streamlit.io/favicon.ico'),
  
  -- Statistical Analysis & Research Tools
  ('research-spss-ai', 'SPSS AI', 'AI-enhanced statistical analysis software with automated hypothesis testing, predictive modeling, and result interpretation.', 'https://ibm.com/spss', 'research-data-analysis', 'Paid', ARRAY['statistical-analysis', 'hypothesis-testing', 'predictive-modeling'], false, false, 'https://ibm.com/favicon.ico'),
  ('research-sas-ai', 'SAS AI', 'AI-powered advanced analytics platform with automated modeling, statistical computing, and business intelligence.', 'https://sas.com', 'research-data-analysis', 'Paid', ARRAY['advanced-analytics', 'automated-modeling', 'statistical-computing'], false, false, 'https://sas.com/favicon.ico'),
  ('research-stata-ai', 'Stata AI', 'AI-enhanced statistical software with automated analysis workflows, reproducible research, and publication-ready output.', 'https://stata.com', 'research-data-analysis', 'Paid', ARRAY['statistical-software', 'automated-workflows', 'reproducible-research'], false, false, 'https://stata.com/favicon.ico'),
  ('research-r-studio', 'RStudio AI', 'AI-powered integrated development environment for R with intelligent code completion and automated package suggestions.', 'https://rstudio.com', 'research-data-analysis', 'Freemium', ARRAY['r-development', 'code-completion', 'package-suggestions'], false, false, 'https://rstudio.com/favicon.ico'),
  ('research-jamovi', 'Jamovi AI', 'AI-enhanced open statistical software with automated analysis selection, visual results, and interpretation guidance.', 'https://jamovi.org', 'research-data-analysis', 'Free', ARRAY['statistical-software', 'automated-selection', 'visual-results'], false, false, 'https://jamovi.org/favicon.ico'),
  ('research-jasp', 'JASP AI', 'AI-powered statistical analysis program with Bayesian and frequentist methods, automated model selection.', 'https://jasp-stats.org', 'research-data-analysis', 'Free', ARRAY['bayesian-analysis', 'frequentist-methods', 'automated-selection'], false, false, 'https://jasp-stats.org/favicon.ico'),
  ('research-orange', 'Orange AI', 'AI-enhanced visual programming tool for data analysis with automated workflows and machine learning components.', 'https://orangedatamining.com', 'research-data-analysis', 'Free', ARRAY['visual-programming', 'automated-workflows', 'ml-components'], false, false, 'https://orangedatamining.com/favicon.ico'),
  ('research-weka', 'Weka AI', 'AI-powered machine learning workbench with automated algorithm selection, data preprocessing, and model evaluation.', 'https://waikato.github.io/weka', 'research-data-analysis', 'Free', ARRAY['ml-workbench', 'algorithm-selection', 'model-evaluation'], false, false, 'https://waikato.github.io/favicon.ico'),
  
  -- Natural Language Processing & Text Analysis
  ('research-spacy', 'spaCy AI', 'AI-powered natural language processing library with advanced tokenization, named entity recognition, and dependency parsing.', 'https://spacy.io', 'research-data-analysis', 'Free', ARRAY['natural-language-processing', 'named-entity-recognition', 'dependency-parsing'], false, false, 'https://spacy.io/favicon.ico'),
  ('research-nltk', 'NLTK AI', 'AI-enhanced natural language toolkit with automated text preprocessing, sentiment analysis, and linguistic analysis.', 'https://nltk.org', 'research-data-analysis', 'Free', ARRAY['natural-language-toolkit', 'text-preprocessing', 'sentiment-analysis'], false, false, 'https://nltk.org/favicon.ico'),
  ('research-huggingface', 'Hugging Face', 'AI-powered transformer models hub with pre-trained models, automated fine-tuning, and deployment tools.', 'https://huggingface.co', 'research-data-analysis', 'Freemium', ARRAY['transformer-models', 'pre-trained-models', 'automated-fine-tuning'], false, true, 'https://huggingface.co/favicon.ico'),
  ('research-gensim', 'Gensim AI', 'AI-enhanced topic modeling library with automated document similarity, word embeddings, and semantic analysis.', 'https://radimrehurek.com/gensim', 'research-data-analysis', 'Free', ARRAY['topic-modeling', 'document-similarity', 'semantic-analysis'], false, false, 'https://radimrehurek.com/favicon.ico'),
  ('research-textblob', 'TextBlob AI', 'AI-powered text processing library with automated sentiment analysis, noun phrase extraction, and language detection.', 'https://textblob.readthedocs.io', 'research-data-analysis', 'Free', ARRAY['text-processing', 'sentiment-analysis', 'language-detection'], false, false, 'https://textblob.readthedocs.io/favicon.ico'),
  ('research-aws-comprehend', 'AWS Comprehend', 'AI-powered natural language processing service with automated sentiment analysis, entity extraction, and topic modeling.', 'https://aws.amazon.com/comprehend', 'research-data-analysis', 'Paid', ARRAY['nlp-service', 'sentiment-analysis', 'entity-extraction'], false, false, 'https://aws.amazon.com/favicon.ico'),
  ('research-google-nlp', 'Google Cloud NLP', 'AI-enhanced natural language API with automated entity recognition, sentiment analysis, and syntax analysis.', 'https://cloud.google.com/natural-language', 'research-data-analysis', 'Paid', ARRAY['natural-language-api', 'entity-recognition', 'syntax-analysis'], false, false, 'https://cloud.google.com/favicon.ico'),
  ('research-azure-text', 'Azure Text Analytics', 'AI-powered text analytics service with automated sentiment analysis, key phrase extraction, and language detection.', 'https://azure.microsoft.com/text-analytics', 'research-data-analysis', 'Paid', ARRAY['text-analytics', 'key-phrase-extraction', 'language-detection'], false, false, 'https://azure.microsoft.com/favicon.ico'),
  
  -- Academic Research & Literature Analysis
  ('research-semantic-scholar', 'Semantic Scholar AI', 'AI-powered academic search engine with automated paper recommendations, citation analysis, and research trends.', 'https://semanticscholar.org', 'research-data-analysis', 'Free', ARRAY['academic-search', 'paper-recommendations', 'citation-analysis'], false, true, 'https://semanticscholar.org/favicon.ico'),
  ('research-connectedpapers', 'Connected Papers', 'AI-enhanced research tool that visualizes academic paper connections, identifies influential works, and suggests related research.', 'https://connectedpapers.com', 'research-data-analysis', 'Freemium', ARRAY['paper-visualization', 'research-connections', 'influential-works'], false, false, 'https://connectedpapers.com/favicon.ico'),
  ('research-researchgate-ai', 'ResearchGate AI', 'AI-powered academic networking platform with automated research recommendations, collaboration suggestions, and impact metrics.', 'https://researchgate.net', 'research-data-analysis', 'Free', ARRAY['academic-networking', 'research-recommendations', 'impact-metrics'], false, false, 'https://researchgate.net/favicon.ico'),
  ('research-arxiv-ai', 'arXiv AI Tools', 'AI-enhanced preprint repository with automated paper categorization, recommendation systems, and trend analysis.', 'https://arxiv.org', 'research-data-analysis', 'Free', ARRAY['preprint-repository', 'paper-categorization', 'trend-analysis'], false, false, 'https://arxiv.org/favicon.ico'),
  ('research-pubmed-ai', 'PubMed AI', 'AI-powered biomedical literature search with automated query expansion, result ranking, and research trend identification.', 'https://pubmed.ncbi.nlm.nih.gov', 'research-data-analysis', 'Free', ARRAY['biomedical-literature', 'query-expansion', 'trend-identification'], false, false, 'https://pubmed.ncbi.nlm.nih.gov/favicon.ico'),
  ('research-zotero-ai', 'Zotero AI', 'AI-enhanced reference management with automated metadata extraction, duplicate detection, and citation formatting.', 'https://zotero.org', 'research-data-analysis', 'Free', ARRAY['reference-management', 'metadata-extraction', 'citation-formatting'], false, false, 'https://zotero.org/favicon.ico'),
  ('research-mendeley-ai', 'Mendeley AI', 'AI-powered reference manager with automated paper recommendations, collaboration features, and research analytics.', 'https://mendeley.com', 'research-data-analysis', 'Freemium', ARRAY['reference-manager', 'paper-recommendations', 'research-analytics'], false, false, 'https://mendeley.com/favicon.ico'),
  ('research-scopus-ai', 'Scopus AI', 'AI-enhanced academic database with automated citation analysis, research metrics, and trend identification tools.', 'https://scopus.com', 'research-data-analysis', 'Paid', ARRAY['academic-database', 'citation-analysis', 'research-metrics'], false, false, 'https://scopus.com/favicon.ico'),
  
  -- Data Mining & Pattern Recognition
  ('research-rapidminer-auto', 'RapidMiner Auto Model', 'AI-powered automated data mining platform with pattern recognition, anomaly detection, and predictive modeling.', 'https://rapidminer.com/automodel', 'research-data-analysis', 'Paid', ARRAY['automated-data-mining', 'pattern-recognition', 'anomaly-detection'], false, false, 'https://rapidminer.com/favicon.ico'),
  ('research-weka-auto', 'Weka AutoWeka', 'AI-enhanced automated machine learning extension with algorithm selection, hyperparameter optimization, and ensemble methods.', 'https://autoweka.github.io', 'research-data-analysis', 'Free', ARRAY['automated-ml', 'algorithm-selection', 'ensemble-methods'], false, false, 'https://autoweka.github.io/favicon.ico'),
  ('research-scikit-learn', 'Scikit-learn AI', 'AI-powered machine learning library with automated feature selection, model selection, and performance optimization.', 'https://scikit-learn.org', 'research-data-analysis', 'Free', ARRAY['machine-learning-library', 'feature-selection', 'model-selection'], false, false, 'https://scikit-learn.org/favicon.ico'),
  ('research-tensorflow', 'TensorFlow AI', 'AI-enhanced machine learning framework with automated model optimization, distributed training, and deployment tools.', 'https://tensorflow.org', 'research-data-analysis', 'Free', ARRAY['ml-framework', 'model-optimization', 'distributed-training'], false, true, 'https://tensorflow.org/favicon.ico'),
  ('research-pytorch', 'PyTorch AI', 'AI-powered deep learning framework with dynamic computation graphs, automated differentiation, and model deployment.', 'https://pytorch.org', 'research-data-analysis', 'Free', ARRAY['deep-learning-framework', 'dynamic-graphs', 'automated-differentiation'], false, true, 'https://pytorch.org/favicon.ico'),
  ('research-keras', 'Keras AI', 'AI-enhanced deep learning API with simplified model building, automated optimization, and transfer learning capabilities.', 'https://keras.io', 'research-data-analysis', 'Free', ARRAY['deep-learning-api', 'simplified-building', 'transfer-learning'], false, false, 'https://keras.io/favicon.ico'),
  ('research-xgboost', 'XGBoost AI', 'AI-powered gradient boosting framework with automated hyperparameter tuning, feature importance, and model interpretation.', 'https://xgboost.ai', 'research-data-analysis', 'Free', ARRAY['gradient-boosting', 'hyperparameter-tuning', 'model-interpretation'], false, false, 'https://xgboost.ai/favicon.ico'),
  ('research-lightgbm', 'LightGBM AI', 'AI-enhanced gradient boosting framework with automated feature selection, fast training, and memory efficiency.', 'https://lightgbm.readthedocs.io', 'research-data-analysis', 'Free', ARRAY['gradient-boosting', 'feature-selection', 'memory-efficiency'], false, false, 'https://lightgbm.readthedocs.io/favicon.ico'),
  
  -- Survey & Market Research AI
  ('research-qualtrics-ai', 'Qualtrics AI', 'AI-powered survey platform with automated question generation, response analysis, and insight extraction.', 'https://qualtrics.com', 'research-data-analysis', 'Paid', ARRAY['survey-platform', 'automated-questions', 'insight-extraction'], false, false, 'https://qualtrics.com/favicon.ico'),
  ('research-surveymonkey-ai', 'SurveyMonkey AI', 'AI-enhanced survey tool with intelligent question suggestions, automated analysis, and predictive insights.', 'https://surveymonkey.com', 'research-data-analysis', 'Freemium', ARRAY['survey-tool', 'question-suggestions', 'predictive-insights'], false, false, 'https://surveymonkey.com/favicon.ico'),
  ('research-typeform-ai', 'Typeform AI', 'AI-powered form builder with intelligent question flow, automated responses, and conversation analytics.', 'https://typeform.com', 'research-data-analysis', 'Freemium', ARRAY['form-builder', 'intelligent-flow', 'conversation-analytics'], false, false, 'https://typeform.com/favicon.ico'),
  ('research-google-forms-ai', 'Google Forms AI', 'AI-enhanced form creation with smart question suggestions, automated data validation, and response analysis.', 'https://forms.google.com', 'research-data-analysis', 'Free', ARRAY['form-creation', 'smart-suggestions', 'response-analysis'], false, false, 'https://forms.google.com/favicon.ico'),
  ('research-brandwatch', 'Brandwatch AI', 'AI-powered social listening and market research platform with sentiment analysis, trend detection, and consumer insights.', 'https://brandwatch.com', 'research-data-analysis', 'Paid', ARRAY['social-listening', 'sentiment-analysis', 'consumer-insights'], false, false, 'https://brandwatch.com/favicon.ico'),
  ('research-crimson-hexagon', 'Crimson Hexagon', 'AI-enhanced consumer insights platform with automated social media analysis, audience segmentation, and trend forecasting.', 'https://crimsonhexagon.com', 'research-data-analysis', 'Paid', ARRAY['consumer-insights', 'social-media-analysis', 'trend-forecasting'], false, false, 'https://crimsonhexagon.com/favicon.ico'),
  ('research-sprout-social', 'Sprout Social AI', 'AI-powered social media analytics with automated sentiment analysis, competitive intelligence, and audience insights.', 'https://sproutsocial.com', 'research-data-analysis', 'Paid', ARRAY['social-media-analytics', 'competitive-intelligence', 'audience-insights'], false, false, 'https://sproutsocial.com/favicon.ico'),
  ('research-hootsuite-insights', 'Hootsuite Insights', 'AI-enhanced social media monitoring with automated trend detection, sentiment analysis, and influencer identification.', 'https://hootsuite.com/insights', 'research-data-analysis', 'Paid', ARRAY['social-media-monitoring', 'trend-detection', 'influencer-identification'], false, false, 'https://hootsuite.com/favicon.ico'),
  
  -- Time Series Analysis & Forecasting
  ('research-prophet', 'Prophet AI', 'AI-powered time series forecasting tool with automated seasonality detection, trend analysis, and anomaly detection.', 'https://facebook.github.io/prophet', 'research-data-analysis', 'Free', ARRAY['time-series-forecasting', 'seasonality-detection', 'anomaly-detection'], false, false, 'https://facebook.github.io/favicon.ico'),
  ('research-forecast-ai', 'Forecast.ai', 'AI-enhanced forecasting platform with automated model selection, uncertainty quantification, and scenario planning.', 'https://forecast.ai', 'research-data-analysis', 'Paid', ARRAY['forecasting-platform', 'model-selection', 'scenario-planning'], false, false, 'https://forecast.ai/favicon.ico'),
  ('research-alteryx-ai', 'Alteryx AI', 'AI-powered data science platform with automated time series analysis, predictive modeling, and workflow automation.', 'https://alteryx.com', 'research-data-analysis', 'Paid', ARRAY['data-science-platform', 'time-series-analysis', 'workflow-automation'], false, false, 'https://alteryx.com/favicon.ico'),
  ('research-datahike', 'DataHike AI', 'AI-enhanced time series database with automated pattern recognition, anomaly detection, and predictive analytics.', 'https://datahike.io', 'research-data-analysis', 'Freemium', ARRAY['time-series-database', 'pattern-recognition', 'predictive-analytics'], false, false, 'https://datahike.io/favicon.ico'),
  ('research-influxdb-ai', 'InfluxDB AI', 'AI-powered time series platform with automated forecasting, anomaly detection, and real-time analytics.', 'https://influxdata.com', 'research-data-analysis', 'Freemium', ARRAY['time-series-platform', 'real-time-analytics', 'automated-forecasting'], false, false, 'https://influxdata.com/favicon.ico'),
  ('research-timescale-ai', 'TimescaleDB AI', 'AI-enhanced time series database with automated compression, continuous aggregation, and predictive queries.', 'https://timescale.com', 'research-data-analysis', 'Freemium', ARRAY['time-series-database', 'automated-compression', 'predictive-queries'], false, false, 'https://timescale.com/favicon.ico'),
  ('research-prometheus', 'Prometheus AI', 'AI-powered monitoring system with automated alerting, anomaly detection, and performance forecasting.', 'https://prometheus.io', 'research-data-analysis', 'Free', ARRAY['monitoring-system', 'automated-alerting', 'performance-forecasting'], false, false, 'https://prometheus.io/favicon.ico'),
  ('research-grafana-ai', 'Grafana AI', 'AI-enhanced monitoring and observability platform with automated dashboard generation and intelligent alerting.', 'https://grafana.com', 'research-data-analysis', 'Freemium', ARRAY['monitoring-platform', 'automated-dashboards', 'intelligent-alerting'], false, false, 'https://grafana.com/favicon.ico'),
  
  -- Experimental Design & A/B Testing
  ('research-optimizely', 'Optimizely AI', 'AI-powered experimentation platform with automated test design, statistical analysis, and result interpretation.', 'https://optimizely.com', 'research-data-analysis', 'Paid', ARRAY['experimentation-platform', 'automated-design', 'statistical-analysis'], false, false, 'https://optimizely.com/favicon.ico'),
  ('research-google-optimize', 'Google Optimize AI', 'AI-enhanced A/B testing tool with automated experiment design, smart objectives, and machine learning insights.', 'https://optimize.google.com', 'research-data-analysis', 'Free', ARRAY['ab-testing', 'automated-design', 'ml-insights'], false, false, 'https://optimize.google.com/favicon.ico'),
  ('research-vwo', 'VWO AI', 'AI-powered conversion optimization platform with automated test creation, audience targeting, and performance prediction.', 'https://vwo.com', 'research-data-analysis', 'Paid', ARRAY['conversion-optimization', 'automated-creation', 'performance-prediction'], false, false, 'https://vwo.com/favicon.ico'),
  ('research-adobe-target', 'Adobe Target AI', 'AI-enhanced personalization and testing platform with automated audience discovery and experience optimization.', 'https://adobe.com/target', 'research-data-analysis', 'Paid', ARRAY['personalization-testing', 'audience-discovery', 'experience-optimization'], false, false, 'https://adobe.com/favicon.ico'),
  ('research-unbounce-ai', 'Unbounce AI', 'AI-powered landing page optimization with automated A/B testing, conversion prediction, and smart recommendations.', 'https://unbounce.com', 'research-data-analysis', 'Paid', ARRAY['landing-page-optimization', 'conversion-prediction', 'smart-recommendations'], false, false, 'https://unbounce.com/favicon.ico'),
  ('research-splitly', 'Splitly AI', 'AI-enhanced split testing platform with automated experiment design, statistical significance detection, and result analysis.', 'https://splitly.com', 'research-data-analysis', 'Paid', ARRAY['split-testing', 'experiment-design', 'significance-detection'], false, false, 'https://splitly.com/favicon.ico'),
  ('research-growthbook', 'GrowthBook AI', 'AI-powered feature flagging and experimentation platform with automated analysis and statistical rigor.', 'https://growthbook.io', 'research-data-analysis', 'Freemium', ARRAY['feature-flagging', 'experimentation', 'statistical-rigor'], false, false, 'https://growthbook.io/favicon.ico'),
  ('research-launchdarkly', 'LaunchDarkly AI', 'AI-enhanced feature management platform with automated experimentation, impact measurement, and rollout optimization.', 'https://launchdarkly.com', 'research-data-analysis', 'Paid', ARRAY['feature-management', 'impact-measurement', 'rollout-optimization'], false, false, 'https://launchdarkly.com/favicon.ico'),
  
  -- Bioinformatics & Scientific Computing
  ('research-bioconductor', 'Bioconductor AI', 'AI-enhanced bioinformatics platform with automated genomic analysis, pathway discovery, and biomarker identification.', 'https://bioconductor.org', 'research-data-analysis', 'Free', ARRAY['bioinformatics', 'genomic-analysis', 'biomarker-identification'], false, false, 'https://bioconductor.org/favicon.ico'),
  ('research-galaxy-ai', 'Galaxy AI', 'AI-powered scientific workflow platform with automated tool selection, parameter optimization, and result interpretation.', 'https://galaxyproject.org', 'research-data-analysis', 'Free', ARRAY['scientific-workflows', 'tool-selection', 'parameter-optimization'], false, false, 'https://galaxyproject.org/favicon.ico'),
  ('research-cytoscape', 'Cytoscape AI', 'AI-enhanced network analysis platform with automated layout algorithms, pathway analysis, and biomarker discovery.', 'https://cytoscape.org', 'research-data-analysis', 'Free', ARRAY['network-analysis', 'pathway-analysis', 'biomarker-discovery'], false, false, 'https://cytoscape.org/favicon.ico'),
  ('research-string-db', 'STRING AI', 'AI-powered protein interaction database with automated function prediction, pathway analysis, and drug target identification.', 'https://string-db.org', 'research-data-analysis', 'Free', ARRAY['protein-interactions', 'function-prediction', 'drug-targets'], false, false, 'https://string-db.org/favicon.ico'),
  ('research-imageJ-ai', 'ImageJ AI', 'AI-enhanced image analysis software with automated feature detection, measurement tools, and plugin ecosystem.', 'https://imagej.net', 'research-data-analysis', 'Free', ARRAY['image-analysis', 'feature-detection', 'measurement-tools'], false, false, 'https://imagej.net/favicon.ico'),
  ('research-fiji-ai', 'Fiji AI', 'AI-powered image processing package with automated analysis workflows, machine learning plugins, and batch processing.', 'https://fiji.sc', 'research-data-analysis', 'Free', ARRAY['image-processing', 'analysis-workflows', 'batch-processing'], false, false, 'https://fiji.sc/favicon.ico'),
  ('research-cellprofiler', 'CellProfiler AI', 'AI-enhanced cell image analysis software with automated cell segmentation, feature extraction, and phenotype classification.', 'https://cellprofiler.org', 'research-data-analysis', 'Free', ARRAY['cell-analysis', 'automated-segmentation', 'phenotype-classification'], false, false, 'https://cellprofiler.org/favicon.ico'),
  ('research-ilastik', 'ilastik AI', 'AI-powered interactive learning and segmentation toolkit with automated pixel classification and object tracking.', 'https://ilastik.org', 'research-data-analysis', 'Free', ARRAY['interactive-learning', 'pixel-classification', 'object-tracking'], false, false, 'https://ilastik.org/favicon.ico'),
  
  -- Geospatial Analysis & GIS
  ('research-arcgis-ai', 'ArcGIS AI', 'AI-powered geographic information system with automated spatial analysis, pattern detection, and predictive modeling.', 'https://arcgis.com', 'research-data-analysis', 'Paid', ARRAY['geographic-information', 'spatial-analysis', 'pattern-detection'], false, false, 'https://arcgis.com/favicon.ico'),
  ('research-qgis-ai', 'QGIS AI', 'AI-enhanced open source GIS with automated geoprocessing, spatial statistics, and machine learning integration.', 'https://qgis.org', 'research-data-analysis', 'Free', ARRAY['open-source-gis', 'geoprocessing', 'spatial-statistics'], false, false, 'https://qgis.org/favicon.ico'),
  ('research-google-earth-engine', 'Google Earth Engine', 'AI-powered planetary-scale geospatial analysis with automated change detection, classification, and time series analysis.', 'https://earthengine.google.com', 'research-data-analysis', 'Free', ARRAY['geospatial-analysis', 'change-detection', 'time-series'], false, false, 'https://earthengine.google.com/favicon.ico'),
  ('research-mapbox-ai', 'Mapbox AI', 'AI-enhanced mapping platform with automated route optimization, location intelligence, and spatial analytics.', 'https://mapbox.com', 'research-data-analysis', 'Paid', ARRAY['mapping-platform', 'route-optimization', 'location-intelligence'], false, false, 'https://mapbox.com/favicon.ico'),
  ('research-carto-ai', 'CARTO AI', 'AI-powered location intelligence platform with automated spatial analysis, predictive modeling, and visualization.', 'https://carto.com', 'research-data-analysis', 'Paid', ARRAY['location-intelligence', 'spatial-analysis', 'predictive-modeling'], false, false, 'https://carto.com/favicon.ico'),
  ('research-kepler-gl', 'Kepler.gl AI', 'AI-enhanced geospatial data visualization tool with automated layer suggestions and interactive exploration.', 'https://kepler.gl', 'research-data-analysis', 'Free', ARRAY['geospatial-visualization', 'layer-suggestions', 'interactive-exploration'], false, false, 'https://kepler.gl/favicon.ico'),
  ('research-folium-ai', 'Folium AI', 'AI-powered Python library for geospatial data visualization with automated map generation and styling.', 'https://folium.readthedocs.io', 'research-data-analysis', 'Free', ARRAY['geospatial-visualization', 'automated-generation', 'python-library'], false, false, 'https://folium.readthedocs.io/favicon.ico'),
  ('research-geopandas', 'GeoPandas AI', 'AI-enhanced Python library for geospatial data analysis with automated spatial operations and visualization.', 'https://geopandas.org', 'research-data-analysis', 'Free', ARRAY['geospatial-analysis', 'spatial-operations', 'python-library'], false, false, 'https://geopandas.org/favicon.ico'),
  
  -- Financial & Economic Analysis
  ('research-bloomberg-ai', 'Bloomberg Terminal AI', 'AI-powered financial data platform with automated market analysis, risk assessment, and trading insights.', 'https://bloomberg.com/terminal', 'research-data-analysis', 'Paid', ARRAY['financial-data', 'market-analysis', 'trading-insights'], false, false, 'https://bloomberg.com/favicon.ico'),
  ('research-refinitiv-ai', 'Refinitiv AI', 'AI-enhanced financial data and analytics platform with automated research, risk modeling, and market intelligence.', 'https://refinitiv.com', 'research-data-analysis', 'Paid', ARRAY['financial-analytics', 'risk-modeling', 'market-intelligence'], false, false, 'https://refinitiv.com/favicon.ico'),
  ('research-morningstar-ai', 'Morningstar AI', 'AI-powered investment research platform with automated portfolio analysis, risk assessment, and performance attribution.', 'https://morningstar.com', 'research-data-analysis', 'Paid', ARRAY['investment-research', 'portfolio-analysis', 'performance-attribution'], false, false, 'https://morningstar.com/favicon.ico'),
  ('research-factset-ai', 'FactSet AI', 'AI-enhanced financial analytics platform with automated research workflows, market screening, and quantitative analysis.', 'https://factset.com', 'research-data-analysis', 'Paid', ARRAY['financial-analytics', 'research-workflows', 'quantitative-analysis'], false, false, 'https://factset.com/favicon.ico'),
  ('research-quandl', 'Quandl AI', 'AI-powered financial and economic data platform with automated data curation, analysis tools, and API access.', 'https://quandl.com', 'research-data-analysis', 'Freemium', ARRAY['financial-data', 'data-curation', 'api-access'], false, false, 'https://quandl.com/favicon.ico'),
  ('research-alpha-architect', 'Alpha Architect AI', 'AI-enhanced quantitative investment research with automated factor analysis, backtesting, and strategy development.', 'https://alphaarchitect.com', 'research-data-analysis', 'Paid', ARRAY['quantitative-research', 'factor-analysis', 'strategy-development'], false, false, 'https://alphaarchitect.com/favicon.ico'),
  ('research-quantconnect', 'QuantConnect AI', 'AI-powered algorithmic trading platform with automated strategy development, backtesting, and live trading.', 'https://quantconnect.com', 'research-data-analysis', 'Freemium', ARRAY['algorithmic-trading', 'strategy-development', 'backtesting'], false, false, 'https://quantconnect.com/favicon.ico'),
  ('research-zipline', 'Zipline AI', 'AI-enhanced algorithmic trading library with automated backtesting, performance analysis, and risk management.', 'https://zipline.ml4trading.io', 'research-data-analysis', 'Free', ARRAY['algorithmic-trading', 'backtesting', 'risk-management'], false, false, 'https://zipline.ml4trading.io/favicon.ico')
ON CONFLICT (id, category_id) DO NOTHING;

-- Update the tool count for the category
UPDATE categories 
SET tool_count = (
  SELECT COUNT(*) 
  FROM tools 
  WHERE category_id = 'research-data-analysis'
) 
WHERE id = 'research-data-analysis';
