-- Image Analysis AI Tools (100 tools)
-- This script adds 100 AI-powered tools for image analysis and recognition
-- Covers computer vision, object detection, OCR, medical imaging, security, and visual AI
-- Uses ON CONFLICT (id, category_id) DO NOTHING to avoid duplicates within the same category

INSERT INTO tools (
  id, name, description, url, category_id, 
  pricing, tags, featured, trending, logo_url
) VALUES 
  -- Computer Vision & Object Detection
  ('img-google-vision', 'Google Cloud Vision AI', 'AI-powered image analysis with object detection, text recognition, facial analysis, and content moderation capabilities.', 'https://cloud.google.com/vision', 'image-analysis', 'Paid', ARRAY['computer-vision', 'object-detection', 'text-recognition'], false, false, 'https://cloud.google.com/favicon.ico'),
  ('img-amazon-rekognition', 'Amazon Rekognition', 'AI image and video analysis service with facial recognition, object detection, scene analysis, and content moderation.', 'https://aws.amazon.com/rekognition', 'image-analysis', 'Paid', ARRAY['facial-recognition', 'object-detection', 'content-moderation'], false, false, 'https://aws.amazon.com/favicon.ico'),
  ('img-microsoft-cognitive', 'Microsoft Computer Vision', 'AI-powered image analysis with optical character recognition, spatial analysis, and intelligent image tagging.', 'https://azure.microsoft.com/cognitive-services/computer-vision', 'image-analysis', 'Paid', ARRAY['ocr', 'spatial-analysis', 'image-tagging'], false, false, 'https://azure.microsoft.com/favicon.ico'),
  ('img-clarifai', 'Clarifai', 'AI platform for computer vision with custom model training, visual search, and content moderation at scale.', 'https://clarifai.com', 'image-analysis', 'Freemium', ARRAY['custom-models', 'visual-search', 'content-moderation'], false, false, 'https://clarifai.com/favicon.ico'),
  ('img-roboflow', 'Roboflow', 'AI computer vision platform for dataset management, model training, and deployment with annotation tools.', 'https://roboflow.com', 'image-analysis', 'Freemium', ARRAY['dataset-management', 'model-training', 'annotation-tools'], false, false, 'https://roboflow.com/favicon.ico'),
  ('img-yolo', 'YOLO (You Only Look Once)', 'Real-time AI object detection system for identifying and localizing multiple objects in images and videos.', 'https://pjreddie.com/darknet/yolo', 'image-analysis', 'Free', ARRAY['real-time-detection', 'object-localization', 'multiple-objects'], false, false, 'https://pjreddie.com/favicon.ico'),
  ('img-imagga', 'Imagga', 'AI image recognition and analysis API with auto-tagging, color extraction, and visual similarity search.', 'https://imagga.com', 'image-analysis', 'Freemium', ARRAY['auto-tagging', 'color-extraction', 'visual-similarity'], false, false, 'https://imagga.com/favicon.ico'),
  ('img-visionai', 'VisionAI', 'Advanced computer vision platform with custom AI model development for industrial and commercial applications.', 'https://visionai.com', 'image-analysis', 'Paid', ARRAY['custom-ai-models', 'industrial-applications', 'commercial-vision'], false, false, 'https://visionai.com/favicon.ico'),
  
  -- Optical Character Recognition (OCR)
  ('img-tesseract', 'Tesseract OCR', 'Open-source AI optical character recognition engine that converts images of text into machine-readable text.', 'https://tesseract-ocr.github.io', 'image-analysis', 'Free', ARRAY['open-source-ocr', 'text-extraction', 'machine-readable'], false, false, 'https://tesseract-ocr.github.io/favicon.ico'),
  ('img-abbyy-finereader', 'ABBYY FineReader', 'AI-powered OCR and document processing software with intelligent text recognition and format preservation.', 'https://abbyy.com/finereader', 'image-analysis', 'Paid', ARRAY['document-processing', 'intelligent-ocr', 'format-preservation'], false, false, 'https://abbyy.com/favicon.ico'),
  ('img-adobe-acrobat', 'Adobe Acrobat OCR', 'AI-enhanced PDF processing with optical character recognition, text editing, and document conversion.', 'https://acrobat.adobe.com', 'image-analysis', 'Paid', ARRAY['pdf-processing', 'text-editing', 'document-conversion'], false, false, 'https://acrobat.adobe.com/favicon.ico'),
  ('img-textract', 'Amazon Textract', 'AI service that automatically extracts text, handwriting, and data from scanned documents and forms.', 'https://aws.amazon.com/textract', 'image-analysis', 'Paid', ARRAY['text-extraction', 'handwriting-recognition', 'form-processing'], false, false, 'https://aws.amazon.com/favicon.ico'),
  ('img-google-ocr', 'Google Cloud Document AI', 'AI-powered document understanding with OCR, form parsing, and intelligent document processing.', 'https://cloud.google.com/document-ai', 'image-analysis', 'Paid', ARRAY['document-understanding', 'form-parsing', 'intelligent-processing'], false, false, 'https://cloud.google.com/favicon.ico'),
  ('img-azure-ocr', 'Azure Form Recognizer', 'AI service that extracts text, key-value pairs, and tables from documents using machine learning.', 'https://azure.microsoft.com/form-recognizer', 'image-analysis', 'Paid', ARRAY['key-value-extraction', 'table-extraction', 'machine-learning'], false, false, 'https://azure.microsoft.com/favicon.ico'),
  ('img-mathpix', 'Mathpix', 'AI-powered OCR for mathematical equations, converting handwritten or printed math into LaTeX and MathML.', 'https://mathpix.com', 'image-analysis', 'Freemium', ARRAY['mathematical-ocr', 'equation-recognition', 'latex-conversion'], false, false, 'https://mathpix.com/favicon.ico'),
  ('img-easyocr', 'EasyOCR', 'Open-source AI OCR library supporting 80+ languages with simple implementation and high accuracy.', 'https://github.com/JaidedAI/EasyOCR', 'image-analysis', 'Free', ARRAY['open-source', '80-languages', 'high-accuracy'], false, false, 'https://github.com/favicon.ico'),
  
  -- Facial Recognition & Analysis
  ('img-face-plus-plus', 'Face++', 'AI facial recognition platform with emotion detection, age estimation, and facial landmark analysis.', 'https://faceplusplus.com', 'image-analysis', 'Freemium', ARRAY['facial-recognition', 'emotion-detection', 'age-estimation'], false, false, 'https://faceplusplus.com/favicon.ico'),
  ('img-kairos', 'Kairos', 'AI facial recognition API with emotion analysis, demographic detection, and face verification capabilities.', 'https://kairos.com', 'image-analysis', 'Paid', ARRAY['emotion-analysis', 'demographic-detection', 'face-verification'], false, false, 'https://kairos.com/favicon.ico'),
  ('img-luxand', 'Luxand FaceSDK', 'AI facial recognition SDK with face detection, identification, and emotion recognition for developers.', 'https://luxand.com', 'image-analysis', 'Paid', ARRAY['facial-sdk', 'face-identification', 'emotion-recognition'], false, false, 'https://luxand.com/favicon.ico'),
  ('img-betaface', 'BetaFace', 'AI facial recognition and analysis API with face detection, recognition, and biometric measurements.', 'https://betaface.com', 'image-analysis', 'Freemium', ARRAY['biometric-measurements', 'face-detection', 'facial-analysis'], false, false, 'https://betaface.com/favicon.ico'),
  ('img-deepface', 'DeepFace', 'Open-source AI facial recognition framework with age, gender, emotion, and race analysis capabilities.', 'https://github.com/serengil/deepface', 'image-analysis', 'Free', ARRAY['open-source-facial', 'gender-analysis', 'race-analysis'], false, false, 'https://github.com/favicon.ico'),
  ('img-aws-recognition', 'AWS Facial Analysis', 'AI-powered facial analysis service with celebrity recognition, emotion detection, and face comparison.', 'https://aws.amazon.com/rekognition/face-detection-and-analysis', 'image-analysis', 'Paid', ARRAY['celebrity-recognition', 'face-comparison', 'emotion-detection'], false, false, 'https://aws.amazon.com/favicon.ico'),
  ('img-opencv-face', 'OpenCV Face Recognition', 'Open-source computer vision library with AI-powered face detection and recognition algorithms.', 'https://opencv.org', 'image-analysis', 'Free', ARRAY['open-source-cv', 'face-algorithms', 'computer-vision'], false, false, 'https://opencv.org/favicon.ico'),
  ('img-faceapi', 'Face-API.js', 'JavaScript AI library for face detection, recognition, and facial landmark detection in web browsers.', 'https://github.com/justadudewhohacks/face-api.js', 'image-analysis', 'Free', ARRAY['javascript-facial', 'web-browsers', 'facial-landmarks'], false, false, 'https://github.com/favicon.ico'),
  
  -- Medical Image Analysis
  ('img-aidoc', 'Aidoc', 'AI radiology platform that analyzes medical images to detect abnormalities and prioritize urgent cases.', 'https://aidoc.com', 'image-analysis', 'Paid', ARRAY['medical-radiology', 'abnormality-detection', 'urgent-cases'], false, false, 'https://aidoc.com/favicon.ico'),
  ('img-zebra-medical', 'Zebra Medical Vision', 'AI medical imaging platform for automated analysis of CT, MRI, and X-ray images with clinical insights.', 'https://zebra-med.com', 'image-analysis', 'Paid', ARRAY['medical-imaging', 'ct-mri-xray', 'clinical-insights'], false, false, 'https://zebra-med.com/favicon.ico'),
  ('img-google-deepmind', 'Google DeepMind Health', 'AI system for medical image analysis including diabetic retinopathy and cancer detection in medical scans.', 'https://deepmind.com/applied/deepmind-health', 'image-analysis', 'Paid', ARRAY['diabetic-retinopathy', 'cancer-detection', 'medical-scans'], false, false, 'https://deepmind.com/favicon.ico'),
  ('img-paige-ai', 'Paige.AI', 'AI-powered digital pathology platform for cancer diagnosis and treatment planning from tissue images.', 'https://paige.ai', 'image-analysis', 'Paid', ARRAY['digital-pathology', 'cancer-diagnosis', 'tissue-analysis'], false, false, 'https://paige.ai/favicon.ico'),
  ('img-butterfly-iq', 'Butterfly iQ', 'AI-powered ultrasound device with automated image optimization and diagnostic assistance.', 'https://butterflynetinc.com', 'image-analysis', 'Paid', ARRAY['ai-ultrasound', 'image-optimization', 'diagnostic-assistance'], false, false, 'https://butterflynetinc.com/favicon.ico'),
  ('img-arterys', 'Arterys', 'AI medical imaging platform for cardiac, lung, and liver analysis with cloud-based processing.', 'https://arterys.com', 'image-analysis', 'Paid', ARRAY['cardiac-analysis', 'lung-liver-analysis', 'cloud-processing'], false, false, 'https://arterys.com/favicon.ico'),
  ('img-enlitic', 'Enlitic', 'AI medical imaging platform that analyzes radiological images to assist in diagnosis and treatment decisions.', 'https://enlitic.com', 'image-analysis', 'Paid', ARRAY['radiological-analysis', 'diagnosis-assistance', 'treatment-decisions'], false, false, 'https://enlitic.com/favicon.ico'),
  ('img-qure-ai', 'Qure.ai', 'AI-powered medical imaging platform for chest X-rays, CT scans, and eye imaging with automated reporting.', 'https://qure.ai', 'image-analysis', 'Paid', ARRAY['chest-xrays', 'ct-scans', 'automated-reporting'], false, false, 'https://qure.ai/favicon.ico'),
  
  -- Visual Search & Similarity
  ('img-google-lens', 'Google Lens', 'AI-powered visual search tool that identifies objects, text, and landmarks through smartphone camera.', 'https://lens.google.com', 'image-analysis', 'Free', ARRAY['visual-search', 'object-identification', 'landmark-recognition'], false, false, 'https://lens.google.com/favicon.ico'),
  ('img-bing-visual', 'Bing Visual Search', 'AI visual search engine that finds similar images, products, and related content from uploaded photos.', 'https://bing.com/visualsearch', 'image-analysis', 'Free', ARRAY['similar-images', 'product-search', 'related-content'], false, false, 'https://bing.com/favicon.ico'),
  ('img-pinterest-lens', 'Pinterest Lens', 'AI visual discovery tool that identifies objects in photos and suggests related pins and products.', 'https://pinterest.com/lens', 'image-analysis', 'Free', ARRAY['visual-discovery', 'object-identification', 'product-suggestions'], false, false, 'https://pinterest.com/favicon.ico'),
  ('img-tineye', 'TinEye', 'AI-powered reverse image search engine that finds where images appear online and tracks image usage.', 'https://tineye.com', 'image-analysis', 'Freemium', ARRAY['reverse-image-search', 'image-tracking', 'usage-detection'], false, false, 'https://tineye.com/favicon.ico'),
  ('img-yandex-images', 'Yandex Images', 'AI visual search platform with advanced image recognition and similarity matching capabilities.', 'https://yandex.com/images', 'image-analysis', 'Free', ARRAY['image-recognition', 'similarity-matching', 'visual-platform'], false, false, 'https://yandex.com/favicon.ico'),
  ('img-camfind', 'CamFind', 'AI-powered visual search app that identifies objects, products, and provides shopping and information results.', 'https://camfindapp.com', 'image-analysis', 'Free', ARRAY['object-identification', 'product-recognition', 'shopping-results'], false, false, 'https://camfindapp.com/favicon.ico'),
  ('img-aliexpress-search', 'AliExpress Image Search', 'AI visual search tool for finding similar products on AliExpress by uploading photos.', 'https://aliexpress.com', 'image-analysis', 'Free', ARRAY['product-search', 'e-commerce', 'photo-upload'], false, false, 'https://aliexpress.com/favicon.ico'),
  ('img-amazon-style', 'Amazon StyleSnap', 'AI fashion search tool that finds similar clothing and accessories from uploaded photos.', 'https://amazon.com/stylesnap', 'image-analysis', 'Free', ARRAY['fashion-search', 'clothing-recognition', 'accessory-matching'], false, false, 'https://amazon.com/favicon.ico'),
  
  -- Content Moderation & Safety
  ('img-azure-content', 'Azure Content Moderator', 'AI content moderation service that detects inappropriate images, text, and videos automatically.', 'https://azure.microsoft.com/content-moderator', 'image-analysis', 'Paid', ARRAY['content-moderation', 'inappropriate-detection', 'automated-safety'], false, false, 'https://azure.microsoft.com/favicon.ico'),
  ('img-aws-moderation', 'AWS Content Moderation', 'AI-powered content filtering service that identifies unsafe or inappropriate visual content.', 'https://aws.amazon.com/rekognition/content-moderation', 'image-analysis', 'Paid', ARRAY['content-filtering', 'unsafe-content', 'visual-moderation'], false, false, 'https://aws.amazon.com/favicon.ico'),
  ('img-google-safesearch', 'Google SafeSearch', 'AI content filtering system that identifies and filters explicit or inappropriate images and videos.', 'https://support.google.com/websearch/answer/510', 'image-analysis', 'Free', ARRAY['explicit-filtering', 'inappropriate-content', 'safe-browsing'], false, false, 'https://support.google.com/favicon.ico'),
  ('img-sightengine', 'Sightengine', 'AI content moderation API that detects nudity, violence, weapons, and other inappropriate visual content.', 'https://sightengine.com', 'image-analysis', 'Freemium', ARRAY['nudity-detection', 'violence-detection', 'weapon-detection'], false, false, 'https://sightengine.com/favicon.ico'),
  ('img-hive-moderation', 'Hive AI Moderation', 'AI-powered content moderation platform with real-time detection of inappropriate images and videos.', 'https://hivemoderation.com', 'image-analysis', 'Paid', ARRAY['real-time-moderation', 'inappropriate-images', 'content-safety'], false, false, 'https://hivemoderation.com/favicon.ico'),
  ('img-crisp-thinking', 'Crisp Thinking', 'AI content moderation and digital risk assessment platform for social media and user-generated content.', 'https://crispthinking.com', 'image-analysis', 'Paid', ARRAY['digital-risk', 'social-media-moderation', 'user-content'], false, false, 'https://crispthinking.com/favicon.ico'),
  ('img-websafety', 'WebSafety AI', 'AI-powered image analysis for detecting unsafe content, cyberbullying, and online threats.', 'https://websafety.ai', 'image-analysis', 'Paid', ARRAY['unsafe-content', 'cyberbullying-detection', 'online-threats'], false, false, 'https://websafety.ai/favicon.ico'),
  ('img-besedo', 'Besedo', 'AI content moderation platform that automatically detects and removes inappropriate visual content.', 'https://besedo.com', 'image-analysis', 'Paid', ARRAY['automatic-detection', 'content-removal', 'visual-moderation'], false, false, 'https://besedo.com/favicon.ico'),
  
  -- Document Analysis & Processing
  ('img-docparser', 'Docparser', 'AI-powered document processing that extracts data from PDFs, invoices, and forms automatically.', 'https://docparser.com', 'image-analysis', 'Freemium', ARRAY['document-processing', 'data-extraction', 'invoice-processing'], false, false, 'https://docparser.com/favicon.ico'),
  ('img-rossum', 'Rossum', 'AI platform for intelligent document processing with automated data extraction from invoices and receipts.', 'https://rossum.ai', 'image-analysis', 'Paid', ARRAY['intelligent-processing', 'invoice-extraction', 'receipt-processing'], false, false, 'https://rossum.ai/favicon.ico'),
  ('img-hyperscience', 'HyperScience', 'AI document processing platform that automates data extraction from unstructured documents.', 'https://hyperscience.com', 'image-analysis', 'Paid', ARRAY['unstructured-documents', 'automated-extraction', 'document-automation'], false, false, 'https://hyperscience.com/favicon.ico'),
  ('img-mindee', 'Mindee', 'AI-powered document parsing API that extracts structured data from receipts, invoices, and IDs.', 'https://mindee.com', 'image-analysis', 'Freemium', ARRAY['document-parsing', 'structured-data', 'receipt-invoice-id'], false, false, 'https://mindee.com/favicon.ico'),
  ('img-klippa', 'Klippa', 'AI document processing platform with OCR, data extraction, and automated invoice processing capabilities.', 'https://klippa.com', 'image-analysis', 'Paid', ARRAY['ocr-processing', 'data-extraction', 'automated-invoicing'], false, false, 'https://klippa.com/favicon.ico'),
  ('img-extracttable', 'ExtractTable', 'AI service that converts tables in images and PDFs into structured data formats like Excel.', 'https://extracttable.com', 'image-analysis', 'Freemium', ARRAY['table-extraction', 'structured-data', 'excel-conversion'], false, false, 'https://extracttable.com/favicon.ico'),
  ('img-nanonets', 'Nanonets', 'AI platform for custom OCR and document processing with model training for specific use cases.', 'https://nanonets.com', 'image-analysis', 'Freemium', ARRAY['custom-ocr', 'model-training', 'specific-use-cases'], false, false, 'https://nanonets.com/favicon.ico'),
  ('img-documint', 'Documint', 'AI document analysis platform that extracts and processes information from various document types.', 'https://documint.me', 'image-analysis', 'Paid', ARRAY['document-analysis', 'information-extraction', 'various-documents'], false, false, 'https://documint.me/favicon.ico'),
  
  -- Quality Control & Inspection
  ('img-cognex-visionpro', 'Cognex VisionPro', 'AI-powered machine vision software for industrial quality control and automated inspection.', 'https://cognex.com/visionpro', 'image-analysis', 'Paid', ARRAY['machine-vision', 'quality-control', 'automated-inspection'], false, false, 'https://cognex.com/favicon.ico'),
  ('img-keyence-vision', 'Keyence Vision System', 'AI vision inspection system for manufacturing quality control with defect detection capabilities.', 'https://keyence.com/vision', 'image-analysis', 'Paid', ARRAY['manufacturing-qc', 'defect-detection', 'vision-inspection'], false, false, 'https://keyence.com/favicon.ico'),
  ('img-omron-vision', 'Omron FH Vision', 'AI-powered vision system for industrial automation with high-speed image processing and analysis.', 'https://omron.com/vision', 'image-analysis', 'Paid', ARRAY['industrial-automation', 'high-speed-processing', 'image-analysis'], false, false, 'https://omron.com/favicon.ico'),
  ('img-sick-vision', 'SICK Vision Systems', 'AI machine vision solutions for logistics, automotive, and electronics quality inspection.', 'https://sick.com/vision', 'image-analysis', 'Paid', ARRAY['logistics-automotive', 'electronics-inspection', 'machine-vision'], false, false, 'https://sick.com/favicon.ico'),
  ('img-basler-vision', 'Basler Vision', 'AI-enhanced machine vision cameras and software for industrial inspection and quality assurance.', 'https://baslerweb.com', 'image-analysis', 'Paid', ARRAY['machine-vision-cameras', 'industrial-inspection', 'quality-assurance'], false, false, 'https://baslerweb.com/favicon.ico'),
  ('img-neurala', 'Neurala VIA', 'AI visual inspection automation platform for manufacturing defect detection and quality control.', 'https://neurala.com', 'image-analysis', 'Paid', ARRAY['visual-inspection', 'manufacturing-defects', 'automation-platform'], false, false, 'https://neurala.com/favicon.ico'),
  ('img-landing-ai', 'Landing AI', 'AI platform for visual inspection in manufacturing with custom model development and deployment.', 'https://landing.ai', 'image-analysis', 'Paid', ARRAY['visual-inspection', 'manufacturing', 'custom-models'], false, false, 'https://landing.ai/favicon.ico'),
  ('img-chooch-ai', 'Chooch AI', 'Computer vision AI platform for industrial inspection, surveillance, and automated quality control.', 'https://chooch.ai', 'image-analysis', 'Paid', ARRAY['industrial-inspection', 'surveillance', 'automated-qc'], false, false, 'https://chooch.ai/favicon.ico'),
  
  -- Automotive & Transportation
  ('img-mobileye', 'Mobileye', 'AI-powered computer vision system for autonomous vehicles with object detection and collision avoidance.', 'https://mobileye.com', 'image-analysis', 'Paid', ARRAY['autonomous-vehicles', 'collision-avoidance', 'object-detection'], false, false, 'https://mobileye.com/favicon.ico'),
  ('img-tesla-autopilot', 'Tesla Autopilot Vision', 'AI computer vision system for Tesla vehicles with real-time road analysis and autonomous driving.', 'https://tesla.com/autopilot', 'image-analysis', 'Paid', ARRAY['tesla-vehicles', 'road-analysis', 'autonomous-driving'], false, false, 'https://tesla.com/favicon.ico'),
  ('img-waymo-vision', 'Waymo Computer Vision', 'AI vision system for autonomous vehicles with advanced perception and environmental understanding.', 'https://waymo.com', 'image-analysis', 'Paid', ARRAY['autonomous-vehicles', 'environmental-understanding', 'advanced-perception'], false, false, 'https://waymo.com/favicon.ico'),
  ('img-scale-ai', 'Scale AI', 'AI data platform for autonomous vehicles providing image annotation and computer vision training data.', 'https://scale.com', 'image-analysis', 'Paid', ARRAY['training-data', 'image-annotation', 'autonomous-vehicles'], false, false, 'https://scale.com/favicon.ico'),
  ('img-aptiv', 'Aptiv ADAS', 'AI-powered advanced driver assistance systems with camera-based perception and safety features.', 'https://aptiv.com', 'image-analysis', 'Paid', ARRAY['driver-assistance', 'camera-perception', 'safety-features'], false, false, 'https://aptiv.com/favicon.ico'),
  ('img-continental-vision', 'Continental Vision', 'AI computer vision solutions for automotive applications including surround view and parking assistance.', 'https://continental.com', 'image-analysis', 'Paid', ARRAY['automotive-vision', 'surround-view', 'parking-assistance'], false, false, 'https://continental.com/favicon.ico'),
  ('img-bosch-vision', 'Bosch Computer Vision', 'AI vision systems for automotive safety with traffic sign recognition and lane detection.', 'https://bosch.com', 'image-analysis', 'Paid', ARRAY['automotive-safety', 'traffic-signs', 'lane-detection'], false, false, 'https://bosch.com/favicon.ico'),
  ('img-cruise-vision', 'Cruise Vision', 'AI computer vision platform for autonomous vehicles with real-time perception and decision making.', 'https://getcruise.com', 'image-analysis', 'Paid', ARRAY['autonomous-vehicles', 'real-time-perception', 'decision-making'], false, false, 'https://getcruise.com/favicon.ico'),
  
  -- Retail & E-commerce
  ('img-visual-search-api', 'Visual Search API', 'AI-powered visual search solution for e-commerce with product recognition and similarity matching.', 'https://visualsearchapi.com', 'image-analysis', 'Paid', ARRAY['e-commerce-search', 'product-recognition', 'similarity-matching'], false, false, 'https://visualsearchapi.com/favicon.ico'),
  ('img-slyce', 'Slyce Visual Search', 'AI visual search platform for retail with image recognition and product discovery capabilities.', 'https://slyce.it', 'image-analysis', 'Paid', ARRAY['retail-search', 'image-recognition', 'product-discovery'], false, false, 'https://slyce.it/favicon.ico'),
  ('img-where2get', 'Where2GetIt', 'AI visual search app that identifies fashion items and finds where to purchase similar products.', 'https://where2getit.com', 'image-analysis', 'Free', ARRAY['fashion-search', 'product-identification', 'purchase-finder'], false, false, 'https://where2getit.com/favicon.ico'),
  ('img-screenshop', 'ScreenShop', 'AI-powered app that identifies products in screenshots and provides shopping links and alternatives.', 'https://screenshop.io', 'image-analysis', 'Free', ARRAY['screenshot-analysis', 'product-identification', 'shopping-links'], false, false, 'https://screenshop.io/favicon.ico'),
  ('img-snap-to-shop', 'Snap to Shop', 'AI visual search platform for fashion and lifestyle products with instant product identification.', 'https://snaptoshop.com', 'image-analysis', 'Freemium', ARRAY['fashion-lifestyle', 'instant-identification', 'visual-shopping'], false, false, 'https://snaptoshop.com/favicon.ico'),
  ('img-findify', 'Findify Visual Search', 'AI-powered search and discovery platform for e-commerce with visual search capabilities.', 'https://findify.io', 'image-analysis', 'Paid', ARRAY['e-commerce-discovery', 'visual-search', 'search-platform'], false, false, 'https://findify.io/favicon.ico'),
  ('img-yotpo-visual', 'Yotpo Visual UGC', 'AI platform that analyzes user-generated content images for brand mentions and product identification.', 'https://yotpo.com', 'image-analysis', 'Paid', ARRAY['user-generated-content', 'brand-mentions', 'product-identification'], false, false, 'https://yotpo.com/favicon.ico'),
  ('img-vue-ai', 'Vue.ai', 'AI platform for fashion and lifestyle brands with visual search, styling, and trend analysis.', 'https://vue.ai', 'image-analysis', 'Paid', ARRAY['fashion-brands', 'styling-analysis', 'trend-analysis'], false, false, 'https://vue.ai/favicon.ico'),
  
  -- Security & Surveillance
  ('img-hikvision-ai', 'Hikvision AI', 'AI-powered video surveillance system with facial recognition, behavior analysis, and threat detection.', 'https://hikvision.com', 'image-analysis', 'Paid', ARRAY['video-surveillance', 'behavior-analysis', 'threat-detection'], false, false, 'https://hikvision.com/favicon.ico'),
  ('img-milestone-ai', 'Milestone XProtect', 'AI video management platform with intelligent video analytics and automated incident detection.', 'https://milestonesys.com', 'image-analysis', 'Paid', ARRAY['video-management', 'intelligent-analytics', 'incident-detection'], false, false, 'https://milestonesys.com/favicon.ico'),
  ('img-axis-analytics', 'Axis Video Analytics', 'AI-powered video analytics for security cameras with object classification and behavior detection.', 'https://axis.com', 'image-analysis', 'Paid', ARRAY['security-cameras', 'object-classification', 'behavior-detection'], false, false, 'https://axis.com/favicon.ico'),
  ('img-verkada', 'Verkada', 'AI cloud-based security camera system with facial recognition, vehicle detection, and anomaly detection.', 'https://verkada.com', 'image-analysis', 'Paid', ARRAY['cloud-security', 'vehicle-detection', 'anomaly-detection'], false, false, 'https://verkada.com/favicon.ico'),
  ('img-deepstream', 'NVIDIA DeepStream', 'AI platform for video analytics with real-time object detection and tracking for security applications.', 'https://nvidia.com/deepstream', 'image-analysis', 'Paid', ARRAY['video-analytics', 'real-time-tracking', 'security-applications'], false, false, 'https://nvidia.com/favicon.ico'),
  ('img-briefcam', 'BriefCam', 'AI video analytics platform that transforms surveillance footage into actionable intelligence and insights.', 'https://briefcam.com', 'image-analysis', 'Paid', ARRAY['surveillance-analytics', 'actionable-intelligence', 'video-insights'], false, false, 'https://briefcam.com/favicon.ico'),
  ('img-avigilon', 'Avigilon Analytics', 'AI video analytics with facial recognition, license plate recognition, and behavioral analysis.', 'https://avigilon.com', 'image-analysis', 'Paid', ARRAY['license-plate-recognition', 'behavioral-analysis', 'facial-recognition'], false, false, 'https://avigilon.com/favicon.ico'),
  ('img-genetec', 'Genetec Security Center', 'AI-powered unified security platform with video analytics, access control, and threat detection.', 'https://genetec.com', 'image-analysis', 'Paid', ARRAY['unified-security', 'access-control', 'threat-detection'], false, false, 'https://genetec.com/favicon.ico'),
  
  -- Sports & Entertainment
  ('img-hawkeye', 'Hawk-Eye', 'AI computer vision system for sports with ball tracking, line calling, and performance analysis.', 'https://hawkeyeinnovations.com', 'image-analysis', 'Paid', ARRAY['sports-analysis', 'ball-tracking', 'performance-analysis'], false, false, 'https://hawkeyeinnovations.com/favicon.ico'),
  ('img-second-spectrum', 'Second Spectrum', 'AI sports analytics platform with player tracking, game analysis, and broadcast enhancement.', 'https://secondspectrum.com', 'image-analysis', 'Paid', ARRAY['sports-analytics', 'player-tracking', 'broadcast-enhancement'], false, false, 'https://secondspectrum.com/favicon.ico'),
  ('img-sportvu', 'SportVU', 'AI player tracking system for basketball with real-time analytics and performance metrics.', 'https://sportvu.com', 'image-analysis', 'Paid', ARRAY['basketball-tracking', 'real-time-analytics', 'performance-metrics'], false, false, 'https://sportvu.com/favicon.ico'),
  ('img-catapult-sports', 'Catapult Sports', 'AI sports performance platform with video analysis, player tracking, and injury prevention.', 'https://catapultsports.com', 'image-analysis', 'Paid', ARRAY['sports-performance', 'video-analysis', 'injury-prevention'], false, false, 'https://catapultsports.com/favicon.ico'),
  ('img-hudl', 'Hudl', 'AI sports video analysis platform with automated tagging, highlight creation, and performance insights.', 'https://hudl.com', 'image-analysis', 'Freemium', ARRAY['sports-video', 'automated-tagging', 'highlight-creation'], false, false, 'https://hudl.com/favicon.ico'),
  ('img-pixellot', 'Pixellot', 'AI automated sports production system with multi-camera tracking and live streaming capabilities.', 'https://pixellot.tv', 'image-analysis', 'Paid', ARRAY['automated-production', 'multi-camera-tracking', 'live-streaming'], false, false, 'https://pixellot.tv/favicon.ico'),
  ('img-veo', 'Veo', 'AI camera system for sports that automatically records and analyzes games with player tracking.', 'https://veo.co', 'image-analysis', 'Paid', ARRAY['sports-recording', 'game-analysis', 'automatic-tracking'], false, false, 'https://veo.co/favicon.ico'),
  ('img-trace', 'Trace', 'AI sports camera that automatically tracks players and creates highlight videos with performance data.', 'https://trace.gg', 'image-analysis', 'Paid', ARRAY['automatic-tracking', 'highlight-videos', 'performance-data'], false, false, 'https://trace.gg/favicon.ico'),
  
  -- Real Estate & Property
  ('img-matterport', 'Matterport', 'AI-powered 3D capture platform for real estate with virtual tours and spatial analysis.', 'https://matterport.com', 'image-analysis', 'Paid', ARRAY['3d-capture', 'virtual-tours', 'spatial-analysis'], false, false, 'https://matterport.com/favicon.ico'),
  ('img-realestate-ai', 'RealEstate AI', 'AI platform for property valuation and analysis using computer vision and market data.', 'https://realestate.ai', 'image-analysis', 'Paid', ARRAY['property-valuation', 'market-analysis', 'computer-vision'], false, false, 'https://realestate.ai/favicon.ico'),
  ('img-homelight', 'HomeLight OwnerInsight', 'AI platform that analyzes property photos to estimate home values and suggest improvements.', 'https://homelight.com', 'image-analysis', 'Free', ARRAY['home-valuation', 'property-photos', 'improvement-suggestions'], false, false, 'https://homelight.com/favicon.ico'),
  ('img-opendoor-vision', 'Opendoor Vision', 'AI property assessment platform that analyzes home photos for automated valuations and condition reports.', 'https://opendoor.com', 'image-analysis', 'Paid', ARRAY['property-assessment', 'automated-valuations', 'condition-reports'], false, false, 'https://opendoor.com/favicon.ico'),
  ('img-structurely', 'Structurely', 'AI assistant for real estate with lead qualification and property matching based on image preferences.', 'https://structurely.com', 'image-analysis', 'Paid', ARRAY['lead-qualification', 'property-matching', 'image-preferences'], false, false, 'https://structurely.com/favicon.ico'),
  ('img-divvy-ai', 'Divvy Homes AI', 'AI platform for rent-to-own properties with automated property analysis and valuation.', 'https://divvyhomes.com', 'image-analysis', 'Paid', ARRAY['rent-to-own', 'property-analysis', 'automated-valuation'], false, false, 'https://divvyhomes.com/favicon.ico'),
  ('img-rentspree', 'RentSpree AI', 'AI rental platform with property photo analysis and automated listing optimization.', 'https://rentspree.com', 'image-analysis', 'Freemium', ARRAY['rental-platform', 'photo-analysis', 'listing-optimization'], false, false, 'https://rentspree.com/favicon.ico'),
  ('img-zestimate', 'Zillow Zestimate', 'AI property valuation model that analyzes home photos and market data for price estimates.', 'https://zillow.com/zestimate', 'image-analysis', 'Free', ARRAY['property-valuation', 'price-estimates', 'market-data'], false, false, 'https://zillow.com/favicon.ico')
ON CONFLICT (id, category_id) DO NOTHING;

-- Update the tool count for the category
UPDATE categories 
SET tool_count = (
  SELECT COUNT(*) 
  FROM tools 
  WHERE category_id = 'image-analysis'
) 
WHERE id = 'image-analysis';
