-- Check for existing tools before insertion
-- Run this query first to see which tools already exist

SELECT 
  id,
  name,
  category_id
FROM tools 
WHERE id IN (
  'midjourney',
  'dall-e-2',
  'stable-diffusion',
  'runway-ml',
  'artbreeder',
  'deep-dream-generator',
  'wombo-dream',
  'nightcafe-creator',
  'starryai',
  'jasper-art',
  'deep-ai-art',
  'ai-painter',
  'neural-love',
  'let-enhance',
  'remove-bg',
  'canva-magic-design',
  'adobe-sensei',
  'photomosh',
  'ai-photo-enhancer',
  'deepart-io',
  'prisma',
  'luminar-ai',
  'topaz-gigapixel',
  'ai-art-generator-free',
  'deep-nostalgia',
  'ai-image-colorizer',
  'vance-ai',
  'bigjpg',
  'face-depixelizer',
  'artisto',
  'deepfacelab',
  'ai-cartoonizer',
  'waifu2x',
  'deep-art-effects',
  'avatarify',
  'deepface',
  'ai-photo-restorer',
  'super-resolution',
  'face-swap-online',
  'ai-background-remover',
  'style-transfer-pytorch',
  'ai-sketch-converter',
  'deepdream',
  'ai-anime-generator',
  'photo-colorizer-ai',
  'ai-portrait-generator',
  'neural-filters-photoshop',
  'ai-face-enhancer',
  'deepfakes-web',
  'ai-art-shop',
  'style-gan',
  'ai-music-video',
  'deepart-ai',
  'ai-logo-maker'
)
ORDER BY id;
