-- Update logo URLs for Chatbots & Virtual Companions tools
-- This script adds logo_url values for all tools in the Chatbots & Virtual Companions category

UPDATE tools 
SET logo_url = CASE 
    WHEN name = 'Character.AI' THEN 'https://character.ai/favicon.ico'
    WHEN name = 'Replika' THEN 'https://replika.com/favicon.ico'
    WHEN name = 'Chai' THEN 'https://www.chai-research.com/favicon.ico'
    WHEN name = 'Botify AI' THEN 'https://botify.com/favicon.ico'
    WHEN name = 'Kajiwoto' THEN 'https://kajiwoto.ai/favicon.ico'
    WHEN name = 'Anima AI' THEN 'https://myanima.ai/favicon.ico'
    WHEN name = 'SoulDeep AI' THEN 'https://souldeep.ai/favicon.ico'
    WHEN name = 'Romantic AI' THEN 'https://romantic.ai/favicon.ico'
    WHEN name = 'EVA AI' THEN 'https://eva.ai/favicon.ico'
    WHEN name = 'Paradot' THEN 'https://paradot.ai/favicon.ico'
    WHEN name = 'DreamBF' THEN 'https://dreambf.ai/favicon.ico'
    WHEN name = 'Nomi AI' THEN 'https://nomi.ai/favicon.ico'
    WHEN name = 'Kindroid' THEN 'https://kindroid.ai/favicon.ico'
    WHEN name = 'Crushon.AI' THEN 'https://crushon.ai/favicon.ico'
    WHEN name = 'Tavern AI' THEN 'https://tavernai.net/favicon.ico'
    WHEN name = 'Janitor AI' THEN 'https://janitorai.com/favicon.ico'
    WHEN name = 'SpicyChat AI' THEN 'https://spicychat.ai/favicon.ico'
    WHEN name = 'Muah AI' THEN 'https://muah.ai/favicon.ico'
    WHEN name = 'CrushOn AI' THEN 'https://crushon.ai/favicon.ico'
    WHEN name = 'Dittin AI' THEN 'https://dittin.ai/favicon.ico'
    WHEN name = 'Joyland AI' THEN 'https://joyland.ai/favicon.ico'
    WHEN name = 'Candy AI' THEN 'https://candy.ai/favicon.ico'
    WHEN name = 'Dreamgf AI' THEN 'https://dreamgf.ai/favicon.ico'
    WHEN name = 'FantasyGF AI' THEN 'https://fantasygf.ai/favicon.ico'
    WHEN name = 'Girlfriend GPT' THEN 'https://girlfriend-gpt.com/favicon.ico'
    WHEN name = 'MyAnima' THEN 'https://myanima.ai/favicon.ico'
    WHEN name = 'Nextpart AI' THEN 'https://nextpart.ai/favicon.ico'
    WHEN name = 'PepHop AI' THEN 'https://pephop.ai/favicon.ico'
    WHEN name = 'Seduced AI' THEN 'https://seduced.ai/favicon.ico'
    WHEN name = 'Soulgen AI' THEN 'https://soulgen.ai/favicon.ico'
    WHEN name = 'Waifu Labs' THEN 'https://waifulabs.com/favicon.ico'
    WHEN name = 'Kupid AI' THEN 'https://kupid.ai/favicon.ico'
    WHEN name = 'Candy.ai' THEN 'https://candy.ai/favicon.ico'
    WHEN name = 'DreamGF' THEN 'https://dreamgf.ai/favicon.ico'
    WHEN name = 'Promptchan AI' THEN 'https://promptchan.ai/favicon.ico'
    WHEN name = 'Unstable Diffusion' THEN 'https://unstable-diffusion.com/favicon.ico'
    WHEN name = 'OnlyWaifus' THEN 'https://onlywaifus.ai/favicon.ico'
    WHEN name = 'Waifu XL' THEN 'https://waifuxl.com/favicon.ico'
    WHEN name = 'AI Dungeon' THEN 'https://aidungeon.io/favicon.ico'
    WHEN name = 'Novel AI' THEN 'https://novelai.net/favicon.ico'
    WHEN name = 'Sudowrite' THEN 'https://sudowrite.com/favicon.ico'
    WHEN name = 'Inferkit' THEN 'https://inferkit.com/favicon.ico'
    WHEN name = 'ChatMapper' THEN 'https://chatmapper.com/favicon.ico'
    WHEN name = 'Botpress' THEN 'https://botpress.com/favicon.ico'
    WHEN name = 'Microsoft Bot Framework' THEN 'https://dev.botframework.com/favicon.ico'
    WHEN name = 'Rasa' THEN 'https://rasa.com/favicon.ico'
    WHEN name = 'Dialogflow' THEN 'https://cloud.google.com/favicon.ico'
    WHEN name = 'Amazon Lex' THEN 'https://aws.amazon.com/favicon.ico'
    WHEN name = 'IBM Watson Assistant' THEN 'https://ibm.com/favicon.ico'
    WHEN name = 'Wit.ai' THEN 'https://wit.ai/favicon.ico'
    WHEN name = 'ManyChat' THEN 'https://manychat.com/favicon.ico'
    WHEN name = 'Chatfuel' THEN 'https://chatfuel.com/favicon.ico'
    WHEN name = 'Flow XO' THEN 'https://flowxo.com/favicon.ico'
    WHEN name = 'Botsify' THEN 'https://botsify.com/favicon.ico'
    WHEN name = 'Motion AI' THEN 'https://motion.ai/favicon.ico'
    WHEN name = 'Sequel' THEN 'https://sequel.io/favicon.ico'
    WHEN name = 'Landbot' THEN 'https://landbot.io/favicon.ico'
    WHEN name = 'Tars' THEN 'https://hellotars.com/favicon.ico'
    WHEN name = 'Drift' THEN 'https://drift.com/favicon.ico'
    WHEN name = 'Intercom' THEN 'https://intercom.com/favicon.ico'
    WHEN name = 'Zendesk Chat' THEN 'https://zendesk.com/favicon.ico'
    WHEN name = 'LiveChat' THEN 'https://livechat.com/favicon.ico'
    WHEN name = 'Freshchat' THEN 'https://freshworks.com/favicon.ico'
    WHEN name = 'Crisp' THEN 'https://crisp.chat/favicon.ico'
    WHEN name = 'Tidio' THEN 'https://tidio.com/favicon.ico'
    WHEN name = 'Olark' THEN 'https://olark.com/favicon.ico'
    WHEN name = 'Pure Chat' THEN 'https://purechat.com/favicon.ico'
    WHEN name = 'Comm100' THEN 'https://comm100.com/favicon.ico'
    WHEN name = 'LiveAgent' THEN 'https://liveagent.com/favicon.ico'
    WHEN name = 'Help Scout' THEN 'https://helpscout.com/favicon.ico'
    WHEN name = 'UserVoice' THEN 'https://uservoice.com/favicon.ico'
    WHEN name = 'Kayako' THEN 'https://kayako.com/favicon.ico'
    WHEN name = 'Desk.com' THEN 'https://salesforce.com/favicon.ico'
    WHEN name = 'Zoho Desk' THEN 'https://zoho.com/favicon.ico'
    WHEN name = 'ServiceNow' THEN 'https://servicenow.com/favicon.ico'
    WHEN name = 'Salesforce Service Cloud' THEN 'https://salesforce.com/favicon.ico'
    WHEN name = 'HubSpot Service Hub' THEN 'https://hubspot.com/favicon.ico'
    WHEN name = 'Ada' THEN 'https://ada.cx/favicon.ico'
    WHEN name = 'Bold360' THEN 'https://bold360.com/favicon.ico'
    WHEN name = 'LiveWorld' THEN 'https://liveworld.com/favicon.ico'
    WHEN name = 'Acquire' THEN 'https://acquire.io/favicon.ico'
    WHEN name = 'Userlike' THEN 'https://userlike.com/favicon.ico'
    WHEN name = 'SnapEngage' THEN 'https://snapengage.com/favicon.ico'
    WHEN name = 'BoldChat' THEN 'https://boldchat.com/favicon.ico'
    WHEN name = 'Click4Assistance' THEN 'https://click4assistance.co.uk/favicon.ico'
    WHEN name = 'LivePerson' THEN 'https://liveperson.com/favicon.ico'
    WHEN name = 'ContactAtOnce' THEN 'https://contactatonce.com/favicon.ico'
    WHEN name = 'Velaro' THEN 'https://velaro.com/favicon.ico'
    WHEN name = 'Provide Support' THEN 'https://providesupport.com/favicon.ico'
    WHEN name = 'MyLiveChat' THEN 'https://mylivechat.com/favicon.ico'
    WHEN name = 'WebsiteAlive' THEN 'https://websitealive.com/favicon.ico'
    WHEN name = 'WhosOn' THEN 'https://whoson.com/favicon.ico'
    WHEN name = 'LiveZilla' THEN 'https://livezilla.net/favicon.ico'
    WHEN name = 'CafeX' THEN 'https://cafex.com/favicon.ico'
    WHEN name = 'eGain' THEN 'https://egain.com/favicon.ico'
    WHEN name = 'InContact' THEN 'https://incontact.com/favicon.ico'
    WHEN name = 'Genesys' THEN 'https://genesys.com/favicon.ico'
    WHEN name = 'Nuance' THEN 'https://nuance.com/favicon.ico'
    WHEN name = 'Aspect' THEN 'https://aspect.com/favicon.ico'
    WHEN name = 'Avaya' THEN 'https://avaya.com/favicon.ico'
    WHEN name = 'Cisco' THEN 'https://cisco.com/favicon.ico'
    WHEN name = 'Oracle' THEN 'https://oracle.com/favicon.ico'
    WHEN name = 'SAP' THEN 'https://sap.com/favicon.ico'
    WHEN name = 'Pegasystems' THEN 'https://pega.com/favicon.ico'
    WHEN name = 'Verint' THEN 'https://verint.com/favicon.ico'
    WHEN name = 'Nice' THEN 'https://nice.com/favicon.ico'
    WHEN name = 'Calabrio' THEN 'https://calabrio.com/favicon.ico'
    WHEN name = 'Envision' THEN 'https://envision.com/favicon.ico'
END
WHERE category_id = (SELECT id FROM categories WHERE name = 'Chatbots & Virtual Companions');

-- Verify the updates
SELECT name, logo_url 
FROM tools 
WHERE category_id = (SELECT id FROM categories WHERE name = 'Chatbots & Virtual Companions')
ORDER BY name;
