-- Update logo URLs for Coding & Development tools
-- This script adds logo URLs for tools that don't have them

UPDATE tools SET logo_url = 'https://kubernetes.io/images/favicon.png' WHERE name = 'Kubernetes AI';
UPDATE tools SET logo_url = 'https://helm.sh/img/helm.svg' WHERE name = 'Helm AI';
UPDATE tools SET logo_url = 'https://github.com/useblackbox/blackbox-vscode/raw/master/icon.png' WHERE name = 'Blackbox AI';
UPDATE tools SET logo_url = 'https://openai.com/favicon.ico' WHERE name = 'OpenAI Codex';
UPDATE tools SET logo_url = 'https://github.com/fauxpilot/fauxpilot/raw/main/img/fauxpilot.png' WHERE name = 'FauxPilot';
UPDATE tools SET logo_url = 'https://aicode.bot/favicon.ico' WHERE name = 'AI Code Bot';
UPDATE tools SET logo_url = 'https://d1.awsstatic.com/logos/aws-logo-lockups/poweredbyaws/PB_AWS_logo_RGB_REV_SQ.8c88ac215fe4e441dc42865dd6962ed4f444a90d.png' WHERE name = 'AWS Cloud9 AI';
UPDATE tools SET logo_url = 'https://cloud.google.com/_static/cloud/images/favicons/onecloud/favicon.ico' WHERE name = 'Google Cloud AI';
UPDATE tools SET logo_url = 'https://azure.microsoft.com/favicon.ico' WHERE name = 'Azure AI Services';
UPDATE tools SET logo_url = 'https://assets-global.website-files.com/5c7036349b5477bf13f828cf/5c7036349b5477d24bf828d6_codacy_round.svg' WHERE name = 'Codacy AI';
UPDATE tools SET logo_url = 'https://refactor.ai/favicon.ico' WHERE name = 'Refactor AI';
UPDATE tools SET logo_url = 'https://swagger.io/favicon-16x16.png' WHERE name = 'Swagger AI';
UPDATE tools SET logo_url = 'https://stoplight.io/favicon.png' WHERE name = 'Stoplight AI';
UPDATE tools SET logo_url = 'https://readme.com/favicon-32x32.png' WHERE name = 'ReadMe API AI';
UPDATE tools SET logo_url = 'https://zapier.com/favicon.ico' WHERE name = 'Zapier AI';
UPDATE tools SET logo_url = 'https://www.make.com/en/help/hc/theme_assets/01HZP9PH3XMDPFJ3MVQED9KMKE' WHERE name = 'Make AI';
UPDATE tools SET logo_url = 'https://unity.com/favicon.ico' WHERE name = 'Unity AI';
UPDATE tools SET logo_url = 'https://www.unrealengine.com/favicon.ico' WHERE name = 'Unreal Engine AI';
UPDATE tools SET logo_url = 'https://godotengine.org/assets/press/icon_color.png' WHERE name = 'Godot AI';
UPDATE tools SET logo_url = 'https://jupyter.org/favicon.ico' WHERE name = 'Jupyter AI';
UPDATE tools SET logo_url = 'https://colab.research.google.com/img/colab_favicon_256px.png' WHERE name = 'Google Colab AI';
UPDATE tools SET logo_url = 'https://bolt.new/favicon.ico' WHERE name = 'Bolt.new';
UPDATE tools SET logo_url = 'https://bubble-users-assets.s3.amazonaws.com/1673264516538x738004089056387100/favicon-32x32.png' WHERE name = 'Bubble';
UPDATE tools SET logo_url = 'https://v0.dev/favicon.ico' WHERE name = 'v0';
UPDATE tools SET logo_url = 'https://aismartcube.com/favicon.ico' WHERE name = 'AISmartCube';
UPDATE tools SET logo_url = 'https://trae.ai/favicon.ico' WHERE name = 'Trae AI';
UPDATE tools SET logo_url = 'https://buildglare.com/favicon.ico' WHERE name = 'Buildglare';
UPDATE tools SET logo_url = 'https://lecca.io/favicon.ico' WHERE name = 'Lecca.io';
UPDATE tools SET logo_url = 'https://genfuse.ai/favicon.ico' WHERE name = 'GenFuse AI';
UPDATE tools SET logo_url = 'https://code2.ai/favicon.ico' WHERE name = 'Code2.AI';
UPDATE tools SET logo_url = 'https://www.kaggle.com/static/images/favicon.ico' WHERE name = 'Kaggle AI';
UPDATE tools SET logo_url = 'https://github.com/eli64s/readme-ai/raw/main/docs/images/logo.png' WHERE name = 'README-AI';
UPDATE tools SET logo_url = 'https://lovable.dev/favicon.ico' WHERE name = 'Lovable';
UPDATE tools SET logo_url = 'https://testcraft.io/favicon.ico' WHERE name = 'TestCraft';
UPDATE tools SET logo_url = 'https://applitools.com/favicon.ico' WHERE name = 'Applitools';
UPDATE tools SET logo_url = 'https://functionize.com/favicon.ico' WHERE name = 'Functionize';
UPDATE tools SET logo_url = 'https://www.postman.com/favicon.ico' WHERE name = 'Postman AI Assistant';
UPDATE tools SET logo_url = 'https://httpie.io/favicon.ico' WHERE name = 'HTTPie AI';
UPDATE tools SET logo_url = 'https://insomnia.rest/favicon.ico' WHERE name = 'Insomnia AI';
UPDATE tools SET logo_url = 'https://rapidapi.com/favicon.ico' WHERE name = 'RapidAPI AI Hub';
UPDATE tools SET logo_url = 'https://aiven.io/favicon.ico' WHERE name = 'Aiven AI';
UPDATE tools SET logo_url = 'https://dbdocs.io/favicon.ico' WHERE name = 'dbdocs AI';
UPDATE tools SET logo_url = 'https://supabase.com/favicon.ico' WHERE name = 'Supabase AI';
UPDATE tools SET logo_url = 'https://gitpod.io/favicon.ico' WHERE name = 'Gitpod AI';
UPDATE tools SET logo_url = 'https://railway.app/favicon.ico' WHERE name = 'Railway AI';
UPDATE tools SET logo_url = 'https://render.com/favicon.ico' WHERE name = 'Render AI';
UPDATE tools SET logo_url = 'https://flutter.dev/favicon.ico' WHERE name = 'Flutter AI Toolkit';
UPDATE tools SET logo_url = 'https://reactnative.dev/img/favicon.ico' WHERE name = 'React Native AI';
UPDATE tools SET logo_url = 'https://expo.dev/favicon.ico' WHERE name = 'Expo AI';
UPDATE tools SET logo_url = 'https://vercel.com/favicon.ico' WHERE name = 'Vercel AI SDK';
UPDATE tools SET logo_url = 'https://www.netlify.com/favicon.ico' WHERE name = 'Netlify AI';
UPDATE tools SET logo_url = 'https://webflow.com/favicon.ico' WHERE name = 'Webflow AI';
UPDATE tools SET logo_url = 'https://www.framer.com/favicon.ico' WHERE name = 'Framer AI';
UPDATE tools SET logo_url = 'https://codeshot.dev/favicon.ico' WHERE name = 'CodeShot';
UPDATE tools SET logo_url = 'https://www.raycast.com/favicon.ico' WHERE name = 'Raycast AI';
UPDATE tools SET logo_url = 'https://d1.awsstatic.com/logos/aws-logo-lockups/poweredbyaws/PB_AWS_logo_RGB_REV_SQ.8c88ac215fe4e441dc42865dd6962ed4f444a90d.png' WHERE name = 'Amazon CodeWhisperer';
UPDATE tools SET logo_url = 'https://coderabbit.ai/favicon.ico' WHERE name = 'CodeRabbit';
UPDATE tools SET logo_url = 'https://whisk.security/favicon.ico' WHERE name = 'Whisk Security';
UPDATE tools SET logo_url = 'https://codegeex.cn/favicon.ico' WHERE name = 'CodeGeeX';
UPDATE tools SET logo_url = 'https://gitahead.github.io/gitahead.com/favicon.ico' WHERE name = 'GitAhead AI';
UPDATE tools SET logo_url = 'https://www.gitkraken.com/favicon.ico' WHERE name = 'GitKraken AI';
UPDATE tools SET logo_url = 'https://about.gitlab.com/favicon.ico' WHERE name = 'GitLab AI';
UPDATE tools SET logo_url = 'https://ai2sql.io/favicon.ico' WHERE name = 'AI2SQL';
UPDATE tools SET logo_url = 'https://regex.ai/favicon.ico' WHERE name = 'Regex AI';
UPDATE tools SET logo_url = 'https://cron.ai/favicon.ico' WHERE name = 'Cron AI';
UPDATE tools SET logo_url = 'https://jsonai.com/favicon.ico' WHERE name = 'JSON AI';
UPDATE tools SET logo_url = 'https://lighthouse.dev/favicon.ico' WHERE name = 'Lighthouse AI';
UPDATE tools SET logo_url = 'https://bundleanalyzer.com/favicon.ico' WHERE name = 'Bundle Analyzer AI';
UPDATE tools SET logo_url = 'https://webpack.js.org/favicon.ico' WHERE name = 'Webpack AI';
UPDATE tools SET logo_url = 'https://snyk.io/favicon.ico' WHERE name = 'Snyk AI';
UPDATE tools SET logo_url = 'https://checkmarx.com/favicon.ico' WHERE name = 'Checkmarx AI';
UPDATE tools SET logo_url = 'https://www.veracode.com/favicon.ico' WHERE name = 'Veracode AI';
UPDATE tools SET logo_url = 'https://sentry.io/favicon.ico' WHERE name = 'Sentry AI';
UPDATE tools SET logo_url = 'https://www.datadoghq.com/favicon.ico' WHERE name = 'Datadog AI';
UPDATE tools SET logo_url = 'https://newrelic.com/favicon.ico' WHERE name = 'New Relic AI';
UPDATE tools SET logo_url = 'https://www.codecademy.com/favicon.ico' WHERE name = 'Codecademy AI';
UPDATE tools SET logo_url = 'https://www.freecodecamp.org/favicon.ico' WHERE name = 'FreeCodeCamp AI';
UPDATE tools SET logo_url = 'https://www.codewars.com/favicon.ico' WHERE name = 'Codewars AI';
UPDATE tools SET logo_url = 'https://leetcode.com/favicon.ico' WHERE name = 'LeetCode AI';
UPDATE tools SET logo_url = 'https://linear.app/favicon.ico' WHERE name = 'Linear AI';
UPDATE tools SET logo_url = 'https://www.notion.so/favicon.ico' WHERE name = 'Notion AI';
UPDATE tools SET logo_url = 'https://www.terraform.io/favicon.ico' WHERE name = 'Terraform AI';
UPDATE tools SET logo_url = 'https://www.pulumi.com/favicon.ico' WHERE name = 'Pulumi AI';
UPDATE tools SET logo_url = 'https://www.ansible.com/favicon.ico' WHERE name = 'Ansible AI';
UPDATE tools SET logo_url = 'https://www.docker.com/favicon.ico' WHERE name = 'Docker AI';

-- Log the update operation
SELECT 'Updated logo URLs for coding development tools' as status;
